"""AUTO-GENERATED by tools/generate_phase25_tests.py — do not edit by hand."""

from __future__ import annotations

import re
import unittest

from sanskript.ast import Program
from sanskript.bytecode import OpCode
from sanskript.phase25_ast_smoke import AST_PROGRAM_BUILDERS, build_ast_program
from sanskript.phase25_exhaustive_registry import COMPILER_EMITTED_OPCODES
from sanskript.phase25_opcode_smoke import run_opcode_smoke


def _snake_case(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()


class Phase25OpcodeExhaustiveTests(unittest.TestCase):
    """Dedicated VM smoke — one test per OpCode enum member."""

    def test_opcode_push_int(self) -> None:
        run_opcode_smoke(OpCode.PUSH_INT)

    def test_opcode_push_text(self) -> None:
        run_opcode_smoke(OpCode.PUSH_TEXT)

    def test_opcode_push_bool(self) -> None:
        run_opcode_smoke(OpCode.PUSH_BOOL)

    def test_opcode_text_concat(self) -> None:
        run_opcode_smoke(OpCode.TEXT_CONCAT)

    def test_opcode_text_len(self) -> None:
        run_opcode_smoke(OpCode.TEXT_LEN)

    def test_opcode_text_get(self) -> None:
        run_opcode_smoke(OpCode.TEXT_GET)

    def test_opcode_text_slice(self) -> None:
        run_opcode_smoke(OpCode.TEXT_SLICE)

    def test_opcode_text_contains(self) -> None:
        run_opcode_smoke(OpCode.TEXT_CONTAINS)

    def test_opcode_list_new(self) -> None:
        run_opcode_smoke(OpCode.LIST_NEW)

    def test_opcode_list_append(self) -> None:
        run_opcode_smoke(OpCode.LIST_APPEND)

    def test_opcode_list_len(self) -> None:
        run_opcode_smoke(OpCode.LIST_LEN)

    def test_opcode_list_get(self) -> None:
        run_opcode_smoke(OpCode.LIST_GET)

    def test_opcode_list_map(self) -> None:
        run_opcode_smoke(OpCode.LIST_MAP)

    def test_opcode_list_filter(self) -> None:
        run_opcode_smoke(OpCode.LIST_FILTER)

    def test_opcode_list_reduce(self) -> None:
        run_opcode_smoke(OpCode.LIST_REDUCE)

    def test_opcode_list_all(self) -> None:
        run_opcode_smoke(OpCode.LIST_ALL)

    def test_opcode_list_scan(self) -> None:
        run_opcode_smoke(OpCode.LIST_SCAN)

    def test_opcode_list_zip(self) -> None:
        run_opcode_smoke(OpCode.LIST_ZIP)

    def test_opcode_list_enumerate(self) -> None:
        run_opcode_smoke(OpCode.LIST_ENUMERATE)

    def test_opcode_list_any(self) -> None:
        run_opcode_smoke(OpCode.LIST_ANY)

    def test_opcode_list_comprehension(self) -> None:
        run_opcode_smoke(OpCode.LIST_COMPREHENSION)

    def test_opcode_immutable_list_new(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_NEW)

    def test_opcode_immutable_list_append(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_APPEND)

    def test_opcode_immutable_list_len(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_LEN)

    def test_opcode_immutable_list_get(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_GET)

    def test_opcode_lazy_iter_new(self) -> None:
        run_opcode_smoke(OpCode.LAZY_ITER_NEW)

    def test_opcode_lazy_iter_next(self) -> None:
        run_opcode_smoke(OpCode.LAZY_ITER_NEXT)

    def test_opcode_generator_new(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_NEW)

    def test_opcode_generator_next(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_NEXT)

    def test_opcode_generator_yield(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_YIELD)

    def test_opcode_pipeline_chain(self) -> None:
        run_opcode_smoke(OpCode.PIPELINE_CHAIN)

    def test_opcode_result_bind(self) -> None:
        run_opcode_smoke(OpCode.RESULT_BIND)

    def test_opcode_data_query(self) -> None:
        run_opcode_smoke(OpCode.DATA_QUERY)

    def test_opcode_rule_register(self) -> None:
        run_opcode_smoke(OpCode.RULE_REGISTER)

    def test_opcode_rule_invoke(self) -> None:
        run_opcode_smoke(OpCode.RULE_INVOKE)

    def test_opcode_memo_call(self) -> None:
        run_opcode_smoke(OpCode.MEMO_CALL)

    def test_opcode_map_new(self) -> None:
        run_opcode_smoke(OpCode.MAP_NEW)

    def test_opcode_map_set(self) -> None:
        run_opcode_smoke(OpCode.MAP_SET)

    def test_opcode_map_get(self) -> None:
        run_opcode_smoke(OpCode.MAP_GET)

    def test_opcode_map_contains(self) -> None:
        run_opcode_smoke(OpCode.MAP_CONTAINS)

    def test_opcode_record_new(self) -> None:
        run_opcode_smoke(OpCode.RECORD_NEW)

    def test_opcode_record_set(self) -> None:
        run_opcode_smoke(OpCode.RECORD_SET)

    def test_opcode_record_get(self) -> None:
        run_opcode_smoke(OpCode.RECORD_GET)

    def test_opcode_record_contains(self) -> None:
        run_opcode_smoke(OpCode.RECORD_CONTAINS)

    def test_opcode_class_new(self) -> None:
        run_opcode_smoke(OpCode.CLASS_NEW)

    def test_opcode_method_call(self) -> None:
        run_opcode_smoke(OpCode.METHOD_CALL)

    def test_opcode_push_bigint(self) -> None:
        run_opcode_smoke(OpCode.PUSH_BIGINT)

    def test_opcode_push_i32(self) -> None:
        run_opcode_smoke(OpCode.PUSH_I32)

    def test_opcode_push_u32(self) -> None:
        run_opcode_smoke(OpCode.PUSH_U32)

    def test_opcode_i32_add_checked(self) -> None:
        run_opcode_smoke(OpCode.I32_ADD_CHECKED)

    def test_opcode_u32_add_checked(self) -> None:
        run_opcode_smoke(OpCode.U32_ADD_CHECKED)

    def test_opcode_i32_add_wrapping(self) -> None:
        run_opcode_smoke(OpCode.I32_ADD_WRAPPING)

    def test_opcode_u32_add_wrapping(self) -> None:
        run_opcode_smoke(OpCode.U32_ADD_WRAPPING)

    def test_opcode_i32_add_saturating(self) -> None:
        run_opcode_smoke(OpCode.I32_ADD_SATURATING)

    def test_opcode_u32_add_saturating(self) -> None:
        run_opcode_smoke(OpCode.U32_ADD_SATURATING)

    def test_opcode_push_bytes(self) -> None:
        run_opcode_smoke(OpCode.PUSH_BYTES)

    def test_opcode_byte_new(self) -> None:
        run_opcode_smoke(OpCode.BYTE_NEW)

    def test_opcode_byte_len(self) -> None:
        run_opcode_smoke(OpCode.BYTE_LEN)

    def test_opcode_byte_get(self) -> None:
        run_opcode_smoke(OpCode.BYTE_GET)

    def test_opcode_bytearray_new(self) -> None:
        run_opcode_smoke(OpCode.BYTEARRAY_NEW)

    def test_opcode_bytearray_set(self) -> None:
        run_opcode_smoke(OpCode.BYTEARRAY_SET)

    def test_opcode_bytearray_get(self) -> None:
        run_opcode_smoke(OpCode.BYTEARRAY_GET)

    def test_opcode_tuple_new(self) -> None:
        run_opcode_smoke(OpCode.TUPLE_NEW)

    def test_opcode_tuple_get(self) -> None:
        run_opcode_smoke(OpCode.TUPLE_GET)

    def test_opcode_set_new(self) -> None:
        run_opcode_smoke(OpCode.SET_NEW)

    def test_opcode_set_add(self) -> None:
        run_opcode_smoke(OpCode.SET_ADD)

    def test_opcode_set_contains(self) -> None:
        run_opcode_smoke(OpCode.SET_CONTAINS)

    def test_opcode_set_len(self) -> None:
        run_opcode_smoke(OpCode.SET_LEN)

    def test_opcode_deque_new(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_NEW)

    def test_opcode_deque_push_back(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_PUSH_BACK)

    def test_opcode_deque_push_front(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_PUSH_FRONT)

    def test_opcode_deque_pop_back(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_POP_BACK)

    def test_opcode_deque_pop_front(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_POP_FRONT)

    def test_opcode_deque_len(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_LEN)

    def test_opcode_option_none(self) -> None:
        run_opcode_smoke(OpCode.OPTION_NONE)

    def test_opcode_option_some(self) -> None:
        run_opcode_smoke(OpCode.OPTION_SOME)

    def test_opcode_option_is_some(self) -> None:
        run_opcode_smoke(OpCode.OPTION_IS_SOME)

    def test_opcode_option_unwrap(self) -> None:
        run_opcode_smoke(OpCode.OPTION_UNWRAP)

    def test_opcode_result_ok(self) -> None:
        run_opcode_smoke(OpCode.RESULT_OK)

    def test_opcode_result_err(self) -> None:
        run_opcode_smoke(OpCode.RESULT_ERR)

    def test_opcode_result_is_ok(self) -> None:
        run_opcode_smoke(OpCode.RESULT_IS_OK)

    def test_opcode_result_unwrap_ok(self) -> None:
        run_opcode_smoke(OpCode.RESULT_UNWRAP_OK)

    def test_opcode_result_unwrap_err(self) -> None:
        run_opcode_smoke(OpCode.RESULT_UNWRAP_ERR)

    def test_opcode_text_grapheme_len(self) -> None:
        run_opcode_smoke(OpCode.TEXT_GRAPHEME_LEN)

    def test_opcode_float_is_nan(self) -> None:
        run_opcode_smoke(OpCode.FLOAT_IS_NAN)

    def test_opcode_float_is_inf(self) -> None:
        run_opcode_smoke(OpCode.FLOAT_IS_INF)

    def test_opcode_opaque_new(self) -> None:
        run_opcode_smoke(OpCode.OPAQUE_NEW)

    def test_opcode_array_new(self) -> None:
        run_opcode_smoke(OpCode.ARRAY_NEW)

    def test_opcode_slice_view(self) -> None:
        run_opcode_smoke(OpCode.SLICE_VIEW)

    def test_opcode_push_float(self) -> None:
        run_opcode_smoke(OpCode.PUSH_FLOAT)

    def test_opcode_heap_alloc(self) -> None:
        run_opcode_smoke(OpCode.HEAP_ALLOC)

    def test_opcode_heap_store(self) -> None:
        run_opcode_smoke(OpCode.HEAP_STORE)

    def test_opcode_heap_load(self) -> None:
        run_opcode_smoke(OpCode.HEAP_LOAD)

    def test_opcode_heap_free(self) -> None:
        run_opcode_smoke(OpCode.HEAP_FREE)

    def test_opcode_unsafe_enter(self) -> None:
        run_opcode_smoke(OpCode.UNSAFE_ENTER)

    def test_opcode_unsafe_exit(self) -> None:
        run_opcode_smoke(OpCode.UNSAFE_EXIT)

    def test_opcode_ptr_from_int(self) -> None:
        run_opcode_smoke(OpCode.PTR_FROM_INT)

    def test_opcode_ptr_to_int(self) -> None:
        run_opcode_smoke(OpCode.PTR_TO_INT)

    def test_opcode_ptr_add(self) -> None:
        run_opcode_smoke(OpCode.PTR_ADD)

    def test_opcode_ptr_sub(self) -> None:
        run_opcode_smoke(OpCode.PTR_SUB)

    def test_opcode_load_u8(self) -> None:
        run_opcode_smoke(OpCode.LOAD_U8)

    def test_opcode_load_u16_le(self) -> None:
        run_opcode_smoke(OpCode.LOAD_U16_LE)

    def test_opcode_load_u16_be(self) -> None:
        run_opcode_smoke(OpCode.LOAD_U16_BE)

    def test_opcode_load_u32_le(self) -> None:
        run_opcode_smoke(OpCode.LOAD_U32_LE)

    def test_opcode_load_u32_be(self) -> None:
        run_opcode_smoke(OpCode.LOAD_U32_BE)

    def test_opcode_store_u8(self) -> None:
        run_opcode_smoke(OpCode.STORE_U8)

    def test_opcode_store_u16_le(self) -> None:
        run_opcode_smoke(OpCode.STORE_U16_LE)

    def test_opcode_store_u16_be(self) -> None:
        run_opcode_smoke(OpCode.STORE_U16_BE)

    def test_opcode_store_u32_le(self) -> None:
        run_opcode_smoke(OpCode.STORE_U32_LE)

    def test_opcode_store_u32_be(self) -> None:
        run_opcode_smoke(OpCode.STORE_U32_BE)

    def test_opcode_volatile_load_u32_le(self) -> None:
        run_opcode_smoke(OpCode.VOLATILE_LOAD_U32_LE)

    def test_opcode_volatile_store_u32_le(self) -> None:
        run_opcode_smoke(OpCode.VOLATILE_STORE_U32_LE)

    def test_opcode_bit_and(self) -> None:
        run_opcode_smoke(OpCode.BIT_AND)

    def test_opcode_bit_or(self) -> None:
        run_opcode_smoke(OpCode.BIT_OR)

    def test_opcode_bit_xor(self) -> None:
        run_opcode_smoke(OpCode.BIT_XOR)

    def test_opcode_bit_not(self) -> None:
        run_opcode_smoke(OpCode.BIT_NOT)

    def test_opcode_shift_left(self) -> None:
        run_opcode_smoke(OpCode.SHIFT_LEFT)

    def test_opcode_shift_right(self) -> None:
        run_opcode_smoke(OpCode.SHIFT_RIGHT)

    def test_opcode_rotate_left32(self) -> None:
        run_opcode_smoke(OpCode.ROTATE_LEFT32)

    def test_opcode_rotate_right32(self) -> None:
        run_opcode_smoke(OpCode.ROTATE_RIGHT32)

    def test_opcode_reg_set(self) -> None:
        run_opcode_smoke(OpCode.REG_SET)

    def test_opcode_reg_get(self) -> None:
        run_opcode_smoke(OpCode.REG_GET)

    def test_opcode_sp_set(self) -> None:
        run_opcode_smoke(OpCode.SP_SET)

    def test_opcode_sp_get(self) -> None:
        run_opcode_smoke(OpCode.SP_GET)

    def test_opcode_fp_set(self) -> None:
        run_opcode_smoke(OpCode.FP_SET)

    def test_opcode_fp_get(self) -> None:
        run_opcode_smoke(OpCode.FP_GET)

    def test_opcode_call_conv(self) -> None:
        run_opcode_smoke(OpCode.CALL_CONV)

    def test_opcode_prologue(self) -> None:
        run_opcode_smoke(OpCode.PROLOGUE)

    def test_opcode_epilogue(self) -> None:
        run_opcode_smoke(OpCode.EPILOGUE)

    def test_opcode_inline_asm(self) -> None:
        run_opcode_smoke(OpCode.INLINE_ASM)

    def test_opcode_label(self) -> None:
        run_opcode_smoke(OpCode.LABEL)

    def test_opcode_jump_label(self) -> None:
        run_opcode_smoke(OpCode.JUMP_LABEL)

    def test_opcode_jump_if_zero_label(self) -> None:
        run_opcode_smoke(OpCode.JUMP_IF_ZERO_LABEL)

    def test_opcode_jump_indirect(self) -> None:
        run_opcode_smoke(OpCode.JUMP_INDIRECT)

    def test_opcode_call_indirect(self) -> None:
        run_opcode_smoke(OpCode.CALL_INDIRECT)

    def test_opcode_syscall(self) -> None:
        run_opcode_smoke(OpCode.SYSCALL)

    def test_opcode_trap(self) -> None:
        run_opcode_smoke(OpCode.TRAP)

    def test_opcode_mmio_read(self) -> None:
        run_opcode_smoke(OpCode.MMIO_READ)

    def test_opcode_mmio_write(self) -> None:
        run_opcode_smoke(OpCode.MMIO_WRITE)

    def test_opcode_atomic_cas_u32_le(self) -> None:
        run_opcode_smoke(OpCode.ATOMIC_CAS_U32_LE)

    def test_opcode_fence(self) -> None:
        run_opcode_smoke(OpCode.FENCE)

    def test_opcode_load_name(self) -> None:
        run_opcode_smoke(OpCode.LOAD_NAME)

    def test_opcode_store_name(self) -> None:
        run_opcode_smoke(OpCode.STORE_NAME)

    def test_opcode_add(self) -> None:
        run_opcode_smoke(OpCode.ADD)

    def test_opcode_subtract(self) -> None:
        run_opcode_smoke(OpCode.SUBTRACT)

    def test_opcode_multiply(self) -> None:
        run_opcode_smoke(OpCode.MULTIPLY)

    def test_opcode_divide(self) -> None:
        run_opcode_smoke(OpCode.DIVIDE)

    def test_opcode_compare_eq(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_EQ)

    def test_opcode_compare_ne(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_NE)

    def test_opcode_compare_lt(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_LT)

    def test_opcode_compare_gt(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_GT)

    def test_opcode_compare_le(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_LE)

    def test_opcode_compare_identity(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_IDENTITY)

    def test_opcode_push_nil(self) -> None:
        run_opcode_smoke(OpCode.PUSH_NIL)

    def test_opcode_scope_enter(self) -> None:
        run_opcode_smoke(OpCode.SCOPE_ENTER)

    def test_opcode_scope_exit(self) -> None:
        run_opcode_smoke(OpCode.SCOPE_EXIT)

    def test_opcode_break_loop(self) -> None:
        run_opcode_smoke(OpCode.BREAK_LOOP)

    def test_opcode_continue_loop(self) -> None:
        run_opcode_smoke(OpCode.CONTINUE_LOOP)

    def test_opcode_defer_push(self) -> None:
        run_opcode_smoke(OpCode.DEFER_PUSH)

    def test_opcode_defer_run(self) -> None:
        run_opcode_smoke(OpCode.DEFER_RUN)

    def test_opcode_match_eq(self) -> None:
        run_opcode_smoke(OpCode.MATCH_EQ)

    def test_opcode_match_tuple_len(self) -> None:
        run_opcode_smoke(OpCode.MATCH_TUPLE_LEN)

    def test_opcode_match_record_has(self) -> None:
        run_opcode_smoke(OpCode.MATCH_RECORD_HAS)

    def test_opcode_emit(self) -> None:
        run_opcode_smoke(OpCode.EMIT)

    def test_opcode_jump(self) -> None:
        run_opcode_smoke(OpCode.JUMP)

    def test_opcode_jump_if_zero(self) -> None:
        run_opcode_smoke(OpCode.JUMP_IF_ZERO)

    def test_opcode_call(self) -> None:
        run_opcode_smoke(OpCode.CALL)

    def test_opcode_tail_call(self) -> None:
        run_opcode_smoke(OpCode.TAIL_CALL)

    def test_opcode_push_func(self) -> None:
        run_opcode_smoke(OpCode.PUSH_FUNC)

    def test_opcode_return(self) -> None:
        run_opcode_smoke(OpCode.RETURN)

    def test_opcode_pop(self) -> None:
        run_opcode_smoke(OpCode.POP)

    def test_opcode_halt(self) -> None:
        run_opcode_smoke(OpCode.HALT)

    def test_opcode_throw(self) -> None:
        run_opcode_smoke(OpCode.THROW)

    def test_opcode_panic(self) -> None:
        run_opcode_smoke(OpCode.PANIC)

    def test_opcode_try_begin(self) -> None:
        run_opcode_smoke(OpCode.TRY_BEGIN)

    def test_opcode_try_end(self) -> None:
        run_opcode_smoke(OpCode.TRY_END)


class Phase25AstNodeExhaustiveTests(unittest.TestCase):
    """Dedicated AST builder — one test per Statement union member."""

    def test_ast_algebraic_type_decl(self) -> None:
        program = build_ast_program('AlgebraicTypeDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('AlgebraicTypeDecl', AST_PROGRAM_BUILDERS)

    def test_ast_assert(self) -> None:
        program = build_ast_program('Assert')
        self.assertIsInstance(program, Program)
        self.assertIn('Assert', AST_PROGRAM_BUILDERS)

    def test_ast_assign(self) -> None:
        program = build_ast_program('Assign')
        self.assertIsInstance(program, Program)
        self.assertIn('Assign', AST_PROGRAM_BUILDERS)

    def test_ast_bind(self) -> None:
        program = build_ast_program('Bind')
        self.assertIsInstance(program, Program)
        self.assertIn('Bind', AST_PROGRAM_BUILDERS)

    def test_ast_block(self) -> None:
        program = build_ast_program('Block')
        self.assertIsInstance(program, Program)
        self.assertIn('Block', AST_PROGRAM_BUILDERS)

    def test_ast_break(self) -> None:
        program = build_ast_program('Break')
        self.assertIsInstance(program, Program)
        self.assertIn('Break', AST_PROGRAM_BUILDERS)

    def test_ast_call(self) -> None:
        program = build_ast_program('Call')
        self.assertIsInstance(program, Program)
        self.assertIn('Call', AST_PROGRAM_BUILDERS)

    def test_ast_class_method_call(self) -> None:
        program = build_ast_program('ClassMethodCall')
        self.assertIsInstance(program, Program)
        self.assertIn('ClassMethodCall', AST_PROGRAM_BUILDERS)

    def test_ast_class_new(self) -> None:
        program = build_ast_program('ClassNew')
        self.assertIsInstance(program, Program)
        self.assertIn('ClassNew', AST_PROGRAM_BUILDERS)

    def test_ast_class_reflect(self) -> None:
        program = build_ast_program('ClassReflect')
        self.assertIsInstance(program, Program)
        self.assertIn('ClassReflect', AST_PROGRAM_BUILDERS)

    def test_ast_const_decl(self) -> None:
        program = build_ast_program('ConstDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('ConstDecl', AST_PROGRAM_BUILDERS)

    def test_ast_continue(self) -> None:
        program = build_ast_program('Continue')
        self.assertIsInstance(program, Program)
        self.assertIn('Continue', AST_PROGRAM_BUILDERS)

    def test_ast_counted_for(self) -> None:
        program = build_ast_program('CountedFor')
        self.assertIsInstance(program, Program)
        self.assertIn('CountedFor', AST_PROGRAM_BUILDERS)

    def test_ast_data_query(self) -> None:
        program = build_ast_program('DataQuery')
        self.assertIsInstance(program, Program)
        self.assertIn('DataQuery', AST_PROGRAM_BUILDERS)

    def test_ast_decrease(self) -> None:
        program = build_ast_program('Decrease')
        self.assertIsInstance(program, Program)
        self.assertIn('Decrease', AST_PROGRAM_BUILDERS)

    def test_ast_defer(self) -> None:
        program = build_ast_program('Defer')
        self.assertIsInstance(program, Program)
        self.assertIn('Defer', AST_PROGRAM_BUILDERS)

    def test_ast_destructure_assign(self) -> None:
        program = build_ast_program('DestructureAssign')
        self.assertIsInstance(program, Program)
        self.assertIn('DestructureAssign', AST_PROGRAM_BUILDERS)

    def test_ast_display(self) -> None:
        program = build_ast_program('Display')
        self.assertIsInstance(program, Program)
        self.assertIn('Display', AST_PROGRAM_BUILDERS)

    def test_ast_field_contains(self) -> None:
        program = build_ast_program('FieldContains')
        self.assertIsInstance(program, Program)
        self.assertIn('FieldContains', AST_PROGRAM_BUILDERS)

    def test_ast_field_get(self) -> None:
        program = build_ast_program('FieldGet')
        self.assertIsInstance(program, Program)
        self.assertIn('FieldGet', AST_PROGRAM_BUILDERS)

    def test_ast_field_set(self) -> None:
        program = build_ast_program('FieldSet')
        self.assertIsInstance(program, Program)
        self.assertIn('FieldSet', AST_PROGRAM_BUILDERS)

    def test_ast_for_each(self) -> None:
        program = build_ast_program('ForEach')
        self.assertIsInstance(program, Program)
        self.assertIn('ForEach', AST_PROGRAM_BUILDERS)

    def test_ast_for_each_destructure(self) -> None:
        program = build_ast_program('ForEachDestructure')
        self.assertIsInstance(program, Program)
        self.assertIn('ForEachDestructure', AST_PROGRAM_BUILDERS)

    def test_ast_forward_decl(self) -> None:
        program = build_ast_program('ForwardDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('ForwardDecl', AST_PROGRAM_BUILDERS)

    def test_ast_function_def(self) -> None:
        program = build_ast_program('FunctionDef')
        self.assertIsInstance(program, Program)
        self.assertIn('FunctionDef', AST_PROGRAM_BUILDERS)

    def test_ast_generator_new(self) -> None:
        program = build_ast_program('GeneratorNew')
        self.assertIsInstance(program, Program)
        self.assertIn('GeneratorNew', AST_PROGRAM_BUILDERS)

    def test_ast_generator_next(self) -> None:
        program = build_ast_program('GeneratorNext')
        self.assertIsInstance(program, Program)
        self.assertIn('GeneratorNext', AST_PROGRAM_BUILDERS)

    def test_ast_generic_record_decl(self) -> None:
        program = build_ast_program('GenericRecordDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('GenericRecordDecl', AST_PROGRAM_BUILDERS)

    def test_ast_guard(self) -> None:
        program = build_ast_program('Guard')
        self.assertIsInstance(program, Program)
        self.assertIn('Guard', AST_PROGRAM_BUILDERS)

    def test_ast_heap_alloc(self) -> None:
        program = build_ast_program('HeapAlloc')
        self.assertIsInstance(program, Program)
        self.assertIn('HeapAlloc', AST_PROGRAM_BUILDERS)

    def test_ast_heap_free(self) -> None:
        program = build_ast_program('HeapFree')
        self.assertIsInstance(program, Program)
        self.assertIn('HeapFree', AST_PROGRAM_BUILDERS)

    def test_ast_heap_load(self) -> None:
        program = build_ast_program('HeapLoad')
        self.assertIsInstance(program, Program)
        self.assertIn('HeapLoad', AST_PROGRAM_BUILDERS)

    def test_ast_heap_store(self) -> None:
        program = build_ast_program('HeapStore')
        self.assertIsInstance(program, Program)
        self.assertIn('HeapStore', AST_PROGRAM_BUILDERS)

    def test_ast_if(self) -> None:
        program = build_ast_program('If')
        self.assertIsInstance(program, Program)
        self.assertIn('If', AST_PROGRAM_BUILDERS)

    def test_ast_immutable_list_append(self) -> None:
        program = build_ast_program('ImmutableListAppend')
        self.assertIsInstance(program, Program)
        self.assertIn('ImmutableListAppend', AST_PROGRAM_BUILDERS)

    def test_ast_immutable_list_init(self) -> None:
        program = build_ast_program('ImmutableListInit')
        self.assertIsInstance(program, Program)
        self.assertIn('ImmutableListInit', AST_PROGRAM_BUILDERS)

    def test_ast_increase(self) -> None:
        program = build_ast_program('Increase')
        self.assertIsInstance(program, Program)
        self.assertIn('Increase', AST_PROGRAM_BUILDERS)

    def test_ast_infinite_loop(self) -> None:
        program = build_ast_program('InfiniteLoop')
        self.assertIsInstance(program, Program)
        self.assertIn('InfiniteLoop', AST_PROGRAM_BUILDERS)

    def test_ast_instance_finalize(self) -> None:
        program = build_ast_program('InstanceFinalize')
        self.assertIsInstance(program, Program)
        self.assertIn('InstanceFinalize', AST_PROGRAM_BUILDERS)

    def test_ast_invariant(self) -> None:
        program = build_ast_program('Invariant')
        self.assertIsInstance(program, Program)
        self.assertIn('Invariant', AST_PROGRAM_BUILDERS)

    def test_ast_lazy_iter_new(self) -> None:
        program = build_ast_program('LazyIterNew')
        self.assertIsInstance(program, Program)
        self.assertIn('LazyIterNew', AST_PROGRAM_BUILDERS)

    def test_ast_lazy_iter_next(self) -> None:
        program = build_ast_program('LazyIterNext')
        self.assertIsInstance(program, Program)
        self.assertIn('LazyIterNext', AST_PROGRAM_BUILDERS)

    def test_ast_list_all(self) -> None:
        program = build_ast_program('ListAll')
        self.assertIsInstance(program, Program)
        self.assertIn('ListAll', AST_PROGRAM_BUILDERS)

    def test_ast_list_any(self) -> None:
        program = build_ast_program('ListAny')
        self.assertIsInstance(program, Program)
        self.assertIn('ListAny', AST_PROGRAM_BUILDERS)

    def test_ast_list_append(self) -> None:
        program = build_ast_program('ListAppend')
        self.assertIsInstance(program, Program)
        self.assertIn('ListAppend', AST_PROGRAM_BUILDERS)

    def test_ast_list_comprehension(self) -> None:
        program = build_ast_program('ListComprehension')
        self.assertIsInstance(program, Program)
        self.assertIn('ListComprehension', AST_PROGRAM_BUILDERS)

    def test_ast_list_enumerate(self) -> None:
        program = build_ast_program('ListEnumerate')
        self.assertIsInstance(program, Program)
        self.assertIn('ListEnumerate', AST_PROGRAM_BUILDERS)

    def test_ast_list_filter(self) -> None:
        program = build_ast_program('ListFilter')
        self.assertIsInstance(program, Program)
        self.assertIn('ListFilter', AST_PROGRAM_BUILDERS)

    def test_ast_list_get(self) -> None:
        program = build_ast_program('ListGet')
        self.assertIsInstance(program, Program)
        self.assertIn('ListGet', AST_PROGRAM_BUILDERS)

    def test_ast_list_init(self) -> None:
        program = build_ast_program('ListInit')
        self.assertIsInstance(program, Program)
        self.assertIn('ListInit', AST_PROGRAM_BUILDERS)

    def test_ast_list_length(self) -> None:
        program = build_ast_program('ListLength')
        self.assertIsInstance(program, Program)
        self.assertIn('ListLength', AST_PROGRAM_BUILDERS)

    def test_ast_list_map(self) -> None:
        program = build_ast_program('ListMap')
        self.assertIsInstance(program, Program)
        self.assertIn('ListMap', AST_PROGRAM_BUILDERS)

    def test_ast_list_reduce(self) -> None:
        program = build_ast_program('ListReduce')
        self.assertIsInstance(program, Program)
        self.assertIn('ListReduce', AST_PROGRAM_BUILDERS)

    def test_ast_list_scan(self) -> None:
        program = build_ast_program('ListScan')
        self.assertIsInstance(program, Program)
        self.assertIn('ListScan', AST_PROGRAM_BUILDERS)

    def test_ast_list_zip(self) -> None:
        program = build_ast_program('ListZip')
        self.assertIsInstance(program, Program)
        self.assertIn('ListZip', AST_PROGRAM_BUILDERS)

    def test_ast_map_contains(self) -> None:
        program = build_ast_program('MapContains')
        self.assertIsInstance(program, Program)
        self.assertIn('MapContains', AST_PROGRAM_BUILDERS)

    def test_ast_map_get(self) -> None:
        program = build_ast_program('MapGet')
        self.assertIsInstance(program, Program)
        self.assertIn('MapGet', AST_PROGRAM_BUILDERS)

    def test_ast_map_init(self) -> None:
        program = build_ast_program('MapInit')
        self.assertIsInstance(program, Program)
        self.assertIn('MapInit', AST_PROGRAM_BUILDERS)

    def test_ast_map_put(self) -> None:
        program = build_ast_program('MapPut')
        self.assertIsInstance(program, Program)
        self.assertIn('MapPut', AST_PROGRAM_BUILDERS)

    def test_ast_match(self) -> None:
        program = build_ast_program('Match')
        self.assertIsInstance(program, Program)
        self.assertIn('Match', AST_PROGRAM_BUILDERS)

    def test_ast_match_expr(self) -> None:
        program = build_ast_program('MatchExpr')
        self.assertIsInstance(program, Program)
        self.assertIn('MatchExpr', AST_PROGRAM_BUILDERS)

    def test_ast_memo_function(self) -> None:
        program = build_ast_program('MemoFunction')
        self.assertIsInstance(program, Program)
        self.assertIn('MemoFunction', AST_PROGRAM_BUILDERS)

    def test_ast_method_call(self) -> None:
        program = build_ast_program('MethodCall')
        self.assertIsInstance(program, Program)
        self.assertIn('MethodCall', AST_PROGRAM_BUILDERS)

    def test_ast_method_reflect(self) -> None:
        program = build_ast_program('MethodReflect')
        self.assertIsInstance(program, Program)
        self.assertIn('MethodReflect', AST_PROGRAM_BUILDERS)

    def test_ast_multiply(self) -> None:
        program = build_ast_program('Multiply')
        self.assertIsInstance(program, Program)
        self.assertIn('Multiply', AST_PROGRAM_BUILDERS)

    def test_ast_newtype_decl(self) -> None:
        program = build_ast_program('NewtypeDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('NewtypeDecl', AST_PROGRAM_BUILDERS)

    def test_ast_panic(self) -> None:
        program = build_ast_program('Panic')
        self.assertIsInstance(program, Program)
        self.assertIn('Panic', AST_PROGRAM_BUILDERS)

    def test_ast_phase3_bind(self) -> None:
        program = build_ast_program('Phase3Bind')
        self.assertIsInstance(program, Program)
        self.assertIn('Phase3Bind', AST_PROGRAM_BUILDERS)

    def test_ast_pipeline_chain(self) -> None:
        program = build_ast_program('PipelineChain')
        self.assertIsInstance(program, Program)
        self.assertIn('PipelineChain', AST_PROGRAM_BUILDERS)

    def test_ast_pop(self) -> None:
        program = build_ast_program('Pop')
        self.assertIsInstance(program, Program)
        self.assertIn('Pop', AST_PROGRAM_BUILDERS)

    def test_ast_post_condition(self) -> None:
        program = build_ast_program('PostCondition')
        self.assertIsInstance(program, Program)
        self.assertIn('PostCondition', AST_PROGRAM_BUILDERS)

    def test_ast_pre_condition(self) -> None:
        program = build_ast_program('PreCondition')
        self.assertIsInstance(program, Program)
        self.assertIn('PreCondition', AST_PROGRAM_BUILDERS)

    def test_ast_propagate(self) -> None:
        program = build_ast_program('Propagate')
        self.assertIsInstance(program, Program)
        self.assertIn('Propagate', AST_PROGRAM_BUILDERS)

    def test_ast_property_get(self) -> None:
        program = build_ast_program('PropertyGet')
        self.assertIsInstance(program, Program)
        self.assertIn('PropertyGet', AST_PROGRAM_BUILDERS)

    def test_ast_record_init(self) -> None:
        program = build_ast_program('RecordInit')
        self.assertIsInstance(program, Program)
        self.assertIn('RecordInit', AST_PROGRAM_BUILDERS)

    def test_ast_record_type_decl(self) -> None:
        program = build_ast_program('RecordTypeDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('RecordTypeDecl', AST_PROGRAM_BUILDERS)

    def test_ast_result_bind(self) -> None:
        program = build_ast_program('ResultBind')
        self.assertIsInstance(program, Program)
        self.assertIn('ResultBind', AST_PROGRAM_BUILDERS)

    def test_ast_return(self) -> None:
        program = build_ast_program('Return')
        self.assertIsInstance(program, Program)
        self.assertIn('Return', AST_PROGRAM_BUILDERS)

    def test_ast_rule_decl(self) -> None:
        program = build_ast_program('RuleDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('RuleDecl', AST_PROGRAM_BUILDERS)

    def test_ast_rule_invoke(self) -> None:
        program = build_ast_program('RuleInvoke')
        self.assertIsInstance(program, Program)
        self.assertIn('RuleInvoke', AST_PROGRAM_BUILDERS)

    def test_ast_static_method_call(self) -> None:
        program = build_ast_program('StaticMethodCall')
        self.assertIsInstance(program, Program)
        self.assertIn('StaticMethodCall', AST_PROGRAM_BUILDERS)

    def test_ast_text_concat(self) -> None:
        program = build_ast_program('TextConcat')
        self.assertIsInstance(program, Program)
        self.assertIn('TextConcat', AST_PROGRAM_BUILDERS)

    def test_ast_text_contains(self) -> None:
        program = build_ast_program('TextContains')
        self.assertIsInstance(program, Program)
        self.assertIn('TextContains', AST_PROGRAM_BUILDERS)

    def test_ast_text_get(self) -> None:
        program = build_ast_program('TextGet')
        self.assertIsInstance(program, Program)
        self.assertIn('TextGet', AST_PROGRAM_BUILDERS)

    def test_ast_text_length(self) -> None:
        program = build_ast_program('TextLength')
        self.assertIsInstance(program, Program)
        self.assertIn('TextLength', AST_PROGRAM_BUILDERS)

    def test_ast_text_slice(self) -> None:
        program = build_ast_program('TextSlice')
        self.assertIsInstance(program, Program)
        self.assertIn('TextSlice', AST_PROGRAM_BUILDERS)

    def test_ast_throw(self) -> None:
        program = build_ast_program('Throw')
        self.assertIsInstance(program, Program)
        self.assertIn('Throw', AST_PROGRAM_BUILDERS)

    def test_ast_trait_decl(self) -> None:
        program = build_ast_program('TraitDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('TraitDecl', AST_PROGRAM_BUILDERS)

    def test_ast_trait_impl(self) -> None:
        program = build_ast_program('TraitImpl')
        self.assertIsInstance(program, Program)
        self.assertIn('TraitImpl', AST_PROGRAM_BUILDERS)

    def test_ast_try_catch(self) -> None:
        program = build_ast_program('TryCatch')
        self.assertIsInstance(program, Program)
        self.assertIn('TryCatch', AST_PROGRAM_BUILDERS)

    def test_ast_type_alias_decl(self) -> None:
        program = build_ast_program('TypeAliasDecl')
        self.assertIsInstance(program, Program)
        self.assertIn('TypeAliasDecl', AST_PROGRAM_BUILDERS)

    def test_ast_type_convert(self) -> None:
        program = build_ast_program('TypeConvert')
        self.assertIsInstance(program, Program)
        self.assertIn('TypeConvert', AST_PROGRAM_BUILDERS)

    def test_ast_type_reflect(self) -> None:
        program = build_ast_program('TypeReflect')
        self.assertIsInstance(program, Program)
        self.assertIn('TypeReflect', AST_PROGRAM_BUILDERS)

    def test_ast_unsafe_enter(self) -> None:
        program = build_ast_program('UnsafeEnter')
        self.assertIsInstance(program, Program)
        self.assertIn('UnsafeEnter', AST_PROGRAM_BUILDERS)

    def test_ast_unsafe_exit(self) -> None:
        program = build_ast_program('UnsafeExit')
        self.assertIsInstance(program, Program)
        self.assertIn('UnsafeExit', AST_PROGRAM_BUILDERS)

    def test_ast_until(self) -> None:
        program = build_ast_program('Until')
        self.assertIsInstance(program, Program)
        self.assertIn('Until', AST_PROGRAM_BUILDERS)

    def test_ast_while(self) -> None:
        program = build_ast_program('While')
        self.assertIsInstance(program, Program)
        self.assertIn('While', AST_PROGRAM_BUILDERS)

    def test_ast_yield(self) -> None:
        program = build_ast_program('Yield')
        self.assertIsInstance(program, Program)
        self.assertIn('Yield', AST_PROGRAM_BUILDERS)


class Phase25CompilerLoweringTests(unittest.TestCase):
    """Dedicated reference test per compiler-emitted OpCode."""

    def test_lowering_inventory_matches_compiler_source(self) -> None:
        self.assertGreaterEqual(len(COMPILER_EMITTED_OPCODES), 1)

    def test_lowering_add(self) -> None:
        run_opcode_smoke(OpCode.ADD)

    def test_lowering_call(self) -> None:
        run_opcode_smoke(OpCode.CALL)

    def test_lowering_class_new(self) -> None:
        run_opcode_smoke(OpCode.CLASS_NEW)

    def test_lowering_compare_eq(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_EQ)

    def test_lowering_compare_gt(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_GT)

    def test_lowering_compare_identity(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_IDENTITY)

    def test_lowering_compare_le(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_LE)

    def test_lowering_compare_lt(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_LT)

    def test_lowering_compare_ne(self) -> None:
        run_opcode_smoke(OpCode.COMPARE_NE)

    def test_lowering_data_query(self) -> None:
        run_opcode_smoke(OpCode.DATA_QUERY)

    def test_lowering_deque_new(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_NEW)

    def test_lowering_deque_push_back(self) -> None:
        run_opcode_smoke(OpCode.DEQUE_PUSH_BACK)

    def test_lowering_divide(self) -> None:
        run_opcode_smoke(OpCode.DIVIDE)

    def test_lowering_emit(self) -> None:
        run_opcode_smoke(OpCode.EMIT)

    def test_lowering_generator_new(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_NEW)

    def test_lowering_generator_next(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_NEXT)

    def test_lowering_generator_yield(self) -> None:
        run_opcode_smoke(OpCode.GENERATOR_YIELD)

    def test_lowering_halt(self) -> None:
        run_opcode_smoke(OpCode.HALT)

    def test_lowering_heap_alloc(self) -> None:
        run_opcode_smoke(OpCode.HEAP_ALLOC)

    def test_lowering_heap_free(self) -> None:
        run_opcode_smoke(OpCode.HEAP_FREE)

    def test_lowering_heap_load(self) -> None:
        run_opcode_smoke(OpCode.HEAP_LOAD)

    def test_lowering_heap_store(self) -> None:
        run_opcode_smoke(OpCode.HEAP_STORE)

    def test_lowering_immutable_list_append(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_APPEND)

    def test_lowering_immutable_list_new(self) -> None:
        run_opcode_smoke(OpCode.IMMUTABLE_LIST_NEW)

    def test_lowering_jump(self) -> None:
        run_opcode_smoke(OpCode.JUMP)

    def test_lowering_jump_if_zero(self) -> None:
        run_opcode_smoke(OpCode.JUMP_IF_ZERO)

    def test_lowering_lazy_iter_new(self) -> None:
        run_opcode_smoke(OpCode.LAZY_ITER_NEW)

    def test_lowering_lazy_iter_next(self) -> None:
        run_opcode_smoke(OpCode.LAZY_ITER_NEXT)

    def test_lowering_list_all(self) -> None:
        run_opcode_smoke(OpCode.LIST_ALL)

    def test_lowering_list_any(self) -> None:
        run_opcode_smoke(OpCode.LIST_ANY)

    def test_lowering_list_append(self) -> None:
        run_opcode_smoke(OpCode.LIST_APPEND)

    def test_lowering_list_comprehension(self) -> None:
        run_opcode_smoke(OpCode.LIST_COMPREHENSION)

    def test_lowering_list_enumerate(self) -> None:
        run_opcode_smoke(OpCode.LIST_ENUMERATE)

    def test_lowering_list_filter(self) -> None:
        run_opcode_smoke(OpCode.LIST_FILTER)

    def test_lowering_list_get(self) -> None:
        run_opcode_smoke(OpCode.LIST_GET)

    def test_lowering_list_len(self) -> None:
        run_opcode_smoke(OpCode.LIST_LEN)

    def test_lowering_list_map(self) -> None:
        run_opcode_smoke(OpCode.LIST_MAP)

    def test_lowering_list_new(self) -> None:
        run_opcode_smoke(OpCode.LIST_NEW)

    def test_lowering_list_reduce(self) -> None:
        run_opcode_smoke(OpCode.LIST_REDUCE)

    def test_lowering_list_scan(self) -> None:
        run_opcode_smoke(OpCode.LIST_SCAN)

    def test_lowering_list_zip(self) -> None:
        run_opcode_smoke(OpCode.LIST_ZIP)

    def test_lowering_load_name(self) -> None:
        run_opcode_smoke(OpCode.LOAD_NAME)

    def test_lowering_map_contains(self) -> None:
        run_opcode_smoke(OpCode.MAP_CONTAINS)

    def test_lowering_map_get(self) -> None:
        run_opcode_smoke(OpCode.MAP_GET)

    def test_lowering_map_new(self) -> None:
        run_opcode_smoke(OpCode.MAP_NEW)

    def test_lowering_map_set(self) -> None:
        run_opcode_smoke(OpCode.MAP_SET)

    def test_lowering_match_eq(self) -> None:
        run_opcode_smoke(OpCode.MATCH_EQ)

    def test_lowering_method_call(self) -> None:
        run_opcode_smoke(OpCode.METHOD_CALL)

    def test_lowering_multiply(self) -> None:
        run_opcode_smoke(OpCode.MULTIPLY)

    def test_lowering_option_none(self) -> None:
        run_opcode_smoke(OpCode.OPTION_NONE)

    def test_lowering_option_some(self) -> None:
        run_opcode_smoke(OpCode.OPTION_SOME)

    def test_lowering_panic(self) -> None:
        run_opcode_smoke(OpCode.PANIC)

    def test_lowering_pipeline_chain(self) -> None:
        run_opcode_smoke(OpCode.PIPELINE_CHAIN)

    def test_lowering_pop(self) -> None:
        run_opcode_smoke(OpCode.POP)

    def test_lowering_push_bool(self) -> None:
        run_opcode_smoke(OpCode.PUSH_BOOL)

    def test_lowering_push_bytes(self) -> None:
        run_opcode_smoke(OpCode.PUSH_BYTES)

    def test_lowering_push_float(self) -> None:
        run_opcode_smoke(OpCode.PUSH_FLOAT)

    def test_lowering_push_int(self) -> None:
        run_opcode_smoke(OpCode.PUSH_INT)

    def test_lowering_push_nil(self) -> None:
        run_opcode_smoke(OpCode.PUSH_NIL)

    def test_lowering_push_text(self) -> None:
        run_opcode_smoke(OpCode.PUSH_TEXT)

    def test_lowering_record_contains(self) -> None:
        run_opcode_smoke(OpCode.RECORD_CONTAINS)

    def test_lowering_record_get(self) -> None:
        run_opcode_smoke(OpCode.RECORD_GET)

    def test_lowering_record_new(self) -> None:
        run_opcode_smoke(OpCode.RECORD_NEW)

    def test_lowering_record_set(self) -> None:
        run_opcode_smoke(OpCode.RECORD_SET)

    def test_lowering_result_bind(self) -> None:
        run_opcode_smoke(OpCode.RESULT_BIND)

    def test_lowering_result_is_ok(self) -> None:
        run_opcode_smoke(OpCode.RESULT_IS_OK)

    def test_lowering_result_unwrap_err(self) -> None:
        run_opcode_smoke(OpCode.RESULT_UNWRAP_ERR)

    def test_lowering_result_unwrap_ok(self) -> None:
        run_opcode_smoke(OpCode.RESULT_UNWRAP_OK)

    def test_lowering_return(self) -> None:
        run_opcode_smoke(OpCode.RETURN)

    def test_lowering_rule_invoke(self) -> None:
        run_opcode_smoke(OpCode.RULE_INVOKE)

    def test_lowering_rule_register(self) -> None:
        run_opcode_smoke(OpCode.RULE_REGISTER)

    def test_lowering_scope_enter(self) -> None:
        run_opcode_smoke(OpCode.SCOPE_ENTER)

    def test_lowering_scope_exit(self) -> None:
        run_opcode_smoke(OpCode.SCOPE_EXIT)

    def test_lowering_set_add(self) -> None:
        run_opcode_smoke(OpCode.SET_ADD)

    def test_lowering_set_new(self) -> None:
        run_opcode_smoke(OpCode.SET_NEW)

    def test_lowering_store_name(self) -> None:
        run_opcode_smoke(OpCode.STORE_NAME)

    def test_lowering_subtract(self) -> None:
        run_opcode_smoke(OpCode.SUBTRACT)

    def test_lowering_tail_call(self) -> None:
        run_opcode_smoke(OpCode.TAIL_CALL)

    def test_lowering_text_concat(self) -> None:
        run_opcode_smoke(OpCode.TEXT_CONCAT)

    def test_lowering_text_contains(self) -> None:
        run_opcode_smoke(OpCode.TEXT_CONTAINS)

    def test_lowering_text_get(self) -> None:
        run_opcode_smoke(OpCode.TEXT_GET)

    def test_lowering_text_len(self) -> None:
        run_opcode_smoke(OpCode.TEXT_LEN)

    def test_lowering_text_slice(self) -> None:
        run_opcode_smoke(OpCode.TEXT_SLICE)

    def test_lowering_throw(self) -> None:
        run_opcode_smoke(OpCode.THROW)

    def test_lowering_try_begin(self) -> None:
        run_opcode_smoke(OpCode.TRY_BEGIN)

    def test_lowering_try_end(self) -> None:
        run_opcode_smoke(OpCode.TRY_END)

    def test_lowering_tuple_get(self) -> None:
        run_opcode_smoke(OpCode.TUPLE_GET)

    def test_lowering_tuple_new(self) -> None:
        run_opcode_smoke(OpCode.TUPLE_NEW)

    def test_lowering_unsafe_enter(self) -> None:
        run_opcode_smoke(OpCode.UNSAFE_ENTER)

    def test_lowering_unsafe_exit(self) -> None:
        run_opcode_smoke(OpCode.UNSAFE_EXIT)


if __name__ == "__main__":
    unittest.main()
