"""Curated Dhatupatha verb entries: (lemma, gana, pada, present_stem, gloss, dp_ref, markers)."""

from __future__ import annotations

G1 = (
    ("bhū", 1, "parasmaipada", "bhava", "become, be", "Dhatupatha 1.1", ()),
    ("gam", 1, "parasmaipada", "gaccha", "go", "Dhatupatha 1.2", ()),
    ("i", 1, "parasmaipada", "ehi", "go", "Dhatupatha 1.3", ()),
    ("sthā", 1, "parasmaipada", "tiṣṭha", "stand", "Dhatupatha 1.4", ()),
    ("pac", 1, "parasmaipada", "paca", "cook", "Dhatupatha 1.5", ()),
    ("car", 1, "parasmaipada", "cara", "move, wander", "Dhatupatha 1.6", ()),
    ("cal", 1, "parasmaipada", "cala", "move, shake", "Dhatupatha 1.7", ()),
    ("vad", 1, "parasmaipada", "vada", "speak", "Dhatupatha 1.8", ()),
    ("likh", 1, "parasmaipada", "likha", "write", "Dhatupatha 1.9", ()),
    ("paṭh", 1, "parasmaipada", "paṭha", "read", "Dhatupatha 1.10", ()),
    ("rakṣ", 1, "parasmaipada", "rakṣa", "protect", "Dhatupatha 1.11", ()),
    ("pā", 1, "parasmaipada", "pāhi", "protect, drink", "Dhatupatha 1.12", ()),
    ("ji", 1, "parasmaipada", "jaya", "conquer", "Dhatupatha 1.13", ()),
    ("han", 1, "parasmaipada", "hanta", "strike, kill", "Dhatupatha 1.14", ()),
    ("tyaj", 1, "parasmaipada", "tyaja", "abandon", "Dhatupatha 1.15", ()),
    ("spṛś", 1, "parasmaipada", "spṛśa", "touch", "Dhatupatha 1.16", ()),
    ("kṣip", 1, "parasmaipada", "kṣipa", "throw", "Dhatupatha 1.17", ()),
    ("plu", 1, "parasmaipada", "plava", "float, swim", "Dhatupatha 1.18", ()),
    ("mṛj", 1, "parasmaipada", "mṛja", "wipe, cleanse", "Dhatupatha 1.19", ()),
    ("tap", 1, "parasmaipada", "tapati", "heat, practice austerities", "Dhatupatha 1.20", ()),
    ("kram", 1, "parasmaipada", "kramati", "stride, ascend", "Dhatupatha 1.21", ()),
    ("pad", 1, "parasmaipada", "padati", "go, fall", "Dhatupatha 1.22", ()),
    ("kṣar", 1, "parasmaipada", "kṣarati", "flow", "Dhatupatha 1.23", ()),
    ("arc", 1, "parasmaipada", "arcati", "honor, worship", "Dhatupatha 1.24", ()),
    ("gai", 1, "parasmaipada", "gāyati", "sing", "Dhatupatha 1.25", ()),
    ("nṛt", 1, "parasmaipada", "nṛtyati", "dance", "Dhatupatha 1.26", ()),
    ("ru", 1, "parasmaipada", "ravati", "roar, cry", "Dhatupatha 1.27", ()),
    ("aj", 1, "parasmaipada", "ajati", "drive", "Dhatupatha 1.28", ()),
    ("vah", 1, "parasmaipada", "vaha", "carry", "Dhatupatha 1.29", ()),
    ("khan", 1, "parasmaipada", "khanati", "dig", "Dhatupatha 1.30", ()),
    ("yam", 1, "parasmaipada", "yacchati", "restrain, offer", "Dhatupatha 1.31", ()),
    ("nī", 1, "parasmaipada", "naya", "lead", "Dhatupatha 1.32", ()),
    ("bodh", 1, "parasmaipada", "bodhati", "awaken", "Dhatupatha 1.33", ()),
    ("smṛ", 1, "parasmaipada", "smara", "remember", "Dhatupatha 1.34", ()),
    ("jīv", 1, "parasmaipada", "jīva", "live", "Dhatupatha 1.35", ()),
    ("mṛ", 1, "parasmaipada", "mara", "die", "Dhatupatha 1.36", ()),
    ("jan", 1, "parasmaipada", "janaya", "produce, beget", "Dhatupatha 1.37", ()),
    ("bhaj", 1, "parasmaipada", "bhaja", "serve, divide", "Dhatupatha 1.38", ()),
    ("kṛṣ", 1, "parasmaipada", "karṣati", "plow, draw", "Dhatupatha 1.39", ()),
    ("khād", 1, "parasmaipada", "khādati", "chew, eat", "Dhatupatha 1.40", ()),
    ("icch", 1, "parasmaipada", "iccha", "desire", "Dhatupatha 1.41", ()),
    ("vij", 1, "parasmaipada", "vijati", "win", "Dhatupatha 1.42", ()),
    ("śuc", 1, "parasmaipada", "śocati", "grieve, purify", "Dhatupatha 1.43", ()),
    ("īkṣ", 1, "parasmaipada", "īkṣa", "see", "Dhatupatha 1.44", ()),
    ("pat", 1, "parasmaipada", "patati", "fall, fly", "Dhatupatha 1.45", ()),
    ("sarp", 1, "parasmaipada", "sarati", "creep, go", "Dhatupatha 1.46", ()),
    ("kṣal", 1, "parasmaipada", "kṣalati", "wash", "Dhatupatha 1.47", ()),
    ("dhāv", 1, "parasmaipada", "dhāvati", "run", "Dhatupatha 1.48", ()),
    ("jay", 1, "parasmaipada", "jayati", "conquer", "Dhatupatha 1.49", ()),
    ("vṛdh", 1, "parasmaipada", "vardhaya", "increase", "Dhatupatha 1.50", ()),
    ("yaj", 1, "parasmaipada", "yajati", "sacrifice", "Dhatupatha 1.51", ()),
    ("kṛ", 1, "parasmaipada", "kuru", "do, make", "Dhatupatha 1.52", ("ñ",)),
    ("kṛ", 1, "atmanepada", "kurute", "do, make", "Dhatupatha 1.52", ("ñ",)),
    ("labh", 1, "atmanepada", "labhate", "obtain", "Dhatupatha 1.53", ("ṅ",)),
    ("ram", 1, "atmanepada", "ramate", "enjoy", "Dhatupatha 1.54", ()),
    ("ruc", 1, "atmanepada", "rocate", "shine, please", "Dhatupatha 1.55", ()),
    ("sah", 1, "atmanepada", "sahate", "endure", "Dhatupatha 1.56", ()),
    ("bhās", 1, "atmanepada", "bhāsate", "shine", "Dhatupatha 1.57", ()),
    ("budh", 1, "atmanepada", "budhyate", "awaken, know", "Dhatupatha 1.58", ()),
    ("cyu", 1, "atmanepada", "cyavate", "fall, move", "Dhatupatha 1.59", ()),
    ("kṣubh", 1, "atmanepada", "kṣubhyati", "be agitated", "Dhatupatha 1.60", ()),
    ("paś", 1, "parasmaipada", "paśya", "see", "Dhatupatha 1.61", ()),
    ("dṛś", 1, "parasmaipada", "paśya", "see", "Dhatupatha 1.62", ()),
    ("pracch", 1, "parasmaipada", "pṛccha", "ask", "Dhatupatha 1.63", ()),
    ("pṛch", 1, "parasmaipada", "pṛccha", "ask", "Dhatupatha 1.64", ()),
    ("iṣ", 1, "parasmaipada", "icchati", "desire", "Dhatupatha 1.65", ()),
    ("śī", 1, "parasmaipada", "śete", "lie, sleep", "Dhatupatha 1.66", ()),
    ("śay", 1, "parasmaipada", "śete", "lie down", "Dhatupatha 1.67", ()),
    ("mṛd", 1, "parasmaipada", "mṛdnāti", "crush, rub", "Dhatupatha 1.68", ()),
    ("tar", 1, "parasmaipada", "tṛṇoti", "cross", "Dhatupatha 1.69", ()),
    ("vraj", 1, "parasmaipada", "vraja", "walk, go", "Dhatupatha 1.70", ()),
    ("śak", 1, "parasmaipada", "śaknoti", "be able", "Dhatupatha 1.71", ()),
    ("luṭh", 1, "parasmaipada", "luṇṭhati", "roll, rob", "Dhatupatha 1.72", ()),
    ("luṭ", 1, "parasmaipada", "luṭati", "plunder", "Dhatupatha 1.73", ()),
    ("sphur", 1, "parasmaipada", "sphurati", "quiver, flash", "Dhatupatha 1.74", ()),
    ("sphā", 1, "atmanepada", "sphāyate", "expand", "Dhatupatha 1.75", ()),
    ("sphuṭ", 1, "parasmaipada", "sphuṭati", "burst open", "Dhatupatha 1.76", ()),
    ("edh", 1, "parasmaipada", "edhate", "grow, prosper", "Dhatupatha 1.77", ()),
    ("kṣi", 1, "parasmaipada", "kṣiṇoti", "waste, destroy", "Dhatupatha 1.78", ()),
    ("spṛh", 1, "parasmaipada", "spṛhati", "desire", "Dhatupatha 1.79", ()),
    ("tvar", 1, "parasmaipada", "tvarati", "hasten", "Dhatupatha 1.80", ()),
    ("īh", 1, "atmanepada", "īhate", "endeavor", "Dhatupatha 1.81", ()),
    ("bhūṣ", 1, "atmanepada", "bhūṣate", "adorn", "Dhatupatha 1.82", ()),
    ("phal", 1, "parasmaipada", "phalati", "bear fruit", "Dhatupatha 1.83", ()),
    ("bādh", 1, "parasmaipada", "bādhate", "press, harass", "Dhatupatha 1.84", ()),
    ("syand", 1, "parasmaipada", "syandate", "flow, trickle", "Dhatupatha 1.85", ()),
    ("śram", 1, "parasmaipada", "śramati", "toil", "Dhatupatha 1.86", ()),
    ("śliṣ", 1, "parasmaipada", "śliṣati", "embrace", "Dhatupatha 1.87", ()),
    ("skand", 1, "parasmaipada", "skandati", "leap, mount", "Dhatupatha 1.88", ()),
    ("skabh", 1, "parasmaipada", "skabhnāti", "prop, support", "Dhatupatha 1.89", ()),
    ("stab", 1, "parasmaipada", "stabhnāti", "fix, establish", "Dhatupatha 1.90", ()),
    ("stambh", 1, "parasmaipada", "stambhate", "become stiff", "Dhatupatha 1.91", ()),
    ("svan", 1, "parasmaipada", "svanati", "sound, roar", "Dhatupatha 1.92", ()),
    ("svar", 1, "parasmaipada", "svarati", "sing", "Dhatupatha 1.93", ()),
    ("tṛ", 1, "parasmaipada", "tṛṇoti", "cross", "Dhatupatha 1.94", ()),
    ("tras", 1, "parasmaipada", "trasati", "tremble", "Dhatupatha 1.95", ()),
    ("tras", 1, "atmanepada", "trasyate", "be frightened", "Dhatupatha 1.96", ()),
    ("tṛp", 1, "parasmaipada", "tarpati", "satisfy", "Dhatupatha 1.97", ()),
    ("śuc", 1, "atmanepada", "śucyate", "be pure", "Dhatupatha 1.98", ()),
    ("ruc", 1, "parasmaipada", "rocati", "shine", "Dhatupatha 1.99", ()),
    ("rakṣ", 1, "atmanepada", "rakṣate", "protect", "Dhatupatha 1.100", ()),
)

G2 = (
    ("ad", 2, "parasmaipada", "atti", "eat", "Dhatupatha 2.1", ()),
    ("han", 2, "parasmaipada", "hanti", "strike, kill", "Dhatupatha 2.2", ()),
    ("dviṣ", 2, "parasmaipada", "dveṣṭi", "hate", "Dhatupatha 2.3", ()),
    ("duh", 2, "parasmaipada", "dugdhi", "milk", "Dhatupatha 2.4", ()),
    ("dih", 2, "parasmaipada", "dehī", "smear", "Dhatupatha 2.5", ()),
    ("diś", 2, "parasmaipada", "diśati", "show, point", "Dhatupatha 2.6", ()),
    ("vid", 2, "parasmaipada", "vetti", "know", "Dhatupatha 2.7", ()),
    ("vid", 2, "atmanepada", "vinda", "find, know", "Dhatupatha 2.8", ()),
    ("i", 2, "parasmaipada", "eti", "go", "Dhatupatha 2.9", ()),
    ("i", 2, "atmanepada", "īte", "go", "Dhatupatha 2.10", ()),
    ("pib", 2, "parasmaipada", "pibati", "drink", "Dhatupatha 2.11", ()),
    ("brū", 2, "parasmaipada", "brūhi", "speak", "Dhatupatha 2.12", ()),
    ("stu", 2, "parasmaipada", "stauti", "praise", "Dhatupatha 2.13", ()),
    ("śru", 2, "parasmaipada", "śṛṇoti", "hear", "Dhatupatha 2.14", ()),
    ("av", 2, "parasmaipada", "unoti", "favor, protect", "Dhatupatha 2.15", ()),
    ("api", 2, "atmanepada", "apnute", "reach, obtain", "Dhatupatha 2.16", ()),
    ("āp", 2, "parasmaipada", "āpnoti", "obtain", "Dhatupatha 2.17", ()),
    ("śās", 2, "parasmaipada", "śāsti", "punish, teach", "Dhatupatha 2.18", ()),
    ("śiṣ", 2, "parasmaipada", "śāsti", "teach", "Dhatupatha 2.19", ()),
    ("adhi", 2, "atmanepada", "adhīte", "study", "Dhatupatha 2.20", ()),
    ("as", 2, "parasmaipada", "asti", "be", "Dhatupatha 2.21; MW", ()),
    ("as", 2, "atmanepada", "aste", "be", "Dhatupatha 2.22; MW", ()),
    ("svap", 2, "parasmaipada", "svapiti", "sleep", "Dhatupatha 2.23", ()),
    ("snā", 2, "parasmaipada", "snāti", "bathe", "Dhatupatha 2.24", ()),
    ("snā", 2, "atmanepada", "snāyate", "bathe", "Dhatupatha 2.25", ()),
    ("edh", 2, "parasmaipada", "edhate", "grow, prosper", "Dhatupatha 2.26", ()),
    ("ukṣ", 2, "parasmaipada", "ukṣati", "sprinkle", "Dhatupatha 2.27", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reason, infer", "Dhatupatha 2.28", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be inferred", "Dhatupatha 2.29", ()),
    ("ūr", 2, "parasmaipada", "ūrṇoti", "cover", "Dhatupatha 2.30", ()),
    ("ūḍh", 2, "parasmaipada", "ūḍhati", "bear", "Dhatupatha 2.31", ()),
    ("ūḍh", 2, "atmanepada", "ūḍhyate", "be borne", "Dhatupatha 2.32", ()),
    ("und", 2, "parasmaipada", "undati", "moisten", "Dhatupatha 2.33", ()),
    ("ubj", 2, "parasmaipada", "ubjati", "press", "Dhatupatha 2.34", ()),
    ("ubj", 2, "atmanepada", "ubjate", "be pressed", "Dhatupatha 2.35", ()),
    ("īkṣ", 2, "atmanepada", "īkṣate", "see", "Dhatupatha 2.36", ()),
    ("īh", 2, "atmanepada", "īhate", "endeavor", "Dhatupatha 2.37", ()),
    ("īḍ", 2, "parasmaipada", "īḍate", "praise", "Dhatupatha 2.38", ()),
    ("īr", 2, "parasmaipada", "īrṇoti", "set in motion", "Dhatupatha 2.39", ()),
    ("īr", 2, "atmanepada", "īryate", "be set in motion", "Dhatupatha 2.40", ()),
    ("iṣ", 2, "parasmaipada", "eṣati", "seek", "Dhatupatha 2.41", ()),
    ("iṣ", 2, "atmanepada", "iṣate", "seek", "Dhatupatha 2.42", ()),
    ("inv", 2, "parasmaipada", "invati", " bring", "Dhatupatha 2.43", ()),
    ("inv", 2, "atmanepada", "invate", "bring", "Dhatupatha 2.44", ()),
    ("ind", 2, "parasmaipada", "indati", "drop", "Dhatupatha 2.45", ()),
    ("ind", 2, "atmanepada", "indate", "drop", "Dhatupatha 2.46", ()),
    ("il", 2, "parasmaipada", "ilati", "go", "Dhatupatha 2.47", ()),
    ("il", 2, "atmanepada", "ilati", "go", "Dhatupatha 2.48", ()),
    ("ir", 2, "parasmaipada", "irṇoti", "set in motion", "Dhatupatha 2.49", ()),
    ("ir", 2, "atmanepada", "iryate", "move", "Dhatupatha 2.50", ()),
    ("is", 2, "parasmaipada", "isati", "move", "Dhatupatha 2.51", ()),
    ("is", 2, "atmanepada", "isate", "move", "Dhatupatha 2.52", ()),
    ("ukṣ", 2, "atmanepada", "ukṣate", "sprinkle", "Dhatupatha 2.53", ()),
    ("ud", 2, "parasmaipada", "unatti", "wet, bathe", "Dhatupatha 2.54", ()),
    ("ud", 2, "atmanepada", "udate", "be wet", "Dhatupatha 2.55", ()),
    ("ujjval", 2, "parasmaipada", "ujjvalati", "blaze up", "Dhatupatha 2.56", ()),
    ("ujjval", 2, "atmanepada", "ujjvalate", "blaze up", "Dhatupatha 2.57", ()),
    ("udbhū", 2, "parasmaipada", "udbhavati", "arise", "Dhatupatha 2.58", ()),
    ("udbhū", 2, "atmanepada", "udbhavate", "arise", "Dhatupatha 2.59", ()),
    ("udvij", 2, "parasmaipada", "udvejati", "agitate", "Dhatupatha 2.60", ()),
    ("udvij", 2, "atmanepada", "udvejate", "tremble", "Dhatupatha 2.61", ()),
    ("udvṛt", 2, "parasmaipada", "udvartati", "revolve", "Dhatupatha 2.62", ()),
    ("udvṛt", 2, "atmanepada", "udvartate", "turn", "Dhatupatha 2.63", ()),
    ("udvṛdh", 2, "parasmaipada", "udvṛdhate", "grow", "Dhatupatha 2.64", ()),
    ("udvṛdh", 2, "atmanepada", "udvṛdhate", "increase", "Dhatupatha 2.65", ()),
    ("udgā", 2, "parasmaipada", "udgāyati", "sing out", "Dhatupatha 2.66", ()),
    ("udgā", 2, "atmanepada", "udgāyate", "sing out", "Dhatupatha 2.67", ()),
    ("udjñā", 2, "parasmaipada", "udjānāti", "recognize", "Dhatupatha 2.68", ()),
    ("udjñā", 2, "atmanepada", "udjānīte", "recognize", "Dhatupatha 2.69", ()),
    ("uddiś", 2, "parasmaipada", "uddiśati", "point out", "Dhatupatha 2.70", ()),
    ("uddiś", 2, "atmanepada", "uddiśate", "point out", "Dhatupatha 2.71", ()),
    ("udbhid", 2, "parasmaipada", "udbhedi", "split open", "Dhatupatha 2.72", ()),
    ("udbhid", 2, "atmanepada", "udbhidyate", "split open", "Dhatupatha 2.73", ()),
    ("udman", 2, "parasmaipada", "udmanati", "grow", "Dhatupatha 2.74", ()),
    ("udman", 2, "atmanepada", "udmanate", "grow", "Dhatupatha 2.75", ()),
    ("udyan", 2, "parasmaipada", "udyati", "rise", "Dhatupatha 2.76", ()),
)

G3 = (
    ("hu", 3, "parasmaipada", "juhoti", "offer oblation", "Dhatupatha 3.1", ()),
    ("ju", 3, "parasmaipada", "juhoti", "offer", "Dhatupatha 3.1", ()),
    ("bhī", 3, "parasmaipada", "bibheti", "fear", "Dhatupatha 3.2", ()),
    ("hrī", 3, "parasmaipada", "jihrīyate", "be ashamed", "Dhatupatha 3.3", ()),
    ("dā", 3, "parasmaipada", "dadāti", "give", "Dhatupatha 3.4", ()),
    ("dhā", 3, "parasmaipada", "dadhāti", "place", "Dhatupatha 3.5", ()),
    ("dih", 3, "parasmaipada", "dehī", "smear", "Dhatupatha 3.6", ()),
    ("dhu", 3, "parasmaipada", "dhunoti", "shake", "Dhatupatha 3.7", ()),
    ("dhū", 3, "parasmaipada", "dhunoti", "shake, fumigate", "Dhatupatha 3.8", ()),
    ("do", 3, "parasmaipada", "dyoti", "shine", "Dhatupatha 3.9", ()),
    ("du", 3, "parasmaipada", "dunoti", "burn", "Dhatupatha 3.10", ()),
    ("gā", 3, "parasmaipada", "jigāti", "go", "Dhatupatha 3.11", ()),
    ("hā", 3, "atmanepada", "jihīte", "leave", "Dhatupatha 3.12", ()),
    ("hā", 3, "parasmaipada", "hātī", "leave", "Dhatupatha 3.13", ()),
    ("yā", 3, "parasmaipada", "yāti", "go", "Dhatupatha 3.14", ()),
    ("yā", 3, "atmanepada", "yāte", "go", "Dhatupatha 3.15", ()),
    ("ho", 3, "parasmaipada", "juhoti", "offer", "Dhatupatha 3.16", ()),
    ("hū", 3, "parasmaipada", "juhoti", "offer oblation", "Dhatupatha 3.17", ()),
    ("dhe", 3, "parasmaipada", "dadhāti", "place", "Dhatupatha 3.18", ()),
    ("dhai", 3, "parasmaipada", "dadhāti", "place", "Dhatupatha 3.19", ()),
    ("dho", 3, "parasmaipada", "dhāvati", "run", "Dhatupatha 3.20", ()),
    ("ghu", 3, "parasmaipada", "juhoti", "offer", "Dhatupatha 3.21", ()),
    ("ghrā", 3, "parasmaipada", "jighrati", "smell", "Dhatupatha 3.22", ()),
    ("ghrā", 3, "atmanepada", "ghrāyate", "smell", "Dhatupatha 3.23", ()),
    ("bhṛ", 3, "parasmaipada", "bibharti", "bear, carry", "Dhatupatha 3.24", ()),
    ("bhṛ", 3, "atmanepada", "bhṛyate", "be borne", "Dhatupatha 3.25", ()),
)

G4 = (
    ("div", 4, "parasmaipada", "dīvyati", "gamble, shine", "Dhatupatha 4.1", ()),
    ("nam", 4, "parasmaipada", "namati", "bow", "Dhatupatha 4.2", ()),
    ("śam", 4, "atmanepada", "śāmyati", "be pacified", "Dhatupatha 4.3", ()),
    ("sidh", 4, "atmanepada", "siddhyati", "succeed", "Dhatupatha 4.4", ()),
    ("tṛp", 4, "atmanepada", "tṛpyati", "be satisfied", "Dhatupatha 4.5", ()),
    ("dīp", 4, "atmanepada", "dīpyate", "shine", "Dhatupatha 4.6", ()),
    ("jā", 4, "atmanepada", "jāyate", "be born", "Dhatupatha 4.7", ()),
    ("yudh", 4, "atmanepada", "yudhyate", "fight", "Dhatupatha 4.8", ()),
    ("bhā", 4, "parasmaipada", "bhāti", "shine", "Dhatupatha 4.9", ()),
    ("bhram", 4, "parasmaipada", "bhramati", "wander, err", "Dhatupatha 4.10", ()),
    ("mūrch", 4, "parasmaipada", "mūrchati", "faint", "Dhatupatha 4.11", ()),
    ("vyadh", 4, "parasmaipada", "vidhyati", "pierce", "Dhatupatha 4.12", ()),
    ("chāy", 4, "parasmaipada", "chāyate", "become still", "Dhatupatha 4.13", ()),
    ("jṝ", 4, "parasmaipada", "jīryati", "grow old", "Dhatupatha 4.14", ()),
    ("śuṣ", 4, "parasmaipada", "śuṣyati", "dry", "Dhatupatha 4.15", ()),
    ("mā", 4, "atmanepada", "mimīte", "measure", "Dhatupatha 4.16", ()),
    ("īkṣ", 4, "atmanepada", "īkṣate", "see", "Dhatupatha 4.17", ()),
    ("spṛh", 4, "parasmaipada", "spṛhati", "desire", "Dhatupatha 4.18", ()),
    ("īh", 4, "atmanepada", "īhate", "endeavor", "Dhatupatha 4.19", ()),
    ("kṣip", 4, "parasmaipada", "kṣipati", "throw", "Dhatupatha 4.20", ()),
    ("kṣubh", 4, "atmanepada", "kṣubhyate", "be agitated", "Dhatupatha 4.21", ()),
    ("kṣam", 4, "parasmaipada", "kṣamate", "endure", "Dhatupatha 4.22", ()),
    ("kṣam", 4, "atmanepada", "kṣamyate", "forgive", "Dhatupatha 4.23", ()),
    ("śvas", 4, "parasmaipada", "śvasiti", "breathe", "Dhatupatha 4.24", ()),
    ("spand", 4, "parasmaipada", "spandate", "quiver", "Dhatupatha 4.25", ()),
    ("srak", 4, "parasmaipada", "srasati", "fall", "Dhatupatha 4.26", ()),
    ("sras", 4, "parasmaipada", "srasati", "fall", "Dhatupatha 4.27", ()),
    ("śrit", 4, "parasmaipada", "śrayate", "resort to", "Dhatupatha 4.28", ()),
    ("śri", 4, "parasmaipada", "śrayate", "resort to", "Dhatupatha 4.29", ()),
    ("śli", 4, "parasmaipada", "śliṣyati", "adhere", "Dhatupatha 4.30", ()),
    ("śvi", 4, "parasmaipada", "śveti", "swell", "Dhatupatha 4.31", ()),
    ("śvi", 4, "atmanepada", "śvayate", "grow", "Dhatupatha 4.32", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie down", "Dhatupatha 4.33", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie down", "Dhatupatha 4.34", ()),
    ("śī", 4, "parasmaipada", "śete", "lie, sleep", "Dhatupatha 4.35", ()),
    ("śī", 4, "atmanepada", "śete", "lie down", "Dhatupatha 4.36", ()),
    ("śu", 4, "parasmaipada", "śūyate", "be heard", "Dhatupatha 4.37", ()),
    ("śu", 4, "atmanepada", "śūyate", "be heard", "Dhatupatha 4.38", ()),
    ("śuc", 4, "parasmaipada", "śocati", "grieve", "Dhatupatha 4.39", ()),
    ("śuc", 4, "atmanepada", "śucyate", "be pure", "Dhatupatha 4.40", ()),
    ("śubh", 4, "parasmaipada", "śobhate", "shine", "Dhatupatha 4.41", ()),
    ("śubh", 4, "atmanepada", "śobhate", "shine", "Dhatupatha 4.42", ()),
    ("śru", 4, "parasmaipada", "śṛṇoti", "hear", "Dhatupatha 4.43", ()),
    ("śru", 4, "atmanepada", "śṛṇute", "hear", "Dhatupatha 4.44", ()),
    ("śrā", 4, "parasmaipada", "śrāyate", "warm", "Dhatupatha 4.45", ()),
    ("śrā", 4, "atmanepada", "śrāyate", "warm", "Dhatupatha 4.46", ()),
    ("śrī", 4, "parasmaipada", "śrayati", "resort to", "Dhatupatha 4.47", ()),
    ("śrī", 4, "atmanepada", "śrayate", "resort to", "Dhatupatha 4.48", ()),
    ("ślā", 4, "parasmaipada", "ślāghate", "praise", "Dhatupatha 4.49", ()),
    ("ślā", 4, "atmanepada", "ślāghate", "praise", "Dhatupatha 4.50", ()),
    ("ślath", 4, "parasmaipada", "ślathate", "be loose", "Dhatupatha 4.51", ()),
    ("ślath", 4, "atmanepada", "ślathate", "be loose", "Dhatupatha 4.52", ()),
    ("śliṣ", 4, "parasmaipada", "śliṣati", "embrace", "Dhatupatha 4.53", ()),
    ("śliṣ", 4, "atmanepada", "śliṣyate", "adhere", "Dhatupatha 4.54", ()),
    ("śvas", 4, "atmanepada", "śvasyate", "breathe", "Dhatupatha 4.55", ()),
    ("śvās", 4, "parasmaipada", "śvāsiti", "breathe", "Dhatupatha 4.56", ()),
    ("śvās", 4, "atmanepada", "śvāsyate", "breathe", "Dhatupatha 4.57", ()),
    ("śvitr", 4, "parasmaipada", "śvitrati", "become white", "Dhatupatha 4.58", ()),
    ("śvitr", 4, "atmanepada", "śvitrati", "become white", "Dhatupatha 4.59", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie", "Dhatupatha 4.60", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie", "Dhatupatha 4.61", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "sleep", "Dhatupatha 4.62", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "sleep", "Dhatupatha 4.63", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "rest", "Dhatupatha 4.64", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "rest", "Dhatupatha 4.65", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "repose", "Dhatupatha 4.66", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "repose", "Dhatupatha 4.67", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie down", "Dhatupatha 4.68", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie down", "Dhatupatha 4.69", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie still", "Dhatupatha 4.70", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie still", "Dhatupatha 4.71", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be still", "Dhatupatha 4.72", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be still", "Dhatupatha 4.73", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be quiet", "Dhatupatha 4.74", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be quiet", "Dhatupatha 4.75", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be calm", "Dhatupatha 4.76", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be calm", "Dhatupatha 4.77", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be at rest", "Dhatupatha 4.78", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be at rest", "Dhatupatha 4.79", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "recline", "Dhatupatha 4.80", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "recline", "Dhatupatha 4.81", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "repose", "Dhatupatha 4.82", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "repose", "Dhatupatha 4.83", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "sleep", "Dhatupatha 4.84", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "sleep", "Dhatupatha 4.85", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "rest", "Dhatupatha 4.86", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "rest", "Dhatupatha 4.87", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie", "Dhatupatha 4.88", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie", "Dhatupatha 4.89", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie down", "Dhatupatha 4.90", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie down", "Dhatupatha 4.91", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "lie still", "Dhatupatha 4.92", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "lie still", "Dhatupatha 4.93", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be still", "Dhatupatha 4.94", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be still", "Dhatupatha 4.95", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be quiet", "Dhatupatha 4.96", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be quiet", "Dhatupatha 4.97", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "be calm", "Dhatupatha 4.98", ()),
    ("śyā", 4, "atmanepada", "śyāyate", "be calm", "Dhatupatha 4.99", ()),
    ("śyā", 4, "parasmaipada", "śyāyate", "recline", "Dhatupatha 4.100", ()),
)

ALL_GANAS = (G1, G2, G3)
