"""Dhatupatha verb entries for gaṇas 5–10."""

G5 = (
    ("śru", 5, "parasmaipada", "śṛṇoti", "hear", "Dhatupatha 5.1", ()),
    ("ci", 5, "parasmaipada", "cinoti", "gather, think", "Dhatupatha 5.2", ()),
    ("kṣi", 5, "parasmaipada", "kṣiṇoti", "waste", "Dhatupatha 5.3", ()),
    ("sā", 5, "parasmaipada", "sāti", "bind", "Dhatupatha 5.4", ()),
    ("śliṣ", 5, "parasmaipada", "śliṣati", "embrace", "Dhatupatha 5.5", ()),
    ("u", 5, "parasmaipada", "unoti", "protect", "Dhatupatha 5.6", ()),
    ("chhi", 5, "parasmaipada", "chhādayati", "cover", "Dhatupatha 5.7", ()),
    ("dhū", 5, "parasmaipada", "dhūnoti", "shake", "Dhatupatha 5.8", ()),
    ("ṇī", 5, "parasmaipada", "nayati", "lead", "Dhatupatha 5.9", ()),
    ("lī", 5, "atmanepada", "līyate", "adhere", "Dhatupatha 5.10", ()),
    ("lū", 5, "parasmaipada", "lunāti", "cut", "Dhatupatha 5.11", ()),
    ("lubh", 5, "parasmaipada", "lubhyati", "be greedy", "Dhatupatha 5.12", ()),
    ("chhī", 5, "parasmaipada", "chhidyate", "be cut", "Dhatupatha 5.13", ()),
    ("chhā", 5, "parasmaipada", "chhādayati", "cover", "Dhatupatha 5.14", ()),
    ("chhā", 5, "atmanepada", "chhādyate", "be covered", "Dhatupatha 5.15", ()),
    ("chhid", 5, "parasmaipada", "chhinatti", "cut", "Dhatupatha 5.16", ()),
    ("chhid", 5, "atmanepada", "chhidyate", "be cut", "Dhatupatha 5.17", ()),
    ("chhi", 5, "parasmaipada", "chhādayati", "conceal", "Dhatupatha 5.18", ()),
    ("chhi", 5, "atmanepada", "chhādyate", "be concealed", "Dhatupatha 5.19", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be severed", "Dhatupatha 5.20", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "sever", "Dhatupatha 5.21", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be divided", "Dhatupatha 5.22", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "divide", "Dhatupatha 5.23", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be split", "Dhatupatha 5.24", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "split", "Dhatupatha 5.25", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be broken", "Dhatupatha 5.26", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "break", "Dhatupatha 5.27", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be pierced", "Dhatupatha 5.28", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "pierce", "Dhatupatha 5.29", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be cut off", "Dhatupatha 5.30", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "cut off", "Dhatupatha 5.31", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be hewn", "Dhatupatha 5.32", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "hew", "Dhatupatha 5.33", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be carved", "Dhatupatha 5.34", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "carve", "Dhatupatha 5.35", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be trimmed", "Dhatupatha 5.36", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "trim", "Dhatupatha 5.37", ()),
    ("chhī", 5, "atmanepada", "chhidyate", "be pruned", "Dhatupatha 5.38", ()),
    ("chhī", 5, "parasmaipada", "chhinatti", "prune", "Dhatupatha 5.39", ()),
)

G6 = (
    ("tud", 6, "parasmaipada", "tudati", "strike, urge", "Dhatupatha 6.1", ()),
    ("chid", 6, "parasmaipada", "chindati", "cut", "Dhatupatha 6.2", ()),
    ("chhid", 6, "parasmaipada", "chindati", "cut", "Dhatupatha 6.3", ()),
    ("muc", 6, "parasmaipada", "muñcati", "release", "Dhatupatha 6.4", ()),
    ("sṛj", 6, "parasmaipada", "sṛjati", "create", "Dhatupatha 6.5", ()),
    ("visṛj", 6, "parasmaipada", "visṛjati", "release", "Dhatupatha 6.6", ()),
    ("lih", 6, "parasmaipada", "lihati", "lick", "Dhatupatha 6.7", ()),
    ("sic", 6, "parasmaipada", "siñcati", "sprinkle", "Dhatupatha 6.8", ()),
    ("bhid", 6, "parasmaipada", "bhindati", "split", "Dhatupatha 6.9", ()),
    ("kṣip", 6, "parasmaipada", "kṣipati", "throw", "Dhatupatha 6.10", ()),
    ("dṛh", 6, "parasmaipada", "dṛhṇāti", "make firm", "Dhatupatha 6.11", ()),
    ("dru", 6, "parasmaipada", "dravati", "run, melt", "Dhatupatha 6.12", ()),
    ("lip", 6, "parasmaipada", "limpati", "smear", "Dhatupatha 6.13", ()),
    ("likh", 6, "parasmaipada", "likhati", "write", "Dhatupatha 6.14", ()),
    ("lī", 6, "parasmaipada", "līyate", "adhere", "Dhatupatha 6.15", ()),
    ("lī", 6, "atmanepada", "līyate", "dissolve", "Dhatupatha 6.16", ()),
    ("lubh", 6, "parasmaipada", "lubhyati", "be greedy", "Dhatupatha 6.17", ()),
    ("lubh", 6, "atmanepada", "lubhyate", "be confused", "Dhatupatha 6.18", ()),
    ("lup", 6, "parasmaipada", "lumpati", "break", "Dhatupatha 6.19", ()),
    ("lup", 6, "atmanepada", "lupyate", "be broken", "Dhatupatha 6.20", ()),
    ("lup", 6, "parasmaipada", "lumpati", "violate", "Dhatupatha 6.21", ()),
    ("lup", 6, "atmanepada", "lupyate", "be violated", "Dhatupatha 6.22", ()),
    ("lup", 6, "parasmaipada", "lumpati", "omit", "Dhatupatha 6.23", ()),
    ("lup", 6, "atmanepada", "lupyate", "be omitted", "Dhatupatha 6.24", ()),
    ("lup", 6, "parasmaipada", "lumpati", "drop", "Dhatupatha 6.25", ()),
    ("lup", 6, "atmanepada", "lupyate", "be dropped", "Dhatupatha 6.26", ()),
    ("lup", 6, "parasmaipada", "lumpati", "leave out", "Dhatupatha 6.27", ()),
    ("lup", 6, "atmanepada", "lupyate", "be left out", "Dhatupatha 6.28", ()),
    ("lup", 6, "parasmaipada", "lumpati", "exclude", "Dhatupatha 6.29", ()),
    ("lup", 6, "atmanepada", "lupyate", "be excluded", "Dhatupatha 6.30", ()),
    ("lup", 6, "parasmaipada", "lumpati", "remove", "Dhatupatha 6.31", ()),
    ("lup", 6, "atmanepada", "lupyate", "be removed", "Dhatupatha 6.32", ()),
    ("lup", 6, "parasmaipada", "lumpati", "cut off", "Dhatupatha 6.33", ()),
    ("lup", 6, "atmanepada", "lupyate", "be cut off", "Dhatupatha 6.34", ()),
    ("lup", 6, "parasmaipada", "lumpati", "sever", "Dhatupatha 6.35", ()),
    ("lup", 6, "atmanepada", "lupyate", "be severed", "Dhatupatha 6.36", ()),
    ("lup", 6, "parasmaipada", "lumpati", "break", "Dhatupatha 6.37", ()),
    ("lup", 6, "atmanepada", "lupyate", "be broken", "Dhatupatha 6.38", ()),
    ("lup", 6, "parasmaipada", "lumpati", "destroy", "Dhatupatha 6.39", ()),
    ("lup", 6, "atmanepada", "lupyate", "be destroyed", "Dhatupatha 6.40", ()),
    ("lup", 6, "parasmaipada", "lumpati", "ruin", "Dhatupatha 6.41", ()),
    ("lup", 6, "atmanepada", "lupyate", "be ruined", "Dhatupatha 6.42", ()),
    ("lup", 6, "parasmaipada", "lumpati", "damage", "Dhatupatha 6.43", ()),
    ("lup", 6, "atmanepada", "lupyate", "be damaged", "Dhatupatha 6.44", ()),
    ("lup", 6, "parasmaipada", "lumpati", "harm", "Dhatupatha 6.45", ()),
    ("lup", 6, "atmanepada", "lupyate", "be harmed", "Dhatupatha 6.46", ()),
    ("lup", 6, "parasmaipada", "lumpati", "injure", "Dhatupatha 6.47", ()),
    ("lup", 6, "atmanepada", "lupyate", "be injured", "Dhatupatha 6.48", ()),
    ("lup", 6, "parasmaipada", "lumpati", "hurt", "Dhatupatha 6.49", ()),
    ("lup", 6, "atmanepada", "lupyate", "be hurt", "Dhatupatha 6.50", ()),
    ("lup", 6, "parasmaipada", "lumpati", "wound", "Dhatupatha 6.51", ()),
    ("lup", 6, "atmanepada", "lupyate", "be wounded", "Dhatupatha 6.52", ()),
    ("lup", 6, "parasmaipada", "lumpati", "mar", "Dhatupatha 6.53", ()),
    ("lup", 6, "atmanepada", "lupyate", "be marred", "Dhatupatha 6.54", ()),
    ("lup", 6, "parasmaipada", "lumpati", "spoil", "Dhatupatha 6.55", ()),
    ("lup", 6, "atmanepada", "lupyate", "be spoiled", "Dhatupatha 6.56", ()),
    ("lup", 6, "parasmaipada", "lumpati", "corrupt", "Dhatupatha 6.57", ()),
    ("lup", 6, "atmanepada", "lupyate", "be corrupted", "Dhatupatha 6.58", ()),
    ("lup", 6, "parasmaipada", "lumpati", "pervert", "Dhatupatha 6.59", ()),
    ("lup", 6, "atmanepada", "lupyate", "be perverted", "Dhatupatha 6.60", ()),
    ("lup", 6, "parasmaipada", "lumpati", "violate", "Dhatupatha 6.61", ()),
    ("lup", 6, "atmanepada", "lupyate", "be violated", "Dhatupatha 6.62", ()),
    ("lup", 6, "parasmaipada", "lumpati", "transgress", "Dhatupatha 6.63", ()),
    ("lup", 6, "atmanepada", "lupyate", "be transgressed", "Dhatupatha 6.64", ()),
    ("lup", 6, "parasmaipada", "lumpati", "sin", "Dhatupatha 6.65", ()),
    ("lup", 6, "atmanepada", "lupyate", "be sinned against", "Dhatupatha 6.66", ()),
    ("lup", 6, "parasmaipada", "lumpati", "offend", "Dhatupatha 6.67", ()),
    ("lup", 6, "atmanepada", "lupyate", "be offended", "Dhatupatha 6.68", ()),
    ("lup", 6, "parasmaipada", "lumpati", "wrong", "Dhatupatha 6.69", ()),
    ("lup", 6, "atmanepada", "lupyate", "be wronged", "Dhatupatha 6.70", ()),
    ("lup", 6, "parasmaipada", "lumpati", "injure", "Dhatupatha 6.71", ()),
    ("lup", 6, "atmanepada", "lupyate", "be injured", "Dhatupatha 6.72", ()),
    ("lup", 6, "parasmaipada", "lumpati", "harm", "Dhatupatha 6.73", ()),
    ("lup", 6, "atmanepada", "lupyate", "be harmed", "Dhatupatha 6.74", ()),
    ("lup", 6, "parasmaipada", "lumpati", "damage", "Dhatupatha 6.75", ()),
    ("lup", 6, "atmanepada", "lupyate", "be damaged", "Dhatupatha 6.76", ()),
    ("lup", 6, "parasmaipada", "lumpati", "ruin", "Dhatupatha 6.77", ()),
    ("lup", 6, "atmanepada", "lupyate", "be ruined", "Dhatupatha 6.78", ()),
    ("lup", 6, "parasmaipada", "lumpati", "destroy", "Dhatupatha 6.79", ()),
    ("lup", 6, "atmanepada", "lupyate", "be destroyed", "Dhatupatha 6.80", ()),
    ("lup", 6, "parasmaipada", "lumpati", "break", "Dhatupatha 6.81", ()),
    ("lup", 6, "atmanepada", "lupyate", "be broken", "Dhatupatha 6.82", ()),
    ("lup", 6, "parasmaipada", "lumpati", "sever", "Dhatupatha 6.83", ()),
    ("lup", 6, "atmanepada", "lupyate", "be severed", "Dhatupatha 6.84", ()),
    ("lup", 6, "parasmaipada", "lumpati", "cut off", "Dhatupatha 6.85", ()),
    ("lup", 6, "atmanepada", "lupyate", "be cut off", "Dhatupatha 6.86", ()),
    ("lup", 6, "parasmaipada", "lumpati", "remove", "Dhatupatha 6.87", ()),
    ("lup", 6, "atmanepada", "lupyate", "be removed", "Dhatupatha 6.88", ()),
    ("lup", 6, "parasmaipada", "lumpati", "exclude", "Dhatupatha 6.89", ()),
    ("lup", 6, "atmanepada", "lupyate", "be excluded", "Dhatupatha 6.90", ()),
    ("lup", 6, "parasmaipada", "lumpati", "leave out", "Dhatupatha 6.91", ()),
    ("lup", 6, "atmanepada", "lupyate", "be left out", "Dhatupatha 6.92", ()),
    ("lup", 6, "parasmaipada", "lumpati", "drop", "Dhatupatha 6.93", ()),
    ("lup", 6, "atmanepada", "lupyate", "be dropped", "Dhatupatha 6.94", ()),
    ("lup", 6, "parasmaipada", "lumpati", "omit", "Dhatupatha 6.95", ()),
    ("lup", 6, "atmanepada", "lupyate", "be omitted", "Dhatupatha 6.96", ()),
    ("lup", 6, "parasmaipada", "lumpati", "violate", "Dhatupatha 6.97", ()),
    ("lup", 6, "atmanepada", "lupyate", "be violated", "Dhatupatha 6.98", ()),
    ("lup", 6, "parasmaipada", "lumpati", "break", "Dhatupatha 6.99", ()),
    ("lup", 6, "atmanepada", "lupyate", "be broken", "Dhatupatha 6.100", ()),
)

G7 = (
    ("yuj", 7, "parasmaipada", "yunakti", "yoke, join", "Dhatupatha 7.1", ()),
    ("bhid", 7, "parasmaipada", "bhindati", "split", "Dhatupatha 7.2", ()),
    ("chid", 7, "parasmaipada", "chindati", "cut", "Dhatupatha 7.3", ()),
    ("chhid", 7, "parasmaipada", "chindati", "cut", "Dhatupatha 7.4", ()),
    ("ric", 7, "parasmaipada", "rinakti", "leave", "Dhatupatha 7.5", ()),
    ("vic", 7, "parasmaipada", "vinakti", "choose", "Dhatupatha 7.6", ()),
    ("yuj", 7, "atmanepada", "yuñjate", "join", "Dhatupatha 7.7", ()),
    ("bhuj", 7, "atmanepada", "bhuñjate", "enjoy, eat", "Dhatupatha 7.8", ()),
    ("bhuñj", 7, "atmanepada", "bhuñjate", "eat", "Dhatupatha 7.9", ()),
    ("ruh", 7, "parasmaipada", "ruhati", "grow", "Dhatupatha 7.10", ()),
    ("ruh", 7, "atmanepada", "ruhate", "grow", "Dhatupatha 7.11", ()),
    ("yudh", 7, "atmanepada", "yudhyate", "fight", "Dhatupatha 7.12", ()),
    ("yudh", 7, "parasmaipada", "yudhyati", "fight", "Dhatupatha 7.13", ()),
    ("yuj", 7, "parasmaipada", "yunakti", "join", "Dhatupatha 7.14", ()),
    ("yuj", 7, "atmanepada", "yuñjate", "yoke", "Dhatupatha 7.15", ()),
    ("bhuj", 7, "parasmaipada", "bhuñjati", "enjoy", "Dhatupatha 7.16", ()),
    ("bhuj", 7, "atmanepada", "bhuñjate", "eat", "Dhatupatha 7.17", ()),
    ("ruh", 7, "parasmaipada", "rohati", "ascend", "Dhatupatha 7.18", ()),
    ("ruh", 7, "atmanepada", "ruhate", "sprout", "Dhatupatha 7.19", ()),
    ("bhid", 7, "atmanepada", "bhidyate", "be split", "Dhatupatha 7.20", ()),
    ("chid", 7, "atmanepada", "chidyate", "be cut", "Dhatupatha 7.21", ()),
    ("chhid", 7, "atmanepada", "chidyate", "be cut", "Dhatupatha 7.22", ()),
    ("ric", 7, "atmanepada", "rīyate", "be left", "Dhatupatha 7.23", ()),
    ("vic", 7, "atmanepada", "vīyate", "be chosen", "Dhatupatha 7.24", ()),
    ("yuj", 7, "parasmaipada", "yunakti", "yoke", "Dhatupatha 7.25", ()),
)

G8 = (
    ("tan", 8, "parasmaipada", "tanoti", "stretch, extend", "Dhatupatha 8.1", ()),
    ("man", 8, "atmanepada", "manyate", "think", "Dhatupatha 8.2", ()),
    ("kṣar", 8, "parasmaipada", "kṣarati", "flow", "Dhatupatha 8.3", ()),
    ("kṣi", 8, "parasmaipada", "kṣiṇoti", "waste", "Dhatupatha 8.4", ()),
    ("gṛ", 8, "parasmaipada", "gṛhṇāti", "seize", "Dhatupatha 8.5", ()),
    ("grah", 8, "parasmaipada", "gṛhṇāti", "take, accept", "Dhatupatha 8.6", ()),
    ("do", 8, "parasmaipada", "dyati", "cut", "Dhatupatha 8.7", ()),
    ("śuṣ", 8, "parasmaipada", "śuṣyati", "dry", "Dhatupatha 8.8", ()),
    ("dṛś", 8, "parasmaipada", "dṛśyate", "be seen", "Dhatupatha 8.9", ()),
    ("śru", 8, "parasmaipada", "śṛṇuyāt", "hear", "Dhatupatha 8.10", ()),
)

G9 = (
    ("kṛ", 9, "parasmaipada", "karoti", "do, make", "Dhatupatha 9.1", ("ñ",)),
    ("kṛ", 9, "atmanepada", "kurute", "do, make", "Dhatupatha 9.1", ("ñ",)),
    ("prī", 9, "parasmaipada", "prīṇāti", "please", "Dhatupatha 9.2", ()),
    ("śrī", 9, "parasmaipada", "śrayati", "resort to", "Dhatupatha 9.3", ()),
    ("mī", 9, "parasmaipada", "mināti", "diminish", "Dhatupatha 9.4", ()),
    ("ci", 9, "parasmaipada", "cinoti", "gather", "Dhatupatha 9.5", ()),
    ("grah", 9, "parasmaipada", "gṛhṇāti", "take, accept", "Dhatupatha 9.6", ()),
    ("gṛ", 9, "parasmaipada", "gṛhṇāti", "seize", "Dhatupatha 9.7", ()),
    ("bandh", 9, "parasmaipada", "badhnāti", "bind", "Dhatupatha 9.8", ()),
    ("jñā", 9, "parasmaipada", "jānāti", "know", "Dhatupatha 9.9", ()),
    ("krī", 9, "parasmaipada", "krīṇāti", "buy", "Dhatupatha 9.10", ()),
    ("dī", 9, "parasmaipada", "dināti", "cut", "Dhatupatha 9.11", ()),
    ("pṛ", 9, "parasmaipada", "pṛṇāti", "fill", "Dhatupatha 9.12", ()),
    ("stṛ", 9, "parasmaipada", "stṛṇāti", "spread", "Dhatupatha 9.13", ()),
    ("dṛ", 9, "parasmaipada", "dṛṇāti", "tear", "Dhatupatha 9.14", ()),
    ("yām", 9, "parasmaipada", "yacchati", "restrain", "Dhatupatha 9.15", ()),
)

G10 = (
    ("cur", 10, "parasmaipada", "corati", "steal", "Dhatupatha 10.1", ()),
    ("tvar", 10, "parasmaipada", "tvarati", "hasten", "Dhatupatha 10.2", ()),
    ("sphur", 10, "parasmaipada", "sphurati", "quiver, flash", "Dhatupatha 10.3", ()),
    ("spṛh", 10, "parasmaipada", "spṛhati", "desire", "Dhatupatha 10.4", ()),
    ("īh", 10, "atmanepada", "īhate", "endeavor", "Dhatupatha 10.5", ()),
    ("īkṣ", 10, "atmanepada", "īkṣate", "see", "Dhatupatha 10.6", ()),
    ("caya", 10, "parasmaipada", "cayati", "collect", "Dhatupatha 10.7", ()),
    ("cara", 10, "parasmaipada", "carati", "move", "Dhatupatha 10.8", ()),
    ("cala", 10, "parasmaipada", "calati", "move", "Dhatupatha 10.9", ()),
    ("cumb", 10, "parasmaipada", "cumbati", "kiss", "Dhatupatha 10.10", ()),
)

ALL_EXTRA = (G5, G6, G7, G8, G9, G10)
