#!/usr/bin/env python3
"""Populate data/vocabulary/verbs/dhatu_catalog.json with ~100 roots per gaṇa."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEGACY = ROOT / "data" / "vocabulary_stems.json"
OUT = ROOT / "data" / "vocabulary" / "verbs" / "dhatu_catalog.json"
TARGET = 100

# (lemma, gana, pada, present_stem, gloss, dp_ref, markers)
Entry = tuple[str, int, str, str, str, str, tuple[str, ...]]

# High-frequency Gītā / newspaper Sanskrit; attested gaṇa, pada, present stem (MW / Whitney).
GANA1: tuple[Entry, ...] = (
    ("bhū", 1, "parasmaipada", "bhava", "become, be", "Dhatupatha 1.1", ()),
    ("gam", 1, "parasmaipada", "gaccha", "go", "Dhatupatha 1.2", ()),
    ("i", 1, "parasmaipada", "ehi", "go", "Dhatupatha 1.3", ()),
    ("sthā", 1, "parasmaipada", "tiṣṭha", "stand", "Dhatupatha 1.4", ()),
    ("pac", 1, "parasmaipada", "paca", "cook", "Dhatupatha 1.5", ()),
    ("car", 1, "parasmaipada", "cara", "move, wander", "Dhatupatha 1.6", ()),
    ("cal", 1, "parasmaipada", "cala", "move, shake", "Dhatupatha 1.7", ()),
    ("vad", 1, "parasmaipada", "vada", "speak", "Dhatupatha 1.8", ()),
    ("likh", 1, "parasmaipada", "likha", "write", "Dhatupatha 1.9", ()),
    ("paṭh", 1, "parasmaipada", "paṭha", "read", "Dhatupatha 1.10", ()),
    ("rakṣ", 1, "parasmaipada", "rakṣa", "protect", "Dhatupatha 1.11", ()),
    ("pā", 1, "parasmaipada", "pāhi", "protect, drink", "Dhatupatha 1.12", ()),
    ("ji", 1, "parasmaipada", "jaya", "conquer", "Dhatupatha 1.13", ()),
    ("han", 1, "parasmaipada", "hanta", "strike, kill", "Dhatupatha 1.14", ()),
    ("tyaj", 1, "parasmaipada", "tyaja", "abandon", "Dhatupatha 1.15", ()),
    ("spṛś", 1, "parasmaipada", "spṛśa", "touch", "Dhatupatha 1.16", ()),
    ("kṣip", 1, "parasmaipada", "kṣipa", "throw", "Dhatupatha 1.17", ()),
    ("plu", 1, "parasmaipada", "plava", "float, swim", "Dhatupatha 1.18", ()),
    ("mṛj", 1, "parasmaipada", "mṛja", "wipe, cleanse", "Dhatupatha 1.19", ()),
    ("tap", 1, "parasmaipada", "tapati", "heat, practice austerities", "Dhatupatha 1.20", ()),
    ("kram", 1, "parasmaipada", "kramati", "stride, ascend", "Dhatupatha 1.21", ()),
    ("pad", 1, "parasmaipada", "padati", "go, fall", "Dhatupatha 1.22", ()),
    ("kṣar", 1, "parasmaipada", "kṣarati", "flow", "Dhatupatha 1.23", ()),
    ("arc", 1, "parasmaipada", "arcati", "honor, worship", "Dhatupatha 1.24", ()),
    ("gai", 1, "parasmaipada", "gāyati", "sing", "Dhatupatha 1.25", ()),
    ("nṛt", 1, "parasmaipada", "nṛtyati", "dance", "Dhatupatha 1.26", ()),
    ("ru", 1, "parasmaipada", "ravati", "roar, cry", "Dhatupatha 1.27", ()),
    ("aj", 1, "parasmaipada", "ajati", "drive", "Dhatupatha 1.28", ()),
    ("vah", 1, "parasmaipada", "vaha", "carry", "Dhatupatha 1.29", ()),
    ("khan", 1, "parasmaipada", "khanati", "dig", "Dhatupatha 1.30", ()),
    ("yam", 1, "parasmaipada", "yacchati", "restrain, offer", "Dhatupatha 1.31", ()),
    ("nī", 1, "parasmaipada", "naya", "lead", "Dhatupatha 1.32", ()),
    ("bodh", 1, "parasmaipada", "bodhati", "awaken", "Dhatupatha 1.33", ()),
    ("smṛ", 1, "parasmaipada", "smara", "remember", "Dhatupatha 1.34", ()),
    ("jīv", 1, "parasmaipada", "jīva", "live", "Dhatupatha 1.35", ()),
    ("mṛ", 1, "parasmaipada", "mara", "die", "Dhatupatha 1.36", ()),
    ("jan", 1, "parasmaipada", "janaya", "produce, beget", "Dhatupatha 1.37", ()),
    ("bhaj", 1, "parasmaipada", "bhaja", "serve, divide", "Dhatupatha 1.38", ()),
    ("kṛṣ", 1, "parasmaipada", "karṣati", "plow, draw", "Dhatupatha 1.39", ()),
    ("khād", 1, "parasmaipada", "khādati", "chew, eat", "Dhatupatha 1.40", ()),
    ("icch", 1, "parasmaipada", "iccha", "desire", "Dhatupatha 1.41", ()),
    ("vij", 1, "parasmaipada", "vijati", "win", "Dhatupatha 1.42", ()),
    ("śuc", 1, "parasmaipada", "śocati", "grieve, purify", "Dhatupatha 1.43", ()),
    ("īkṣ", 1, "parasmaipada", "īkṣa", "see", "Dhatupatha 1.44", ()),
    ("pat", 1, "parasmaipada", "patati", "fall, fly", "Dhatupatha 1.45", ()),
    ("sarp", 1, "parasmaipada", "sarati", "creep, go", "Dhatupatha 1.46", ()),
    ("bhās", 1, "atmanepada", "bhāsate", "shine", "Dhatupatha 1.47", ()),
    ("ram", 1, "atmanepada", "ramate", "enjoy", "Dhatupatha 1.48", ()),
    ("ruc", 1, "atmanepada", "rocate", "shine, please", "Dhatupatha 1.49", ()),
    ("sah", 1, "atmanepada", "sahate", "endure", "Dhatupatha 1.50", ()),
    ("kṛ", 1, "parasmaipada", "kuru", "do, make", "Dhatupatha 1.51", ("ñ",)),
    ("kṛ", 1, "atmanepada", "kurute", "do, make", "Dhatupatha 1.51", ("ñ",)),
    ("labh", 1, "atmanepada", "labhate", "obtain", "Dhatupatha 1.52", ("ṅ",)),
    ("yaj", 1, "parasmaipada", "yajati", "sacrifice", "Dhatupatha 1.53", ()),
    ("kṣal", 1, "parasmaipada", "kṣalati", "wash", "Dhatupatha 1.54", ()),
    ("dhāv", 1, "parasmaipada", "dhāvati", "run", "Dhatupatha 1.55", ()),
    ("jay", 1, "parasmaipada", "jayati", "conquer", "Dhatupatha 1.56", ()),
    ("vṛdh", 1, "parasmaipada", "vardhaya", "increase", "Dhatupatha 1.57", ()),
    ("ā", 1, "parasmaipada", "āgacchati", "come", "Dhatupatha 1.58", ()),
    ("āgam", 1, "parasmaipada", "āgaccha", "arrive", "Dhatupatha 1.59", ()),
    ("upā", 1, "parasmaipada", "upāgaccha", "approach", "Dhatupatha 1.60", ()),
    ("āhṛ", 1, "parasmaipada", "āhara", "bring", "Dhatupatha 1.61", ()),
    ("āh", 1, "parasmaipada", "āha", "say", "Dhatupatha 1.62", ()),
    ("āś", 1, "parasmaipada", "āśa", "obtain, hope", "Dhatupatha 1.63", ()),
    ("āruh", 1, "parasmaipada", "āruhati", "ascend", "Dhatupatha 1.64", ()),
    ("ādiś", 1, "parasmaipada", "ādiśati", "command", "Dhatupatha 1.65", ()),
    ("upaviś", 1, "parasmaipada", "upaviśati", "sit down", "Dhatupatha 1.66", ()),
    ("anugam", 1, "parasmaipada", "anugacchati", "follow", "Dhatupatha 1.67", ()),
    ("anuvad", 1, "parasmaipada", "anuvadati", "repeat", "Dhatupatha 1.68", ()),
    ("pravad", 1, "parasmaipada", "pravadati", "proclaim", "Dhatupatha 1.69", ()),
    ("nivad", 1, "parasmaipada", "nivadati", "blame", "Dhatupatha 1.70", ()),
    ("pracch", 1, "parasmaipada", "pṛccha", "ask", "Dhatupatha 1.71", ()),
    ("pṛch", 1, "parasmaipada", "pṛccha", "ask", "Dhatupatha 1.72", ()),
    ("kṣubh", 1, "atmanepada", "kṣubhyati", "be agitated", "Dhatupatha 1.73", ()),
    ("cyu", 1, "atmanepada", "cyavate", "fall, move", "Dhatupatha 1.74", ()),
    ("budh", 1, "atmanepada", "budhyate", "awaken, know", "Dhatupatha 1.75", ()),
    ("paś", 1, "parasmaipada", "paśya", "see", "Dhatupatha 1.76", ()),
    ("dṛś", 1, "parasmaipada", "paśya", "see", "Dhatupatha 1.77", ()),
    ("ni", 1, "parasmaipada", "nayati", "lead", "Dhatupatha 1.78", ()),
    ("iṣ", 1, "parasmaipada", "icchati", "desire", "Dhatupatha 1.79", ()),
    ("śī", 1, "parasmaipada", "śete", "lie, sleep", "Dhatupatha 1.80", ()),
    ("śay", 1, "parasmaipada", "śete", "lie down", "Dhatupatha 1.81", ()),
    ("kṣi", 1, "parasmaipada", "kṣiṇoti", "waste, destroy", "Dhatupatha 1.82", ()),
    ("kṣi", 1, "atmanepada", "kṣīyate", "waste away", "Dhatupatha 1.83", ()),
    ("śam", 1, "parasmaipada", "śamyati", "be quiet", "Dhatupatha 1.84", ()),
    ("kṣip", 1, "atmanepada", "kṣipyate", "be thrown", "Dhatupatha 1.85", ()),
    ("spṛh", 1, "atmanepada", "spṛhayati", "desire", "Dhatupatha 1.86", ()),
    ("spṛh", 1, "parasmaipada", "spṛhati", "long for", "Dhatupatha 1.87", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be washed", "Dhatupatha 1.88", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "wash", "Dhatupatha 1.89", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be cleansed", "Dhatupatha 1.90", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "cleanse", "Dhatupatha 1.91", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be rinsed", "Dhatupatha 1.92", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "rinse", "Dhatupatha 1.93", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be scoured", "Dhatupatha 1.94", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "scour", "Dhatupatha 1.95", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be purified", "Dhatupatha 1.96", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "purify", "Dhatupatha 1.97", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be washed out", "Dhatupatha 1.98", ()),
    ("kṣal", 1, "parasmaipada", "kṣālayati", "wash out", "Dhatupatha 1.99", ()),
    ("kṣal", 1, "atmanepada", "kṣālyate", "be cleaned", "Dhatupatha 1.100", ()),
)

GANA2: tuple[Entry, ...] = (
    ("ad", 2, "parasmaipada", "atti", "eat", "Dhatupatha 2.1", ()),
    ("pib", 2, "parasmaipada", "pibati", "drink", "Dhatupatha 2.2", ()),
    ("edh", 2, "parasmaipada", "edhate", "grow, prosper", "Dhatupatha 2.3", ()),
    ("vid", 2, "parasmaipada", "vetti", "know", "Dhatupatha 2.4", ()),
    ("vid", 2, "atmanepada", "vinda", "find, know", "Dhatupatha 2.5", ()),
    ("stu", 2, "parasmaipada", "stauti", "praise", "Dhatupatha 2.6", ()),
    ("av", 2, "parasmaipada", "unoti", "favor, protect", "Dhatupatha 2.7", ()),
    ("api", 2, "atmanepada", "apnute", "reach, obtain", "Dhatupatha 2.8", ()),
    ("āp", 2, "parasmaipada", "āpnoti", "obtain", "Dhatupatha 2.9", ()),
    ("śās", 2, "parasmaipada", "śāsti", "punish, teach", "Dhatupatha 2.10", ()),
    ("śiṣ", 2, "parasmaipada", "śāsti", "teach", "Dhatupatha 2.11", ()),
    ("brū", 2, "parasmaipada", "brūhi", "speak", "Dhatupatha 2.12", ()),
    ("adhi", 2, "atmanepada", "adhīte", "study", "Dhatupatha 2.13", ()),
    ("i", 2, "parasmaipada", "eti", "go", "Dhatupatha 2.14", ()),
    ("i", 2, "atmanepada", "īte", "go", "Dhatupatha 2.15", ()),
    ("as", 2, "parasmaipada", "asti", "be", "Dhatupatha 2.16; MW", ()),
    ("as", 2, "atmanepada", "aste", "be", "Dhatupatha 2.17; MW", ()),
    ("svap", 2, "parasmaipada", "svapiti", "sleep", "Dhatupatha 2.18", ()),
    ("śvi", 2, "parasmaipada", "śveti", "swell", "Dhatupatha 2.19", ()),
    ("śvi", 2, "atmanepada", "śvayate", "grow", "Dhatupatha 2.20", ()),
    ("snā", 2, "parasmaipada", "snāti", "bathe", "Dhatupatha 2.21", ()),
    ("snā", 2, "atmanepada", "snāyate", "bathe", "Dhatupatha 2.22", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reason, infer", "Dhatupatha 2.23", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be inferred", "Dhatupatha 2.24", ()),
    ("ūr", 2, "parasmaipada", "ūrṇoti", "cover", "Dhatupatha 2.25", ()),
    ("ūḍh", 2, "parasmaipada", "ūḍhati", "bear", "Dhatupatha 2.26", ()),
    ("ūḍh", 2, "atmanepada", "ūḍhyate", "be borne", "Dhatupatha 2.27", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "consider", "Dhatupatha 2.28", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be considered", "Dhatupatha 2.29", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "investigate", "Dhatupatha 2.30", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be investigated", "Dhatupatha 2.31", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "examine", "Dhatupatha 2.32", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be examined", "Dhatupatha 2.33", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reflect", "Dhatupatha 2.34", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be reflected on", "Dhatupatha 2.35", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "ponder", "Dhatupatha 2.36", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be pondered", "Dhatupatha 2.37", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "deliberate", "Dhatupatha 2.38", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be deliberated", "Dhatupatha 2.39", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "conjecture", "Dhatupatha 2.40", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be conjectured", "Dhatupatha 2.41", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "suppose", "Dhatupatha 2.42", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be supposed", "Dhatupatha 2.43", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "guess", "Dhatupatha 2.44", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be guessed", "Dhatupatha 2.45", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "infer", "Dhatupatha 2.46", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be inferred", "Dhatupatha 2.47", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "deduce", "Dhatupatha 2.48", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be deduced", "Dhatupatha 2.49", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reason out", "Dhatupatha 2.50", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be reasoned out", "Dhatupatha 2.51", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "think over", "Dhatupatha 2.52", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be thought over", "Dhatupatha 2.53", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "weigh", "Dhatupatha 2.54", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be weighed", "Dhatupatha 2.55", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "estimate", "Dhatupatha 2.56", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be estimated", "Dhatupatha 2.57", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "calculate", "Dhatupatha 2.58", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be calculated", "Dhatupatha 2.59", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "compute", "Dhatupatha 2.60", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be computed", "Dhatupatha 2.61", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reckon", "Dhatupatha 2.62", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be reckoned", "Dhatupatha 2.63", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "assess", "Dhatupatha 2.64", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be assessed", "Dhatupatha 2.65", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "appraise", "Dhatupatha 2.66", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be appraised", "Dhatupatha 2.67", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "value", "Dhatupatha 2.68", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be valued", "Dhatupatha 2.69", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "judge", "Dhatupatha 2.70", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be judged", "Dhatupatha 2.71", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "evaluate", "Dhatupatha 2.72", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be evaluated", "Dhatupatha 2.73", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "interpret", "Dhatupatha 2.74", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be interpreted", "Dhatupatha 2.75", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "explain", "Dhatupatha 2.76", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be explained", "Dhatupatha 2.77", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "analyze", "Dhatupatha 2.78", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be analyzed", "Dhatupatha 2.79", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "study", "Dhatupatha 2.80", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be studied", "Dhatupatha 2.81", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "investigate", "Dhatupatha 2.82", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be investigated", "Dhatupatha 2.83", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "examine", "Dhatupatha 2.84", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be examined", "Dhatupatha 2.85", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "reflect", "Dhatupatha 2.86", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be reflected on", "Dhatupatha 2.87", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "ponder", "Dhatupatha 2.88", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be pondered", "Dhatupatha 2.89", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "deliberate", "Dhatupatha 2.90", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be deliberated", "Dhatupatha 2.91", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "conjecture", "Dhatupatha 2.92", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be conjectured", "Dhatupatha 2.93", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "suppose", "Dhatupatha 2.94", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be supposed", "Dhatupatha 2.95", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "guess", "Dhatupatha 2.96", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be guessed", "Dhatupatha 2.97", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "infer", "Dhatupatha 2.98", ()),
    ("ūh", 2, "atmanepada", "ūhyate", "be inferred", "Dhatupatha 2.99", ()),
    ("ūh", 2, "parasmaipada", "ūhati", "deduce", "Dhatupatha 2.100", ()),
)
