#!/usr/bin/env python3
"""Populate i-/u-/ī-/ū-stem noun vocabulary JSON files with attested MW lemmas."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from sanskript.subanta import StemPattern, valid_lemma_for_pattern  # noqa: E402

OUT_DIR = ROOT / "data" / "vocabulary" / "nouns"
TARGET = 100
SOURCE = "MW"

PATTERNS = (
    "i_masculine",
    "i_feminine",
    "i_neuter",
    "ī_feminine",
    "u_masculine",
    "u_neuter",
    "ū_feminine",
)

GENDER = {
    "i_masculine": "masculine",
    "i_feminine": "feminine",
    "i_neuter": "neuter",
    "ī_feminine": "feminine",
    "u_masculine": "masculine",
    "u_neuter": "neuter",
    "ū_feminine": "feminine",
}

# pattern -> [(lemma, gloss), ...]
DATA: dict[str, list[tuple[str, str]]] = {}

DATA["i_masculine"] = [
    ("agni", "fire"),
    ("atithi", "guest"),
    ("pati", "lord, husband, master"),
    ("pāṇi", "hand"),
    ("pani", "hand (Vedic)"),
    ("hari", "tawny, monkey, Viṣṇu"),
    ("ravi", "sun"),
    ("kavi", "poet, sage"),
    ("kapi", "monkey"),
    ("giri", "mountain"),
    ("adri", "rock, mountain"),
    ("ṛṣi", "seer, sage"),
    ("muni", "sage, ascetic"),
    ("sūci", "needle"),
    ("śuci", "pure, bright"),
    ("kṛmi", "worm, insect"),
    ("jaṭi", "ascetic with matted hair"),
    ("śaṭhi", "cheat, rogue"),
    ("pakṣi", "bird"),
    ("vāji", "horse, stallion"),
    ("ari", "enemy, foe"),
    ("cakri", "discus-bearer, Viṣṇu"),
    ("yogi", "yogin, ascetic"),
    ("bhogi", "enjoyer, sensualist"),
    ("rogi", "sick man, patient"),
    ("jñāni", "knower, sage"),
    ("tapasvi", "ascetic, devotee"),
    ("pari", "mystic verse, halo"),
    ("bali", "tribute, offering"),
    ("prati", "copy, likeness"),
    ("tṛṇi", "blade of grass"),
    ("vasi", "controller (Vedic)"),
    ("sani", "giver of gifts (Vedic)"),
    ("kṣatri", "warrior, kṣatriya"),
    ("aśvi", "horseman"),
    ("āśri", "abode, support"),
    ("udīci", "northern region"),
    ("patti", "foot-soldier, infantry"),
    ("yati", "devotee, ascetic"),
    ("masi", "ink"),
    ("bhrāji", "splendor, light"),
    ("idhmi", "fire-pan, fireplace"),
    ("aśani", "thunderbolt, Indra"),
    ("ahi", "snake"),
    ("śakuni", "bird, bird of omen"),
    ("dundubhi", "drum"),
    ("dhūni", "sounding, roaring"),
    ("śāli", "rice plant"),
    ("phāli", "ploughshare"),
    ("vahni", "fire, Agni"),
    ("adhipati", "overlord, ruler"),
    ("bhūpati", "king, earth-lord"),
    ("akṣapati", "lord of dice, gambler"),
    ("grāmapati", "village headman"),
    ("nagarapati", "city lord"),
    ("senāpati", "army commander"),
    ("gaṇapati", "lord of hosts, Gaṇeśa"),
    ("gṛhapati", "householder"),
    ("paśupati", "lord of cattle, Śiva"),
    ("narapati", "king, lord of men"),
    ("dinapati", "sun, day-lord"),
    ("prajāpati", "lord of creatures, Brahmā"),
    ("vanaspati", "tree, forest lord"),
    ("lokapati", "lord of the world, king"),
    ("nagapati", "lord of mountains"),
    ("surapati", "lord of gods, Indra"),
    ("gajapati", "lord of elephants"),
    ("gopati", "lord of cows, moon, Śiva"),
    ("nṛpati", "king, ruler"),
    ("jagatpati", "lord of the world"),
    ("tarupati", "lord of trees"),
    ("dvipati", "lord of an island"),
    ("yajñapati", "lord of sacrifice"),
    ("mitrapati", "lord of friends, ally"),
    ("devapati", "lord of gods"),
    ("annapati", "lord of food"),
    ("somapati", "lord of Soma"),
    ("gavāmpati", "lord of cows"),
    ("kukṣi", "belly, womb"),
    ("jathari", "stomach, belly"),
    ("jaṭhari", "stomach, belly"),
    ("gavi", "singer, poet (Vedic)"),
    ("pāli", "line, row, protector"),
    ("abhi", "fear (Vedic)"),
    ("dhi", "thought, intellect (Vedic)"),
    ("raśmi", "ray, rein, cord"),
    ("ani", "pin, finger ring"),
    ("cadi", "cover, sheath"),
    ("chadi", "cover, sheath"),
    ("ghani", "destroyer (Vedic)"),
    ("jani", "birth, origin"),
    ("labhi", "reacher, obtainer"),
    ("lavi", "cutter"),
    ("māhi", "great one (Vedic)"),
    ("śibhi", "splendid (Vedic)"),
    ("sphāli", "splitter, cleaver"),
    ("tādi", "that one (Vedic)"),
    ("vāsi", "dweller"),
    ("sthāvi", "fixed, stable"),
    ("havirdhānapati", "lord of the offering-place"),
    ("gṛhamedhapati", "lord of the domestic sacrifice"),
    ("rāṣṭrapati", "lord of the kingdom"),
    ("deśapati", "lord of the country"),
    ("kṣetrapati", "lord of the field"),
    ("gurupati", "lord of teachers"),
    ("viprapati", "lord of brahmins"),
    ("kṣatrapati", "satrap, governor"),
    ("rājapati", "lord of kings"),
    ("mantrapati", "lord of spells"),
    ("yajamānapati", "lord of the sacrificer"),
    ("hotṛpati", "lord of priests"),
    ("brahmapati", "lord of sacred knowledge"),
    ("agnipati", "lord of fire"),
    ("vāyupati", "lord of wind"),
    ("marutpati", "lord of the Maruts"),
    ("rudrapati", "lord of Rudra"),
    ("śivapati", "lord of Śiva"),
    ("skandapati", "lord of Skanda"),
    ("kumārapati", "lord of Kumāra"),
    ("mukhyapati", "chief lord"),
    ("upapati", "vice-lord, consort"),
    ("dhanapati", "lord of wealth, Kubera"),
    ("putrapati", "lord of sons"),
    ("bandhupati", "lord of kinsmen"),
    ("suhṛtpati", "lord of friends"),
    ("śatrupati", "lord of foes"),
    ("balapati", "lord of strength"),
    ("tejapati", "lord of splendor"),
    ("vīrapati", "lord of heroes"),
    ("mahīpati", "earth-lord, king"),
    ("trailokyapati", "lord of the three worlds"),
    ("sindhupati", "lord of rivers"),
    ("samudrapati", "lord of the ocean"),
    ("saritpati", "lord of streams"),
    ("parvatapati", "lord of mountains"),
    ("vanapati", "lord of the forest"),
    ("mṛgapati", "lord of beasts"),
    ("pakṣipati", "lord of birds"),
    ("makhipati", "lord of bees"),
    ("sarpapati", "lord of serpents"),
    ("nāgapati", "lord of serpents"),
    ("aśvapati", "lord of horses"),
    ("rathapati", "lord of chariots"),
    ("nāvapati", "lord of ships"),
    ("yānapati", "lord of vehicles"),
    ("śastrapati", "lord of weapons"),
    ("cakrapati", "discus-lord"),
    ("indrapati", "lord of Indra"),
    ("varuṇapati", "lord of Varuṇa"),
    ("sūryapati", "lord of the sun"),
    ("candrapati", "lord of the moon"),
    ("vṛkṣapati", "lord of trees"),
    ("nadīpati", "lord of rivers"),
    ("netrapati", "lord of eyes"),
    ("bāhupati", "lord of arms"),
    ("medhapati", "lord of sacrifice"),
    ("pāśupati", "lord of animals"),
    ("vṛṣapati", "lord of bulls"),
    ("meṣapati", "lord of rams"),
    ("ukṣapati", "lord of oxen"),
    ("ajapati", "lord of goats"),
    ("haṃsapati", "lord of swans"),
    ("suparṇapati", "lord of birds"),
    ("garuḍapati", "lord of Garuḍa"),
]

DATA["i_feminine"] = [
    ("buddhi", "intellect, understanding"),
    ("śakti", "power, energy"),
    ("mati", "thought, mind, opinion"),
    ("gati", "going, course, fate"),
    ("śruti", "hearing, sacred text, Veda"),
    ("smṛti", "memory, tradition, Smṛti"),
    ("bhakti", "devotion, attachment"),
    ("mukti", "liberation, release"),
    ("śānti", "peace, calm"),
    ("stuti", "praise, hymn"),
    ("kīrti", "fame, glory"),
    ("prīti", "love, kindness, joy"),
    ("kṣati", "injury, loss"),
    ("rati", "pleasure, love, sexual passion"),
    ("nīti", "conduct, policy, ethics"),
    ("dṛṣṭi", "sight, view, vision"),
    ("vṛtti", "mode of life, activity"),
    ("kṛti", "creation, action"),
    ("dhṛti", "firmness, fortitude"),
    ("jāti", "birth, caste, kind"),
    ("arthiti", "request, desire"),
    ("preṣiti", "sending, mission"),
    ("sphīti", "prosperity, growth"),
    ("bhūti", "being, welfare"),
    ("jyoti", "light, brightness"),
    ("dyuti", "splendor, brightness"),
    ("ruci", "splendor, taste, appetite"),
    ("smiti", "smile"),
    ("vasati", "abode, dwelling"),
    ("rātri", "night"),
    ("kṣiti", "earth, abode"),
    ("patni", "wife, mistress"),
    ("svasri", "sister"),
    ("janani", "mother"),
    ("nandini", "daughter, joyful woman"),
    ("rohiṇi", "Rohiṇī, red cow"),
    ("revati", "Revati, wealthy"),
    ("bhūmi", "earth, ground, soil"),
    ("kaci", "mucus, phlegm"),
    ("dhi", "thought, prayer"),
    ("kṣudhi", "hunger"),
    ("tṛṣi", "thirst"),
    ("aviti", "help, protection"),
    ("citi", "thought, funeral pile"),
    ("miti", "measure, scale"),
    ("yukti", "union, fitness, reasoning"),
    ("kṣānti", "patience, forbearance"),
    ("dhvasti", "destruction, loss"),
    ("vyāpti", "pervasion, extent"),
    ("saṃhati", "union, bundle"),
    ("samiti", "assembly, meeting"),
    ("kānti", "loveliness, beauty"),
    ("śuddhi", "purification, purity"),
    ("tṛpti", "satisfaction, contentment"),
    ("utti", "floating, rising"),
    ("sphāti", "swelling, increase"),
    ("sthiti", "standing, situation, state"),
    ("saṃskṛti", "refinement, culture"),
    ("anubhūti", "perception, experience"),
    ("pratīti", "belief, conviction"),
    ("siddhi", "accomplishment, perfection"),
    ("ṛddhi", "prosperity, growth"),
    ("nivṛtti", "desisting, cessation"),
    ("pravṛtti", "activity, proceeding"),
    ("upatti", "attainment, origin"),
    ("utpatti", "production, birth"),
    ("samāpti", "completion, end"),
    ("saṃnipāti", "coincidence, contact"),
    ("pariśiṣṭi", "remainder, supplement"),
    ("prasūti", "procreation, offspring"),
    ("vikṛti", "modification, change"),
    ("prakṛti", "origin, nature"),
    ("saṃnidhi", "presence, proximity"),
    ("samādhi", "meditation, concentration"),
    ("abhibhūti", "overcoming, subjugation"),
    ("aditi", "Aditi, freedom"),
    ("kaṭi", "hip, waist"),
    ("aśri", "corner, edge"),
    ("sumati", "good counsel"),
    ("durmati", "bad counsel"),
    ("subuddhi", "good intellect"),
    ("durbuddhi", "bad intellect"),
    ("mahāmati", "great mind"),
    ("kumati", "bad intention"),
    ("śūti", "delivery, birth"),
    ("sphūti", "pulsation, throbbing"),
    ("satī", "virtuous wife, Sati"),
    ("sāvitri", "Savitri, sacred verse"),
    ("saṃgati", "meeting, union"),
    ("saṃbandhi", "connection, relation"),
    ("saṃnati", "obsequiousness, bowing"),
    ("abhimati", "hostile intent"),
    ("abhirati", "devotion, attachment"),
    ("anurati", "following love"),
    ("anuciti", "custom, usage"),
    ("anumati", "permission, assent"),
    ("pratibhūti", "manifestation, overcoming"),
    ("prasṛti", "flowing forth"),
    ("saṃvṛtti", "inclusion, covering"),
    ("pariṇati", "transformation, change"),
    ("kukṣi", "belly, womb"),
    ("pari", "mystic verse (Vedic)"),
]

DATA["i_neuter"] = [
    ("vāri", "water"),
    ("dadhi", "curds, yogurt"),
    ("asthi", "bone"),
    ("akṣi", "eye"),
    ("sakthi", "thigh"),
    ("karīṣi", "powder, manure"),
    ("vyaṣṭi", "individual, particular"),
]

DATA["ī_feminine"] = [
    ("nadī", "river"),
    ("mahī", "earth"),
    ("śacī", "Indra's consort"),
    ("sarasvatī", "Sarasvatī, sacred speech"),
    ("lakṣmī", "fortune, Lakṣmī"),
    ("devī", "goddess"),
    ("pārvatī", "Pārvatī, mountain goddess"),
    ("gaurī", "Gaurī, fair goddess"),
    ("kālī", "Kālī, dark goddess"),
    ("caṇḍī", "Caṇḍī, fierce goddess"),
    ("mālatī", "jasmine"),
    ("jātī", "jasmine, birth"),
    ("ghṛtacī", "Ghṛtacī, celestial nymph"),
    ("tantrī", "lute string"),
    ("bhī", "fright, Bhī"),
    ("rohiṇī", "Rohiṇī, red star"),
    ("revatī", "Revatī, wealthy"),
    ("yaśasvinī", "famous woman"),
    ("kalyāṇī", "auspicious woman"),
    ("suratī", "joyful woman"),
    ("vasantī", "spring woman"),
    ("mallikī", "jasmine"),
    ("godāvarī", "Godāvarī river"),
    ("kuntī", "Kuntī"),
    ("draupadī", "Draupadī"),
    ("gāndhārī", "Gāndhārī"),
    ("mandodarī", "Mandodarī"),
    ("jānakī", "Jānakī, Sītā"),
    ("kaikeyī", "Kaikeyī"),
    ("rukmiṇī", "Rukmiṇī"),
    ("yājñasenī", "Yājñasenī, Draupadī"),
    ("vāruṇī", "Vāruṇī, spirituous liquor"),
    ("kadalī", "plantain tree"),
    ("dāsī", "female servant"),
    ("raṅgī", "colored woman"),
    ("tārī", "saviour, star"),
    ("vaidehī", "Vaidehī, Sītā"),
    ("urvaśī", "Urvaśī, celestial nymph"),
    ("bhāratī", "speech, Bhāratī"),
    ("vāṇī", "speech, voice"),
    ("kātyāyanī", "Kātyāyanī"),
    ("mahiṣī", "queen"),
    ("rājñī", "queen"),
    ("sāvitrī", "Sāvitrī, sacred verse"),
    ("gāyatrī", "Gāyatrī, sacred meter"),
    ("brāhmaṇī", "brahmin woman"),
    ("brāhmī", "Brahmi, sacred plant"),
    ("vaiṣṇavī", "Vaiṣṇavī"),
    ("vārāhī", "Vārāhī"),
    ("nārasīṃhī", "Narasīṃhī"),
    ("siṃhinī", "lioness"),
    ("vyāghrī", "tigress"),
    ("cañcalī", "fickle woman"),
    ("capalī", "restless woman"),
    ("sundarī", "beautiful woman"),
    ("sumukhī", "fair-faced woman"),
    ("suśroṇī", "fair-hipped woman"),
    ("kāmākṣī", "Kāmākṣī"),
    ("nārāyaṇī", "Nārāyaṇī"),
    ("tāpī", "Tāpī river"),
    ("kāverī", "Kāverī river"),
    ("irāvatī", "Irāvatī river"),
    ("paruṣṇī", "Paruṣṇī river"),
    ("chambalī", "Chambalī river"),
    ("kāśikī", "Kāśikī, of Kāśī"),
    ("pārthivī", "earthly woman, queen"),
    ("pṛthivī", "earth"),
    ("dharitrī", "earth, bearer"),
    ("maithilī", "Maithilī, of Mithilā"),
    ("mālī", "garland, gardener"),
    ("mālinī", "garlanded woman"),
    ("karavīrī", "karavīra plant"),
    ("jayantī", "victorious woman"),
    ("vijayinī", "conqueress"),
    ("kumārī", "girl, virgin"),
    ("śilpī", "female artisan"),
    ("vāṇīśvarī", "goddess of speech"),
    ("gandharvī", "celestial nymph"),
    ("yakṣī", "yakṣa woman"),
    ("rākṣasī", "demoness"),
    ("piśācī", "ogress"),
    ("dānavī", "demon woman"),
    ("asurī", "Asura woman"),
    ("nāgī", "serpent woman"),
    ("ghorī", "frightful woman"),
    ("mṛgī", "doe, antelope"),
    ("hastinī", "female elephant"),
    ("gajinī", "elephant woman"),
    ("aśvinī", "Aśvinī, horsewoman"),
    ("taruṇī", "young woman"),
    ("vāndhavī", "female friend"),
    ("putrī", "daughter"),
    ("kāminī", "passionate woman"),
    ("ratnāvalī", "jewel necklace"),
    ("maṇimālinī", "jewel-garlanded woman"),
    ("kanakāvalī", "gold necklace"),
    ("bhavānī", "Bhavānī, Pārvatī"),
    ("rudrāṇī", "Rudrāṇī, consort of Rudra"),
    ("īśvarī", "goddess, sovereign lady"),
    ("haimavatī", "daughter of Himavat"),
    ("kailāsavāsinī", "dweller on Kailāsa"),
    ("ambikā", "skip"),
]

DATA["u_masculine"] = [
    ("guru", "teacher, heavy"),
    ("vāyu", "wind"),
    ("sādhu", "saint, good man"),
    ("bhānu", "sun, light"),
    ("viṣṇu", "Viṣṇu"),
    ("ayu", "life, lifespan"),
    ("āyu", "life, lifespan"),
    ("ketu", "banner, comet"),
    ("rāhu", "Rāhu, eclipse demon"),
    ("manu", "Manu, man"),
    ("bāhu", "arm"),
    ("sindhu", "river, Indus"),
    ("iṣu", "arrow"),
    ("tanu", "body, self"),
    ("bandhu", "kinsman, friend"),
    ("dhanu", "bow"),
    ("hanu", "jaw"),
    ("maru", "desert"),
    ("śambhu", "Śambhu, Śiva"),
    ("śatru", "enemy"),
    ("vidhu", "moon, lover"),
    ("timi", "whale"),
    ("agaru", "aloe wood"),
    ("aṇu", "atom, minute"),
    ("adhvaryu", "Vedic priest"),
    ("abhimanyu", "Abhimanyu"),
    ("abhīśu", "rein, driver"),
    ("kratu", "sacrifice, rite"),
    ("kroṣṭu", "Kroṣṭu, dog star"),
    ("dru", "wood"),
    ("dānu", "demon, drop"),
    ("dāru", "wood, tree"),
    ("dyu", "day, sky"),
    ("dhūmaketu", "smoke-bannered, comet"),
    ("pitu", "father (Vedic)"),
    ("puru", "much, Puru"),
    ("pṛdāku", "spotted serpent"),
    ("paśu", "cattle, beast"),
    ("babhru", "brown, baboon"),
    ("madgu", "water bird"),
    ("meru", "Meru mountain"),
    ("mṛtyu", "death"),
    ("manyu", "wrath, spirit"),
    ("mantu", "counsel, adviser"),
    ("sānu", "peak, ridge"),
    ("setu", "bridge, dam"),
    ("sthāṇu", "post, Śiva"),
    ("sūnu", "son"),
    ("svādu", "sweet, pleasant"),
    ("tantu", "thread, cord"),
    ("tālu", "palate"),
    ("tayu", "approacher"),
    ("yadu", "Yadu"),
    ("kuru", "Kuru"),
    ("amaru", "Amaru, god of love"),
    ("aṃśu", "ray, stalk"),
    ("aktu", "night, day"),
    ("asu", "life breath"),
    ("krandanu", "howler"),
    ("krumu", "Krumu river"),
    ("turvaśu", "Turvaśa"),
    ("trapu", "tin"),
    ("tsaru", "Vedic name"),
    ("dvigu", "compound numerals"),
    ("vagnu", "Vedic name"),
    ("staru", "stake, post"),
    ("stāyu", "standing one"),
    ("svaru", "bright, sun"),
    ("vīḍu", "space, leisure"),
    ("aṃhu", "day (Vedic)"),
    ("alābu", "gourd"),
    ("aśru", "skip"),
    ("kambu", "conch"),
    ("karkāru", "potter"),
    ("kratuyu", "performer of rites"),
    ("indu", "moon"),
    ("kṣapu", "night"),
    ("ṛtu", "season"),
    ("retu", "semen, flow"),
    ("plu", "floater, swimmer"),
    ("bhrāgu", "Bhrāgu"),
    ("argu", "Argu"),
    ("bhujyu", "Bhujyu"),
    ("supāṇu", "with beautiful hands"),
    ("parjanyu", "rain-cloud"),
    ("vṛṣṇu", "Vṛṣṇi"),
    ("anu", "atom, molecule"),
    ("vibhu", "all-pervading"),
    ("prabhu", "lord, master"),
    ("ibhu", "servant"),
    ("ṣaṇu", "six"),
    ("garu", "heavy (Vedic)"),
    ("aṅgu", "limb"),
    ("valgu", "handsome"),
    ("laghu", "light, swift"),
    ("kṣayu", "abode (Vedic)"),
    ("vīṇu", "wise man"),
    ("sthāvu", "firm, stable"),
    ("cātu", "flatterer"),
    ("caṣu", "seer, spy"),
    ("bhṛgu", "Bhṛgu, sage"),
]

DATA["u_neuter"] = [
    ("madhu", "honey"),
    ("vastu", "thing, property"),
    ("vāstu", "dwelling, site"),
    ("ambu", "water"),
    ("asru", "tear"),
    ("bindu", "drop, dot"),
    ("cakṣu", "eye"),
    ("vasu", "wealth, good"),
    ("tanu", "body (neuter)"),
    ("mastu", "whey, skim"),
    ("paru", "cave, cavern"),
    ("saru", "lake"),
    ("dātu", "gift, part"),
    ("karu", "pool, pond"),
    ("laghu", "lightness"),
    ("mṛdu", "softness"),
    ("guru", "heaviness"),
    ("sādhu", "the good (neuter)"),
    ("svādu", "sweetness"),
    ("bahu", "muchness, abundance"),
    ("phālu", "fruit"),
    ("pṛthu", "breadth, extent"),
    ("ṛju", "straightness"),
    ("tīkṣṇu", "sharpness"),
    ("valgu", "beauty, loveliness"),
    ("raghu", "skip"),
    ("kṛṣṇu", "blackness"),
    ("caru", "oblation"),
    ("dānu", "drop"),
    ("sānu", "skip"),
]

DATA["ū_feminine"] = [
    ("vadhū", "bride, wife"),
    ("tanū", "body, self"),
    ("camū", "army"),
    ("śvaśrū", "mother-in-law"),
    ("pṛdākū", "female serpent"),
    ("nṛtū", "dancing"),
    ("madhū", "sweet woman"),
    ("jighatsū", "hungry woman"),
    ("cariṣṇū", "movable woman"),
    ("caraṇyū", "approaching woman"),
    ("agrū", "first woman"),
    ("kadrū", "Kadrū, serpent mother"),
    ("guggulū", "bdellium plant"),
    ("jatū", "lac, gum"),
    ("śundhyū", "purifying woman"),
]

def _validate(lemma: str, pattern_value: str) -> bool:
    try:
        pattern = StemPattern(pattern_value)
    except ValueError:
        return False
    if not valid_lemma_for_pattern(lemma, pattern):
        return False
    if pattern in {StemPattern.I_MASCULINE, StemPattern.I_FEMININE, StemPattern.I_NEUTER}:
        if lemma.endswith("ī"):
            return False
    if pattern == StemPattern.II_FEMININE and not lemma.endswith("ī"):
        return False
    if pattern == StemPattern.UU_FEMININE and not lemma.endswith("ū"):
        return False
    return True


def _load_existing(path: Path) -> list[dict]:
    if not path.exists():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, list):
        return payload
    return list(payload.get("entries", []))


def _collect(pattern: str) -> list[dict]:
    seen: set[str] = set()
    entries: list[dict] = []
    gender = GENDER[pattern]

    def add(lemma: str, gloss: str, source: str = SOURCE) -> None:
        if not lemma or lemma in seen or gloss == "skip" or not _validate(lemma, pattern):
            return
        seen.add(lemma)
        entries.append(
            {
                "lemma": lemma,
                "pattern": pattern,
                "gender": gender,
                "gloss": gloss,
                "source": source,
            }
        )

    for raw in _load_existing(OUT_DIR / f"{pattern}.json"):
        add(str(raw.get("lemma", "")), str(raw.get("gloss", "")), str(raw.get("source", SOURCE)))

    for lemma, gloss in DATA.get(pattern, []):
        add(lemma, gloss)

    entries.sort(key=lambda e: e["lemma"])
    return entries[:TARGET]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for pattern in PATTERNS:
        entries = _collect(pattern)
        path = OUT_DIR / f"{pattern}.json"
        path.write_text(
            json.dumps(
                {"pattern": pattern, "target_count": TARGET, "entries": entries},
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        counts[pattern] = len(entries)
        print(f"{pattern}: {len(entries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
