from __future__ import annotations

import hashlib
import hmac
import json
import os
from dataclasses import dataclass
from pathlib import Path

from .errors import CompileError
from .package_lock import LOCK_FILE
from .package_manifest import MANIFEST_PROSE, MANIFEST_PROSE_ASCII, MANIFEST_TOML, load_manifest


@dataclass(frozen=True)
class SignatureRecord:
    algorithm: str
    digest: str
    signature: str


def package_digest(root: Path, *, extra: bytes = b"") -> str:
    hasher = hashlib.sha256()
    hasher.update(_security_binding_blob(root))
    hasher.update(extra)
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.name in {"ssk.lock", "ssk.toml", "saṃskaraṇa.sskm", "samskarana.sskm"}:
            continue
        rel = str(path.relative_to(root)).replace("\\", "/")
        hasher.update(rel.encode("utf-8"))
        hasher.update(path.read_bytes())
    return hasher.hexdigest()


def _security_binding_blob(root: Path) -> bytes:
    chunks: list[bytes] = []
    manifest_path = _manifest_path_for_root(root)
    if manifest_path.is_file():
        manifest = load_manifest(manifest_path)
        canonical_manifest = {
            "package": {
                "name": manifest.name,
                "version": manifest.version,
                "vendor_dir": manifest.vendor_dir,
                "stdlib_namespace": manifest.stdlib_namespace,
                "user_namespace": manifest.user_namespace,
                "lock_required": manifest.lock_required,
                "signature_required": manifest.signature_required,
            },
            "dependencies": [
                {
                    "name": dep.name,
                    "kind": dep.kind,
                    "path": dep.path,
                    "version": dep.version,
                    "registry": dep.registry,
                    "locked": dep.locked,
                }
                for dep in sorted(manifest.dependencies, key=lambda item: item.name)
            ],
        }
        chunks.append(b"manifest:")
        chunks.append(json.dumps(canonical_manifest, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8"))
    lock_path = root / LOCK_FILE
    if lock_path.is_file():
        payload = json.loads(lock_path.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            payload.pop("signature", None)
        chunks.append(b"\nlock:")
        chunks.append(json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8"))
    return b"".join(chunks)


def _manifest_path_for_root(root: Path) -> Path:
    for name in (MANIFEST_TOML, MANIFEST_PROSE, MANIFEST_PROSE_ASCII):
        candidate = root / name
        if candidate.is_file():
            return candidate
    return root / MANIFEST_TOML


def sign_digest(digest: str, *, secret: str | None = None) -> SignatureRecord:
    key_text = secret or os.environ.get("SANSKRIPT_SIGNING_KEY")
    if not key_text:
        raise CompileError(
            "Missing package signing key",
            hint="Set SANSKRIPT_SIGNING_KEY (or provide secret=...) before signing or verifying packages.",
            code="SANSKRIPT_PACKAGE_SIGNING_KEY",
        )
    key = key_text.encode("utf-8")
    signature = hmac.new(key, digest.encode("utf-8"), hashlib.sha256).hexdigest()
    return SignatureRecord(algorithm="hmac-sha256", digest=digest, signature=signature)


def verify_signature(
    digest: str,
    signature: str,
    *,
    secret: str | None = None,
    on_failure: callable | None = None,
) -> bool:
    expected = sign_digest(digest, secret=secret).signature
    ok = hmac.compare_digest(expected, signature)
    if not ok and on_failure is not None:
        on_failure(digest, signature, expected)
    return ok


def verify_package_signature(root: Path, signature: str | None) -> None:
    if not signature:
        return
    parts = signature.split(":")
    if len(parts) != 3:
        raise CompileError(
            "Invalid package signature format",
            hint="Expected signature format: hmac-sha256:<digest>:<signature>.",
            code="SANSKRIPT_PACKAGE_SIGNATURE_FORMAT",
        )
    algorithm, signed_digest, mac = parts
    if algorithm != "hmac-sha256":
        raise CompileError(
            f"Unsupported package signature algorithm: {algorithm}",
            hint="Use hmac-sha256 signatures generated by sign_package().",
            code="SANSKRIPT_PACKAGE_SIGNATURE_FORMAT",
        )
    digest = package_digest(root)
    if not hmac.compare_digest(signed_digest, digest):
        raise CompileError(
            "Package signature digest does not match package contents",
            hint="Re-sign the package after any source change.",
            code="SANSKRIPT_PACKAGE_SIGNATURE",
        )
    if not verify_signature(digest, mac):
        raise CompileError(
            "Package signature verification failed",
            hint="Set SANSKRIPT_SIGNING_KEY or update the manifest signature after signing.",
            code="SANSKRIPT_PACKAGE_SIGNATURE",
        )


def sign_package(root: Path, *, secret: str | None = None) -> str:
    record = sign_digest(package_digest(root), secret=secret)
    return f"{record.algorithm}:{record.digest}:{record.signature}"


__all__ = [
    "SignatureRecord",
    "package_digest",
    "sign_digest",
    "sign_package",
    "verify_package_signature",
    "verify_signature",
]
