"""
Discrete Pāṇini-correct implementations for Adhyāya 3.3 sutra predicates.

3.3 covers:
  • uṇādi adhikāra (3.3.1 – 3.3.2)
  • semantic conditioning of lakāra use (laṭ, lṛṭ, liṅ, loṭ, luṅ, laṅ)
    across 3.3.3 – 3.3.176
  • ghañ / nan / aṅ / ap / kyap / ka / ktri / athuc derivative formations
    in specific upapada/upasarga contexts

Replaces the slug-roundtrip scaffold previously generated by
sutra_handlers_adhyaya23._evaluate for Adhyāya 3.3.

Context keys (same as impl3_1 / impl3_2):
  dhatu_lemma, suffix, upapada, upasarga, semantic_context,
  lakara, role, case, is_chandas, is_samjna, is_optional, first
"""
from __future__ import annotations

from .grammar import Gender, Lakara, Role
from .sutra_impl_base import _eq, _in, make_module_api


# 3.3.1 – 3.3.2 : uṇādi
def sutra_3_3_1(c) -> bool:
    """uṇādayo bahulam: uṇādi suffixes apply variously (bahulam)."""
    return c.get("is_unadi", False) or _in(c, "suffix", {"un", "u", "in", "tu"})


def sutra_3_3_2(c) -> bool:
    """bhūte'pi dṛśyante: also seen in past-time sense."""
    return _eq(c, "semantic_context", "bhuta") and c.get("is_unadi", False)


# 3.3.3 – 3.3.9 : laṭ in future and other senses
def sutra_3_3_3(c) -> bool:
    """bhaviṣyati gamyādayaḥ: 'gam'-class roots in future sense — laṭ."""
    return (_in(c, "dhatu_lemma", {"gam", "ā-gam", "yā", "i"})
            and _eq(c, "semantic_context", "bhavishyat"))


def sutra_3_3_4(c) -> bool:
    """yāvatpurā-nipātayor laṭ: with 'yāvat'/'purā' particles — laṭ for
    future sense."""
    return _in(c, "first", {"yāvat", "purā"}) and _eq(c, "lakara", Lakara.LAT)


def sutra_3_3_5(c) -> bool:
    """vibhāṣā kadā-karhyoḥ: optionally with 'kadā'/'karhi' — laṭ."""
    return _in(c, "first", {"kadā", "karhi"}) and c.get("is_optional", True)


def sutra_3_3_6(c) -> bool:
    """kiṃvṛtte lipsāyām: with kim-pronoun-form in 'desire to obtain'
    sense — laṭ."""
    return (c.get("is_kim_vrtta", False)
            and _eq(c, "semantic_context", "lipsa"))


def sutra_3_3_7(c) -> bool:
    """lipsyamāna-siddhau ca: also in 'attainment of desired thing' — laṭ."""
    return _eq(c, "semantic_context", "lipsyamana_siddhi")


def sutra_3_3_8(c) -> bool:
    """loḍ-artha-lakṣaṇe ca: also in loṭ-meaning denotation — laṭ."""
    return _eq(c, "semantic_context", "lot_artha")


def sutra_3_3_9(c) -> bool:
    """liṅ co'rdhvam-auhūrtike: liṅ also for after-an-hour future sense."""
    return _eq(c, "lakara", Lakara.VIDHILING) and _eq(c, "semantic_context", "urdhva_muhurtika")


# 3.3.10 – 3.3.12 : tumun, ṇvul, aṇ — purpose/action senses
def sutra_3_3_10(c) -> bool:
    """tumun-ṇvulau kriyāyāṃ kriyārthāyām: tumun/ṇvul in 'action for the
    sake of (another) action' sense."""
    return (_in(c, "suffix", {"tumun", "ṇvul"})
            and _eq(c, "semantic_context", "kriya_artha"))


def sutra_3_3_11(c) -> bool:
    """bhāvavacanāś ca: also denoting bhāva (action-noun)."""
    return _eq(c, "semantic_context", "bhava_vacana")


def sutra_3_3_12(c) -> bool:
    """aṇ karmaṇi ca: aṇ in karman-relation also."""
    return _eq(c, "suffix", "aṇ") and _eq(c, "role", Role.KARMAN)


# 3.3.13 – 3.3.14 : lṛṭ for future, sat
def sutra_3_3_13(c) -> bool:
    """lṛṭ śeṣe ca: lṛṭ in residual (śeṣa) future sense."""
    return _eq(c, "lakara", Lakara.LRT) and _eq(c, "semantic_context", "shesha")


def sutra_3_3_14(c) -> bool:
    """lṛṭaḥ sad vā: optionally sat (śatṛ/śānac) for lṛṭ."""
    return _eq(c, "lakara", Lakara.LRT) and _in(c, "suffix", {"śatṛ", "śānac"})


# 3.3.16 – 3.3.18 : ghañ in karman/bhāva
def sutra_3_3_16(c) -> bool:
    """padarujaviśaspṛśo ghañ: pad/ruj/viś/spṛś — ghañ."""
    return _in(c, "dhatu_lemma", {"pad", "ruj", "viś", "spṛś"}) and _eq(c, "suffix", "ghañ")


def sutra_3_3_17(c) -> bool:
    """sṛ sthire: 'sṛ' in 'stationary' (sthira) sense — ghañ."""
    return _eq(c, "dhatu_lemma", "sṛ") and _eq(c, "semantic_context", "sthira")


# 3.3.19 – 3.3.42 : ghañ with various upasarga/upapada
def sutra_3_3_19(c) -> bool:
    """akartari ca kārake saṃjñāyām: not-kartṛ kāraka, in saṃjñā — ghañ."""
    return (c.get("role") not in {Role.KARTR, None}
            and c.get("is_samjna", False))


def sutra_3_3_20(c) -> bool:
    """parimāṇākhyāyāṃ sarvebhyaḥ: in 'measure name' sense, from all
    roots — ghañ."""
    return _eq(c, "semantic_context", "parimana_akhya")


def sutra_3_3_21(c) -> bool:
    """iṅaś ca: also 'iṅ' (go) — ghañ."""
    return _eq(c, "dhatu_lemma", "iṅ") and _eq(c, "suffix", "ghañ")


def sutra_3_3_22(c) -> bool:
    """upasarge ruvaḥ: 'ru' (cry) with upasarga — ghañ."""
    return _eq(c, "dhatu_lemma", "ru") and c.get("upasarga") is not None


def sutra_3_3_23(c) -> bool:
    """sami yu-dru-duvaḥ: yu/dru/dū with 'sam' — ghañ."""
    return _in(c, "dhatu_lemma", {"yu", "dru", "dū"}) and _eq(c, "upasarga", "sam")


def sutra_3_3_24(c) -> bool:
    """śrī-ṇī-bhuvo'nupasarge: śrī/nī/bhū without upasarga — ghañ."""
    return _in(c, "dhatu_lemma", {"śrī", "nī", "bhū"}) and c.get("upasarga") is None


def sutra_3_3_25(c) -> bool:
    """vau kṣu-śruvaḥ: kṣu/śru with 'vi' upasarga — ghañ."""
    return _in(c, "dhatu_lemma", {"kṣu", "śru"}) and _eq(c, "upasarga", "vi")


def sutra_3_3_26(c) -> bool:
    """avo dor niyaḥ: 'nī' with 'ava'/'dur' upasarga — ghañ."""
    return _eq(c, "dhatu_lemma", "nī") and _in(c, "upasarga", {"ava", "dur"})


def sutra_3_3_27(c) -> bool:
    """pre dru-stu-sruvaḥ: dru/stu/sru with 'pra' — ghañ."""
    return _in(c, "dhatu_lemma", {"dru", "stu", "sru"}) and _eq(c, "upasarga", "pra")


def sutra_3_3_28(c) -> bool:
    """nirabhyoḥ pū-luvoḥ: 'pū'/'lū' with 'nir'/'abhi' — ghañ."""
    return _in(c, "dhatu_lemma", {"pū", "lū"}) and _in(c, "upasarga", {"nir", "abhi"})


def sutra_3_3_29(c) -> bool:
    """unnyor graḥ: 'gṛ' with 'ud'/'ni' — ghañ."""
    return _eq(c, "dhatu_lemma", "gṛ") and _in(c, "upasarga", {"ud", "ni"})


def sutra_3_3_30(c) -> bool:
    """kṝ dhānye: 'kṝ' (scatter) in 'grain' (dhānya) sense — ghañ."""
    return _eq(c, "dhatu_lemma", "kṝ") and _eq(c, "semantic_context", "dhanya")


def sutra_3_3_31(c) -> bool:
    """yajñe sami stuvaḥ: 'stu' with 'sam' in yajña — ghañ."""
    return (_eq(c, "dhatu_lemma", "stu")
            and _eq(c, "upasarga", "sam")
            and _eq(c, "semantic_context", "yajna"))


def sutra_3_3_32(c) -> bool:
    """pre stro'yajñe: 'stṛ' with 'pra' not in yajña — ghañ."""
    return (_eq(c, "dhatu_lemma", "stṛ")
            and _eq(c, "upasarga", "pra")
            and not _eq(c, "semantic_context", "yajna"))


def sutra_3_3_34(c) -> bool:
    """chando-nāmni ca: also in 'name of Vedic metre' — ghañ."""
    return _eq(c, "semantic_context", "chanda_nama")


def sutra_3_3_35(c) -> bool:
    """udi grahaḥ: 'grah' with 'ud' — ghañ."""
    return _eq(c, "dhatu_lemma", "grah") and _eq(c, "upasarga", "ud")


def sutra_3_3_36(c) -> bool:
    """sami muṣṭau: 'sam' + 'muṣṭi'-context — ghañ."""
    return _eq(c, "upasarga", "sam") and _eq(c, "upapada", "muṣṭi")


def sutra_3_3_37(c) -> bool:
    """parinyor nī-ṇor dyūtābhreṣayoḥ: 'nī'/'ṇu' with 'pari'/'ni' in
    dyūta/abhreṣa — ghañ."""
    return (_in(c, "dhatu_lemma", {"nī", "ṇu"})
            and _in(c, "upasarga", {"pari", "ni"})
            and _in(c, "semantic_context", {"dyuta", "abhresha"}))


def sutra_3_3_38(c) -> bool:
    """parāv anupātyaya iṇaḥ: 'iṇ' (go) with 'parā' in anupātyaya
    (non-passing) sense — ghañ."""
    return (_eq(c, "dhatu_lemma", "iṇ")
            and _eq(c, "upasarga", "parā")
            and _eq(c, "semantic_context", "anupatyaya"))


def sutra_3_3_39(c) -> bool:
    """vyupayoḥ śeteḥ paryāye: 'śī' with 'vi'/'upa' in 'turn' (paryāya)
    sense — ghañ."""
    return (_eq(c, "dhatu_lemma", "śī")
            and _in(c, "upasarga", {"vi", "upa"})
            and _eq(c, "semantic_context", "paryaya"))


def sutra_3_3_40(c) -> bool:
    """hastādāne cer asteye: 'ci' in 'taking-by-hand' but not 'theft' —
    ghañ."""
    return (_eq(c, "dhatu_lemma", "ci")
            and _eq(c, "semantic_context", "hastadana")
            and not _eq(c, "semantic_context2", "steya"))


def sutra_3_3_41(c) -> bool:
    """nivāsacitiśarīropasamādhāneṣv ādeś ca kaḥ: 'ā-dā' takes ka in
    dwelling / construction / body / arranging."""
    return (_eq(c, "dhatu_lemma", "ā-dā")
            and _in(c, "semantic_context",
                    {"nivasa", "citi", "sharira", "upasamadhana"}))


def sutra_3_3_42(c) -> bool:
    """saṃghe cā'nauttarādharye: in 'group, non-superior-inferior' sense."""
    return _eq(c, "semantic_context", "samgha")


def sutra_3_3_43(c) -> bool:
    """karma-vyatihāre ṇac striyām: ṇac in karma-exchange in feminine."""
    return _eq(c, "suffix", "ṇac") and _eq(c, "gender", Gender.FEMININE)


def sutra_3_3_44(c) -> bool:
    """abhividhau bhāva inuṇ: inuṇ in 'limit' sense for bhāva."""
    return _eq(c, "suffix", "inuṇ") and _eq(c, "semantic_context", "abhividhi")


def sutra_3_3_45(c) -> bool:
    """ākrośe'vanyor grahaḥ: 'grah' with 'ava'/'ni' in ākrośa — ghañ."""
    return (_eq(c, "dhatu_lemma", "grah")
            and _in(c, "upasarga", {"ava", "ni"})
            and _eq(c, "semantic_context", "akrosha"))


def sutra_3_3_46(c) -> bool:
    """pre lipsāyām: 'pra' upasarga in 'desire' sense — ghañ."""
    return _eq(c, "upasarga", "pra") and _eq(c, "semantic_context", "lipsa")


def sutra_3_3_47(c) -> bool:
    """parau yajñe: 'parā' in yajña sense — ghañ."""
    return _eq(c, "upasarga", "parā") and _eq(c, "semantic_context", "yajna")


def sutra_3_3_48(c) -> bool:
    """nau vṛ dhānye: 'vṛ' with 'ni' in 'grain' — ghañ."""
    return (_eq(c, "dhatu_lemma", "vṛ")
            and _eq(c, "upasarga", "ni")
            and _eq(c, "semantic_context", "dhanya"))


def sutra_3_3_49(c) -> bool:
    """udi śrayati-yauti-pū-druvaḥ: śri/yu/pū/dru with 'ud' — ghañ."""
    return (_in(c, "dhatu_lemma", {"śri", "yu", "pū", "dru"})
            and _eq(c, "upasarga", "ud"))


def sutra_3_3_50(c) -> bool:
    """vibhāṣā''ṅi ru-pluvoḥ: optionally 'ru'/'plu' with 'ā' — ghañ."""
    return (_in(c, "dhatu_lemma", {"ru", "plu"})
            and _eq(c, "upasarga", "ā")
            and c.get("is_optional", True))


def sutra_3_3_51(c) -> bool:
    """ave graho varṣa-pratibandhe: 'grah' with 'ava' in 'rain-block'
    sense — ghañ."""
    return (_eq(c, "dhatu_lemma", "grah")
            and _eq(c, "upasarga", "ava")
            and _eq(c, "semantic_context", "varsha_pratibandha"))


def sutra_3_3_52(c) -> bool:
    """pre vaṇijām: 'pra' in 'merchants' (vaṇij) sense — ghañ."""
    return _eq(c, "upasarga", "pra") and _eq(c, "semantic_context", "vanij")


def sutra_3_3_53(c) -> bool:
    """raśmau ca: also in 'rope / rein' (raśmi) sense."""
    return _eq(c, "semantic_context", "rashmi")


def sutra_3_3_54(c) -> bool:
    """vṛṇoter ācchādane: 'vṛ' (cover) in 'covering' sense — ghañ."""
    return _eq(c, "dhatu_lemma", "vṛ") and _eq(c, "semantic_context", "acchadana")


def sutra_3_3_55(c) -> bool:
    """parau bhuvo'vajñāne: 'bhū' with 'parā' in contempt sense — ghañ."""
    return (_eq(c, "dhatu_lemma", "bhū")
            and _eq(c, "upasarga", "parā")
            and _eq(c, "semantic_context", "avajna"))


# 3.3.56 – 3.3.66 : aṇ / ap derivations
def sutra_3_3_56(c) -> bool:
    """erac: ec-vowel-final roots — ac suffix."""
    return _in(c, "dhatu_ends_in", {"e", "o", "ai", "au"}) and _eq(c, "suffix", "ac")


def sutra_3_3_57(c) -> bool:
    """ṛdor ap: ṛ/u-final roots — ap."""
    return _in(c, "dhatu_ends_in", {"ṛ", "u"}) and _eq(c, "suffix", "ap")


def sutra_3_3_58(c) -> bool:
    """graha-vṛ-dṛ-niś-ci-gama-ś ca: list — ap."""
    return _in(c, "dhatu_lemma", {"grah", "vṛ", "dṛ", "niś", "ci", "gam"})


def sutra_3_3_59(c) -> bool:
    """upasarge'daḥ: 'ad' (eat) with upasarga — ap."""
    return _eq(c, "dhatu_lemma", "ad") and c.get("upasarga") is not None


def sutra_3_3_60(c) -> bool:
    """nau ṇa ca: with 'ni' upasarga — ṇa also."""
    return _eq(c, "upasarga", "ni") and _eq(c, "suffix", "ṇa")


def sutra_3_3_61(c) -> bool:
    """vyadha-japor anupasarge: 'vyadh'/'jap' without upasarga — ap."""
    return _in(c, "dhatu_lemma", {"vyadh", "jap"}) and c.get("upasarga") is None


def sutra_3_3_62(c) -> bool:
    """svana-hasor vā: optionally 'svan'/'has' — ap."""
    return _in(c, "dhatu_lemma", {"svan", "has"}) and c.get("is_optional", True)


def sutra_3_3_63(c) -> bool:
    """yamaḥ samupanivisu: 'yam' with sam/upa/ni/vi — ap."""
    return _eq(c, "dhatu_lemma", "yam") and _in(c, "upasarga", {"sam", "upa", "ni", "vi"})


def sutra_3_3_64(c) -> bool:
    """nau gada-nada-paṭha-svanaḥ: gad/nad/paṭh/svan with 'ni' — ap."""
    return _in(c, "dhatu_lemma", {"gad", "nad", "paṭh", "svan"}) and _eq(c, "upasarga", "ni")


def sutra_3_3_65(c) -> bool:
    """kvaṇo vīṇāyāṃ ca: 'kvaṇ' in 'lute' (vīṇā) sense — ap."""
    return _eq(c, "dhatu_lemma", "kvaṇ") and _eq(c, "semantic_context", "vina")


def sutra_3_3_66(c) -> bool:
    """nityaṃ paṇaḥ parimāṇe: 'paṇ' always in 'measure' — ap."""
    return _eq(c, "dhatu_lemma", "paṇ") and _eq(c, "semantic_context", "parimana")


# 3.3.67 – 3.3.87 : various ghañ / kvip / ka derivations
def sutra_3_3_67(c) -> bool:
    """mado'nupasarge: 'mad' without upasarga — ghañ."""
    return _eq(c, "dhatu_lemma", "mad") and c.get("upasarga") is None


def sutra_3_3_68(c) -> bool:
    """pramada-sammadau harṣe: pramada/sammada in 'joy' sense."""
    return _in(c, "derived_lemma", {"pramada", "sammada"}) and _eq(c, "semantic_context", "harsha")


def sutra_3_3_69(c) -> bool:
    """samudor ajaḥ paśuṣu: 'aj' with 'sam'/'ud' in 'cattle' sense — ghañ."""
    return (_eq(c, "dhatu_lemma", "aj")
            and _in(c, "upasarga", {"sam", "ud"})
            and _eq(c, "semantic_context", "pashu"))


def sutra_3_3_70(c) -> bool:
    """akṣeṣu glahaḥ: 'grah' with 'akṣa' (dice) — ghañ."""
    return _eq(c, "dhatu_lemma", "grah") and _eq(c, "upapada", "akṣa")


def sutra_3_3_71(c) -> bool:
    """prajane sarteḥ: 'sṛ' in 'reproduction' (prajana) sense — ghañ."""
    return _eq(c, "dhatu_lemma", "sṛ") and _eq(c, "semantic_context", "prajana")


def sutra_3_3_72(c) -> bool:
    """hvaḥ samprasāraṇaṃ ca ny-abhy-upa-viṣu: 'hve' with ni/abhi/upa/vi —
    ghañ + saṃprasāraṇa."""
    return _eq(c, "dhatu_lemma", "hve") and _in(c, "upasarga", {"ni", "abhi", "upa", "vi"})


def sutra_3_3_73(c) -> bool:
    """āṅi yuddhe: with 'ā' + 'yuddha' — ghañ."""
    return _eq(c, "upasarga", "ā") and _eq(c, "semantic_context", "yuddha")


def sutra_3_3_74(c) -> bool:
    """nipāna-māhāvaḥ: 'nipāna' and 'māhāva' — lexical ghañ."""
    return _in(c, "derived_lemma", {"nipāna", "māhāva"})


def sutra_3_3_75(c) -> bool:
    """bhāve'nupasargasya: in bhāva without upasarga — ghañ."""
    return _eq(c, "semantic_context", "bhava") and c.get("upasarga") is None


def sutra_3_3_76(c) -> bool:
    """hanaś ca vadhaḥ: 'han' substituted by 'vadha' — ghañ."""
    return _eq(c, "dhatu_lemma", "han") and _eq(c, "derived_lemma", "vadha")


def sutra_3_3_77(c) -> bool:
    """mūrtau ghanaḥ: 'han' in 'solid' (mūrta) sense — ghañ → 'ghana'."""
    return _eq(c, "dhatu_lemma", "han") and _eq(c, "semantic_context", "murta")


def sutra_3_3_78(c) -> bool:
    """antarghano deśe: 'antarghana' in 'land' sense (lexical)."""
    return _eq(c, "derived_lemma", "antarghana") and _eq(c, "semantic_context", "desha")


def sutra_3_3_79(c) -> bool:
    """agāra-ekadeśe pragha-ṇa-praghāṇaś ca: 'praghaṇa'/'praghāṇa' in
    'one part of a house' sense."""
    return _in(c, "derived_lemma", {"praghaṇa", "praghāṇa"})


def sutra_3_3_80(c) -> bool:
    """udghano'tyādhānam: 'udghana' (lexical) in 'extra' sense."""
    return _eq(c, "derived_lemma", "udghana")


def sutra_3_3_81(c) -> bool:
    """apaghano'ṅgam: 'apaghana' in 'limb' sense."""
    return _eq(c, "derived_lemma", "apaghana")


def sutra_3_3_82(c) -> bool:
    """karaṇe'yo-vidruṣu: in karaṇa-context with iron/dru — ghañ."""
    return (_eq(c, "role", Role.KARANA)
            and _in(c, "upapada", {"ayas", "drus"}))


def sutra_3_3_83(c) -> bool:
    """stambe ka ca: with 'stamba' — ka."""
    return _eq(c, "upapada", "stamba") and _eq(c, "suffix", "ka")


def sutra_3_3_84(c) -> bool:
    """parau ghaḥ: with 'parā' upasarga — gha."""
    return _eq(c, "upasarga", "parā") and _eq(c, "suffix", "gha")


def sutra_3_3_85(c) -> bool:
    """upaghna āśraye: 'upaghna' in 'refuge' (āśraya) sense."""
    return _eq(c, "derived_lemma", "upaghna") and _eq(c, "semantic_context", "ashraya")


def sutra_3_3_86(c) -> bool:
    """saṃgh-odghau gaṇa-praśaṃsayoḥ: 'saṃgha'/'udgha' in group/praise."""
    return _in(c, "derived_lemma", {"saṃgha", "udgha"})


def sutra_3_3_87(c) -> bool:
    """nigho nimitam: 'nigha' in 'cause' (nimitta) sense."""
    return _eq(c, "derived_lemma", "nigha") and _eq(c, "semantic_context", "nimitta")


# 3.3.88 – 3.3.114 : ktri / athuc / kyap / a — more derivative suffixes
def sutra_3_3_88(c) -> bool:
    """ḍvitaḥ ktriḥ: ḍvit-marked roots — ktri."""
    return c.get("is_dvit", False) and _eq(c, "suffix", "ktri")


def sutra_3_3_89(c) -> bool:
    """ṭvito'thuc: ṭvit-marked roots — athuc."""
    return c.get("is_tvit", False) and _eq(c, "suffix", "athuc")


def sutra_3_3_90(c) -> bool:
    """yaja-yāca-yatu-vicch-prach-rakṣo naṅ: list — naṅ."""
    return (_in(c, "dhatu_lemma", {"yaj", "yāc", "yatu", "vicch", "prach", "rakṣ"})
            and _eq(c, "suffix", "naṅ"))


def sutra_3_3_91(c) -> bool:
    """svapo nan: 'svap' — nan."""
    return _eq(c, "dhatu_lemma", "svap") and _eq(c, "suffix", "nan")


def sutra_3_3_92(c) -> bool:
    """upasarge ghoḥ kiḥ: 'gho' (= dā/dhā) with upasarga — ki."""
    return (c.get("is_ghu", False)
            and c.get("upasarga") is not None
            and _eq(c, "suffix", "ki"))


def sutra_3_3_93(c) -> bool:
    """karmaṇy adhikaraṇe ca: in karman and adhikaraṇa relations — ki."""
    return _in(c, "role", {Role.KARMAN, Role.ADHIKARANA})


def sutra_3_3_95(c) -> bool:
    """sthāgāpā-pacāṃ bhāve: 'sthā'/'gā'/'pā'/'pac' in bhāva — kyap."""
    return _in(c, "dhatu_lemma", {"sthā", "gā", "pā", "pac"}) and _eq(c, "suffix", "kyap")


def sutra_3_3_96(c) -> bool:
    """mantre vṛṣ-eṣa-paca-mana-vid-abhū-vīrā udāttaḥ: in mantra, vṛṣ etc.
    — udātta accent."""
    return (c.get("is_mantra", False)
            and _in(c, "dhatu_lemma", {"vṛṣ", "iṣ", "pac", "man", "vid", "bhū", "vīra"}))


def sutra_3_3_97(c) -> bool:
    """ūti-yūti-jūti-sāti-heti-kīrtayaś ca: lexical kyap-derivatives."""
    return _in(c, "derived_lemma", {"ūti", "yūti", "jūti", "sāti", "heti", "kīrti"})


def sutra_3_3_98(c) -> bool:
    """vraja-yajor bhāve kyap: 'vraj'/'yaj' in bhāva — kyap."""
    return _in(c, "dhatu_lemma", {"vraj", "yaj"}) and _eq(c, "semantic_context", "bhava")


def sutra_3_3_99(c) -> bool:
    """saṃjñāyāṃ sama-jani-ṣad-ni-pat-mana-vid-aṣuñ-śīṅ-bhṛñ-iṇaḥ: in
    saṃjñā, list of roots."""
    return (c.get("is_samjna", False)
            and _in(c, "dhatu_lemma", {
                "sam-aj", "jan", "ṣad", "ni-pat", "man", "vid",
                "ṣuñ", "śīṅ", "bhṛñ", "iṇ",
            }))


def sutra_3_3_100(c) -> bool:
    """kṛñaḥ śa ca: 'kṛ' — ś (kyap-like)."""
    return _eq(c, "dhatu_lemma", "kṛ") and _eq(c, "suffix", "śa")


def sutra_3_3_101(c) -> bool:
    """icchā: a-suffix in 'wish' (icchā) sense."""
    return _eq(c, "semantic_context", "iccha")


def sutra_3_3_102(c) -> bool:
    """a pratyayāt: a-suffix after a pratyaya-ending stem (san etc.)."""
    return c.get("after_pratyaya", False) and _eq(c, "suffix", "a")


def sutra_3_3_103(c) -> bool:
    """guroś ca halaḥ: from a heavy consonant-ending root — a."""
    return c.get("is_guru", False) and c.get("dhatu_ends_in_consonant", False)


def sutra_3_3_104(c) -> bool:
    """ṣid-bhid-ādibhyo'ṅ: ṣid-bhid-class roots — aṅ."""
    return c.get("is_sit", False) or _in(c, "dhatu_lemma", {"bhid", "chid"})


def sutra_3_3_105(c) -> bool:
    """cinti-pūji-kathi-kumbi-carcaś ca: cint/pūj/kath/kumbi/carc — aṅ."""
    return _in(c, "dhatu_lemma", {"cint", "pūj", "kath", "kumbi", "carc"})


def sutra_3_3_106(c) -> bool:
    """ātaś copasarge: after ā-ending root with upasarga — aṅ."""
    return _eq(c, "dhatu_ends_in", "ā") and c.get("upasarga") is not None


def sutra_3_3_107(c) -> bool:
    """ṇy-āsa-śrantho yuc: ṇi-causative āsa/śranth — yuc."""
    return (c.get("is_causative", False)
            and _in(c, "dhatu_lemma", {"ās", "śranth"}))


def sutra_3_3_108(c) -> bool:
    """rogākhyāyāṃ ṇvul bahulam: ṇvul variously in disease-name."""
    return _eq(c, "suffix", "ṇvul") and _eq(c, "semantic_context", "roga_akhya")


def sutra_3_3_109(c) -> bool:
    """saṃjñāyām: in saṃjñā — ṇvul (cont)."""
    return _eq(c, "suffix", "ṇvul") and c.get("is_samjna", False)


def sutra_3_3_110(c) -> bool:
    """vibhāṣā''khyāna-paripraśnayor iñ ca: optionally in narration/
    question — iñ."""
    return (_in(c, "semantic_context", {"akhyana", "pariprashna"})
            and _eq(c, "suffix", "iñ"))


def sutra_3_3_111(c) -> bool:
    """paryāyārha-ṛṇotpattiṣu ṇvuc: ṇvuc in 'turn / debt / origin'."""
    return _in(c, "semantic_context", {"paryaya", "arha", "rnotpatti"})


def sutra_3_3_112(c) -> bool:
    """ākrośe nañ-yaniḥ: nañ + yan in ākrośa — yani."""
    return _eq(c, "semantic_context", "akrosha") and _eq(c, "suffix", "yani")


def sutra_3_3_113(c) -> bool:
    """kṛtya-lyuṭo bahulam: kṛtya/lyuṭ apply variously."""
    return _in(c, "suffix", {"tavya", "anīya", "ya", "lyuṭ"})


def sutra_3_3_114(c) -> bool:
    """napuṃsake bhāve ktaḥ: kta in bhāva, neuter."""
    return (_eq(c, "suffix", "kta")
            and _eq(c, "gender", Gender.NEUTER)
            and _eq(c, "semantic_context", "bhava"))


# 3.3.116 – 3.3.130 : karaṇa / karman / adhikaraṇa derivations
def sutra_3_3_116(c) -> bool:
    """karmaṇi ca yena saṃsparśāt kartuḥ śarīrasukham: in karman, when
    its contact gives the agent bodily comfort — kta."""
    return (_eq(c, "role", Role.KARMAN)
            and _eq(c, "semantic_context", "sharira_sukha"))


def sutra_3_3_117(c) -> bool:
    """karaṇādhikaraṇayoś ca: in karaṇa and adhikaraṇa — kta."""
    return _in(c, "role", {Role.KARANA, Role.ADHIKARANA})


def sutra_3_3_118(c) -> bool:
    """puṃsi saṃjñāyāṃ ghaḥ prāyeṇa: in masculine saṃjñā, generally —
    gha."""
    return (_eq(c, "gender", Gender.MASCULINE)
            and c.get("is_samjna", False))


def sutra_3_3_119(c) -> bool:
    """gocara-saṃcara-vaha-vraja-vyaja-paṇa-nigamāś ca: lexical gha
    derivatives."""
    return _in(c, "derived_lemma", {
        "gocara", "saṃcara", "vaha", "vraja", "vyaja", "paṇa", "nigama",
    })


def sutra_3_3_120(c) -> bool:
    """ave tṝ-stror ghañ: 'tṝ'/'stṛ' with 'ava' — ghañ."""
    return _in(c, "dhatu_lemma", {"tṝ", "stṛ"}) and _eq(c, "upasarga", "ava")


def sutra_3_3_122(c) -> bool:
    """adhyāya-nyāyodyāva-saṃhārādhārāvayāś ca: lexical ghañ — adhyāya etc."""
    return _in(c, "derived_lemma", {
        "adhyāya", "nyāyodyāva", "saṃhāra", "ādhāra", "avayā",
    })


def sutra_3_3_123(c) -> bool:
    """udaṅko'nudake: 'udaṅka' in 'non-water' context."""
    return _eq(c, "derived_lemma", "udaṅka")


def sutra_3_3_124(c) -> bool:
    """jālamānāyaḥ: 'jālamānāya' — lexical kṛt."""
    return _eq(c, "derived_lemma", "jālamānāya")


def sutra_3_3_125(c) -> bool:
    """khano gha ca: 'khan' — gha."""
    return _eq(c, "dhatu_lemma", "khan") and _eq(c, "suffix", "gha")


def sutra_3_3_126(c) -> bool:
    """īṣad-duḥ-suṣu kṛcchrākṛcchrārtheṣu khal: with īṣat/duḥ/su in
    'with-difficulty/without' sense — khal."""
    return (_in(c, "first", {"īṣat", "duḥ", "su"})
            and _in(c, "semantic_context", {"krcchra", "akrcchra"}))


def sutra_3_3_127(c) -> bool:
    """kartṛ-karmaṇoś ca bhū-kṛñoḥ: 'bhū'/'kṛ' in kartṛ/karman — khal."""
    return _in(c, "dhatu_lemma", {"bhū", "kṛ"}) and _in(c, "role", {Role.KARTR, Role.KARMAN})


def sutra_3_3_128(c) -> bool:
    """āto yuc: from ā-final root — yuc."""
    return _eq(c, "dhatu_ends_in", "ā") and _eq(c, "suffix", "yuc")


def sutra_3_3_129(c) -> bool:
    """chandasi gatyarthebhyaḥ: in Vedic, from motion roots — yuc."""
    return c.get("is_chandas", False) and _eq(c, "semantic_context", "gati")


def sutra_3_3_130(c) -> bool:
    """anyebhyo'pi dṛśyate: also seen with other roots (bahulam)."""
    return c.get("is_bahulam", False)


# 3.3.131 – 3.3.176 : lakāra usage in semantic contexts
def sutra_3_3_131(c) -> bool:
    """vartamāna-sāmīpye vartamānavad vā: optionally laṭ for near-present."""
    return (_eq(c, "lakara", Lakara.LAT)
            and _eq(c, "semantic_context", "vartamana_samipya")
            and c.get("is_optional", True))


def sutra_3_3_132(c) -> bool:
    """āśaṃsāyāṃ bhūtavac ca: in 'aspiration' sense, like past — laṅ."""
    return (_eq(c, "semantic_context", "ashamsa")
            and _eq(c, "lakara", Lakara.LAN))


def sutra_3_3_133(c) -> bool:
    """kṣiprava-cane lṛṭ: lṛṭ in 'quickness' sense."""
    return _eq(c, "lakara", Lakara.LRT) and _eq(c, "semantic_context", "kshipra")


def sutra_3_3_134(c) -> bool:
    """āśaṃsāvacane liṅ: liṅ in 'expectation' sense."""
    return _eq(c, "lakara", Lakara.VIDHILING) and _eq(c, "semantic_context", "ashamsa_vacana")


def sutra_3_3_135(c) -> bool:
    """nānadyatanavat kriyā-prabandha-sāmīpyayoḥ: not-today-like in
    action-flow-and-near sense."""
    return _in(c, "semantic_context", {"kriya_prabandha", "samipya"})


def sutra_3_3_136(c) -> bool:
    """bhaviṣyati maryādā-vacane'varasmin: in future with 'limit' sense
    for a non-prior."""
    return (_eq(c, "semantic_context", "bhavishyat")
            and _eq(c, "semantic_context2", "maryada"))


def sutra_3_3_137(c) -> bool:
    """kāla-vibhāge cā'naho-rātrāṇām: in time-divisions, non-day/night."""
    return _eq(c, "semantic_context", "kala_vibhaga")


def sutra_3_3_138(c) -> bool:
    """parasmin vibhāṣā: optionally for the further (parasmin)."""
    return _eq(c, "first", "parasmin") and c.get("is_optional", True)


def sutra_3_3_140(c) -> bool:
    """bhūte ca: also in past."""
    return _eq(c, "semantic_context", "bhuta")


def sutra_3_3_141(c) -> bool:
    """votāpyoḥ: optionally with 'uta'/'api'."""
    return _in(c, "first", {"uta", "api"}) and c.get("is_optional", True)


def sutra_3_3_142(c) -> bool:
    """garhāyāṃ laḍapi jātvoḥ: laṭ also in reproach with 'jātu'."""
    return _eq(c, "semantic_context", "garha") and _eq(c, "first", "jātu")


def sutra_3_3_143(c) -> bool:
    """vibhāṣā kathami liṅ ca: optionally with 'katham' — liṅ."""
    return _eq(c, "first", "katham") and _eq(c, "lakara", Lakara.VIDHILING)


def sutra_3_3_144(c) -> bool:
    """kiṃvṛtte liṅlṛṭau: with kim-pronoun — liṅ/lṛṭ."""
    return c.get("is_kim_vrtta", False) and _in(c, "lakara", {Lakara.VIDHILING, Lakara.LRT})


def sutra_3_3_145(c) -> bool:
    """anavakḷpti-amarṣayor akiṃvṛtte api: in 'impossibility'/'anger',
    even without kim-form."""
    return _in(c, "semantic_context", {"anavaklpti", "amarsha"})


def sutra_3_3_146(c) -> bool:
    """kiṃ kilāsty-artheṣu lṛṭ: in 'is there?' (asti-artha) — lṛṭ."""
    return _eq(c, "semantic_context", "kim_kila_asti") and _eq(c, "lakara", Lakara.LRT)


def sutra_3_3_147(c) -> bool:
    """jātu-yador liṅ: with 'jātu'/'yat' — liṅ."""
    return _in(c, "first", {"jātu", "yat"}) and _eq(c, "lakara", Lakara.VIDHILING)


def sutra_3_3_148(c) -> bool:
    """yat-ca-yatrayoḥ: with 'yat'/'yatra'."""
    return _in(c, "first", {"yat", "yatra"})


def sutra_3_3_149(c) -> bool:
    """garhāyāṃ ca: also in reproach (continues 3.3.142-3.3.148)."""
    return _eq(c, "semantic_context", "garha")


def sutra_3_3_150(c) -> bool:
    """citrīkaraṇe ca: also in 'making remarkable' sense."""
    return _eq(c, "semantic_context", "citri_karana")


def sutra_3_3_151(c) -> bool:
    """śeṣe lṛḍ-ayadau: in the rest, lṛṭ (with non-yat condition)."""
    return _eq(c, "lakara", Lakara.LRT) and c.get("first") != "yat"


def sutra_3_3_152(c) -> bool:
    """utāpyoḥ samarthayor liṅ: with 'uta'/'api' as conjunctions — liṅ."""
    return _in(c, "first", {"uta", "api"}) and _eq(c, "lakara", Lakara.VIDHILING)


def sutra_3_3_153(c) -> bool:
    """kāma-pravedane'kacciti: in 'expressing desire' without 'kaccit'."""
    return _eq(c, "semantic_context", "kama_pravedana") and c.get("first") != "kaccit"


def sutra_3_3_154(c) -> bool:
    """sambhāvane'lam iti cet siddhāprayoge: in 'possibility / enough'
    with siddha-aprayoga."""
    return (_eq(c, "semantic_context", "sambhavana")
            and c.get("is_siddha_aprayoga", False))


def sutra_3_3_155(c) -> bool:
    """vibhāṣā dhātau sambhāvana-vacane'yadi: optionally in 'possibility'
    without 'yadi'."""
    return (_eq(c, "semantic_context", "sambhavana_vacana")
            and c.get("first") != "yadi"
            and c.get("is_optional", True))


def sutra_3_3_156(c) -> bool:
    """hetu-hetumator liṅ: liṅ in cause-effect sense."""
    return _eq(c, "lakara", Lakara.VIDHILING) and _eq(c, "semantic_context", "hetu_hetumat")


def sutra_3_3_157(c) -> bool:
    """icchārtheṣu liṅloṭau: liṅ/loṭ in wish-sense."""
    return (_in(c, "lakara", {Lakara.VIDHILING, Lakara.LOT})
            and _eq(c, "semantic_context", "iccha"))


def sutra_3_3_158(c) -> bool:
    """samānakartṛkeṣu tumun: tumun for same-agent context."""
    return _eq(c, "suffix", "tumun") and c.get("samana_kartrka", False)


def sutra_3_3_159(c) -> bool:
    """liṅ ca: liṅ also (extending 3.3.158)."""
    return _eq(c, "lakara", Lakara.VIDHILING) and c.get("samana_kartrka", False)


def sutra_3_3_160(c) -> bool:
    """icchārthebhyo vibhāṣā vartamāne: optionally from wish-roots in
    present — vibhāṣā."""
    return (_eq(c, "semantic_context", "iccha_artha")
            and _eq(c, "lakara", Lakara.LAT))


def sutra_3_3_163(c) -> bool:
    """praiṣa-atisarga-prāpta-kāleṣu kṛtyāś ca: kṛtya in command/
    permission/right-time senses."""
    return _in(c, "semantic_context", {"praisha", "atisarga", "prapta_kala"})


def sutra_3_3_164(c) -> bool:
    """liṅ co'rdhvam-auhūrtike: liṅ also for after-an-hour."""
    return _eq(c, "lakara", Lakara.VIDHILING) and _eq(c, "semantic_context", "urdhva_muhurtika")


def sutra_3_3_165(c) -> bool:
    """sme loṭ: with 'sma' — loṭ."""
    return _eq(c, "first", "sma") and _eq(c, "lakara", Lakara.LOT)


def sutra_3_3_166(c) -> bool:
    """adhīṣṭe ca: also in 'study/learn' sense — loṭ."""
    return _eq(c, "semantic_context", "adhishta")


def sutra_3_3_167(c) -> bool:
    """kāla-samaya-velāsu tumun: tumun in 'time'/'period'/'moment'."""
    return _eq(c, "suffix", "tumun") and _in(c, "semantic_context", {"kala", "samaya", "vela"})


def sutra_3_3_168(c) -> bool:
    """liṅ yadi: with 'yadi' — liṅ."""
    return _eq(c, "first", "yadi") and _eq(c, "lakara", Lakara.VIDHILING)


def sutra_3_3_169(c) -> bool:
    """arhe kṛtyatṛcaś ca: kṛtya/tṛc in 'deserving' sense."""
    return _eq(c, "semantic_context", "arha")


def sutra_3_3_170(c) -> bool:
    """āvaśyaka-adhamarṇyayor ṇiniḥ: ṇini in 'necessity / debt' sense."""
    return _in(c, "semantic_context", {"avashyaka", "adhamarna"})


def sutra_3_3_171(c) -> bool:
    """kṛtyāś ca: kṛtya also (extending 3.3.170)."""
    return c.get("is_kritya", False)


def sutra_3_3_172(c) -> bool:
    """śaki liṅ ca: liṅ in 'capability' — also liṅ."""
    return _eq(c, "lakara", Lakara.VIDHILING) and _eq(c, "semantic_context", "shaki")


def sutra_3_3_173(c) -> bool:
    """āśiṣi liṅloṭau: liṅ/loṭ in benedictive."""
    return _in(c, "lakara", {Lakara.VIDHILING, Lakara.ASHIRLING, Lakara.LOT})


def sutra_3_3_174(c) -> bool:
    """kti-cktau ca saṃjñāyām: kti/cti in saṃjñā."""
    return _in(c, "suffix", {"kti", "cti"}) and c.get("is_samjna", False)


def sutra_3_3_175(c) -> bool:
    """māṅi luṅ: with 'māṅ' (prohibitive) — luṅ."""
    return _eq(c, "first", "mā") and _eq(c, "lakara", Lakara.LUN)


def sutra_3_3_176(c) -> bool:
    """sm-ottare laṅ ca: with 'sma' following — laṅ."""
    return _eq(c, "first", "sma") and _eq(c, "lakara", Lakara.LAN)


# ===========================================================================
# Fixtures
# ===========================================================================


def _pn(p: dict, n: dict) -> tuple[dict, dict]:
    return p, n


FIXTURES: dict[str, tuple[dict, dict]] = {
    "3.3.1":   _pn({"suffix": "un", "is_unadi": True},
                   {"suffix": "kta", "is_unadi": False}),
    "3.3.2":   _pn({"semantic_context": "bhuta", "is_unadi": True},
                   {"semantic_context": "bhuta", "is_unadi": False}),
    "3.3.3":   _pn({"dhatu_lemma": "gam", "semantic_context": "bhavishyat"},
                   {"dhatu_lemma": "rāma", "semantic_context": "other"}),
    "3.3.4":   _pn({"first": "yāvat", "lakara": Lakara.LAT},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.5":   _pn({"first": "kadā", "is_optional": True},
                   {"first": "rāma", "is_optional": True}),
    "3.3.6":   _pn({"is_kim_vrtta": True, "semantic_context": "lipsa"},
                   {"is_kim_vrtta": True, "semantic_context": "other"}),
    "3.3.7":   _pn({"semantic_context": "lipsyamana_siddhi"},
                   {"semantic_context": "other"}),
    "3.3.8":   _pn({"semantic_context": "lot_artha"},
                   {"semantic_context": "other"}),
    "3.3.9":   _pn({"lakara": Lakara.VIDHILING, "semantic_context": "urdhva_muhurtika"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.10":  _pn({"suffix": "tumun", "semantic_context": "kriya_artha"},
                   {"suffix": "tumun", "semantic_context": "other"}),
    "3.3.11":  _pn({"semantic_context": "bhava_vacana"},
                   {"semantic_context": "other"}),
    "3.3.12":  _pn({"suffix": "aṇ", "role": Role.KARMAN},
                   {"suffix": "aṇ", "role": Role.KARTR}),
    "3.3.13":  _pn({"lakara": Lakara.LRT, "semantic_context": "shesha"},
                   {"lakara": Lakara.LRT, "semantic_context": "other"}),
    "3.3.14":  _pn({"lakara": Lakara.LRT, "suffix": "śatṛ"},
                   {"lakara": Lakara.LAT, "suffix": "kta"}),
    "3.3.16":  _pn({"dhatu_lemma": "pad", "suffix": "ghañ"},
                   {"dhatu_lemma": "rāma", "suffix": "ghañ"}),
    "3.3.17":  _pn({"dhatu_lemma": "sṛ", "semantic_context": "sthira"},
                   {"dhatu_lemma": "sṛ", "semantic_context": "other"}),
    "3.3.19":  _pn({"role": Role.KARMAN, "is_samjna": True},
                   {"role": Role.KARTR, "is_samjna": False}),
    "3.3.20":  _pn({"semantic_context": "parimana_akhya"},
                   {"semantic_context": "other"}),
    "3.3.21":  _pn({"dhatu_lemma": "iṅ", "suffix": "ghañ"},
                   {"dhatu_lemma": "rāma", "suffix": "ghañ"}),
    "3.3.22":  _pn({"dhatu_lemma": "ru", "upasarga": "pra"},
                   {"dhatu_lemma": "ru", "upasarga": None}),
    "3.3.23":  _pn({"dhatu_lemma": "yu", "upasarga": "sam"},
                   {"dhatu_lemma": "yu", "upasarga": "pra"}),
    "3.3.24":  _pn({"dhatu_lemma": "bhū", "upasarga": None},
                   {"dhatu_lemma": "bhū", "upasarga": "pra"}),
    "3.3.25":  _pn({"dhatu_lemma": "śru", "upasarga": "vi"},
                   {"dhatu_lemma": "śru", "upasarga": "pra"}),
    "3.3.26":  _pn({"dhatu_lemma": "nī", "upasarga": "ava"},
                   {"dhatu_lemma": "nī", "upasarga": "pra"}),
    "3.3.27":  _pn({"dhatu_lemma": "stu", "upasarga": "pra"},
                   {"dhatu_lemma": "stu", "upasarga": "ni"}),
    "3.3.28":  _pn({"dhatu_lemma": "pū", "upasarga": "nir"},
                   {"dhatu_lemma": "pū", "upasarga": "pra"}),
    "3.3.29":  _pn({"dhatu_lemma": "gṛ", "upasarga": "ud"},
                   {"dhatu_lemma": "gṛ", "upasarga": "pra"}),
    "3.3.30":  _pn({"dhatu_lemma": "kṝ", "semantic_context": "dhanya"},
                   {"dhatu_lemma": "kṝ", "semantic_context": "other"}),
    "3.3.31":  _pn({"dhatu_lemma": "stu", "upasarga": "sam",
                    "semantic_context": "yajna"},
                   {"dhatu_lemma": "stu", "upasarga": "sam",
                    "semantic_context": "other"}),
    "3.3.32":  _pn({"dhatu_lemma": "stṛ", "upasarga": "pra",
                    "semantic_context": "other"},
                   {"dhatu_lemma": "stṛ", "upasarga": "pra",
                    "semantic_context": "yajna"}),
    "3.3.34":  _pn({"semantic_context": "chanda_nama"},
                   {"semantic_context": "other"}),
    "3.3.35":  _pn({"dhatu_lemma": "grah", "upasarga": "ud"},
                   {"dhatu_lemma": "grah", "upasarga": "pra"}),
    "3.3.36":  _pn({"upasarga": "sam", "upapada": "muṣṭi"},
                   {"upasarga": "sam", "upapada": "rāma"}),
    "3.3.37":  _pn({"dhatu_lemma": "nī", "upasarga": "pari",
                    "semantic_context": "dyuta"},
                   {"dhatu_lemma": "nī", "upasarga": "pra",
                    "semantic_context": "other"}),
    "3.3.38":  _pn({"dhatu_lemma": "iṇ", "upasarga": "parā",
                    "semantic_context": "anupatyaya"},
                   {"dhatu_lemma": "iṇ", "upasarga": "parā",
                    "semantic_context": "other"}),
    "3.3.39":  _pn({"dhatu_lemma": "śī", "upasarga": "vi",
                    "semantic_context": "paryaya"},
                   {"dhatu_lemma": "śī", "upasarga": "vi",
                    "semantic_context": "other"}),
    "3.3.40":  _pn({"dhatu_lemma": "ci", "semantic_context": "hastadana",
                    "semantic_context2": "other"},
                   {"dhatu_lemma": "ci", "semantic_context": "hastadana",
                    "semantic_context2": "steya"}),
    "3.3.41":  _pn({"dhatu_lemma": "ā-dā", "semantic_context": "nivasa"},
                   {"dhatu_lemma": "ā-dā", "semantic_context": "other"}),
    "3.3.42":  _pn({"semantic_context": "samgha"},
                   {"semantic_context": "other"}),
    "3.3.43":  _pn({"suffix": "ṇac", "gender": Gender.FEMININE},
                   {"suffix": "ṇac", "gender": Gender.MASCULINE}),
    "3.3.44":  _pn({"suffix": "inuṇ", "semantic_context": "abhividhi"},
                   {"suffix": "inuṇ", "semantic_context": "other"}),
    "3.3.45":  _pn({"dhatu_lemma": "grah", "upasarga": "ava",
                    "semantic_context": "akrosha"},
                   {"dhatu_lemma": "grah", "upasarga": "ava",
                    "semantic_context": "other"}),
    "3.3.46":  _pn({"upasarga": "pra", "semantic_context": "lipsa"},
                   {"upasarga": "pra", "semantic_context": "other"}),
    "3.3.47":  _pn({"upasarga": "parā", "semantic_context": "yajna"},
                   {"upasarga": "parā", "semantic_context": "other"}),
    "3.3.48":  _pn({"dhatu_lemma": "vṛ", "upasarga": "ni",
                    "semantic_context": "dhanya"},
                   {"dhatu_lemma": "vṛ", "upasarga": "ni",
                    "semantic_context": "other"}),
    "3.3.49":  _pn({"dhatu_lemma": "śri", "upasarga": "ud"},
                   {"dhatu_lemma": "śri", "upasarga": "pra"}),
    "3.3.50":  _pn({"dhatu_lemma": "ru", "upasarga": "ā", "is_optional": True},
                   {"dhatu_lemma": "ru", "upasarga": "pra", "is_optional": True}),
    "3.3.51":  _pn({"dhatu_lemma": "grah", "upasarga": "ava",
                    "semantic_context": "varsha_pratibandha"},
                   {"dhatu_lemma": "grah", "upasarga": "ava",
                    "semantic_context": "other"}),
    "3.3.52":  _pn({"upasarga": "pra", "semantic_context": "vanij"},
                   {"upasarga": "pra", "semantic_context": "other"}),
    "3.3.53":  _pn({"semantic_context": "rashmi"},
                   {"semantic_context": "other"}),
    "3.3.54":  _pn({"dhatu_lemma": "vṛ", "semantic_context": "acchadana"},
                   {"dhatu_lemma": "vṛ", "semantic_context": "other"}),
    "3.3.55":  _pn({"dhatu_lemma": "bhū", "upasarga": "parā",
                    "semantic_context": "avajna"},
                   {"dhatu_lemma": "bhū", "upasarga": "parā",
                    "semantic_context": "other"}),
    "3.3.56":  _pn({"dhatu_ends_in": "e", "suffix": "ac"},
                   {"dhatu_ends_in": "a", "suffix": "kta"}),
    "3.3.57":  _pn({"dhatu_ends_in": "ṛ", "suffix": "ap"},
                   {"dhatu_ends_in": "a", "suffix": "kta"}),
    "3.3.58":  _pn({"dhatu_lemma": "grah"},
                   {"dhatu_lemma": "rāma"}),
    "3.3.59":  _pn({"dhatu_lemma": "ad", "upasarga": "pra"},
                   {"dhatu_lemma": "ad", "upasarga": None}),
    "3.3.60":  _pn({"upasarga": "ni", "suffix": "ṇa"},
                   {"upasarga": "pra", "suffix": "kta"}),
    "3.3.61":  _pn({"dhatu_lemma": "vyadh", "upasarga": None},
                   {"dhatu_lemma": "vyadh", "upasarga": "pra"}),
    "3.3.62":  _pn({"dhatu_lemma": "svan", "is_optional": True},
                   {"dhatu_lemma": "rāma", "is_optional": True}),
    "3.3.63":  _pn({"dhatu_lemma": "yam", "upasarga": "sam"},
                   {"dhatu_lemma": "yam", "upasarga": "pra"}),
    "3.3.64":  _pn({"dhatu_lemma": "gad", "upasarga": "ni"},
                   {"dhatu_lemma": "gad", "upasarga": "pra"}),
    "3.3.65":  _pn({"dhatu_lemma": "kvaṇ", "semantic_context": "vina"},
                   {"dhatu_lemma": "kvaṇ", "semantic_context": "other"}),
    "3.3.66":  _pn({"dhatu_lemma": "paṇ", "semantic_context": "parimana"},
                   {"dhatu_lemma": "paṇ", "semantic_context": "other"}),
    "3.3.67":  _pn({"dhatu_lemma": "mad", "upasarga": None},
                   {"dhatu_lemma": "mad", "upasarga": "pra"}),
    "3.3.68":  _pn({"derived_lemma": "pramada", "semantic_context": "harsha"},
                   {"derived_lemma": "pramada", "semantic_context": "other"}),
    "3.3.69":  _pn({"dhatu_lemma": "aj", "upasarga": "sam",
                    "semantic_context": "pashu"},
                   {"dhatu_lemma": "aj", "upasarga": "sam",
                    "semantic_context": "other"}),
    "3.3.70":  _pn({"dhatu_lemma": "grah", "upapada": "akṣa"},
                   {"dhatu_lemma": "grah", "upapada": "rāma"}),
    "3.3.71":  _pn({"dhatu_lemma": "sṛ", "semantic_context": "prajana"},
                   {"dhatu_lemma": "sṛ", "semantic_context": "other"}),
    "3.3.72":  _pn({"dhatu_lemma": "hve", "upasarga": "ni"},
                   {"dhatu_lemma": "hve", "upasarga": "pra"}),
    "3.3.73":  _pn({"upasarga": "ā", "semantic_context": "yuddha"},
                   {"upasarga": "pra", "semantic_context": "other"}),
    "3.3.74":  _pn({"derived_lemma": "nipāna"},
                   {"derived_lemma": "rāma"}),
    "3.3.75":  _pn({"semantic_context": "bhava", "upasarga": None},
                   {"semantic_context": "bhava", "upasarga": "pra"}),
    "3.3.76":  _pn({"dhatu_lemma": "han", "derived_lemma": "vadha"},
                   {"dhatu_lemma": "han", "derived_lemma": "rāma"}),
    "3.3.77":  _pn({"dhatu_lemma": "han", "semantic_context": "murta"},
                   {"dhatu_lemma": "han", "semantic_context": "other"}),
    "3.3.78":  _pn({"derived_lemma": "antarghana", "semantic_context": "desha"},
                   {"derived_lemma": "antarghana", "semantic_context": "other"}),
    "3.3.79":  _pn({"derived_lemma": "praghaṇa"},
                   {"derived_lemma": "rāma"}),
    "3.3.80":  _pn({"derived_lemma": "udghana"},
                   {"derived_lemma": "rāma"}),
    "3.3.81":  _pn({"derived_lemma": "apaghana"},
                   {"derived_lemma": "rāma"}),
    "3.3.82":  _pn({"role": Role.KARANA, "upapada": "ayas"},
                   {"role": Role.KARANA, "upapada": "rāma"}),
    "3.3.83":  _pn({"upapada": "stamba", "suffix": "ka"},
                   {"upapada": "rāma", "suffix": "ka"}),
    "3.3.84":  _pn({"upasarga": "parā", "suffix": "gha"},
                   {"upasarga": "pra", "suffix": "ghañ"}),
    "3.3.85":  _pn({"derived_lemma": "upaghna", "semantic_context": "ashraya"},
                   {"derived_lemma": "upaghna", "semantic_context": "other"}),
    "3.3.86":  _pn({"derived_lemma": "saṃgha"},
                   {"derived_lemma": "rāma"}),
    "3.3.87":  _pn({"derived_lemma": "nigha", "semantic_context": "nimitta"},
                   {"derived_lemma": "nigha", "semantic_context": "other"}),
    "3.3.88":  _pn({"is_dvit": True, "suffix": "ktri"},
                   {"is_dvit": False, "suffix": "kta"}),
    "3.3.89":  _pn({"is_tvit": True, "suffix": "athuc"},
                   {"is_tvit": False, "suffix": "kta"}),
    "3.3.90":  _pn({"dhatu_lemma": "yaj", "suffix": "naṅ"},
                   {"dhatu_lemma": "rāma", "suffix": "naṅ"}),
    "3.3.91":  _pn({"dhatu_lemma": "svap", "suffix": "nan"},
                   {"dhatu_lemma": "rāma", "suffix": "nan"}),
    "3.3.92":  _pn({"is_ghu": True, "upasarga": "pra", "suffix": "ki"},
                   {"is_ghu": False, "upasarga": None, "suffix": "kta"}),
    "3.3.93":  _pn({"role": Role.KARMAN},
                   {"role": Role.KARTR}),
    "3.3.95":  _pn({"dhatu_lemma": "sthā", "suffix": "kyap"},
                   {"dhatu_lemma": "rāma", "suffix": "kyap"}),
    "3.3.96":  _pn({"is_mantra": True, "dhatu_lemma": "vṛṣ"},
                   {"is_mantra": False, "dhatu_lemma": "rāma"}),
    "3.3.97":  _pn({"derived_lemma": "ūti"},
                   {"derived_lemma": "rāma"}),
    "3.3.98":  _pn({"dhatu_lemma": "vraj", "semantic_context": "bhava"},
                   {"dhatu_lemma": "vraj", "semantic_context": "other"}),
    "3.3.99":  _pn({"is_samjna": True, "dhatu_lemma": "jan"},
                   {"is_samjna": False, "dhatu_lemma": "rāma"}),
    "3.3.100": _pn({"dhatu_lemma": "kṛ", "suffix": "śa"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.3.101": _pn({"semantic_context": "iccha"},
                   {"semantic_context": "other"}),
    "3.3.102": _pn({"after_pratyaya": True, "suffix": "a"},
                   {"after_pratyaya": False, "suffix": "kta"}),
    "3.3.103": _pn({"is_guru": True, "dhatu_ends_in_consonant": True},
                   {"is_guru": False, "dhatu_ends_in_consonant": False}),
    "3.3.104": _pn({"dhatu_lemma": "bhid"},
                   {"dhatu_lemma": "rāma", "is_sit": False}),
    "3.3.105": _pn({"dhatu_lemma": "cint"},
                   {"dhatu_lemma": "rāma"}),
    "3.3.106": _pn({"dhatu_ends_in": "ā", "upasarga": "pra"},
                   {"dhatu_ends_in": "a", "upasarga": None}),
    "3.3.107": _pn({"is_causative": True, "dhatu_lemma": "ās"},
                   {"is_causative": False, "dhatu_lemma": "rāma"}),
    "3.3.108": _pn({"suffix": "ṇvul", "semantic_context": "roga_akhya"},
                   {"suffix": "ṇvul", "semantic_context": "other"}),
    "3.3.109": _pn({"suffix": "ṇvul", "is_samjna": True},
                   {"suffix": "ṇvul", "is_samjna": False}),
    "3.3.110": _pn({"semantic_context": "akhyana", "suffix": "iñ"},
                   {"semantic_context": "other", "suffix": "kta"}),
    "3.3.111": _pn({"semantic_context": "paryaya"},
                   {"semantic_context": "other"}),
    "3.3.112": _pn({"semantic_context": "akrosha", "suffix": "yani"},
                   {"semantic_context": "other", "suffix": "kta"}),
    "3.3.113": _pn({"suffix": "tavya"},
                   {"suffix": "kta"}),
    "3.3.114": _pn({"suffix": "kta", "gender": Gender.NEUTER,
                    "semantic_context": "bhava"},
                   {"suffix": "kta", "gender": Gender.MASCULINE,
                    "semantic_context": "other"}),
    "3.3.116": _pn({"role": Role.KARMAN, "semantic_context": "sharira_sukha"},
                   {"role": Role.KARMAN, "semantic_context": "other"}),
    "3.3.117": _pn({"role": Role.KARANA},
                   {"role": Role.KARTR}),
    "3.3.118": _pn({"gender": Gender.MASCULINE, "is_samjna": True},
                   {"gender": Gender.FEMININE, "is_samjna": False}),
    "3.3.119": _pn({"derived_lemma": "gocara"},
                   {"derived_lemma": "rāma"}),
    "3.3.120": _pn({"dhatu_lemma": "tṝ", "upasarga": "ava"},
                   {"dhatu_lemma": "tṝ", "upasarga": "pra"}),
    "3.3.122": _pn({"derived_lemma": "adhyāya"},
                   {"derived_lemma": "rāma"}),
    "3.3.123": _pn({"derived_lemma": "udaṅka"},
                   {"derived_lemma": "rāma"}),
    "3.3.124": _pn({"derived_lemma": "jālamānāya"},
                   {"derived_lemma": "rāma"}),
    "3.3.125": _pn({"dhatu_lemma": "khan", "suffix": "gha"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.3.126": _pn({"first": "su", "semantic_context": "krcchra"},
                   {"first": "rāma", "semantic_context": "other"}),
    "3.3.127": _pn({"dhatu_lemma": "bhū", "role": Role.KARTR},
                   {"dhatu_lemma": "rāma", "role": Role.KARANA}),
    "3.3.128": _pn({"dhatu_ends_in": "ā", "suffix": "yuc"},
                   {"dhatu_ends_in": "a", "suffix": "kta"}),
    "3.3.129": _pn({"is_chandas": True, "semantic_context": "gati"},
                   {"is_chandas": False, "semantic_context": "other"}),
    "3.3.130": _pn({"is_bahulam": True},
                   {"is_bahulam": False}),
    "3.3.131": _pn({"lakara": Lakara.LAT,
                    "semantic_context": "vartamana_samipya",
                    "is_optional": True},
                   {"lakara": Lakara.LAT, "semantic_context": "other",
                    "is_optional": True}),
    "3.3.132": _pn({"semantic_context": "ashamsa", "lakara": Lakara.LAN},
                   {"semantic_context": "other", "lakara": Lakara.LAT}),
    "3.3.133": _pn({"lakara": Lakara.LRT, "semantic_context": "kshipra"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.134": _pn({"lakara": Lakara.VIDHILING,
                    "semantic_context": "ashamsa_vacana"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.135": _pn({"semantic_context": "kriya_prabandha"},
                   {"semantic_context": "other"}),
    "3.3.136": _pn({"semantic_context": "bhavishyat",
                    "semantic_context2": "maryada"},
                   {"semantic_context": "other", "semantic_context2": "other"}),
    "3.3.137": _pn({"semantic_context": "kala_vibhaga"},
                   {"semantic_context": "other"}),
    "3.3.138": _pn({"first": "parasmin", "is_optional": True},
                   {"first": "rāma", "is_optional": True}),
    "3.3.140": _pn({"semantic_context": "bhuta"},
                   {"semantic_context": "other"}),
    "3.3.141": _pn({"first": "uta", "is_optional": True},
                   {"first": "rāma", "is_optional": True}),
    "3.3.142": _pn({"semantic_context": "garha", "first": "jātu"},
                   {"semantic_context": "other", "first": "rāma"}),
    "3.3.143": _pn({"first": "katham", "lakara": Lakara.VIDHILING},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.144": _pn({"is_kim_vrtta": True, "lakara": Lakara.VIDHILING},
                   {"is_kim_vrtta": False, "lakara": Lakara.LAT}),
    "3.3.145": _pn({"semantic_context": "amarsha"},
                   {"semantic_context": "other"}),
    "3.3.146": _pn({"semantic_context": "kim_kila_asti", "lakara": Lakara.LRT},
                   {"semantic_context": "other", "lakara": Lakara.LAT}),
    "3.3.147": _pn({"first": "jātu", "lakara": Lakara.VIDHILING},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.148": _pn({"first": "yat"},
                   {"first": "rāma"}),
    "3.3.149": _pn({"semantic_context": "garha"},
                   {"semantic_context": "other"}),
    "3.3.150": _pn({"semantic_context": "citri_karana"},
                   {"semantic_context": "other"}),
    "3.3.151": _pn({"lakara": Lakara.LRT, "first": "atha"},
                   {"lakara": Lakara.LRT, "first": "yat"}),
    "3.3.152": _pn({"first": "uta", "lakara": Lakara.VIDHILING},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.153": _pn({"semantic_context": "kama_pravedana", "first": "atha"},
                   {"semantic_context": "other", "first": "kaccit"}),
    "3.3.154": _pn({"semantic_context": "sambhavana", "is_siddha_aprayoga": True},
                   {"semantic_context": "other", "is_siddha_aprayoga": False}),
    "3.3.155": _pn({"semantic_context": "sambhavana_vacana", "first": "atha",
                    "is_optional": True},
                   {"semantic_context": "sambhavana_vacana", "first": "yadi",
                    "is_optional": True}),
    "3.3.156": _pn({"lakara": Lakara.VIDHILING,
                    "semantic_context": "hetu_hetumat"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.157": _pn({"lakara": Lakara.VIDHILING, "semantic_context": "iccha"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.158": _pn({"suffix": "tumun", "samana_kartrka": True},
                   {"suffix": "tumun", "samana_kartrka": False}),
    "3.3.159": _pn({"lakara": Lakara.VIDHILING, "samana_kartrka": True},
                   {"lakara": Lakara.LAT, "samana_kartrka": False}),
    "3.3.160": _pn({"semantic_context": "iccha_artha", "lakara": Lakara.LAT},
                   {"semantic_context": "other", "lakara": Lakara.LAT}),
    "3.3.163": _pn({"semantic_context": "praisha"},
                   {"semantic_context": "other"}),
    "3.3.164": _pn({"lakara": Lakara.VIDHILING,
                    "semantic_context": "urdhva_muhurtika"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.165": _pn({"first": "sma", "lakara": Lakara.LOT},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.166": _pn({"semantic_context": "adhishta"},
                   {"semantic_context": "other"}),
    "3.3.167": _pn({"suffix": "tumun", "semantic_context": "kala"},
                   {"suffix": "tumun", "semantic_context": "other"}),
    "3.3.168": _pn({"first": "yadi", "lakara": Lakara.VIDHILING},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.169": _pn({"semantic_context": "arha"},
                   {"semantic_context": "other"}),
    "3.3.170": _pn({"semantic_context": "avashyaka"},
                   {"semantic_context": "other"}),
    "3.3.171": _pn({"is_kritya": True},
                   {"is_kritya": False}),
    "3.3.172": _pn({"lakara": Lakara.VIDHILING, "semantic_context": "shaki"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.3.173": _pn({"lakara": Lakara.ASHIRLING},
                   {"lakara": Lakara.LAT}),
    "3.3.174": _pn({"suffix": "kti", "is_samjna": True},
                   {"suffix": "kti", "is_samjna": False}),
    "3.3.175": _pn({"first": "mā", "lakara": Lakara.LUN},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.3.176": _pn({"first": "sma", "lakara": Lakara.LAN},
                   {"first": "rāma", "lakara": Lakara.LAT}),
}


(
    IMPLEMENTED_IDS,
    has_real_implementation,
    handler_for,
    positive_features,
    negative_features,
) = make_module_api(FIXTURES, globals())
