"""
Discrete Pāṇini-correct implementations for Adhyāya 3.4 sutra predicates.

3.4 covers:
  • dhātu-sambandha adhikāra (3.4.1) — suffixes under verbal relation
  • semantic-conditioned lakāra/lakāra-substitute usage (3.4.2 – 3.4.6)
  • tumun, ṇamul, kasun and similar adverbial/infinitival kṛts (3.4.7 – 3.4.66)
  • kṛt adhikāras for kartari / karmaṇi / bhāve (3.4.67 – 3.4.76)
  • the lasya adhikāra (3.4.77) — tiṅ endings replace the la-lakāras
  • the master ending table (3.4.78) and its rewriting rules
  • specific ending substitutions across the various lakāras (3.4.81 – 3.4.117)

Replaces the slug-roundtrip scaffold previously generated by
sutra_handlers_adhyaya23._evaluate for Adhyāya 3.4.
"""
from __future__ import annotations

from .grammar import Case, Lakara, Pada, Person, Role
from .sutra_impl_base import make_module_api


# ---------------------------------------------------------------------------
# 3.4.1 — dhātusambandhe pratyayāḥ : adhikāra
# ---------------------------------------------------------------------------

def sutra_3_4_1(c) -> bool:
    """dhātusambandhe pratyayāḥ: from here, the suffixes are introduced
    under a verbal-relation (dhātu-sambandha) context."""
    return c.get("scope") == "dhatu_sambandha" or c.get("dhatu_lemma") is not None


# ---------------------------------------------------------------------------
# 3.4.2 – 3.4.6 : conditioned lakāra use (kriyāsamabhihāra etc.)
# ---------------------------------------------------------------------------

def sutra_3_4_2(c) -> bool:
    """kriyāsamabhihāre loṭ: loṭ in 'continuous repetition' sense."""
    return (c.get("lakara") == Lakara.LOT
            and c.get("semantic_context") == "kriya_samabhihara")


def sutra_3_4_3(c) -> bool:
    """samuccaye'nyatarasyām: optionally in 'conjunction' sense."""
    return (c.get("semantic_context") == "samuccaya"
            and c.get("is_optional", True))


def sutra_3_4_4(c) -> bool:
    """yathāvidhy anuprayogaḥ pūrvasmin: the secondary verb follows
    its prescribed pattern in [the first construction]."""
    return c.get("is_anuprayoga", False)


def sutra_3_4_5(c) -> bool:
    """samuccaye sāmānyavacanasya: in conjunction of a general statement."""
    return (c.get("semantic_context") == "samuccaya"
            and c.get("is_samanya_vacana", False))


def sutra_3_4_6(c) -> bool:
    """chandasi luṅlaṅliṭaḥ: in Vedic, luṅ/laṅ/liṭ are used variously."""
    return (c.get("is_chandas", False)
            and c.get("lakara") in {Lakara.LUN, Lakara.LAN, Lakara.LIT})


# ---------------------------------------------------------------------------
# 3.4.7 – 3.4.8 : leṭ for liṅ-meaning and special senses
# ---------------------------------------------------------------------------

def sutra_3_4_7(c) -> bool:
    """liṅarthe leṭ: leṭ in the sense of liṅ (Vedic subjunctive for
    optative)."""
    return (c.get("lakara") == Lakara.LET
            and c.get("semantic_context") == "ling_artha")


def sutra_3_4_8(c) -> bool:
    """upasaṃvādāśaṅkayoś ca: also in promise / apprehension senses."""
    return c.get("semantic_context") in {"upasamvada", "ashanka"}


# ---------------------------------------------------------------------------
# 3.4.9 – 3.4.17 : tumun, sen, asen and other infinitive-like suffixes
# ---------------------------------------------------------------------------

def sutra_3_4_9(c) -> bool:
    """tumarthe sesenase…: list of Vedic infinitives in tumun-sense
    (se, sen, ase, ksen, kase, dhyai, śadhyai, taven, tavainn, etc.)."""
    return c.get("suffix", "") in {
        "se", "sen", "ase", "asen", "ksen", "kasen",
        "adhyai", "adhyainn", "kadhyai", "kadhyainn",
        "śadhyai", "śadhyainn", "tavai", "taveṅ", "taven",
    } and c.get("semantic_context") == "tumartha"


def sutra_3_4_10(c) -> bool:
    """prayai rohiṣyai avyathiṣyai: lexical Vedic infinitive forms
    'prayai', 'rohiṣyai', 'avyathiṣyai'."""
    return c.get("derived_lemma", "") in {"prayai", "rohiṣyai", "avyathiṣyai"}


def sutra_3_4_11(c) -> bool:
    """dṛśe vikhye ca: 'dṛśe' / 'vikhye' [as infinitive-like forms]."""
    return c.get("derived_lemma", "") in {"dṛśe", "vikhye"}


def sutra_3_4_12(c) -> bool:
    """śaki ṇamulkamulau: ṇamul and kamul after roots in 'being able'
    (śak) sense."""
    return (c.get("suffix", "") in {"ṇamul", "kamul"}
            and c.get("semantic_context") == "shaki")


def sutra_3_4_13(c) -> bool:
    """īśvare tosunkasunau: tosun and kasun in 'being in command' (īśvara)
    sense."""
    return (c.get("suffix", "") in {"tosun", "kasun"}
            and c.get("semantic_context") == "ishvara")


def sutra_3_4_14(c) -> bool:
    """kṛtyārthe tavaikenkenyatvanaḥ: tavai/keny/atvana in kṛtya-sense."""
    return (c.get("suffix", "") in {"tavai", "keny", "atvana", "kenya"}
            and c.get("semantic_context") == "krtya_artha")


def sutra_3_4_15(c) -> bool:
    """avacakṣe ca: 'avacakṣe' is a similar infinitive form."""
    return c.get("derived_lemma", "") == "avacakṣe"


def sutra_3_4_16(c) -> bool:
    """bhāvalakṣaṇe sthe-ṅkṛñ-vadi-cari-hu-tami-janibhyas tosun: tosun
    after sthā/kṛ/vad/car/hu/tam/jan in bhāva-lakṣaṇa context."""
    return (c.get("suffix", "") == "tosun"
            and c.get("dhatu_lemma", "") in {
                "sthā", "kṛ", "vad", "car", "hu", "tam", "jan",
            }
            and c.get("semantic_context") == "bhava_lakshana")


def sutra_3_4_17(c) -> bool:
    """sṛpitṛdoḥ kasun: kasun after 'sṛp' and 'tṛd'."""
    return (c.get("suffix", "") == "kasun"
            and c.get("dhatu_lemma", "") in {"sṛp", "tṛd"})


# ---------------------------------------------------------------------------
# 3.4.18 – 3.4.20 : ktvā in prohibition / reciprocity contexts
# ---------------------------------------------------------------------------

def sutra_3_4_18(c) -> bool:
    """alaṅkhalvoḥ pratiṣedhayoḥ prācāṃ ktvā: ktvā after alaṅ/khalu in
    prohibition contexts, per eastern grammarians."""
    return (c.get("suffix", "") == "ktvā"
            and c.get("first", "") in {"alaṅ", "khalu"}
            and c.get("semantic_context") == "pratisedha")


def sutra_3_4_19(c) -> bool:
    """udīcāṃ māṅo vyatīhāre: 'māṅ' [in mutual exchange sense], per
    northern grammarians — ktvā."""
    return (c.get("dhatu_lemma", "") == "mā"
            and c.get("semantic_context") == "vyatihara")


def sutra_3_4_20(c) -> bool:
    """parāvarayoge ca: also in 'separate / joined' (para-avara) yoga."""
    return c.get("semantic_context") in {"paravara_yoga", "para_avara"}


# ---------------------------------------------------------------------------
# 3.4.21 – 3.4.64 : ktvā / ṇamul use in specific semantic contexts
# ---------------------------------------------------------------------------

def sutra_3_4_21(c) -> bool:
    """samānakartṛkayoḥ pūrvakāle: ktvā when both actions share the same
    agent and the first action is prior in time."""
    return (c.get("suffix", "") == "ktvā"
            and c.get("samana_kartrka", False)
            and c.get("is_purvakala", False))


def sutra_3_4_22(c) -> bool:
    """ābhīkṣṇye ṇamul ca: ṇamul also in 'frequent repetition' sense."""
    return (c.get("suffix", "") == "ṇamul"
            and c.get("semantic_context") == "abhikshnya")


def sutra_3_4_23(c) -> bool:
    """na yady anākāṅkṣe: NOT [ktvā] when there is no expectation of
    a connected second action (anākāṅkṣa)."""
    return not c.get("is_anakanksha", False)


def sutra_3_4_24(c) -> bool:
    """vibhāṣā'gre-prathama-pūrveṣu: optionally with 'agre'/'prathama'/
    'pūrva' — ṇamul."""
    return (c.get("first", "") in {"agre", "prathama", "pūrva"}
            and c.get("is_optional", True))


def sutra_3_4_25(c) -> bool:
    """karmaṇyākrośe kṛñaḥ khamuñ: khamuñ for 'kṛ' in karman-relation
    with abuse (ākrośa) context."""
    return (c.get("dhatu_lemma", "") == "kṛ"
            and c.get("suffix", "") == "khamuñ"
            and c.get("semantic_context") == "akrosha"
            and c.get("role") == Role.KARMAN)


def sutra_3_4_26(c) -> bool:
    """svādumi ṇamul: ṇamul after 'svādu' (tasty / sweet)."""
    return (c.get("suffix", "") == "ṇamul"
            and c.get("first", "") == "svādu")


def sutra_3_4_27(c) -> bool:
    """anyathaivaṃkathamitthaṃsu siddhāprayogaś cet: ṇamul after anyathā/
    evam/katham/ittham if the construction is 'siddha-aprayoga'."""
    return (c.get("first", "") in {"anyathā", "evam", "katham", "ittham"}
            and c.get("is_siddha_aprayoga", False))


def sutra_3_4_28(c) -> bool:
    """yathātathayor asūyāprativacane: ṇamul after 'yathā'/'tathā' in
    a reply expressing displeasure (asūyā)."""
    return (c.get("first", "") in {"yathā", "tathā"}
            and c.get("semantic_context") == "asuya_prativacana")


def sutra_3_4_29(c) -> bool:
    """karmaṇi dṛśivido sākalye: ṇamul for 'dṛś'/'vid' in karman role
    with totality (sākalya)."""
    return (c.get("dhatu_lemma", "") in {"dṛś", "vid"}
            and c.get("role") == Role.KARMAN
            and c.get("semantic_context") == "sakalya")


def sutra_3_4_30(c) -> bool:
    """yāvati vinda-jīvoḥ: ṇamul for 'vind'/'jīv' with 'yāvat'."""
    return (c.get("dhatu_lemma", "") in {"vind", "jīv"}
            and c.get("first", "") == "yāvat")


def sutra_3_4_31(c) -> bool:
    """carmodarayoḥ pūreḥ: ṇamul for 'pūr' (fill) with 'carma'/'udara'."""
    return (c.get("dhatu_lemma", "") == "pūr"
            and c.get("first", "") in {"carma", "udara"})


def sutra_3_4_32(c) -> bool:
    """varṣapramāṇa ūlopaś cāsyānyatarasyām: ṇamul for the noun whose
    measure is in years; with ū-loss optionally."""
    return c.get("semantic_context") == "varsha_pramana"


def sutra_3_4_33(c) -> bool:
    """cele knopeḥ: ṇamul for 'knop' (soak) with 'cela' (cloth)."""
    return (c.get("dhatu_lemma", "") == "knop"
            and c.get("first", "") == "cela")


def sutra_3_4_34(c) -> bool:
    """nimūlasamūlayoḥ kaṣaḥ: ṇamul for 'kaṣ' with 'nimūla'/'samūla'."""
    return (c.get("dhatu_lemma", "") == "kaṣ"
            and c.get("first", "") in {"nimūla", "samūla"})


def sutra_3_4_35(c) -> bool:
    """śuṣka-cūrṇa-rūkṣeṣu piṣaḥ: ṇamul for 'piṣ' with śuṣka/cūrṇa/rūkṣa."""
    return (c.get("dhatu_lemma", "") == "piṣ"
            and c.get("first", "") in {"śuṣka", "cūrṇa", "rūkṣa"})


def sutra_3_4_36(c) -> bool:
    """samūlākṛtajīveṣu hankṛñgrahaḥ: han/kṛ/grah with samūla/akṛta/jīva."""
    return (c.get("dhatu_lemma", "") in {"han", "kṛ", "grah"}
            and c.get("first", "") in {"samūla", "akṛta", "jīva"})


def sutra_3_4_37(c) -> bool:
    """karaṇe hanaḥ: ṇamul for 'han' in karaṇa-relation."""
    return (c.get("dhatu_lemma", "") == "han"
            and c.get("role") == Role.KARANA)


def sutra_3_4_38(c) -> bool:
    """snehane piṣaḥ: ṇamul for 'piṣ' in 'lubricating' (snehana) sense."""
    return (c.get("dhatu_lemma", "") == "piṣ"
            and c.get("semantic_context") == "snehana")


def sutra_3_4_39(c) -> bool:
    """haste vartti-grahoḥ: ṇamul for 'vart'/'grah' with 'hasta'."""
    return (c.get("dhatu_lemma", "") in {"vart", "grah"}
            and c.get("first", "") == "hasta")


def sutra_3_4_40(c) -> bool:
    """sve puṣaḥ: ṇamul for 'puṣ' with 'sva' (own)."""
    return (c.get("dhatu_lemma", "") == "puṣ"
            and c.get("first", "") == "sva")


def sutra_3_4_41(c) -> bool:
    """adhikaraṇe bandhaḥ: ṇamul for 'bandh' in adhikaraṇa-relation."""
    return (c.get("dhatu_lemma", "") == "bandh"
            and c.get("role") == Role.ADHIKARANA)


def sutra_3_4_42(c) -> bool:
    """saṃjñāyām: in a proper-name (saṃjñā) context — ṇamul."""
    return c.get("is_samjna", False)


def sutra_3_4_43(c) -> bool:
    """kartror jīvapuruṣayor naśivahoḥ: ṇamul for naś/vah with kartṛ
    'jīva'/'puruṣa'."""
    return (c.get("dhatu_lemma", "") in {"naś", "vah"}
            and c.get("kartri_lemma", "") in {"jīva", "puruṣa"})


def sutra_3_4_44(c) -> bool:
    """ūrdhve śuṣipūroḥ: ṇamul for 'śuṣ'/'pūr' with 'ūrdhva'."""
    return (c.get("dhatu_lemma", "") in {"śuṣ", "pūr"}
            and c.get("first", "") == "ūrdhva")


def sutra_3_4_45(c) -> bool:
    """upamāne karmaṇi ca: also in upamāna with karman-relation — ṇamul."""
    return (c.get("is_upamana", False)
            and c.get("role") == Role.KARMAN)


def sutra_3_4_46(c) -> bool:
    """kaṣādiṣu yathāvidhyanuprayogaḥ: with kaṣ-class, secondary verb
    follows the same pattern."""
    return c.get("dhatu_lemma", "") in {"kaṣ", "piṣ", "han"}


def sutra_3_4_47(c) -> bool:
    """upadaṃśas tṛtīyāyām: ṇamul for 'upadaṃś' with instrumental."""
    return (c.get("dhatu_lemma", "") == "upadaṃś"
            and c.get("case") == Case.INSTRUMENTAL)


def sutra_3_4_48(c) -> bool:
    """hiṃsārthānāṃ ca samānakarmakāṇām: roots of violence sense with
    shared karman."""
    return (c.get("semantic_context") == "himsa"
            and c.get("samana_karman", False))


def sutra_3_4_49(c) -> bool:
    """saptamyāṃ copa-pīḍa-rudha-karṣaḥ: ṇamul for upa-pīḍ/rudh/karṣ
    with locative."""
    return (c.get("dhatu_lemma", "") in {"upapīḍ", "rudh", "karṣ"}
            and c.get("case") == Case.LOCATIVE)


def sutra_3_4_50(c) -> bool:
    """samāsattau: in close-contact / immediacy context."""
    return c.get("semantic_context") == "samasatti"


def sutra_3_4_51(c) -> bool:
    """pramāṇe ca: also in 'measure' sense."""
    return c.get("semantic_context") == "pramana"


def sutra_3_4_52(c) -> bool:
    """apādāne parīpsāyām: in apādāna-relation with 'eager-desire' sense."""
    return (c.get("role") == Role.APADANA
            and c.get("semantic_context") == "paripsa")


def sutra_3_4_53(c) -> bool:
    """dvitīyāyāṃ ca: also in accusative (dvitīyā) — ṇamul."""
    return c.get("case") == Case.ACCUSATIVE


def sutra_3_4_54(c) -> bool:
    """svāṅge'dhruve: in 'non-permanent part of own body' context."""
    return (c.get("semantic_context") == "svanga"
            and not c.get("is_dhruva", False))


def sutra_3_4_55(c) -> bool:
    """parikliśyamāne ca: also in 'being troubled' sense."""
    return c.get("semantic_context") == "pariklishyamana"


def sutra_3_4_56(c) -> bool:
    """viśipatipadiskandāṃ vyāpyamāna-āsevyamānayoḥ: viś/pat/pad/skand
    in 'being pervaded / consumed' sense."""
    return (c.get("dhatu_lemma", "") in {"viś", "pat", "pad", "skand"}
            and c.get("semantic_context") in {"vyapyamana", "asevyamana"})


def sutra_3_4_57(c) -> bool:
    """asyati-tṛṣoḥ kriyā'ntare kāleṣu: for 'as'/'tṛṣ' in different-
    activity time contexts."""
    return (c.get("dhatu_lemma", "") in {"as", "tṛṣ"}
            and c.get("semantic_context") == "kriya_antara")


def sutra_3_4_58(c) -> bool:
    """nāmny ādiśi-grahoḥ: for 'ādiś'/'grah' with a proper name."""
    return (c.get("dhatu_lemma", "") in {"ādiś", "grah"}
            and c.get("first") is not None
            and c.get("is_naamya", False))


def sutra_3_4_59(c) -> bool:
    """avyaye'yathābhipreta-ākhyāne kṛñaḥ ktvā ṇamulau: with an avyaya,
    in non-expected statement, 'kṛ' takes ktvā/ṇamul."""
    return (c.get("dhatu_lemma", "") == "kṛ"
            and c.get("is_avyaya_present", False)
            and c.get("semantic_context") == "ayathabhipreta")


def sutra_3_4_60(c) -> bool:
    """tiryacy apavarge: in 'completion' sense with 'tiryac' (sideways)."""
    return c.get("first", "") == "tiryac"


def sutra_3_4_61(c) -> bool:
    """svāṅge tas-pratyaye kṛbhvoḥ: 'kṛ'/'bhū' with tas-suffix on svāṅga."""
    return (c.get("dhatu_lemma", "") in {"kṛ", "bhū"}
            and c.get("first_suffix", "") == "tas")


def sutra_3_4_62(c) -> bool:
    """nādhā'rtha-pratyaye cvyarthe: NOT with the cvi-meaning of -dhā
    suffix."""
    return not (c.get("suffix") == "cvi" and c.get("is_dha_artha", False))


def sutra_3_4_63(c) -> bool:
    """tūṣṇīmi bhuvaḥ: 'bhū' with 'tūṣṇīm' (silently)."""
    return (c.get("dhatu_lemma", "") == "bhū"
            and c.get("first", "") == "tūṣṇīm")


def sutra_3_4_64(c) -> bool:
    """anvacy ānulomye: in 'following / according to' sense — ktvā."""
    return c.get("semantic_context") == "anulomya"


# ---------------------------------------------------------------------------
# 3.4.65 – 3.4.66 : tumun in 'capability' senses
# ---------------------------------------------------------------------------

def sutra_3_4_65(c) -> bool:
    """śakadhṛṣa-jñā-glā-ghaṭa-rabha-labha-krama-saha-arha-asty-artheṣu
    tumun: tumun after a list of roots in 'being able / ought to' senses."""
    return (c.get("suffix", "") == "tumun"
            and c.get("dhatu_lemma", "") in {
                "śak", "dhṛṣ", "jñā", "glā", "ghaṭ", "rabh",
                "labh", "kram", "sah", "arh", "as",
            })


def sutra_3_4_66(c) -> bool:
    """paryāptivacaneṣv alam-artheṣu: tumun also in 'enough / sufficient'
    senses (alam-artha)."""
    return (c.get("suffix", "") == "tumun"
            and c.get("semantic_context") == "alam_artha")


# ---------------------------------------------------------------------------
# 3.4.67 – 3.4.76 : kṛt adhikāras for kartari / karmaṇi / bhāve
# ---------------------------------------------------------------------------

def sutra_3_4_67(c) -> bool:
    """kartari kṛt: kṛt suffixes [from here on] are in the agent (kartṛ)
    sense by default."""
    return c.get("is_kartari", False) or c.get("scope") == "kartari_krt"


def sutra_3_4_68(c) -> bool:
    """bhavyageyapravacanīyopasthānīyajanyāplāvyāpātyā vā: optionally
    'bhavya'/'geya'/'pravacanīya'/etc. lexical kṛtya derivatives."""
    return c.get("derived_lemma", "") in {
        "bhavya", "geya", "pravacanīya", "upasthānīya",
        "janya", "āplāvya", "āpātya",
    }


def sutra_3_4_70(c) -> bool:
    """tayor eva kṛtya-kta-khalarthāḥ: kṛtya, kta, and khal-meanings apply
    only in karman/bhāva."""
    return c.get("suffix", "") in {"tavya", "anīya", "ya", "kta", "khal"}


def sutra_3_4_73(c) -> bool:
    """dāśa-goghnau sampradāne: 'dāśa'/'goghna' in sampradāna context
    (specific lexical kṛts)."""
    return (c.get("derived_lemma", "") in {"dāśa", "goghna"}
            and c.get("role") == Role.SAMPRADANA)


def sutra_3_4_74(c) -> bool:
    """bhīmādayo'pādāne: 'bhīma' etc. in apādāna sense."""
    return (c.get("derived_lemma", "") in {"bhīma", "bhīṣma", "bhāsura"}
            and c.get("role") == Role.APADANA)


def sutra_3_4_75(c) -> bool:
    """tābhyām anyatroṇādayaḥ: uṇādi suffixes apply elsewhere [than
    those two senses]."""
    return c.get("suffix", "").startswith("un") or c.get("is_unadi", False)


def sutra_3_4_76(c) -> bool:
    """kto'dhikaraṇe ca dhrauvyagati-pratyavasāna-arthebhyaḥ: kta also
    in adhikaraṇa-relation for roots of stability / motion / consumption."""
    return (c.get("suffix", "") == "kta"
            and c.get("role") == Role.ADHIKARANA
            and c.get("semantic_context") in {"dhrauvya", "gati", "pratyavasana"})


# ---------------------------------------------------------------------------
# 3.4.77 – 3.4.78 : lasya adhikāra and the master tiṅ ending list
# ---------------------------------------------------------------------------

def sutra_3_4_77(c) -> bool:
    """lasya: adhikāra — from here, the tiṅ endings replace the la-lakāras
    (la-replacement section)."""
    return c.get("scope") == "lasya" or c.get("is_la_replacement", False)


# Master ending tables for 3.4.78.
PARASMAI_ENDINGS = ("tip", "tas", "jhi", "sip", "thas", "tha",
                    "mip", "vas", "mas")
ATMANE_ENDINGS = ("ta", "ātām", "jha", "thās", "āthām", "dhvam",
                  "iṭ", "vahi", "mahiṅ")


def sutra_3_4_78(c) -> bool:
    """tip-tas-jhi-sip-thas-tha-mib-vas-mas tātāṃ-jha-thās-āthāṃ-dhvam-
    iḍ-vahi-mahiṅ: the canonical 18 tiṅ endings replace la (9 P + 9 Ā)."""
    return c.get("suffix", "") in PARASMAI_ENDINGS + ATMANE_ENDINGS


# ---------------------------------------------------------------------------
# 3.4.81 – 3.4.117 : specific lakāra→ending substitutions and refinements
# ---------------------------------------------------------------------------

def sutra_3_4_81(c) -> bool:
    """liṭas tajhayor eśirec: 'eś'/'irec' replace 't'/'jha' in liṭ."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("ending", "") in {"eś", "irec", "t", "jha"})


def sutra_3_4_82(c) -> bool:
    """parasmaipadānāṃ ṇal-atus-us-thal-athus-a-ṇal-va-māḥ: the 9 special
    parasmaipada endings of liṭ."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("pada") == Pada.PARASMAIPADA
            and c.get("ending", "") in {
                "ṇal", "atus", "us", "thal", "athus", "a", "va", "ma",
            })


def sutra_3_4_83(c) -> bool:
    """vido laṭo vā: 'vid' may take liṭ-endings in laṭ optionally."""
    return (c.get("dhatu_lemma", "") == "vid"
            and c.get("lakara") == Lakara.LAT
            and c.get("is_optional", True))


def sutra_3_4_84(c) -> bool:
    """bruvaḥ pañcānām āditā āho bruvaḥ: 'brū' replaces with 'āh' in five
    forms beginning with 1st-singular liṭ."""
    return (c.get("dhatu_lemma", "") == "brū"
            and c.get("lakara") == Lakara.LIT)


def sutra_3_4_85(c) -> bool:
    """loṭo laṅvat: loṭ behaves like laṅ for ending replacement."""
    return c.get("lakara") in {Lakara.LOT, Lakara.LAN}


def sutra_3_4_89(c) -> bool:
    """mer niḥ: 'm' (1st-singular ending) is replaced by 'ni' [in loṭ]."""
    return (c.get("lakara") == Lakara.LOT
            and c.get("person") == Person.FIRST
            and c.get("ending", "") == "mi")


def sutra_3_4_90(c) -> bool:
    """āmetaḥ: 'ā' replaces 'e'-ending in loṭ-ātmanepada."""
    return (c.get("lakara") == Lakara.LOT
            and c.get("pada") == Pada.ATMANEPADA
            and c.get("ending", "") == "e")


def sutra_3_4_91(c) -> bool:
    """savābhyāṃ vāmau: with 's'/'v' marker — 'va'/'ma' replacements."""
    return c.get("ending", "") in {"sva", "vam", "vāṃ"}


def sutra_3_4_93(c) -> bool:
    """eta ai: 'e' becomes 'ai' [in specific loṭ-ātmanepada contexts]."""
    return (c.get("lakara") == Lakara.LOT
            and c.get("ending", "") == "e"
            and c.get("pada") == Pada.ATMANEPADA)


def sutra_3_4_94(c) -> bool:
    """leṭo'ḍāṭau: 'aḍ'/'āṭ' augments for leṭ."""
    return (c.get("lakara") == Lakara.LET
            and c.get("augment", "") in {"aḍ", "āṭ"})


def sutra_3_4_95(c) -> bool:
    """āta ai: final 'ā' becomes 'ai' [in leṭ/loṭ contexts]."""
    return (c.get("lakara") in {Lakara.LET, Lakara.LOT}
            and c.get("stem_ends_in", "") == "ā")


def sutra_3_4_96(c) -> bool:
    """vaito'nyatra: 'vai' replaces elsewhere [in leṭ]."""
    return (c.get("lakara") == Lakara.LET
            and c.get("ending", "") == "vai")


def sutra_3_4_97(c) -> bool:
    """itaś ca lopaḥ parasmaipadeṣu: 'i' is dropped in parasmaipada."""
    return (c.get("pada") == Pada.PARASMAIPADA
            and c.get("ending", "").endswith("i"))


def sutra_3_4_98(c) -> bool:
    """sa uttamasya: 's' is the augment of the 1st-person (uttama) ending."""
    return c.get("person") == Person.FIRST and c.get("is_s_augment", False)


def sutra_3_4_99(c) -> bool:
    """nityaṃ ṅitaḥ: obligatorily after ṅit-marked roots."""
    return c.get("is_nit", False) and c.get("is_obligatory", True)


def sutra_3_4_102(c) -> bool:
    """liṅas sīyuṭ: 'sīy' is the augment for liṅ (potential)."""
    return (c.get("lakara") in {Lakara.VIDHILING, Lakara.ASHIRLING}
            and c.get("augment", "") == "sīy")


def sutra_3_4_103(c) -> bool:
    """yāsuṭ parasmaipadeṣv udātto ṅit ca: 'yās' augment in parasmaipada-
    liṅ is udātta and ṅit."""
    return (c.get("lakara") in {Lakara.VIDHILING, Lakara.ASHIRLING}
            and c.get("pada") == Pada.PARASMAIPADA
            and c.get("augment", "") == "yās")


def sutra_3_4_104(c) -> bool:
    """kid āśiṣi: kit-marker in āśiṣ (benedictive) context."""
    return (c.get("lakara") == Lakara.ASHIRLING
            and c.get("is_kit", False))


def sutra_3_4_105(c) -> bool:
    """jhasya ran: 'jha' (3rd-pl-ātmanepada) is replaced by 'ran'."""
    return (c.get("ending", "") == "jha"
            and c.get("replacement", "") == "ran")


def sutra_3_4_106(c) -> bool:
    """iṭo't: 'iṭ' (2nd-sg-ātmanepada) becomes 'at'."""
    return (c.get("ending", "") == "iṭ"
            and c.get("replacement", "") == "at")


def sutra_3_4_107(c) -> bool:
    """suṭ tithoḥ: 'suṭ' augment for 't'/'th' endings [in liṅ]."""
    return (c.get("lakara") in {Lakara.VIDHILING, Lakara.ASHIRLING}
            and c.get("ending", "") in {"t", "th"}
            and c.get("augment", "") == "suṭ")


def sutra_3_4_109(c) -> bool:
    """sij abhyasta-vidibhyaś ca: also for sic/abhyasta/vid — special
    ending behavior."""
    return (c.get("dhatu_lemma", "") in {"sic", "vid"}
            or c.get("is_abhyasta", False))


def sutra_3_4_110(c) -> bool:
    """ātaḥ: after 'ā'-final [stem, the 3rd-pl ending is 'us']."""
    return c.get("stem_ends_in", "") == "ā"


def sutra_3_4_111(c) -> bool:
    """laṅaḥ śākaṭāyanasyaiva: for laṅ, per Śākaṭāyana only [special
    substitution]."""
    return (c.get("lakara") == Lakara.LAN
            and c.get("is_shakatayana", False))


def sutra_3_4_112(c) -> bool:
    """dviṣaś ca: also for 'dviṣ' [in laṅ-special context]."""
    return (c.get("dhatu_lemma", "") == "dviṣ"
            and c.get("lakara") == Lakara.LAN)


def sutra_3_4_116(c) -> bool:
    """liṅ āśiṣi: liṅ in āśiṣ (benedictive) sense."""
    return c.get("lakara") == Lakara.ASHIRLING


def sutra_3_4_117(c) -> bool:
    """chandasy ubhayathā: in Vedic, both ways [P and Ā endings] are
    permitted."""
    return c.get("is_chandas", False)


# ===========================================================================
# Fixtures
# ===========================================================================

FIXTURES: dict[str, tuple[dict, dict]] = {
    "3.4.1":   ({"scope": "dhatu_sambandha", "dhatu_lemma": "bhū"},
                {"scope": "other", "dhatu_lemma": None}),
    "3.4.2":   ({"lakara": Lakara.LOT, "semantic_context": "kriya_samabhihara"},
                {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.4.3":   ({"semantic_context": "samuccaya", "is_optional": True},
                {"semantic_context": "other", "is_optional": True}),
    "3.4.4":   ({"is_anuprayoga": True},
                {"is_anuprayoga": False}),
    "3.4.5":   ({"semantic_context": "samuccaya", "is_samanya_vacana": True},
                {"semantic_context": "samuccaya", "is_samanya_vacana": False}),
    "3.4.6":   ({"is_chandas": True, "lakara": Lakara.LUN},
                {"is_chandas": False, "lakara": Lakara.LAT}),
    "3.4.7":   ({"lakara": Lakara.LET, "semantic_context": "ling_artha"},
                {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.4.8":   ({"semantic_context": "upasamvada"},
                {"semantic_context": "other"}),
    "3.4.9":   ({"suffix": "se", "semantic_context": "tumartha"},
                {"suffix": "se", "semantic_context": "other"}),
    "3.4.10":  ({"derived_lemma": "prayai"},
                {"derived_lemma": "rāma"}),
    "3.4.11":  ({"derived_lemma": "dṛśe"},
                {"derived_lemma": "rāma"}),
    "3.4.12":  ({"suffix": "ṇamul", "semantic_context": "shaki"},
                {"suffix": "ṇamul", "semantic_context": "other"}),
    "3.4.13":  ({"suffix": "tosun", "semantic_context": "ishvara"},
                {"suffix": "tosun", "semantic_context": "other"}),
    "3.4.14":  ({"suffix": "tavai", "semantic_context": "krtya_artha"},
                {"suffix": "tavai", "semantic_context": "other"}),
    "3.4.15":  ({"derived_lemma": "avacakṣe"},
                {"derived_lemma": "rāma"}),
    "3.4.16":  ({"suffix": "tosun", "dhatu_lemma": "sthā",
                 "semantic_context": "bhava_lakshana"},
                {"suffix": "tosun", "dhatu_lemma": "rāma",
                 "semantic_context": "other"}),
    "3.4.17":  ({"suffix": "kasun", "dhatu_lemma": "sṛp"},
                {"suffix": "kasun", "dhatu_lemma": "rāma"}),
    "3.4.18":  ({"suffix": "ktvā", "first": "alaṅ",
                 "semantic_context": "pratisedha"},
                {"suffix": "ktvā", "first": "rāma",
                 "semantic_context": "other"}),
    "3.4.19":  ({"dhatu_lemma": "mā", "semantic_context": "vyatihara"},
                {"dhatu_lemma": "mā", "semantic_context": "other"}),
    "3.4.20":  ({"semantic_context": "paravara_yoga"},
                {"semantic_context": "other"}),
    "3.4.21":  ({"suffix": "ktvā", "samana_kartrka": True,
                 "is_purvakala": True},
                {"suffix": "ktvā", "samana_kartrka": False,
                 "is_purvakala": False}),
    "3.4.22":  ({"suffix": "ṇamul", "semantic_context": "abhikshnya"},
                {"suffix": "ṇamul", "semantic_context": "other"}),
    "3.4.23":  ({"is_anakanksha": False},
                {"is_anakanksha": True}),
    "3.4.24":  ({"first": "agre", "is_optional": True},
                {"first": "rāma", "is_optional": True}),
    "3.4.25":  ({"dhatu_lemma": "kṛ", "suffix": "khamuñ",
                 "semantic_context": "akrosha", "role": Role.KARMAN},
                {"dhatu_lemma": "kṛ", "suffix": "khamuñ",
                 "semantic_context": "other", "role": Role.KARTR}),
    "3.4.26":  ({"suffix": "ṇamul", "first": "svādu"},
                {"suffix": "ṇamul", "first": "rāma"}),
    "3.4.27":  ({"first": "anyathā", "is_siddha_aprayoga": True},
                {"first": "rāma", "is_siddha_aprayoga": False}),
    "3.4.28":  ({"first": "yathā", "semantic_context": "asuya_prativacana"},
                {"first": "rāma", "semantic_context": "other"}),
    "3.4.29":  ({"dhatu_lemma": "dṛś", "role": Role.KARMAN,
                 "semantic_context": "sakalya"},
                {"dhatu_lemma": "dṛś", "role": Role.KARTR,
                 "semantic_context": "other"}),
    "3.4.30":  ({"dhatu_lemma": "vind", "first": "yāvat"},
                {"dhatu_lemma": "vind", "first": "rāma"}),
    "3.4.31":  ({"dhatu_lemma": "pūr", "first": "carma"},
                {"dhatu_lemma": "pūr", "first": "rāma"}),
    "3.4.32":  ({"semantic_context": "varsha_pramana"},
                {"semantic_context": "other"}),
    "3.4.33":  ({"dhatu_lemma": "knop", "first": "cela"},
                {"dhatu_lemma": "rāma", "first": "rāma"}),
    "3.4.34":  ({"dhatu_lemma": "kaṣ", "first": "nimūla"},
                {"dhatu_lemma": "rāma", "first": "rāma"}),
    "3.4.35":  ({"dhatu_lemma": "piṣ", "first": "śuṣka"},
                {"dhatu_lemma": "rāma", "first": "rāma"}),
    "3.4.36":  ({"dhatu_lemma": "han", "first": "samūla"},
                {"dhatu_lemma": "rāma", "first": "rāma"}),
    "3.4.37":  ({"dhatu_lemma": "han", "role": Role.KARANA},
                {"dhatu_lemma": "han", "role": Role.KARTR}),
    "3.4.38":  ({"dhatu_lemma": "piṣ", "semantic_context": "snehana"},
                {"dhatu_lemma": "piṣ", "semantic_context": "other"}),
    "3.4.39":  ({"dhatu_lemma": "grah", "first": "hasta"},
                {"dhatu_lemma": "grah", "first": "rāma"}),
    "3.4.40":  ({"dhatu_lemma": "puṣ", "first": "sva"},
                {"dhatu_lemma": "puṣ", "first": "rāma"}),
    "3.4.41":  ({"dhatu_lemma": "bandh", "role": Role.ADHIKARANA},
                {"dhatu_lemma": "bandh", "role": Role.KARTR}),
    "3.4.42":  ({"is_samjna": True},
                {"is_samjna": False}),
    "3.4.43":  ({"dhatu_lemma": "naś", "kartri_lemma": "jīva"},
                {"dhatu_lemma": "naś", "kartri_lemma": "rāma"}),
    "3.4.44":  ({"dhatu_lemma": "śuṣ", "first": "ūrdhva"},
                {"dhatu_lemma": "śuṣ", "first": "rāma"}),
    "3.4.45":  ({"is_upamana": True, "role": Role.KARMAN},
                {"is_upamana": False, "role": Role.KARTR}),
    "3.4.46":  ({"dhatu_lemma": "kaṣ"},
                {"dhatu_lemma": "rāma"}),
    "3.4.47":  ({"dhatu_lemma": "upadaṃś", "case": Case.INSTRUMENTAL},
                {"dhatu_lemma": "upadaṃś", "case": Case.NOMINATIVE}),
    "3.4.48":  ({"semantic_context": "himsa", "samana_karman": True},
                {"semantic_context": "other", "samana_karman": False}),
    "3.4.49":  ({"dhatu_lemma": "rudh", "case": Case.LOCATIVE},
                {"dhatu_lemma": "rudh", "case": Case.NOMINATIVE}),
    "3.4.50":  ({"semantic_context": "samasatti"},
                {"semantic_context": "other"}),
    "3.4.51":  ({"semantic_context": "pramana"},
                {"semantic_context": "other"}),
    "3.4.52":  ({"role": Role.APADANA, "semantic_context": "paripsa"},
                {"role": Role.KARTR, "semantic_context": "other"}),
    "3.4.53":  ({"case": Case.ACCUSATIVE},
                {"case": Case.NOMINATIVE}),
    "3.4.54":  ({"semantic_context": "svanga", "is_dhruva": False},
                {"semantic_context": "svanga", "is_dhruva": True}),
    "3.4.55":  ({"semantic_context": "pariklishyamana"},
                {"semantic_context": "other"}),
    "3.4.56":  ({"dhatu_lemma": "viś", "semantic_context": "vyapyamana"},
                {"dhatu_lemma": "viś", "semantic_context": "other"}),
    "3.4.57":  ({"dhatu_lemma": "as", "semantic_context": "kriya_antara"},
                {"dhatu_lemma": "as", "semantic_context": "other"}),
    "3.4.58":  ({"dhatu_lemma": "ādiś", "first": "rāma", "is_naamya": True},
                {"dhatu_lemma": "ādiś", "first": None, "is_naamya": False}),
    "3.4.59":  ({"dhatu_lemma": "kṛ", "is_avyaya_present": True,
                 "semantic_context": "ayathabhipreta"},
                {"dhatu_lemma": "kṛ", "is_avyaya_present": False,
                 "semantic_context": "other"}),
    "3.4.60":  ({"first": "tiryac"},
                {"first": "rāma"}),
    "3.4.61":  ({"dhatu_lemma": "kṛ", "first_suffix": "tas"},
                {"dhatu_lemma": "kṛ", "first_suffix": "kta"}),
    "3.4.62":  ({"suffix": "kta", "is_dha_artha": False},
                {"suffix": "cvi", "is_dha_artha": True}),
    "3.4.63":  ({"dhatu_lemma": "bhū", "first": "tūṣṇīm"},
                {"dhatu_lemma": "bhū", "first": "rāma"}),
    "3.4.64":  ({"semantic_context": "anulomya"},
                {"semantic_context": "other"}),
    "3.4.65":  ({"suffix": "tumun", "dhatu_lemma": "śak"},
                {"suffix": "tumun", "dhatu_lemma": "rāma"}),
    "3.4.66":  ({"suffix": "tumun", "semantic_context": "alam_artha"},
                {"suffix": "tumun", "semantic_context": "other"}),
    "3.4.67":  ({"is_kartari": True},
                {"is_kartari": False, "scope": "other"}),
    "3.4.68":  ({"derived_lemma": "bhavya"},
                {"derived_lemma": "rāma"}),
    "3.4.70":  ({"suffix": "kta"},
                {"suffix": "ṇvul"}),
    "3.4.73":  ({"derived_lemma": "dāśa", "role": Role.SAMPRADANA},
                {"derived_lemma": "dāśa", "role": Role.KARTR}),
    "3.4.74":  ({"derived_lemma": "bhīma", "role": Role.APADANA},
                {"derived_lemma": "bhīma", "role": Role.KARTR}),
    "3.4.75":  ({"suffix": "un", "is_unadi": True},
                {"suffix": "kta", "is_unadi": False}),
    "3.4.76":  ({"suffix": "kta", "role": Role.ADHIKARANA,
                 "semantic_context": "dhrauvya"},
                {"suffix": "kta", "role": Role.KARTR,
                 "semantic_context": "other"}),
    "3.4.77":  ({"scope": "lasya", "is_la_replacement": True},
                {"scope": "other", "is_la_replacement": False}),
    "3.4.78":  ({"suffix": "tip"},
                {"suffix": "kta"}),
    "3.4.81":  ({"lakara": Lakara.LIT, "ending": "eś"},
                {"lakara": Lakara.LAT, "ending": "ti"}),
    "3.4.82":  ({"lakara": Lakara.LIT, "pada": Pada.PARASMAIPADA,
                 "ending": "ṇal"},
                {"lakara": Lakara.LAT, "pada": Pada.PARASMAIPADA,
                 "ending": "tip"}),
    "3.4.83":  ({"dhatu_lemma": "vid", "lakara": Lakara.LAT,
                 "is_optional": True},
                {"dhatu_lemma": "rāma", "lakara": Lakara.LAT,
                 "is_optional": True}),
    "3.4.84":  ({"dhatu_lemma": "brū", "lakara": Lakara.LIT},
                {"dhatu_lemma": "rāma", "lakara": Lakara.LIT}),
    "3.4.85":  ({"lakara": Lakara.LOT},
                {"lakara": Lakara.LAT}),
    "3.4.89":  ({"lakara": Lakara.LOT, "person": Person.FIRST,
                 "ending": "mi"},
                {"lakara": Lakara.LAT, "person": Person.THIRD,
                 "ending": "ti"}),
    "3.4.90":  ({"lakara": Lakara.LOT, "pada": Pada.ATMANEPADA,
                 "ending": "e"},
                {"lakara": Lakara.LAT, "pada": Pada.PARASMAIPADA,
                 "ending": "ti"}),
    "3.4.91":  ({"ending": "sva"},
                {"ending": "ti"}),
    "3.4.93":  ({"lakara": Lakara.LOT, "ending": "e",
                 "pada": Pada.ATMANEPADA},
                {"lakara": Lakara.LAT, "ending": "ti",
                 "pada": Pada.PARASMAIPADA}),
    "3.4.94":  ({"lakara": Lakara.LET, "augment": "aḍ"},
                {"lakara": Lakara.LAT, "augment": None}),
    "3.4.95":  ({"lakara": Lakara.LET, "stem_ends_in": "ā"},
                {"lakara": Lakara.LAT, "stem_ends_in": "a"}),
    "3.4.96":  ({"lakara": Lakara.LET, "ending": "vai"},
                {"lakara": Lakara.LAT, "ending": "ti"}),
    "3.4.97":  ({"pada": Pada.PARASMAIPADA, "ending": "ti"},
                {"pada": Pada.ATMANEPADA, "ending": "te"}),
    "3.4.98":  ({"person": Person.FIRST, "is_s_augment": True},
                {"person": Person.THIRD, "is_s_augment": False}),
    "3.4.99":  ({"is_nit": True, "is_obligatory": True},
                {"is_nit": False, "is_obligatory": True}),
    "3.4.102": ({"lakara": Lakara.VIDHILING, "augment": "sīy"},
                {"lakara": Lakara.LAT, "augment": None}),
    "3.4.103": ({"lakara": Lakara.VIDHILING, "pada": Pada.PARASMAIPADA,
                 "augment": "yās"},
                {"lakara": Lakara.LAT, "pada": Pada.PARASMAIPADA,
                 "augment": None}),
    "3.4.104": ({"lakara": Lakara.ASHIRLING, "is_kit": True},
                {"lakara": Lakara.LAT, "is_kit": False}),
    "3.4.105": ({"ending": "jha", "replacement": "ran"},
                {"ending": "ti", "replacement": None}),
    "3.4.106": ({"ending": "iṭ", "replacement": "at"},
                {"ending": "ti", "replacement": None}),
    "3.4.107": ({"lakara": Lakara.VIDHILING, "ending": "t",
                 "augment": "suṭ"},
                {"lakara": Lakara.LAT, "ending": "ti", "augment": None}),
    "3.4.109": ({"dhatu_lemma": "vid"},
                {"dhatu_lemma": "rāma", "is_abhyasta": False}),
    "3.4.110": ({"stem_ends_in": "ā"},
                {"stem_ends_in": "a"}),
    "3.4.111": ({"lakara": Lakara.LAN, "is_shakatayana": True},
                {"lakara": Lakara.LAT, "is_shakatayana": False}),
    "3.4.112": ({"dhatu_lemma": "dviṣ", "lakara": Lakara.LAN},
                {"dhatu_lemma": "rāma", "lakara": Lakara.LAT}),
    "3.4.116": ({"lakara": Lakara.ASHIRLING},
                {"lakara": Lakara.LAT}),
    "3.4.117": ({"is_chandas": True},
                {"is_chandas": False}),
}


(
    IMPLEMENTED_IDS,
    has_real_implementation,
    handler_for,
    positive_features,
    negative_features,
) = make_module_api(FIXTURES, globals())
