"""
Discrete Pāṇini-correct implementations for Adhyāya 3.1 sutra predicates.

Each function sutra_3_1_X(c) -> bool returns True iff sutra 3.1.X fires in the
derivation context c (a plain dict / SutraContext).

This module REPLACES the slug-roundtrip scaffold previously generated by
sutra_handlers_adhyaya23._evaluate for Adhyāya 3.1.

Context keys used across Adhyāya 3.1:
  dhatu_lemma     str        – root being derived from
  suffix          str        – suffix being introduced (san, ṇic, kyaṅ, …)
  upasarga        str|None   – verbal prefix (pra, ni, vi, …)
  upapada         str|None   – upapada governing the kṛt
  semantic_context str|None  – fine-grained meaning tag (ācāra, ākroṣa, …)
  kartri_lemma    str|None   – agent in kartṛ relation
  karman_lemma    str|None   – object in karman relation
  samana_kartrka  bool       – same-agent context (for san 3.1.7)
  is_iccha        bool       – wish/desire context
  lakara          Lakara|None
  pada            Pada|None
  is_chandas      bool       – Vedic register
  is_sarvadhatuka bool
  is_ardhadhatuka bool
  is_optional     bool       – vikalpa licensed
  is_kartari      bool       – kartṛ-prayoga
  is_karmani      bool       – karma-prayoga
  is_bhave        bool       – impersonal
  varga           int        – conjugational class (1..10)
  source_pos      PartOfSpeech|None – source category (noun/numeral/…)
  is_namadhatu    bool       – denominative context
  is_causative    bool       – ṇic / hetumat context
  acc_object      bool       – accusative object expressed (for 3.1.87)
  is_lit_compatible bool     – context allows liṭ-periphrastic āṃ
  num_syllables   int        – syllable count for 3.1.35-ish anuv.
  is_ghu          bool       – root has ghu-saṃjñā
  is_vowel_initial bool      – first sound of next morpheme is a vowel

Conventions:
  • Each predicate is conservative: it returns True only when the listed
    Pāṇinian conditions in the sutra are met.
  • The accompanying FIXTURES dict provides a real linguistic positive and
    negative example per sutra, exercised by tests.
"""
from __future__ import annotations

from .grammar import Gender, Lakara, Pada, Role
from .sutra_impl_base import make_module_api


# ---------------------------------------------------------------------------
# Lexical groups referenced by multiple sutras
# ---------------------------------------------------------------------------

# 3.1.6 — roots whose abhyāsa is lengthened in san (desiderative)
MAN_BADH_DAN_SAN = frozenset({"mān", "badh", "dān", "śān"})

# 3.1.12 — bhṛśādi roots (in bhū-sense, ac-vi-lopa, with final hal)
BHRSHADI = frozenset({"bhṛśa", "śīghra", "manda", "cira", "abhīkṣṇa"})

# 3.1.13 — lohitādi + ḍāj class (kyaṣ)
LOHITADI = frozenset({"lohita", "nīla", "harita", "pīta", "kṛṣṇa", "śveta", "babhru"})

# 3.1.18 — sukhādi (kyaṅ in kartṛ-vedana)
SUKHADI = frozenset({"sukha", "duḥkha", "śoka", "tṛpti", "ūrjas", "kṛcchra", "alasya"})

# 3.1.20 — puccha/bhāṇḍa/cīvara (ṇiṅ)
PUCCHA_ETC = frozenset({"puccha", "bhāṇḍa", "cīvara"})

# 3.1.21 — muṇḍa-class (ṇic in kṛ sense)
MUNDADI = frozenset({
    "muṇḍa", "miśra", "ślakṣṇa", "lavaṇa", "vrata", "vastra",
    "hala", "kala", "kṛta", "tūsta",
})

# 3.1.24 — lup/sad/car/jap/jabh/dah/daś/gṝ (yaṅ in bhāva-garhā)
LUPADI = frozenset({"lup", "sad", "car", "jap", "jabh", "dah", "daś", "gṝ"})

# 3.1.27 — kaṇḍū-class (yak — denominative)
KANDVADI = frozenset({
    "kaṇḍū", "manda", "pruṣ", "asū", "leḍ", "leṭ", "lāj", "lokṛ",
    "ileḷ", "rama", "sukha", "śabda",
})

# 3.1.28 — gup, dhūp, vicch, paṇ, pan (āya suffix)
GUP_DHUP_ETC = frozenset({"gup", "dhūp", "vicch", "paṇ", "pan"})

# 3.1.36 — gurumat roots taking āṃ in liṭ (excluding ṛc-)
GURUMAT_LIT_ROOTS = frozenset({"īkṣ", "edh", "īṣ", "īh", "īraya"})

# 3.1.39 — bhī/hrī/bhṛ/hu (śluvat for liṭ-āṃ in some contexts)
BHI_HRI_BHR_HU = frozenset({"bhī", "hrī", "bhṛ", "hu"})

# 3.1.45 — śal-class iguupadhā aniṭ roots → ksa
SHAL_IGUPADHA_ANIT = frozenset({"diś", "duh", "dih", "lih", "viś", "kṛṣ", "ruh", "muh", "snih", "snuh"})

# 3.1.48 — ṇi/śri/dru/sru (caṅ in kartari)
NI_SRI_DRU_SRU = frozenset({"śri", "dru", "sru"})

# 3.1.51 — non-ay-ay roots
NON_AY_AY = frozenset({"nonay", "dhvanay", "elay", "arday"})

# 3.1.52 — as/vac/khyā (aṅ)
AS_VAC_KHYA = frozenset({"as", "vac", "khyā"})

# 3.1.55 — puṣādi/dyutādi/ḷdit (parasmaipada aṅ)
PUSHADI = frozenset({"puṣ", "dyut", "śvit", "mid", "svid", "kṣubh", "tap", "dyup"})

# 3.1.58 — jṛ/stambhu/mrucu/mlucu/grucu/glucu/gluñcu/śvi (aṅ)
JR_STAMBHU_ETC = frozenset({"jṛ", "stambh", "mruc", "mluc", "gruc", "gluc", "gluñc", "śvi"})

# 3.1.61 — dīp/jan/budh/pūri/tāyi/pyāyi (vā cli substitution)
DIP_JAN_BUDH_ETC = frozenset({"dīp", "jan", "budh", "pūri", "tāyi", "pyāyi"})

# 3.1.83 — śna with hal — śā substitutes śna before consonant
# (handled by checking varga 9 + halādi suffix)

# 3.1.109 — eti, stu, śas, vṛ, dṛ, juṣ (kyap)
ETI_STU_ETC = frozenset({"i", "stu", "śas", "vṛ", "dṛ", "juṣ"})

# 3.1.134 — nandi/grahi/paci-class (lyu / ṇini / ac)
NANDI_GRAHI_PACI = frozenset({
    "nand", "grah", "pac", "vad", "car", "vah", "khan", "ji",
    "ad", "dā", "bhuj", "hṛ", "vid",
})

# 3.1.135 — ik-upadha + jñā/prī/kṝ (ka)
IGUPADHA_JNA_PRI_KRR = frozenset({"jñā", "prī", "kṝ", "viś", "diś", "kṛṣ"})

# 3.1.140 — jvalitikasanta roots (ṇa)
JVALITI_KASANTA = frozenset({"jval", "kas", "kīṭ"})

# 3.1.141 — śyā/dyu/vyadh/āsru/saṃsṛ/vatī/avahṛ/lih/śliṣ/śvas (ṇa)
SHYA_ETC = frozenset({"śyā", "dyu", "vyadh", "āsru", "saṃsṛ", "avahṛ", "lih", "śliṣ", "śvas"})


# ===========================================================================
# 3.1.1 – 3.1.4 : meta-rules (adhikāra / accent)
# ===========================================================================

def sutra_3_1_1(c) -> bool:
    """pratyayaḥ: adhikāra — these rules introduce suffixes (pratyaya).
    Fires whenever the derivation context is introducing a pratyaya."""
    return c.get("scope") == "pratyaya" or c.get("suffix") is not None


def sutra_3_1_2(c) -> bool:
    """paraś ca: the pratyaya stands after [the base, paraṃ]. Fires when
    the context positions a suffix to the right of its base."""
    return c.get("scope") == "para" or c.get("suffix_is_para", False)


def sutra_3_1_3(c) -> bool:
    """ādyudāttaś ca: a suffix is ādyudātta (first-syllable accented),
    unless overridden. Saṃjñā/accent rule."""
    return c.get("scope") == "adyudatta" or c.get("is_adyudatta", False)


def sutra_3_1_4(c) -> bool:
    """anudāttau suppitau: sup endings and pit suffixes are anudātta.
    Accent rule on case-endings and pit-marked suffixes."""
    suffix = c.get("suffix", "")
    return (c.get("is_sup", False)
            or c.get("is_pit", False)
            or suffix.startswith("p"))


# ===========================================================================
# 3.1.6 – 3.1.31 : san, kyaṅ, kyaṣ, kyac, ṇic, yak, āya, iyaṅ — derived dhātus
# ===========================================================================

def sutra_3_1_6(c) -> bool:
    """mānbadhadānśānbhyo dīrghaś cābhyāsasya: for mān/badh/dān/śān roots,
    the abhyāsa (reduplication) is lengthened in san (desiderative)."""
    return (c.get("dhatu_lemma", "") in MAN_BADH_DAN_SAN
            and c.get("suffix", "") == "san")


def sutra_3_1_7(c) -> bool:
    """dhātoḥ karmaṇaḥ samānakartṛkād icchāyāṃ vā: san (desiderative) is
    introduced after a root that is the karman of icchā when the agent
    of icchā and the agent of the root are the same."""
    return (c.get("suffix", "") == "san"
            and c.get("is_iccha", False)
            and c.get("samana_kartrka", False))


def sutra_3_1_9(c) -> bool:
    """kāmyac ca: also kāmyac suffix [in desire/want context, after a
    nominal stem]."""
    return c.get("suffix", "") == "kāmyac"


def sutra_3_1_10(c) -> bool:
    """upamānādācāre: kyaṅ after an upamāna (simile-standard) noun in
    ācāra (behaving like) sense."""
    return (c.get("suffix", "") == "kyaṅ"
            and c.get("is_upamana", False)
            and c.get("semantic_context") == "acara")


def sutra_3_1_11(c) -> bool:
    """kartuḥ kyaṅ salopaś ca: kyaṅ after a kartṛ-relation noun, with
    s-lopa (sa-elision)."""
    return (c.get("suffix", "") == "kyaṅ"
            and c.get("is_kartari", False))


def sutra_3_1_12(c) -> bool:
    """bhṛśādibhyo bhuvy acver lopaś ca halaḥ: kyaṅ after bhṛśādi in
    'becoming' (bhū) sense, with loss of final hal under specific conds."""
    return (c.get("dhatu_lemma", "") in BHRSHADI
            and c.get("semantic_context") == "bhavana")


def sutra_3_1_13(c) -> bool:
    """lohitādiḍājbhyaḥ kyaṣ: kyaṣ after lohitādi/ḍāj-class words
    (becoming red etc.)."""
    return (c.get("suffix", "") == "kyaṣ"
            and c.get("dhatu_lemma", "") in LOHITADI)


def sutra_3_1_14(c) -> bool:
    """kaṣṭāya kramaṇe: kyaṅ after 'kaṣṭa' in 'striving / advancing'
    sense."""
    return (c.get("dhatu_lemma", "") == "kaṣṭa"
            and c.get("semantic_context") == "kramana")


def sutra_3_1_15(c) -> bool:
    """karmaṇaḥ romanthatapobhyāṃ varti caroḥ: kyaṅ after 'romantha' /
    'tapas' in karman role (chewing cud / practising austerity)."""
    return (c.get("dhatu_lemma", "") in {"romantha", "tapas"}
            and c.get("role") == Role.KARMAN)


def sutra_3_1_16(c) -> bool:
    """bāṣpoṣmābhyāṃ udvamane: kyaṅ after 'bāṣpa' / 'ūṣmā' in 'emitting'
    sense (giving forth steam/heat)."""
    return (c.get("dhatu_lemma", "") in {"bāṣpa", "ūṣma"}
            and c.get("semantic_context") == "udvamana")


def sutra_3_1_17(c) -> bool:
    """śabdavairakalahābhrakaṇvameghebhyaḥ karaṇe: kyaṅ after
    śabda/vaira/kalaha/abhra/kaṇva/megha in karaṇa (making) sense."""
    return (c.get("dhatu_lemma", "") in {
        "śabda", "vaira", "kalaha", "abhra", "kaṇva", "megha"
    } and c.get("role") == Role.KARANA)


def sutra_3_1_18(c) -> bool:
    """sukhādibhyaḥ kartṛvedanāyām: kyaṅ after sukhādi (sukha/duḥkha/…)
    in 'feeling, experiencing' (kartṛ-vedana) sense."""
    return (c.get("dhatu_lemma", "") in SUKHADI
            and c.get("semantic_context") == "kartri_vedana")


def sutra_3_1_19(c) -> bool:
    """namovarivaścitraṅaḥ kyac: kyac after namas/varivas/citra (homage,
    wealth, varied)."""
    return (c.get("suffix", "") == "kyac"
            and c.get("dhatu_lemma", "") in {"namas", "varivas", "citra"})


def sutra_3_1_20(c) -> bool:
    """pucchabhāṇḍacīvarāṇṇiṅ: ṇiṅ after puccha/bhāṇḍa/cīvara
    (denominative — to make a tail / pot / robe)."""
    return (c.get("suffix", "") == "ṇiṅ"
            and c.get("dhatu_lemma", "") in PUCCHA_ETC)


def sutra_3_1_21(c) -> bool:
    """muṇḍamiśraślakṣṇa…: ṇic after muṇḍādi (to shave/mix/polish/…)."""
    return (c.get("suffix", "") == "ṇic"
            and c.get("dhatu_lemma", "") in MUNDADI)


def sutra_3_1_23(c) -> bool:
    """nityaṃ kauṭilye gatau: yaṅ obligatorily in 'crookedness in motion'
    sense."""
    return (c.get("suffix", "") == "yaṅ"
            and c.get("semantic_context") == "kautilya_gati")


def sutra_3_1_24(c) -> bool:
    """lupasadacarajapajabhadahadaśagṝbhyo bhāvagarhāyām: yaṅ after
    lup/sad/car/jap/jabh/dah/daś/gṝ in 'reproach of action' sense."""
    return (c.get("suffix", "") == "yaṅ"
            and c.get("dhatu_lemma", "") in LUPADI
            and c.get("semantic_context") == "bhava_garha")


def sutra_3_1_26(c) -> bool:
    """hetumati ca: ṇic (causative) in hetumat (causative-of-X) sense."""
    return (c.get("suffix", "") == "ṇic"
            and c.get("is_causative", False))


def sutra_3_1_27(c) -> bool:
    """kaṇḍvādibhyo yak: yak after kaṇḍū-class roots (denominative).
    These give 'kaṇḍūyati' etc."""
    return (c.get("suffix", "") == "yak"
            and c.get("dhatu_lemma", "") in KANDVADI)


def sutra_3_1_28(c) -> bool:
    """gupūdhūpavicchipaṇipanibhya āyaḥ: āya suffix after
    gup/dhūp/vicch/paṇ/pan."""
    return (c.get("suffix", "") == "āya"
            and c.get("dhatu_lemma", "") in GUP_DHUP_ETC)


def sutra_3_1_29(c) -> bool:
    """ṛter īyaṅ: īyaṅ after 'ṛti' (going)."""
    return (c.get("suffix", "") == "īyaṅ"
            and c.get("dhatu_lemma", "") == "ṛti")


def sutra_3_1_30(c) -> bool:
    """kamer ṇiṅ: ṇiṅ after 'kam' (love/desire)."""
    return (c.get("suffix", "") == "ṇiṅ"
            and c.get("dhatu_lemma", "") == "kam")


def sutra_3_1_31(c) -> bool:
    """āyādaya ārdhadhātuke vā: āya etc. (3.1.28-30) optionally in
    ārdhadhātuka context."""
    return (c.get("suffix", "") in {"āya", "īyaṅ", "ṇiṅ"}
            and c.get("is_ardhadhatuka", False))


# ===========================================================================
# 3.1.32 : sanādyantā dhātavaḥ — meta-rule
# ===========================================================================

def sutra_3_1_32(c) -> bool:
    """sanādyantā dhātavaḥ: stems ending in san, kyac, kāmyac, kyaṅ, kyaṣ,
    ṇiṅ, ṇic, yaṅ, yak, āya, īyaṅ get the saṃjñā 'dhātu'."""
    return c.get("suffix", "") in {
        "san", "kyac", "kāmyac", "kyaṅ", "kyaṣ", "ṇiṅ", "ṇic",
        "yaṅ", "yak", "āya", "īyaṅ",
    }


# ===========================================================================
# 3.1.33 – 3.1.42 : lakāra helpers (sya/tās/āṃ in lṛ-, luṭ-, liṭ-)
# ===========================================================================

def sutra_3_1_33(c) -> bool:
    """syatāsī lṛluṭoḥ: sya is the vikaraṇa of lṛt and lṛṅ; tās is
    introduced for luṭ."""
    return c.get("lakara") in {Lakara.LRT, Lakara.LRN, Lakara.LUT}


def sutra_3_1_34(c) -> bool:
    """sib bahulaṃ leṭi: sip variously in leṭ (Vedic subjunctive)."""
    return (c.get("lakara") == Lakara.LET
            and c.get("is_chandas", False))


def sutra_3_1_35(c) -> bool:
    """kāspratyayād āmamantre liṭi: kās + the periphrastic āṃ in liṭ
    outside of mantra."""
    return (c.get("dhatu_lemma", "") == "kās"
            and c.get("lakara") == Lakara.LIT
            and not c.get("is_mantra", False))


def sutra_3_1_36(c) -> bool:
    """ijādeś ca gurumato'nṛcchaḥ: gurumat root beginning with ij- (vowel)
    takes āṃ in liṭ, except 'ṛc'."""
    lemma = c.get("dhatu_lemma", "")
    return (c.get("lakara") == Lakara.LIT
            and lemma in GURUMAT_LIT_ROOTS
            and lemma != "ṛc")


def sutra_3_1_37(c) -> bool:
    """dayāyāsaś ca: also 'day', 'ās' take āṃ in liṭ."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("dhatu_lemma", "") in {"day", "ās"})


def sutra_3_1_38(c) -> bool:
    """uṣavidajāgṛbhyo'nyatarasyām: optionally for uṣ/vid/jāgṛ — āṃ in
    liṭ."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("dhatu_lemma", "") in {"uṣ", "vid", "jāgṛ"}
            and c.get("is_optional", True))


def sutra_3_1_39(c) -> bool:
    """bhīhrībhṛhuvāṃ śluvat ca: śluvat (reduplication-like) treatment in
    liṭ-āṃ context for bhī/hrī/bhṛ/hu."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("dhatu_lemma", "") in BHI_HRI_BHR_HU)


def sutra_3_1_40(c) -> bool:
    """kṛñ cānuprayujyate liṭi: 'kṛ' is conjoined (anuprayukta) after the
    periphrastic āṃ in liṭ. (Forms like 'cakāra' is replaced by
    'X-āṃ cakre/cakāra/babhūva'.)"""
    return (c.get("lakara") == Lakara.LIT
            and c.get("is_am_paribhasha", False))


def sutra_3_1_41(c) -> bool:
    """vidāṅkurvantv ity anyatarasyām: 'kurvantu' is optionally the
    auxiliary for 'vid' in liṭ-āṃ."""
    return (c.get("dhatu_lemma", "") == "vid"
            and c.get("lakara") == Lakara.LIT
            and c.get("is_optional", True))


def sutra_3_1_42(c) -> bool:
    """abhyutsādayāṃ prajanayāṃ … : compound + āṃ + auxiliary forms in
    liṭ-āṃ context (specific lexically listed compounds)."""
    return (c.get("lakara") == Lakara.LIT
            and c.get("is_compound_am", False))


# ===========================================================================
# 3.1.43 – 3.1.66 : cli vikaraṇa for luṅ + replacements (sic / ksa / aṅ / caṅ)
# ===========================================================================

def sutra_3_1_43(c) -> bool:
    """cli luṅi: the vikaraṇa 'cli' is introduced for luṅ. cli is a
    technical placeholder later replaced by sic, ksa, aṅ, caṅ."""
    return c.get("lakara") == Lakara.LUN


def sutra_3_1_44(c) -> bool:
    """cleḥ sic: the default substitute for cli is sic (s-aorist)."""
    return (c.get("lakara") == Lakara.LUN
            and c.get("suffix", "") == "sic")


def sutra_3_1_45(c) -> bool:
    """śal igupadhād aniṭaḥ ksaḥ: ksa replaces cli for śal-final
    ig-upadha aniṭ roots."""
    return (c.get("lakara") == Lakara.LUN
            and c.get("suffix", "") == "ksa"
            and c.get("dhatu_lemma", "") in SHAL_IGUPADHA_ANIT)


def sutra_3_1_46(c) -> bool:
    """śliṣa āliṅgane: ksa for 'śliṣ' in 'embracing' sense."""
    return (c.get("dhatu_lemma", "") == "śliṣ"
            and c.get("semantic_context") == "alingana"
            and c.get("suffix", "") == "ksa")


def sutra_3_1_47(c) -> bool:
    """na dṛśaḥ: ksa does NOT apply to 'dṛś'. (Prohibition for 3.1.45)."""
    return c.get("dhatu_lemma", "") != "dṛś"


def sutra_3_1_48(c) -> bool:
    """ṇiśridrusrubhyaḥ kartari caṅ: caṅ replaces cli for ṇi/śri/dru/sru
    in kartari (active) prayoga."""
    return (c.get("suffix", "") == "caṅ"
            and c.get("dhatu_lemma", "") in NI_SRI_DRU_SRU
            and c.get("is_kartari", False))


def sutra_3_1_49(c) -> bool:
    """vibhāṣā dheṭśvyoḥ: optionally for 'dheṭ' (to suck) and 'śvi'
    (to swell) — caṅ."""
    return (c.get("dhatu_lemma", "") in {"dhe", "śvi"}
            and c.get("suffix", "") == "caṅ"
            and c.get("is_optional", True))


def sutra_3_1_50(c) -> bool:
    """gupeś chandasi: 'gup' takes caṅ in Vedic register."""
    return (c.get("dhatu_lemma", "") == "gup"
            and c.get("is_chandas", False)
            and c.get("suffix", "") == "caṅ")


def sutra_3_1_51(c) -> bool:
    """nonayatidhvanayaty elayaty ardayatibhyaḥ: caṅ for non-ay /
    dhvanay / elay / arday."""
    return (c.get("dhatu_lemma", "") in NON_AY_AY
            and c.get("suffix", "") == "caṅ")


def sutra_3_1_52(c) -> bool:
    """asyativaktikhyātibhyaḥ aṅ: aṅ for 'as'/'vac'/'khyā' in luṅ."""
    return (c.get("dhatu_lemma", "") in AS_VAC_KHYA
            and c.get("suffix", "") == "aṅ"
            and c.get("lakara") == Lakara.LUN)


def sutra_3_1_53(c) -> bool:
    """lipisicihvaśca: also for 'lip' (smear), 'sic' (sprinkle), 'hve'
    (call) — aṅ."""
    return (c.get("dhatu_lemma", "") in {"lip", "sic", "hve"}
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_54(c) -> bool:
    """ātmanepadeṣv anyatarasyām: optionally in ātmanepada [forms]."""
    return (c.get("pada") == Pada.ATMANEPADA
            and c.get("is_optional", True))


def sutra_3_1_55(c) -> bool:
    """puṣādidyutādyḷditaḥ parasmaipadeṣu: aṅ for puṣ-/dyut-/ḷ-marked
    roots in parasmaipada."""
    return (c.get("dhatu_lemma", "") in PUSHADI
            and c.get("pada") == Pada.PARASMAIPADA
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_56(c) -> bool:
    """sarttiśāstyartibhyaś ca: aṅ also for 'sṛ', 'śās', 'ṛ' [in luṅ]."""
    return (c.get("dhatu_lemma", "") in {"sṛ", "śās", "ṛ"}
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_57(c) -> bool:
    """irito vā: optionally for ir-marked roots [in luṅ]."""
    return (c.get("is_irit", False)
            and c.get("is_optional", True))


def sutra_3_1_58(c) -> bool:
    """jṛstambhumrucumlucu…: aṅ for jṛ/stambh/mruc/mluc/gruc/gluc/gluñc/śvi
    in luṅ."""
    return (c.get("dhatu_lemma", "") in JR_STAMBHU_ETC
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_59(c) -> bool:
    """kṛmṛdṛruhibhyaś chandasi: aṅ for kṛ/mṛ/dṛ/ruh in Vedic."""
    return (c.get("dhatu_lemma", "") in {"kṛ", "mṛ", "dṛ", "ruh"}
            and c.get("is_chandas", False)
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_60(c) -> bool:
    """ciṇ te padaḥ: ciṇ for 'pad' before 'ta' [3sg ātmanepada in karmaṇi]."""
    return (c.get("dhatu_lemma", "") == "pad"
            and c.get("suffix", "") == "ciṇ"
            and c.get("ending", "") == "ta")


def sutra_3_1_61(c) -> bool:
    """dīpajanabudhapūritāyipyāyibhyo'nyatarasyām: optionally ciṇ for
    dīp/jan/budh/pūri/tāyi/pyāyi."""
    return (c.get("dhatu_lemma", "") in DIP_JAN_BUDH_ETC
            and c.get("suffix", "") == "ciṇ"
            and c.get("is_optional", True))


def sutra_3_1_62(c) -> bool:
    """acaḥ karmakartari: ciṇ for vowel-ending roots in karman-as-kartṛ
    construction (reflexive-passive)."""
    return (c.get("is_karmakartri", False)
            and c.get("dhatu_ends_in_vowel", False)
            and c.get("suffix", "") == "ciṇ")


def sutra_3_1_63(c) -> bool:
    """duhaś ca: also for 'duh' [ciṇ in karmakartṛ]."""
    return (c.get("dhatu_lemma", "") == "duh"
            and c.get("suffix", "") == "ciṇ")


def sutra_3_1_64(c) -> bool:
    """na rudhaḥ: ciṇ does NOT apply to 'rudh'."""
    return c.get("dhatu_lemma", "") != "rudh"


def sutra_3_1_65(c) -> bool:
    """tapo'nutāpe ca: 'tap' in 'anutāpa' (repentance) sense — ciṇ."""
    return (c.get("dhatu_lemma", "") == "tap"
            and c.get("semantic_context") == "anutapa"
            and c.get("suffix", "") == "ciṇ")


def sutra_3_1_66(c) -> bool:
    """ciṇ bhāvakarmaṇoḥ: ciṇ in bhāva (impersonal) and karman (passive)
    constructions (general rule)."""
    return (c.get("suffix", "") == "ciṇ"
            and (c.get("is_bhave", False) or c.get("is_karmani", False)))


# ===========================================================================
# 3.1.67 – 3.1.90 : yak (passive marker) + śnu / śna / śyan
# ===========================================================================

def sutra_3_1_67(c) -> bool:
    """sārvadhātuke yak: yak (passive marker) in sārvadhātuka context."""
    return (c.get("suffix", "") == "yak"
            and c.get("is_sarvadhatuka", False))


def sutra_3_1_70(c) -> bool:
    """vā bhrāśabhlāśabhramukramuklamutrasitruṭilaṣaḥ: optionally for
    bhrāś/bhlāś/bhram/kram/klam/tras/truṭ/laṣ — śyan."""
    return (c.get("dhatu_lemma", "") in {
        "bhrāś", "bhlāś", "bhram", "kram", "klam", "tras", "truṭ", "laṣ"
    } and c.get("suffix", "") == "śyan"
        and c.get("is_optional", True))


def sutra_3_1_71(c) -> bool:
    """yaso'nupasargāt: 'yas' [takes śyan] when not prefixed by an
    upasarga."""
    return (c.get("dhatu_lemma", "") == "yas"
            and c.get("upasarga") is None)


def sutra_3_1_72(c) -> bool:
    """saṃyasaś ca: also 'sam-yas' (with sam-prefix) — śyan."""
    return (c.get("dhatu_lemma", "") == "yas"
            and c.get("upasarga") == "sam")


def sutra_3_1_74(c) -> bool:
    """śruvaḥ śṛ ca: 'śru' substitutes 'śṛ' [in this context, with śnu]."""
    return (c.get("dhatu_lemma", "") == "śru"
            and c.get("suffix", "") == "śnu")


def sutra_3_1_75(c) -> bool:
    """akṣo'nyatarasyām: optionally for 'akṣ' — śnu."""
    return (c.get("dhatu_lemma", "") == "akṣ"
            and c.get("suffix", "") == "śnu"
            and c.get("is_optional", True))


def sutra_3_1_76(c) -> bool:
    """tanūkaraṇe takṣaḥ: 'takṣ' in 'thinning/paring' sense — śnu."""
    return (c.get("dhatu_lemma", "") == "takṣ"
            and c.get("semantic_context") == "tanu_karana"
            and c.get("suffix", "") == "śnu")


def sutra_3_1_80(c) -> bool:
    """dhinvikṛṇvyora ca: 'dhinv' and 'kṛṇv' [take śnu] also."""
    return (c.get("dhatu_lemma", "") in {"dhinv", "kṛṇv"}
            and c.get("suffix", "") == "śnu")


def sutra_3_1_82(c) -> bool:
    """stambhustumbhuskambhuskumbhuskuñbhyaḥ śnuś ca: śnu also for
    stambh/stumbh/skambh/skumbh/skuñ (kṣubh-class)."""
    return (c.get("dhatu_lemma", "") in {
        "stambh", "stumbh", "skambh", "skumbh", "skuñ",
    } and c.get("suffix", "") == "śnu")


def sutra_3_1_83(c) -> bool:
    """halaḥ śnaḥ śā nau jhau: in śna (varga 9) before a consonant-initial
    suffix, śna is replaced by 'śā'."""
    return (c.get("varga", 0) == 9
            and c.get("suffix", "") == "śna"
            and c.get("is_halaadi_ending", False))


def sutra_3_1_84(c) -> bool:
    """chandasi śāyaj api: in Vedic, 'śāyaj' is also possible."""
    return (c.get("is_chandas", False)
            and c.get("suffix", "") in {"śāyaj", "śna"})


def sutra_3_1_85(c) -> bool:
    """vyatyayo bahulam: interchange (vyatyaya) of forms is variously
    permitted (a meta-rule for Vedic flexibility)."""
    return (c.get("is_chandas", False)
            and c.get("is_vyatyaya", False))


def sutra_3_1_86(c) -> bool:
    """liṅy āśiṣy aṅ: aṅ vikaraṇa for liṅ in āśiṣ (benedictive) sense."""
    return (c.get("lakara") == Lakara.ASHIRLING
            and c.get("suffix", "") == "aṅ")


def sutra_3_1_87(c) -> bool:
    """karmavat karmaṇā tulyakriyaḥ: a karman (object) is treated like
    karman when its action is the same as the agent's action.
    (Reflexive-like construction; underlies karmakartṛ.)"""
    return (c.get("is_karmakartri", False)
            or c.get("role") == Role.KARMAN)


def sutra_3_1_88(c) -> bool:
    """tapas tapaḥkarmakasyaiva: 'tap' is karmavat only when 'tapas' is
    its specific object."""
    return (c.get("dhatu_lemma", "") == "tap"
            and c.get("karman_lemma", "") == "tapas")


def sutra_3_1_89(c) -> bool:
    """na duhasnunamāṃ yakciṇau: yak and ciṇ do NOT apply to
    duh/snu/nam in karmavat construction."""
    return c.get("dhatu_lemma", "") not in {"duh", "snu", "nam"}


def sutra_3_1_90(c) -> bool:
    """kuṣirajoḥ prācāṃ śyan parasmaipadaṃ ca: for 'kuṣ'/'rañj' per
    eastern grammarians, śyan with parasmaipada."""
    return (c.get("dhatu_lemma", "") in {"kuṣ", "rañj"}
            and c.get("suffix", "") == "śyan"
            and c.get("pada") == Pada.PARASMAIPADA)


# ===========================================================================
# 3.1.92 – 3.1.150 : kṛt suffixes (kṛtya / ṇvul / tṛc / ka / ṣvun …)
# ===========================================================================

def sutra_3_1_92(c) -> bool:
    """tatropapadaṃ saptamīstham: the upapada in a kṛt construction stands
    in the locative (saptamī). Saṃjñā-like rule."""
    return c.get("upapada") is not None and c.get("scope") == "upapada"


def sutra_3_1_94(c) -> bool:
    """vā'sarūpo'striyām: an unlike-form suffix is optional, except in
    feminine. Paribhāṣā for non-conflicting kṛt suffixes."""
    return (c.get("is_unlike_suffix", False)
            and c.get("gender") != Gender.FEMININE)


def sutra_3_1_95(c) -> bool:
    """kṛtyāḥ prāṅ ṇvulaḥ: kṛtya suffixes (tavya/anīya/ya) are taught
    before ṇvul. Adhikāra for the kṛtya section."""
    return c.get("suffix", "") in {"tavya", "anīya", "ya", "ṇyat", "kyap", "kelima"}


def sutra_3_1_96(c) -> bool:
    """tavyat tavyānīyaraḥ: tavyat, tavya, anīyar — the three primary
    kṛtya suffixes."""
    return c.get("suffix", "") in {"tavyat", "tavya", "anīyar", "anīya"}


def sutra_3_1_97(c) -> bool:
    """aco yat: yat after vowel-ending roots."""
    return (c.get("suffix", "") == "yat"
            and c.get("dhatu_ends_in_vowel", False))


def sutra_3_1_98(c) -> bool:
    """pora dupadhāt: yat also after roots ending in -p with -a upadhā."""
    return (c.get("suffix", "") == "yat"
            and c.get("dhatu_ends_in", "") == "p"
            and c.get("upadha") == "a")


def sutra_3_1_99(c) -> bool:
    """śakisahoś ca: also for 'śak' and 'sah' — yat."""
    return (c.get("suffix", "") == "yat"
            and c.get("dhatu_lemma", "") in {"śak", "sah"})


def sutra_3_1_100(c) -> bool:
    """gadamadacarayamaś cānupasarge: yat for gad/mad/car/yam without
    upasarga."""
    return (c.get("suffix", "") == "yat"
            and c.get("dhatu_lemma", "") in {"gad", "mad", "car", "yam"}
            and c.get("upasarga") is None)


def sutra_3_1_101(c) -> bool:
    """avadyapaṇyavaryā garhyapaṇitavyānirodheṣu: specific lexical kṛtya
    derivatives — avadya / paṇya / varya in 'garhya / paṇitavya / nirodha'."""
    return c.get("derived_lemma", "") in {"avadya", "paṇya", "varya"}


def sutra_3_1_102(c) -> bool:
    """vahyaṃ karaṇam: 'vahya' (yat from 'vah') in karaṇa sense."""
    return (c.get("derived_lemma", "") == "vahya"
            and c.get("role") == Role.KARANA)


def sutra_3_1_103(c) -> bool:
    """aryaḥ svāmivaiśyayoḥ: 'arya' (yat from 'ṛ') in 'master/vaiśya'
    sense."""
    return (c.get("derived_lemma", "") == "arya"
            and c.get("semantic_context") in {"svami", "vaishya"})


def sutra_3_1_104(c) -> bool:
    """upasaryā kālyā prajane: 'upasaryā' / 'kālyā' in 'reproductive
    period' sense."""
    return (c.get("derived_lemma", "") in {"upasaryā", "kālyā"}
            and c.get("semantic_context") == "prajana")


def sutra_3_1_105(c) -> bool:
    """ajaryaṃ saṃgatam: 'ajarya' in 'firm union' sense."""
    return (c.get("derived_lemma", "") == "ajarya"
            and c.get("semantic_context") == "samgata")


def sutra_3_1_106(c) -> bool:
    """vadaḥ supi kyap ca: kyap after 'vad' with sup-attached upapada."""
    return (c.get("dhatu_lemma", "") == "vad"
            and c.get("suffix", "") == "kyap"
            and c.get("has_sup_upapada", False))


def sutra_3_1_107(c) -> bool:
    """bhuvo bhāve: kyap after 'bhū' in bhāva (impersonal) sense."""
    return (c.get("dhatu_lemma", "") == "bhū"
            and c.get("suffix", "") == "kyap"
            and c.get("is_bhave", False))


def sutra_3_1_108(c) -> bool:
    """hanas ta ca: 'han' takes kyap with substitute 'vadh'-like form."""
    return (c.get("dhatu_lemma", "") == "han"
            and c.get("suffix", "") == "kyap")


def sutra_3_1_109(c) -> bool:
    """etistuśasvṛdṛjuṣaḥ kyap: kyap after eti/stu/śas/vṛ/dṛ/juṣ."""
    return (c.get("dhatu_lemma", "") in ETI_STU_ETC
            and c.get("suffix", "") == "kyap")


def sutra_3_1_110(c) -> bool:
    """ṛdupadhāc cākḷpicṛteḥ: kyap also after roots with -ṛ-upadhā,
    except 'kḷp' and 'cṛt'."""
    return (c.get("upadha") == "ṛ"
            and c.get("suffix", "") == "kyap"
            and c.get("dhatu_lemma", "") not in {"kḷp", "cṛt"})


def sutra_3_1_111(c) -> bool:
    """ī ca khanaḥ: 'khan' takes kyap with 'ī' substitution
    ('kheya')."""
    return (c.get("dhatu_lemma", "") == "khan"
            and c.get("suffix", "") == "kyap")


def sutra_3_1_112(c) -> bool:
    """bhṛño'saṃjñāyām: 'bhṛ' takes kyap when not a proper-name (saṃjñā)
    context."""
    return (c.get("dhatu_lemma", "") == "bhṛ"
            and c.get("suffix", "") == "kyap"
            and not c.get("is_samjna", False))


def sutra_3_1_113(c) -> bool:
    """mṛjer vibhāṣā: optionally for 'mṛj' — kyap."""
    return (c.get("dhatu_lemma", "") == "mṛj"
            and c.get("suffix", "") == "kyap"
            and c.get("is_optional", True))


def sutra_3_1_114(c) -> bool:
    """rājasūyasūryamṛṣodyarucyakupyakṛṣṭapacyāvyathyāḥ: lexical kṛtya
    derivatives — rājasūya / sūrya / mṛṣodya / rucya / kupya / kṛṣṭapacya /
    avyathya."""
    return c.get("derived_lemma", "") in {
        "rājasūya", "sūrya", "mṛṣodya", "rucya", "kupya",
        "kṛṣṭapacya", "avyathya",
    }


def sutra_3_1_115(c) -> bool:
    """bhidyoddhyau nade: 'bhidya' / 'uddhya' — for a river-name."""
    return (c.get("derived_lemma", "") in {"bhidya", "uddhya"}
            and c.get("semantic_context") == "nadi")


def sutra_3_1_116(c) -> bool:
    """puṣyasiddhyau nakṣatre: 'puṣya' / 'siddhya' — for a nakṣatra
    (asterism)."""
    return (c.get("derived_lemma", "") in {"puṣya", "siddhya"}
            and c.get("semantic_context") == "nakshatra")


def sutra_3_1_117(c) -> bool:
    """vipūyavinīyajityā muñjakalkahaliṣu: vipūya / vinīya / jityā for
    muñja / kalka / hali."""
    return c.get("derived_lemma", "") in {"vipūya", "vinīya", "jityā"}


def sutra_3_1_118(c) -> bool:
    """pratyapibhyāṃ graheś chandasi: 'grah' with prati/api in Vedic —
    yat."""
    return (c.get("dhatu_lemma", "") == "grah"
            and c.get("upasarga", "") in {"prati", "api"}
            and c.get("is_chandas", False))


def sutra_3_1_119(c) -> bool:
    """padāsvairibāhyāpakṣyeṣu ca: also for pada / asvairi / bāhya /
    apakṣya — yat."""
    return c.get("derived_lemma", "") in {"pada", "asvairi", "bāhya", "apakṣya"}


def sutra_3_1_120(c) -> bool:
    """vibhāṣā kṛvṛṣoḥ: optionally yat for 'kṛ' and 'vṛṣ'."""
    return (c.get("dhatu_lemma", "") in {"kṛ", "vṛṣ"}
            and c.get("suffix", "") == "yat"
            and c.get("is_optional", True))


def sutra_3_1_121(c) -> bool:
    """yugyaṃ ca pattre: 'yugya' (yat from 'yuj') in 'wheel/vehicle'
    sense."""
    return (c.get("derived_lemma", "") == "yugya"
            and c.get("semantic_context") == "pattra")


def sutra_3_1_122(c) -> bool:
    """amāvasyadanyatarasyām: 'amāvasya' optionally."""
    return (c.get("derived_lemma", "") == "amāvasya"
            and c.get("is_optional", True))


def sutra_3_1_123(c) -> bool:
    """chandasi niṣṭarkya...: list of Vedic lexical kṛtyas (niṣṭarkya /
    devahūya / praṇīya / unnīya / ucchiṣya)."""
    return (c.get("is_chandas", False)
            and c.get("derived_lemma", "") in {
                "niṣṭarkya", "devahūya", "praṇīya", "unnīya", "ucchiṣya",
            })


def sutra_3_1_124(c) -> bool:
    """ṛhalor ṇyat: ṇyat after roots ending in ṛ or hal."""
    return (c.get("suffix", "") == "ṇyat"
            and (c.get("dhatu_ends_in", "") == "ṛ"
                 or c.get("dhatu_ends_in_consonant", False)))


def sutra_3_1_125(c) -> bool:
    """or āvaśyake: ṇyat in 'necessary' (āvaśyaka) sense."""
    return (c.get("suffix", "") == "ṇyat"
            and c.get("semantic_context") == "avashyaka")


def sutra_3_1_126(c) -> bool:
    """āsuyuvapirapilapitrapicamaś ca: ṇyat also for ās / yu / vap / rap /
    lap / trap / cam."""
    return (c.get("suffix", "") == "ṇyat"
            and c.get("dhatu_lemma", "") in {
                "ās", "yu", "vap", "rap", "lap", "trap", "cam",
            })


def sutra_3_1_127(c) -> bool:
    """ānāyyo'nitye: 'ānāyya' (from 'ā-nī') in non-permanent context."""
    return (c.get("derived_lemma", "") == "ānāyya"
            and not c.get("is_nitya", False))


def sutra_3_1_128(c) -> bool:
    """praṇāyyo'sammatau: 'praṇāyya' in 'disapproval' (asammati) sense."""
    return (c.get("derived_lemma", "") == "praṇāyya"
            and c.get("semantic_context") == "asammati")


def sutra_3_1_129(c) -> bool:
    """pāyyasānnāyyanikāyyadhāyyā mānahavirnivāsasāmidhenīṣu: lexical
    ṇyat-derivatives — pāyya / sānnāyya / nikāyya / dhāyyā."""
    return c.get("derived_lemma", "") in {
        "pāyya", "sānnāyya", "nikāyya", "dhāyyā",
    }


def sutra_3_1_130(c) -> bool:
    """kratau kuṇḍapāyyasaṃcāyyau: 'kuṇḍapāyya' / 'saṃcāyya' in a sacrifice
    (kratu) context."""
    return (c.get("derived_lemma", "") in {"kuṇḍapāyya", "saṃcāyya"}
            and c.get("semantic_context") == "kratu")


def sutra_3_1_131(c) -> bool:
    """agnau paricāyyopacāyyasamūhyāḥ: 'paricāyya' / 'upacāyya' /
    'samūhya' in fire (agni) context."""
    return (c.get("derived_lemma", "") in {"paricāyya", "upacāyya", "samūhya"}
            and c.get("semantic_context") == "agni")


def sutra_3_1_132(c) -> bool:
    """cityāgnicitye ca: 'citya' in 'piling of the fire-altar' (agnicitya)
    sense."""
    return (c.get("derived_lemma", "") == "citya"
            and c.get("semantic_context") == "agni_citya")


# ===========================================================================
# 3.1.133 – 3.1.150 : ṇvul / tṛc / ac / kṛt agent-noun suffixes
# ===========================================================================

def sutra_3_1_133(c) -> bool:
    """ṇvultṛcau: ṇvul and tṛc are the primary kṛt agent-noun suffixes
    (yielding agent-nouns like 'kāraka', 'kartṛ')."""
    return c.get("suffix", "") in {"ṇvul", "tṛc"}


def sutra_3_1_134(c) -> bool:
    """nandigrahipacādibhyo lyuṇinyacaḥ: lyu / ṇini / ac after
    nandi-/grahi-/paci-class roots."""
    return (c.get("dhatu_lemma", "") in NANDI_GRAHI_PACI
            and c.get("suffix", "") in {"lyu", "ṇini", "ac"})


def sutra_3_1_135(c) -> bool:
    """igupadhajñāprīkiraḥ kaḥ: ka after ik-upadha / jñā / prī / kiraḥ
    roots."""
    return (c.get("suffix", "") == "ka"
            and (c.get("dhatu_lemma", "") in IGUPADHA_JNA_PRI_KRR
                 or c.get("is_igupadha", False)))


def sutra_3_1_136(c) -> bool:
    """ātaś copasarge: also ka after ā-final roots when upasarga present."""
    return (c.get("suffix", "") == "ka"
            and c.get("dhatu_ends_in", "") == "ā"
            and c.get("upasarga") is not None)


def sutra_3_1_137(c) -> bool:
    """pāghrādhmādheṭdṛśaḥ śaḥ: śa after pā/ghrā/dhmā/dheṭ/dṛś."""
    return (c.get("suffix", "") == "śa"
            and c.get("dhatu_lemma", "") in {
                "pā", "ghrā", "dhmā", "dhe", "dṛś",
            })


def sutra_3_1_138(c) -> bool:
    """anupasargāl limpa-vinda-dhāri-pārivedi-udeji-cetisāti-sāhibhyaś ca:
    śa also for a list of compound stems without upasarga."""
    return (c.get("suffix", "") == "śa"
            and c.get("dhatu_lemma", "") in {
                "limp", "vind", "dhārī", "pārivedī", "udeji", "cetisāti",
                "sāhī",
            }
            and c.get("upasarga") is None)


def sutra_3_1_139(c) -> bool:
    """dadātidadhātyor vibhāṣā: optionally for 'dā' (dadāti) and 'dhā'
    (dadhāti) — śa."""
    return (c.get("dhatu_lemma", "") in {"dā", "dhā"}
            and c.get("suffix", "") == "śa"
            and c.get("is_optional", True))


def sutra_3_1_140(c) -> bool:
    """jvalitikasantebhyo ṇaḥ: ṇa after jval / kas / -kīṭ-ending stems."""
    return (c.get("suffix", "") == "ṇa"
            and c.get("dhatu_lemma", "") in JVALITI_KASANTA)


def sutra_3_1_141(c) -> bool:
    """śyādvyadhāsrusaṃsrvatīṇavasāऽvahṛlihaśliṣaśvasaś ca: ṇa also for
    śyā/dyu/vyadh/āsru/saṃsṛ/avahṛ/lih/śliṣ/śvas."""
    return (c.get("suffix", "") == "ṇa"
            and c.get("dhatu_lemma", "") in SHYA_ETC)


def sutra_3_1_142(c) -> bool:
    """dunyor anupasarge: 'du' / 'nu' without upasarga — ṇa."""
    return (c.get("dhatu_lemma", "") in {"du", "nu"}
            and c.get("upasarga") is None
            and c.get("suffix", "") == "ṇa")


def sutra_3_1_143(c) -> bool:
    """vibhāṣā graheḥ: optionally for 'grah' — ṇa (or ka)."""
    return (c.get("dhatu_lemma", "") == "grah"
            and c.get("suffix", "") in {"ṇa", "ka"}
            and c.get("is_optional", True))


def sutra_3_1_144(c) -> bool:
    """gehe kaḥ: 'ka' suffix in 'house/dwelling' (geha) sense."""
    return (c.get("suffix", "") == "ka"
            and c.get("semantic_context") == "geha")


def sutra_3_1_145(c) -> bool:
    """śilpini ṣvun: ṣvun after a root in 'craftsman/artisan' (śilpin)
    sense."""
    return (c.get("suffix", "") == "ṣvun"
            and c.get("semantic_context") == "shilpa")


def sutra_3_1_146(c) -> bool:
    """gasthakan: 'gasthakan' suffix [a specific kṛt derivative]."""
    return c.get("suffix", "") == "gasthakan"


def sutra_3_1_147(c) -> bool:
    """ṇyuṭ ca: also ṇyuṭ [in craftsman sense]."""
    return c.get("suffix", "") == "ṇyuṭ"


def sutra_3_1_148(c) -> bool:
    """haś ca vrīhikālayoḥ: 'ha' suffix in 'rice' or 'time' (vrīhi /
    kāla) sense."""
    return (c.get("suffix", "") == "ha"
            and c.get("semantic_context") in {"vrihi", "kala"})


def sutra_3_1_149(c) -> bool:
    """prusṛlvaḥ samabhihāre vun: vun after pra-sṛ/lū in 'continual
    repetition' (samabhihāra) sense."""
    return (c.get("suffix", "") == "vun"
            and c.get("dhatu_lemma", "") in {"sṛ", "lū", "pra-sṛ"}
            and c.get("semantic_context") == "samabhihara")


def sutra_3_1_150(c) -> bool:
    """āśiṣi ca: also in āśiṣ (benedictive) sense — vun."""
    return (c.get("suffix", "") == "vun"
            and c.get("semantic_context") == "ashish")


# ===========================================================================
# Fixtures — real linguistic positive / negative examples per sutra.
# ===========================================================================

FIXTURES: dict[str, tuple[dict, dict]] = {
    # 3.1.1 – 3.1.4 : adhikāra / accent
    "3.1.1":  ({"scope": "pratyaya", "suffix": "san"},
               {"scope": "other", "suffix": None}),
    "3.1.2":  ({"scope": "para", "suffix_is_para": True},
               {"scope": "other", "suffix_is_para": False}),
    "3.1.3":  ({"scope": "adyudatta", "is_adyudatta": True},
               {"scope": "other", "is_adyudatta": False}),
    "3.1.4":  ({"is_sup": True, "suffix": "su"},
               {"is_sup": False, "is_pit": False, "suffix": "ṇic"}),

    # 3.1.6 – 3.1.31 : san / kyaṅ / kyaṣ / kyac / ṇic / yak / āya / iyaṅ
    "3.1.6":  ({"dhatu_lemma": "mān", "suffix": "san"},
               {"dhatu_lemma": "bhū", "suffix": "san"}),
    "3.1.7":  ({"suffix": "san", "is_iccha": True, "samana_kartrka": True},
               {"suffix": "san", "is_iccha": True, "samana_kartrka": False}),
    "3.1.9":  ({"suffix": "kāmyac"},
               {"suffix": "ṇic"}),
    "3.1.10": ({"suffix": "kyaṅ", "is_upamana": True, "semantic_context": "acara"},
               {"suffix": "kyaṅ", "is_upamana": False, "semantic_context": "other"}),
    "3.1.11": ({"suffix": "kyaṅ", "is_kartari": True},
               {"suffix": "kyaṅ", "is_kartari": False}),
    "3.1.12": ({"dhatu_lemma": "bhṛśa", "semantic_context": "bhavana"},
               {"dhatu_lemma": "rāma", "semantic_context": "other"}),
    "3.1.13": ({"suffix": "kyaṣ", "dhatu_lemma": "lohita"},
               {"suffix": "kyaṣ", "dhatu_lemma": "rāma"}),
    "3.1.14": ({"dhatu_lemma": "kaṣṭa", "semantic_context": "kramana"},
               {"dhatu_lemma": "kaṣṭa", "semantic_context": "other"}),
    "3.1.15": ({"dhatu_lemma": "romantha", "role": Role.KARMAN},
               {"dhatu_lemma": "romantha", "role": Role.KARTR}),
    "3.1.16": ({"dhatu_lemma": "bāṣpa", "semantic_context": "udvamana"},
               {"dhatu_lemma": "bāṣpa", "semantic_context": "other"}),
    "3.1.17": ({"dhatu_lemma": "śabda", "role": Role.KARANA},
               {"dhatu_lemma": "śabda", "role": Role.KARMAN}),
    "3.1.18": ({"dhatu_lemma": "sukha", "semantic_context": "kartri_vedana"},
               {"dhatu_lemma": "sukha", "semantic_context": "other"}),
    "3.1.19": ({"suffix": "kyac", "dhatu_lemma": "namas"},
               {"suffix": "kyac", "dhatu_lemma": "rāma"}),
    "3.1.20": ({"suffix": "ṇiṅ", "dhatu_lemma": "puccha"},
               {"suffix": "ṇiṅ", "dhatu_lemma": "rāma"}),
    "3.1.21": ({"suffix": "ṇic", "dhatu_lemma": "muṇḍa"},
               {"suffix": "ṇic", "dhatu_lemma": "rāma"}),
    "3.1.23": ({"suffix": "yaṅ", "semantic_context": "kautilya_gati"},
               {"suffix": "yaṅ", "semantic_context": "other"}),
    "3.1.24": ({"suffix": "yaṅ", "dhatu_lemma": "lup",
                "semantic_context": "bhava_garha"},
               {"suffix": "yaṅ", "dhatu_lemma": "rāma",
                "semantic_context": "other"}),
    "3.1.26": ({"suffix": "ṇic", "is_causative": True},
               {"suffix": "ṇic", "is_causative": False}),
    "3.1.27": ({"suffix": "yak", "dhatu_lemma": "kaṇḍū"},
               {"suffix": "yak", "dhatu_lemma": "rāma"}),
    "3.1.28": ({"suffix": "āya", "dhatu_lemma": "gup"},
               {"suffix": "āya", "dhatu_lemma": "rāma"}),
    "3.1.29": ({"suffix": "īyaṅ", "dhatu_lemma": "ṛti"},
               {"suffix": "īyaṅ", "dhatu_lemma": "rāma"}),
    "3.1.30": ({"suffix": "ṇiṅ", "dhatu_lemma": "kam"},
               {"suffix": "ṇiṅ", "dhatu_lemma": "rāma"}),
    "3.1.31": ({"suffix": "āya", "is_ardhadhatuka": True},
               {"suffix": "āya", "is_ardhadhatuka": False}),

    # 3.1.32 : sanādyantā dhātavaḥ
    "3.1.32": ({"suffix": "san"},
               {"suffix": "kta"}),

    # 3.1.33 – 3.1.42 : lakāra helpers
    "3.1.33": ({"lakara": Lakara.LRT},
               {"lakara": Lakara.LAT}),
    "3.1.34": ({"lakara": Lakara.LET, "is_chandas": True},
               {"lakara": Lakara.LET, "is_chandas": False}),
    "3.1.35": ({"dhatu_lemma": "kās", "lakara": Lakara.LIT, "is_mantra": False},
               {"dhatu_lemma": "kās", "lakara": Lakara.LIT, "is_mantra": True}),
    "3.1.36": ({"dhatu_lemma": "īkṣ", "lakara": Lakara.LIT},
               {"dhatu_lemma": "ṛc", "lakara": Lakara.LIT}),
    "3.1.37": ({"dhatu_lemma": "day", "lakara": Lakara.LIT},
               {"dhatu_lemma": "rāma", "lakara": Lakara.LIT}),
    "3.1.38": ({"dhatu_lemma": "uṣ", "lakara": Lakara.LIT, "is_optional": True},
               {"dhatu_lemma": "rāma", "lakara": Lakara.LIT, "is_optional": True}),
    "3.1.39": ({"dhatu_lemma": "bhī", "lakara": Lakara.LIT},
               {"dhatu_lemma": "rāma", "lakara": Lakara.LIT}),
    "3.1.40": ({"lakara": Lakara.LIT, "is_am_paribhasha": True},
               {"lakara": Lakara.LAT, "is_am_paribhasha": False}),
    "3.1.41": ({"dhatu_lemma": "vid", "lakara": Lakara.LIT,
                "is_optional": True},
               {"dhatu_lemma": "rāma", "lakara": Lakara.LIT,
                "is_optional": True}),
    "3.1.42": ({"lakara": Lakara.LIT, "is_compound_am": True},
               {"lakara": Lakara.LAT, "is_compound_am": False}),

    # 3.1.43 – 3.1.66 : cli substitutions in luṅ
    "3.1.43": ({"lakara": Lakara.LUN},
               {"lakara": Lakara.LAT}),
    "3.1.44": ({"lakara": Lakara.LUN, "suffix": "sic"},
               {"lakara": Lakara.LUN, "suffix": "caṅ"}),
    "3.1.45": ({"lakara": Lakara.LUN, "suffix": "ksa",
                "dhatu_lemma": "diś"},
               {"lakara": Lakara.LUN, "suffix": "ksa",
                "dhatu_lemma": "rāma"}),
    "3.1.46": ({"dhatu_lemma": "śliṣ", "semantic_context": "alingana",
                "suffix": "ksa"},
               {"dhatu_lemma": "śliṣ", "semantic_context": "other",
                "suffix": "ksa"}),
    "3.1.47": ({"dhatu_lemma": "bhū"},
               {"dhatu_lemma": "dṛś"}),
    "3.1.48": ({"suffix": "caṅ", "dhatu_lemma": "śri", "is_kartari": True},
               {"suffix": "caṅ", "dhatu_lemma": "rāma", "is_kartari": False}),
    "3.1.49": ({"dhatu_lemma": "dhe", "suffix": "caṅ", "is_optional": True},
               {"dhatu_lemma": "rāma", "suffix": "caṅ", "is_optional": True}),
    "3.1.50": ({"dhatu_lemma": "gup", "is_chandas": True, "suffix": "caṅ"},
               {"dhatu_lemma": "gup", "is_chandas": False, "suffix": "caṅ"}),
    "3.1.51": ({"dhatu_lemma": "nonay", "suffix": "caṅ"},
               {"dhatu_lemma": "rāma", "suffix": "caṅ"}),
    "3.1.52": ({"dhatu_lemma": "as", "suffix": "aṅ", "lakara": Lakara.LUN},
               {"dhatu_lemma": "rāma", "suffix": "aṅ", "lakara": Lakara.LUN}),
    "3.1.53": ({"dhatu_lemma": "lip", "suffix": "aṅ"},
               {"dhatu_lemma": "rāma", "suffix": "aṅ"}),
    "3.1.54": ({"pada": Pada.ATMANEPADA, "is_optional": True},
               {"pada": Pada.PARASMAIPADA, "is_optional": True}),
    "3.1.55": ({"dhatu_lemma": "puṣ", "pada": Pada.PARASMAIPADA,
                "suffix": "aṅ"},
               {"dhatu_lemma": "puṣ", "pada": Pada.ATMANEPADA,
                "suffix": "aṅ"}),
    "3.1.56": ({"dhatu_lemma": "sṛ", "suffix": "aṅ"},
               {"dhatu_lemma": "rāma", "suffix": "aṅ"}),
    "3.1.57": ({"is_irit": True, "is_optional": True},
               {"is_irit": False, "is_optional": True}),
    "3.1.58": ({"dhatu_lemma": "jṛ", "suffix": "aṅ"},
               {"dhatu_lemma": "rāma", "suffix": "aṅ"}),
    "3.1.59": ({"dhatu_lemma": "kṛ", "is_chandas": True, "suffix": "aṅ"},
               {"dhatu_lemma": "kṛ", "is_chandas": False, "suffix": "aṅ"}),
    "3.1.60": ({"dhatu_lemma": "pad", "suffix": "ciṇ", "ending": "ta"},
               {"dhatu_lemma": "pad", "suffix": "ciṇ", "ending": "ti"}),
    "3.1.61": ({"dhatu_lemma": "dīp", "suffix": "ciṇ", "is_optional": True},
               {"dhatu_lemma": "rāma", "suffix": "ciṇ", "is_optional": True}),
    "3.1.62": ({"is_karmakartri": True, "dhatu_ends_in_vowel": True,
                "suffix": "ciṇ"},
               {"is_karmakartri": False, "dhatu_ends_in_vowel": False,
                "suffix": "ciṇ"}),
    "3.1.63": ({"dhatu_lemma": "duh", "suffix": "ciṇ"},
               {"dhatu_lemma": "rāma", "suffix": "ciṇ"}),
    "3.1.64": ({"dhatu_lemma": "bhū"},
               {"dhatu_lemma": "rudh"}),
    "3.1.65": ({"dhatu_lemma": "tap", "semantic_context": "anutapa",
                "suffix": "ciṇ"},
               {"dhatu_lemma": "tap", "semantic_context": "other",
                "suffix": "ciṇ"}),
    "3.1.66": ({"suffix": "ciṇ", "is_bhave": True},
               {"suffix": "ciṇ", "is_bhave": False, "is_karmani": False}),

    # 3.1.67 – 3.1.90 : yak / śnu / śna / śyan
    "3.1.67": ({"suffix": "yak", "is_sarvadhatuka": True},
               {"suffix": "yak", "is_sarvadhatuka": False}),
    "3.1.70": ({"dhatu_lemma": "bhrāś", "suffix": "śyan",
                "is_optional": True},
               {"dhatu_lemma": "rāma", "suffix": "śyan",
                "is_optional": True}),
    "3.1.71": ({"dhatu_lemma": "yas", "upasarga": None},
               {"dhatu_lemma": "yas", "upasarga": "pra"}),
    "3.1.72": ({"dhatu_lemma": "yas", "upasarga": "sam"},
               {"dhatu_lemma": "yas", "upasarga": "pra"}),
    "3.1.74": ({"dhatu_lemma": "śru", "suffix": "śnu"},
               {"dhatu_lemma": "rāma", "suffix": "śnu"}),
    "3.1.75": ({"dhatu_lemma": "akṣ", "suffix": "śnu", "is_optional": True},
               {"dhatu_lemma": "rāma", "suffix": "śnu", "is_optional": True}),
    "3.1.76": ({"dhatu_lemma": "takṣ", "semantic_context": "tanu_karana",
                "suffix": "śnu"},
               {"dhatu_lemma": "takṣ", "semantic_context": "other",
                "suffix": "śnu"}),
    "3.1.80": ({"dhatu_lemma": "dhinv", "suffix": "śnu"},
               {"dhatu_lemma": "rāma", "suffix": "śnu"}),
    "3.1.82": ({"dhatu_lemma": "stambh", "suffix": "śnu"},
               {"dhatu_lemma": "rāma", "suffix": "śnu"}),
    "3.1.83": ({"varga": 9, "suffix": "śna", "is_halaadi_ending": True},
               {"varga": 1, "suffix": "śna", "is_halaadi_ending": False}),
    "3.1.84": ({"is_chandas": True, "suffix": "śāyaj"},
               {"is_chandas": False, "suffix": "kta"}),
    "3.1.85": ({"is_chandas": True, "is_vyatyaya": True},
               {"is_chandas": False, "is_vyatyaya": False}),
    "3.1.86": ({"lakara": Lakara.ASHIRLING, "suffix": "aṅ"},
               {"lakara": Lakara.LAT, "suffix": "aṅ"}),
    "3.1.87": ({"is_karmakartri": True},
               {"is_karmakartri": False, "role": Role.KARTR}),
    "3.1.88": ({"dhatu_lemma": "tap", "karman_lemma": "tapas"},
               {"dhatu_lemma": "tap", "karman_lemma": "phala"}),
    "3.1.89": ({"dhatu_lemma": "bhū"},
               {"dhatu_lemma": "duh"}),
    "3.1.90": ({"dhatu_lemma": "kuṣ", "suffix": "śyan",
                "pada": Pada.PARASMAIPADA},
               {"dhatu_lemma": "kuṣ", "suffix": "śyan",
                "pada": Pada.ATMANEPADA}),

    # 3.1.92 – 3.1.132 : kṛtya suffixes
    "3.1.92":  ({"upapada": "stamba", "scope": "upapada"},
                {"upapada": None, "scope": "other"}),
    "3.1.94":  ({"is_unlike_suffix": True, "gender": Gender.MASCULINE},
                {"is_unlike_suffix": True, "gender": Gender.FEMININE}),
    "3.1.95":  ({"suffix": "tavya"},
                {"suffix": "ṇvul"}),
    "3.1.96":  ({"suffix": "tavyat"},
                {"suffix": "ṇvul"}),
    "3.1.97":  ({"suffix": "yat", "dhatu_ends_in_vowel": True},
                {"suffix": "yat", "dhatu_ends_in_vowel": False}),
    "3.1.98":  ({"suffix": "yat", "dhatu_ends_in": "p", "upadha": "a"},
                {"suffix": "yat", "dhatu_ends_in": "k", "upadha": "i"}),
    "3.1.99":  ({"suffix": "yat", "dhatu_lemma": "śak"},
                {"suffix": "yat", "dhatu_lemma": "rāma"}),
    "3.1.100": ({"suffix": "yat", "dhatu_lemma": "gad", "upasarga": None},
                {"suffix": "yat", "dhatu_lemma": "gad", "upasarga": "pra"}),
    "3.1.101": ({"derived_lemma": "avadya"},
                {"derived_lemma": "rāma"}),
    "3.1.102": ({"derived_lemma": "vahya", "role": Role.KARANA},
                {"derived_lemma": "vahya", "role": Role.KARMAN}),
    "3.1.103": ({"derived_lemma": "arya", "semantic_context": "svami"},
                {"derived_lemma": "arya", "semantic_context": "other"}),
    "3.1.104": ({"derived_lemma": "upasaryā", "semantic_context": "prajana"},
                {"derived_lemma": "upasaryā", "semantic_context": "other"}),
    "3.1.105": ({"derived_lemma": "ajarya", "semantic_context": "samgata"},
                {"derived_lemma": "ajarya", "semantic_context": "other"}),
    "3.1.106": ({"dhatu_lemma": "vad", "suffix": "kyap",
                 "has_sup_upapada": True},
                {"dhatu_lemma": "vad", "suffix": "kyap",
                 "has_sup_upapada": False}),
    "3.1.107": ({"dhatu_lemma": "bhū", "suffix": "kyap", "is_bhave": True},
                {"dhatu_lemma": "bhū", "suffix": "kyap", "is_bhave": False}),
    "3.1.108": ({"dhatu_lemma": "han", "suffix": "kyap"},
                {"dhatu_lemma": "rāma", "suffix": "kyap"}),
    "3.1.109": ({"dhatu_lemma": "stu", "suffix": "kyap"},
                {"dhatu_lemma": "rāma", "suffix": "kyap"}),
    "3.1.110": ({"upadha": "ṛ", "suffix": "kyap", "dhatu_lemma": "kṛ"},
                {"upadha": "ṛ", "suffix": "kyap", "dhatu_lemma": "kḷp"}),
    "3.1.111": ({"dhatu_lemma": "khan", "suffix": "kyap"},
                {"dhatu_lemma": "rāma", "suffix": "kyap"}),
    "3.1.112": ({"dhatu_lemma": "bhṛ", "suffix": "kyap", "is_samjna": False},
                {"dhatu_lemma": "bhṛ", "suffix": "kyap", "is_samjna": True}),
    "3.1.113": ({"dhatu_lemma": "mṛj", "suffix": "kyap", "is_optional": True},
                {"dhatu_lemma": "rāma", "suffix": "kyap", "is_optional": True}),
    "3.1.114": ({"derived_lemma": "rājasūya"},
                {"derived_lemma": "rāma"}),
    "3.1.115": ({"derived_lemma": "bhidya", "semantic_context": "nadi"},
                {"derived_lemma": "bhidya", "semantic_context": "other"}),
    "3.1.116": ({"derived_lemma": "puṣya", "semantic_context": "nakshatra"},
                {"derived_lemma": "puṣya", "semantic_context": "other"}),
    "3.1.117": ({"derived_lemma": "vipūya"},
                {"derived_lemma": "rāma"}),
    "3.1.118": ({"dhatu_lemma": "grah", "upasarga": "prati",
                 "is_chandas": True},
                {"dhatu_lemma": "grah", "upasarga": "prati",
                 "is_chandas": False}),
    "3.1.119": ({"derived_lemma": "pada"},
                {"derived_lemma": "rāma"}),
    "3.1.120": ({"dhatu_lemma": "kṛ", "suffix": "yat", "is_optional": True},
                {"dhatu_lemma": "rāma", "suffix": "yat", "is_optional": True}),
    "3.1.121": ({"derived_lemma": "yugya", "semantic_context": "pattra"},
                {"derived_lemma": "yugya", "semantic_context": "other"}),
    "3.1.122": ({"derived_lemma": "amāvasya", "is_optional": True},
                {"derived_lemma": "rāma", "is_optional": True}),
    "3.1.123": ({"is_chandas": True, "derived_lemma": "niṣṭarkya"},
                {"is_chandas": True, "derived_lemma": "rāma"}),
    "3.1.124": ({"suffix": "ṇyat", "dhatu_ends_in": "ṛ"},
                {"suffix": "ṇyat", "dhatu_ends_in": "a",
                 "dhatu_ends_in_consonant": False}),
    "3.1.125": ({"suffix": "ṇyat", "semantic_context": "avashyaka"},
                {"suffix": "ṇyat", "semantic_context": "other"}),
    "3.1.126": ({"suffix": "ṇyat", "dhatu_lemma": "ās"},
                {"suffix": "ṇyat", "dhatu_lemma": "rāma"}),
    "3.1.127": ({"derived_lemma": "ānāyya", "is_nitya": False},
                {"derived_lemma": "ānāyya", "is_nitya": True}),
    "3.1.128": ({"derived_lemma": "praṇāyya", "semantic_context": "asammati"},
                {"derived_lemma": "praṇāyya", "semantic_context": "other"}),
    "3.1.129": ({"derived_lemma": "pāyya"},
                {"derived_lemma": "rāma"}),
    "3.1.130": ({"derived_lemma": "kuṇḍapāyya", "semantic_context": "kratu"},
                {"derived_lemma": "kuṇḍapāyya", "semantic_context": "other"}),
    "3.1.131": ({"derived_lemma": "paricāyya", "semantic_context": "agni"},
                {"derived_lemma": "paricāyya", "semantic_context": "other"}),
    "3.1.132": ({"derived_lemma": "citya", "semantic_context": "agni_citya"},
                {"derived_lemma": "citya", "semantic_context": "other"}),

    # 3.1.133 – 3.1.150 : ṇvul / tṛc and agent-noun suffixes
    "3.1.133": ({"suffix": "ṇvul"},
                {"suffix": "kta"}),
    "3.1.134": ({"dhatu_lemma": "nand", "suffix": "lyu"},
                {"dhatu_lemma": "rāma", "suffix": "lyu"}),
    "3.1.135": ({"suffix": "ka", "dhatu_lemma": "jñā"},
                {"suffix": "ka", "dhatu_lemma": "rāma", "is_igupadha": False}),
    "3.1.136": ({"suffix": "ka", "dhatu_ends_in": "ā", "upasarga": "pra"},
                {"suffix": "ka", "dhatu_ends_in": "ā", "upasarga": None}),
    "3.1.137": ({"suffix": "śa", "dhatu_lemma": "pā"},
                {"suffix": "śa", "dhatu_lemma": "rāma"}),
    "3.1.138": ({"suffix": "śa", "dhatu_lemma": "limp", "upasarga": None},
                {"suffix": "śa", "dhatu_lemma": "limp", "upasarga": "pra"}),
    "3.1.139": ({"dhatu_lemma": "dā", "suffix": "śa", "is_optional": True},
                {"dhatu_lemma": "rāma", "suffix": "śa", "is_optional": True}),
    "3.1.140": ({"suffix": "ṇa", "dhatu_lemma": "jval"},
                {"suffix": "ṇa", "dhatu_lemma": "rāma"}),
    "3.1.141": ({"suffix": "ṇa", "dhatu_lemma": "śyā"},
                {"suffix": "ṇa", "dhatu_lemma": "rāma"}),
    "3.1.142": ({"dhatu_lemma": "du", "upasarga": None, "suffix": "ṇa"},
                {"dhatu_lemma": "du", "upasarga": "pra", "suffix": "ṇa"}),
    "3.1.143": ({"dhatu_lemma": "grah", "suffix": "ṇa", "is_optional": True},
                {"dhatu_lemma": "rāma", "suffix": "ṇa", "is_optional": True}),
    "3.1.144": ({"suffix": "ka", "semantic_context": "geha"},
                {"suffix": "ka", "semantic_context": "other"}),
    "3.1.145": ({"suffix": "ṣvun", "semantic_context": "shilpa"},
                {"suffix": "ṣvun", "semantic_context": "other"}),
    "3.1.146": ({"suffix": "gasthakan"},
                {"suffix": "kta"}),
    "3.1.147": ({"suffix": "ṇyuṭ"},
                {"suffix": "kta"}),
    "3.1.148": ({"suffix": "ha", "semantic_context": "vrihi"},
                {"suffix": "ha", "semantic_context": "other"}),
    "3.1.149": ({"suffix": "vun", "dhatu_lemma": "sṛ",
                 "semantic_context": "samabhihara"},
                {"suffix": "vun", "dhatu_lemma": "rāma",
                 "semantic_context": "other"}),
    "3.1.150": ({"suffix": "vun", "semantic_context": "ashish"},
                {"suffix": "vun", "semantic_context": "other"}),
}


(
    IMPLEMENTED_IDS,
    has_real_implementation,
    handler_for,
    positive_features,
    negative_features,
) = make_module_api(FIXTURES, globals())
