"""
Discrete Pāṇini-correct implementations for Adhyāya 3.2 sutra predicates.

3.2 introduces an extensive system of kṛt suffixes (ka, ṭa, ṇvi, kvip, khac,
khaś, in, ḍa, ṇini, ñyuṭ, kvanip, ksnu, ghinun, ālu, ru, kmara, ghura, …)
in specific upapada or semantic contexts. The predicates here exhaustively
check the upapada lemma, dhātu lemma, role, and / or semantic context per
sutra. They replace the slug-roundtrip scaffold previously generated by
sutra_handlers_adhyaya23._evaluate.

Context keys:
  dhatu_lemma     str        – verbal root in the kṛt construction
  suffix          str        – kṛt suffix being introduced
  upapada         str|None   – upapada word that licenses the suffix
  semantic_context str|None  – fine-grained meaning (tācchīlya, vrata, …)
  role            Role|None  – kāraka role of the upapada / agent
  is_chandas      bool
  is_optional     bool
"""
from __future__ import annotations

from .grammar import Case, Lakara, Role
from .sutra_impl_base import _eq, _in, make_module_api


def sutra_3_2_2(c) -> bool:
    """hvāvāmaś ca: 'hve'/'vā'/'am' as upapada with 'kṛ' — ka suffix."""
    return _in(c, "upapada", {"hve", "vā", "am"}) and _eq(c, "dhatu_lemma", "kṛ")


def sutra_3_2_4(c) -> bool:
    """supi sthaḥ: 'sthā' takes ka with a sup-ending upapada."""
    return _eq(c, "dhatu_lemma", "sthā") and c.get("has_sup_upapada", False)


def sutra_3_2_5(c) -> bool:
    """tundaśokayoḥ parimṛjāpanudoḥ: 'parimṛj' / 'apa-nud' with 'tunda' /
    'śoka' as upapada."""
    return (_in(c, "dhatu_lemma", {"parimṛj", "apa-nud"})
            and _in(c, "upapada", {"tunda", "śoka"}))


def sutra_3_2_6(c) -> bool:
    """pre dājñaḥ: 'dā'/'jñā' with 'pra' upasarga — ka."""
    return (_in(c, "dhatu_lemma", {"dā", "jñā"})
            and _eq(c, "upasarga", "pra"))


def sutra_3_2_7(c) -> bool:
    """sami khyaḥ: 'khyā' with 'sam' upasarga — ka."""
    return _eq(c, "dhatu_lemma", "khyā") and _eq(c, "upasarga", "sam")


def sutra_3_2_8(c) -> bool:
    """gāpoṣṭak: 'gā' / 'pā' (drink) take ṭak."""
    return _in(c, "dhatu_lemma", {"gā", "pā"}) and _eq(c, "suffix", "ṭak")


def sutra_3_2_9(c) -> bool:
    """harater anudyamane'c: 'hṛ' (take) in non-effort sense — ac."""
    return (_eq(c, "dhatu_lemma", "hṛ")
            and _eq(c, "semantic_context", "anudyamana")
            and _eq(c, "suffix", "ac"))


def sutra_3_2_10(c) -> bool:
    """vayasi ca: also in 'age' (vayas) sense — ac."""
    return _eq(c, "semantic_context", "vayas") and _eq(c, "suffix", "ac")


def sutra_3_2_11(c) -> bool:
    """āṅi tācchīlye: with 'ā' upasarga in tācchīlya (habitual) sense — ac."""
    return (_eq(c, "upasarga", "ā")
            and _eq(c, "semantic_context", "tacchilya"))


def sutra_3_2_12(c) -> bool:
    """arhaḥ: 'arh' (deserve) takes ac."""
    return _eq(c, "dhatu_lemma", "arh") and _eq(c, "suffix", "ac")


def sutra_3_2_13(c) -> bool:
    """stambakarṇayor rami japoḥ: 'ram'/'jap' with 'stamba'/'karṇa' — ac."""
    return (_in(c, "dhatu_lemma", {"ram", "jap"})
            and _in(c, "upapada", {"stamba", "karṇa"}))


def sutra_3_2_14(c) -> bool:
    """śami dhātoḥ saṃjñāyām: a root with 'śam' upapada in saṃjñā — ac."""
    return _eq(c, "upapada", "śam") and c.get("is_samjna", False)


def sutra_3_2_15(c) -> bool:
    """adhikaraṇe śeteḥ: 'śī' (lie) in adhikaraṇa-relation — ac."""
    return _eq(c, "dhatu_lemma", "śī") and _eq(c, "role", Role.ADHIKARANA)


def sutra_3_2_17(c) -> bool:
    """bhikṣāsenā''dāyeṣu ca: with 'bhikṣā'/'senā'/'ādāya' as upapada — ac."""
    return _in(c, "upapada", {"bhikṣā", "senā", "ādāya"})


def sutra_3_2_18(c) -> bool:
    """puro'grato'greṣu sarteḥ: 'sṛ' with 'puras'/'agratas'/'agre' — ac."""
    return (_eq(c, "dhatu_lemma", "sṛ")
            and _in(c, "upapada", {"puras", "agratas", "agre"}))


def sutra_3_2_19(c) -> bool:
    """pūrve kartari: with 'pūrva' as upapada in kartṛ-relation — ac."""
    return _eq(c, "upapada", "pūrva") and _eq(c, "role", Role.KARTR)


def sutra_3_2_20(c) -> bool:
    """kṛño hetutācchīlyānulomyeṣu: 'kṛ' in hetu / tācchīlya / ānulomya
    senses — ṭa."""
    return (_eq(c, "dhatu_lemma", "kṛ")
            and _in(c, "semantic_context",
                    {"hetu", "tacchilya", "anulomya"}))


def sutra_3_2_21(c) -> bool:
    """divāvibhāniśāprabhā...: a long lexical list of upapadas + kṛ — ṭa."""
    return _in(c, "upapada", {
        "divā", "vibhā", "niśā", "prabhā", "bhāskara", "ananta",
        "bahu", "nāndī", "kim", "lipi", "libi", "bali",
        "bhakti", "kartṛ", "citra", "kṣetra", "saṃkhyā",
        "jaṅghā", "bāhu", "ahar", "yat", "tat", "dhanus", "aruṣ",
    })


def sutra_3_2_22(c) -> bool:
    """karmaṇi bhṛtau: 'bhṛ' in karman-relation — ṭa."""
    return _eq(c, "dhatu_lemma", "bhṛ") and _eq(c, "role", Role.KARMAN)


def sutra_3_2_23(c) -> bool:
    """na śabdaśloka-…-padeṣu: NOT with śabda/śloka/kalaha/gāthā/vaira/
    cāṭu/sūtra/mantra/pada — prohibition for 3.2.22."""
    return c.get("upapada", "") not in {
        "śabda", "śloka", "kalaha", "gāthā", "vaira",
        "cāṭu", "sūtra", "mantra", "pada",
    }


def sutra_3_2_24(c) -> bool:
    """stambaśakṛtor in: 'stamba'/'śakṛt' as upapada — in suffix."""
    return _in(c, "upapada", {"stamba", "śakṛt"}) and _eq(c, "suffix", "in")


def sutra_3_2_25(c) -> bool:
    """harater dṛti-nāthayoḥ paśau: 'hṛ' with 'dṛti'/'nātha' in cattle
    (paśu) context — in."""
    return (_eq(c, "dhatu_lemma", "hṛ")
            and _in(c, "upapada", {"dṛti", "nātha"})
            and _eq(c, "semantic_context", "pashu"))


def sutra_3_2_26(c) -> bool:
    """phalegrahirātmambhariś ca: 'phalegrahi' and 'ātmambhari' — in."""
    return _in(c, "upapada", {"phalegrahi", "ātmambhari"})


def sutra_3_2_27(c) -> bool:
    """chandasi vanasanarakṣimathām: in Vedic, van/san/rakṣ/math — in."""
    return (c.get("is_chandas", False)
            and _in(c, "dhatu_lemma", {"van", "san", "rakṣ", "math"}))


def sutra_3_2_28(c) -> bool:
    """ejeḥ khaś: 'ej' (tremble) takes khaś."""
    return _eq(c, "dhatu_lemma", "ej") and _eq(c, "suffix", "khaś")


def sutra_3_2_29(c) -> bool:
    """nāsikāstanayor dhmādheṭoḥ: 'dhmā'/'dhe' with 'nāsikā'/'stana' — khaś."""
    return (_in(c, "dhatu_lemma", {"dhmā", "dhe"})
            and _in(c, "upapada", {"nāsikā", "stana"}))


def sutra_3_2_30(c) -> bool:
    """nāḍīmuṣṭyoś ca: also with 'nāḍī'/'muṣṭi' — khaś."""
    return _in(c, "upapada", {"nāḍī", "muṣṭi"})


def sutra_3_2_31(c) -> bool:
    """udi kūle rujivahoḥ: 'ruj'/'vah' with 'ud' + 'kūla' — khaś."""
    return (_in(c, "dhatu_lemma", {"ruj", "vah"})
            and _eq(c, "upasarga", "ud")
            and _eq(c, "upapada", "kūla"))


def sutra_3_2_32(c) -> bool:
    """vahābhre lihaḥ: 'lih' with 'vahā'/'abhra' — khaś."""
    return (_eq(c, "dhatu_lemma", "lih")
            and _in(c, "upapada", {"vahā", "abhra"}))


def sutra_3_2_33(c) -> bool:
    """parimāṇe pacaḥ: 'pac' (cook) in 'measure' (parimāṇa) sense — khaś."""
    return (_eq(c, "dhatu_lemma", "pac")
            and _eq(c, "semantic_context", "parimana"))


def sutra_3_2_34(c) -> bool:
    """mitanakhe ca: also with 'mita'/'nakha' — khaś."""
    return _in(c, "upapada", {"mita", "nakha"})


def sutra_3_2_35(c) -> bool:
    """vidhvaruṣoḥ tudaḥ: 'tud' with 'vidhu'/'aruṣ' — khaś."""
    return (_eq(c, "dhatu_lemma", "tud")
            and _in(c, "upapada", {"vidhu", "aruṣ"}))


def sutra_3_2_36(c) -> bool:
    """asūryalalāṭayor dṛśitapoḥ: 'dṛś'/'tap' with 'asūrya'/'lalāṭa'."""
    return (_in(c, "dhatu_lemma", {"dṛś", "tap"})
            and _in(c, "upapada", {"asūrya", "lalāṭa"}))


def sutra_3_2_37(c) -> bool:
    """ugrampaśyer ammada-pāṇindhamāś ca: lexical compounds — khaś."""
    return _in(c, "derived_lemma", {
        "ugrampaśya", "ammada", "pāṇindhama",
    })


def sutra_3_2_38(c) -> bool:
    """priyavaśe vadaḥ khac: 'vad' with 'priya'/'vaśe' — khac."""
    return (_eq(c, "dhatu_lemma", "vad")
            and _in(c, "upapada", {"priya", "vaśa"}))


def sutra_3_2_39(c) -> bool:
    """dviṣatparayos tāpeḥ: 'tap' with 'dviṣant'/'para' — khac."""
    return (_eq(c, "dhatu_lemma", "tap")
            and _in(c, "upapada", {"dviṣant", "para"}))


def sutra_3_2_40(c) -> bool:
    """vāci yamo vrate: 'yam' (restrain) with 'vāc' in vrata sense — khac."""
    return (_eq(c, "dhatu_lemma", "yam")
            and _eq(c, "upapada", "vāc")
            and _eq(c, "semantic_context", "vrata"))


def sutra_3_2_41(c) -> bool:
    """pūḥsarvayor dārisahoḥ: 'dṛ'/'sah' with 'pur'/'sarva' — khac."""
    return (_in(c, "dhatu_lemma", {"dṛ", "sah"})
            and _in(c, "upapada", {"pur", "sarva"}))


def sutra_3_2_42(c) -> bool:
    """sarvakūlābhrakarīṣeṣu kaṣaḥ: 'kaṣ' with sarvakūla/abhra/karīṣa."""
    return (_eq(c, "dhatu_lemma", "kaṣ")
            and _in(c, "upapada", {"sarvakūla", "abhra", "karīṣa"}))


def sutra_3_2_43(c) -> bool:
    """meghartibhayeṣu kṛñaḥ: 'kṛ' with 'megha'/'ṛti'/'bhaya' — khac."""
    return (_eq(c, "dhatu_lemma", "kṛ")
            and _in(c, "upapada", {"megha", "ṛti", "bhaya"}))


def sutra_3_2_44(c) -> bool:
    """kṣemapriyamadre'ṇ ca: 'kṣema'/'priya'/'madra' — aṇ also."""
    return _in(c, "upapada", {"kṣema", "priya", "madra"})


def sutra_3_2_45(c) -> bool:
    """āśite bhuvaḥ karaṇabhāvayoḥ: 'bhū' in 'eaten' sense, karaṇa/bhāva."""
    return (_eq(c, "dhatu_lemma", "bhū")
            and _eq(c, "semantic_context", "ashita")
            and _in(c, "role", {Role.KARANA, Role.KARMAN}))


def sutra_3_2_46(c) -> bool:
    """saṃjñāyāṃ bhṛtṝvṛjidhārisahitapidamaḥ: in saṃjñā context, with
    bhṛ/tṝ/vṛj/dhāri/sah/tap/dam — kṛt."""
    return (c.get("is_samjna", False)
            and _in(c, "dhatu_lemma", {
                "bhṛ", "tṝ", "vṛj", "dhāri", "sah", "tap", "dam",
            }))


def sutra_3_2_47(c) -> bool:
    """gamaś ca: also 'gam' [in saṃjñā context] — kṛt."""
    return _eq(c, "dhatu_lemma", "gam") and c.get("is_samjna", False)


def sutra_3_2_48(c) -> bool:
    """antātyantādhvadūrapārasarvānanteṣu ḍaḥ: with anta/atyanta/adhvan/
    dūra/pāra/sarvānanta — ḍa."""
    return _in(c, "upapada", {
        "anta", "atyanta", "adhvan", "dūra", "pāra", "sarvānanta",
    })


def sutra_3_2_49(c) -> bool:
    """āśiṣi hanaḥ: 'han' in āśiṣ (benedictive) — ḍa."""
    return (_eq(c, "dhatu_lemma", "han")
            and _eq(c, "semantic_context", "ashish"))


def sutra_3_2_50(c) -> bool:
    """ape kleśatamasoḥ: with 'apa' + 'kleśa'/'tamas' — ḍa."""
    return (_eq(c, "upasarga", "apa")
            and _in(c, "upapada", {"kleśa", "tamas"}))


def sutra_3_2_51(c) -> bool:
    """kumāraśīrṣayor ṇiniḥ: with 'kumāra'/'śīrṣa' — ṇini."""
    return (_in(c, "upapada", {"kumāra", "śīrṣa"})
            and _eq(c, "suffix", "ṇini"))


def sutra_3_2_52(c) -> bool:
    """lakṣaṇe jāyāpatyoṣ ṭak: 'jāyā'/'pati' in 'sign / mark' sense — ṭak."""
    return (_in(c, "upapada", {"jāyā", "pati"})
            and _eq(c, "semantic_context", "lakshana"))


def sutra_3_2_53(c) -> bool:
    """amanuṣyakartṛke ca: also with a non-human agent — ṭak."""
    return c.get("is_amanusha_kartri", False)


def sutra_3_2_54(c) -> bool:
    """śaktau hastikapāṭayoḥ: 'hasti'/'kapāṭa' in 'capability' sense — ṭak."""
    return (_in(c, "upapada", {"hasti", "kapāṭa"})
            and _eq(c, "semantic_context", "shakti"))


def sutra_3_2_55(c) -> bool:
    """pāṇighatāḍaghau śilpini: 'pāṇighāta'/'tāḍagha' for an artisan."""
    return (_in(c, "derived_lemma", {"pāṇighāta", "tāḍagha"})
            and _eq(c, "semantic_context", "shilpa"))


def sutra_3_2_56(c) -> bool:
    """āḍhyasubhaga...kṛñaḥ karaṇe khyun: 'kṛ' with āḍhya/subhaga/sthūla/
    palita/nagna/andha/priya in cvi-sense, karaṇa — khyun."""
    return (_eq(c, "dhatu_lemma", "kṛ")
            and _in(c, "upapada", {
                "āḍhya", "subhaga", "sthūla", "palita",
                "nagna", "andha", "priya",
            })
            and _eq(c, "role", Role.KARANA))


def sutra_3_2_57(c) -> bool:
    """kartari bhuvaḥ khiṣṇuc-khukañau: 'bhū' in kartṛ — khiṣṇuc/khukañ."""
    return (_eq(c, "dhatu_lemma", "bhū")
            and _eq(c, "is_kartari", True)
            and _in(c, "suffix", {"khiṣṇuc", "khukañ"}))


def sutra_3_2_58(c) -> bool:
    """spṛśo'nudake kvin: 'spṛś' without 'udaka' upapada — kvin."""
    return (_eq(c, "dhatu_lemma", "spṛś")
            and c.get("upapada") != "udaka"
            and _eq(c, "suffix", "kvin"))


def sutra_3_2_59(c) -> bool:
    """ṛtvigdadhṛksragdiguṣṇigañcuyujikruñcāṃ ca: list of stems — kvin."""
    return _in(c, "derived_lemma", {
        "ṛtvij", "dadhṛk", "srak", "dik", "uṣṇik", "añcu", "yuj", "kruñc",
    })


def sutra_3_2_60(c) -> bool:
    """tyadādiṣu dṛśo'nālocane kañ ca: 'dṛś' with tyad-pronouns in
    non-seeing (anālocana) sense — kañ also."""
    return (_eq(c, "dhatu_lemma", "dṛś")
            and _in(c, "upapada", {"tyad", "tad", "yad", "kim", "etad"})
            and _eq(c, "semantic_context", "analocana"))


def sutra_3_2_61(c) -> bool:
    """satsū…upasarge'pi kvip: list of roots (sat/sū/dviṣ/druh/duh/yuj/
    vid/abhid/cchid/jin/rāj) — kvip, even with upasarga."""
    return (_in(c, "dhatu_lemma", {
        "sat", "sū", "dviṣ", "druh", "duh", "yuj", "vid",
        "abhid", "cchid", "jin", "rāj",
    }) and _eq(c, "suffix", "kvip"))


def sutra_3_2_62(c) -> bool:
    """bhajo ṇviḥ: 'bhaj' (share) takes ṇvi."""
    return _eq(c, "dhatu_lemma", "bhaj") and _eq(c, "suffix", "ṇvi")


def sutra_3_2_63(c) -> bool:
    """chandasi sahaḥ: in Vedic, 'sah' [takes ṇvi]."""
    return _eq(c, "dhatu_lemma", "sah") and c.get("is_chandas", False)


def sutra_3_2_64(c) -> bool:
    """vahaś ca: also 'vah' — ṇvi."""
    return _eq(c, "dhatu_lemma", "vah") and _eq(c, "suffix", "ṇvi")


def sutra_3_2_65(c) -> bool:
    """kavyapurīṣapurīṣyeṣu ñyuṭ: with kavya/purīṣa/purīṣya — ñyuṭ."""
    return _in(c, "upapada", {"kavya", "purīṣa", "purīṣya"})


def sutra_3_2_66(c) -> bool:
    """havye'nantaḥ pādam: with 'havya' [in mantra context] without
    intervening pāda — ñyuṭ."""
    return _eq(c, "upapada", "havya")


def sutra_3_2_67(c) -> bool:
    """janasanakhanakramagamo viṭ: jan/san/khan/kram/gam — viṭ."""
    return (_in(c, "dhatu_lemma", {"jan", "san", "khan", "kram", "gam"})
            and _eq(c, "suffix", "viṭ"))


def sutra_3_2_68(c) -> bool:
    """ado'nanne: 'ad' (eat) without 'anna' upapada — viṭ."""
    return _eq(c, "dhatu_lemma", "ad") and c.get("upapada") != "anna"


def sutra_3_2_69(c) -> bool:
    """kravye ca: also with 'kravya' (raw flesh) — viṭ."""
    return _eq(c, "upapada", "kravya")


def sutra_3_2_70(c) -> bool:
    """duhaḥ kab ghaś ca: 'duh' (milk) takes 'kab' and 'gha'."""
    return _eq(c, "dhatu_lemma", "duh") and _in(c, "suffix", {"kab", "gha"})


def sutra_3_2_71(c) -> bool:
    """mantre śveta-vahau-ktha-śas-puroḍāśo ṇvin: lexical mantra
    compounds — ṇvin."""
    return (c.get("is_mantra", False)
            and _in(c, "derived_lemma", {
                "śvetavah", "uktha", "śas", "puroḍāś",
            }))


def sutra_3_2_72(c) -> bool:
    """ave yajaḥ: 'yaj' (sacrifice) with 'ava' upasarga — ṇvin."""
    return _eq(c, "dhatu_lemma", "yaj") and _eq(c, "upasarga", "ava")


def sutra_3_2_73(c) -> bool:
    """vijupe chandasi: 'vij'/'pe' [or 'pa'] in Vedic — ṇvin."""
    return (c.get("is_chandas", False)
            and _in(c, "dhatu_lemma", {"vij", "pā", "pe"}))


def sutra_3_2_74(c) -> bool:
    """āto maninkvanipvanipaś ca: after ā-final root, manin / kvanip / vanip."""
    return (_eq(c, "dhatu_ends_in", "ā")
            and _in(c, "suffix", {"manin", "kvanip", "vanip"}))


def sutra_3_2_75(c) -> bool:
    """anyebhyo'pi dṛśyante: also for other roots, [these suffixes are
    seen]. Bahulam adhikāra."""
    return c.get("is_bahulam", False)


def sutra_3_2_76(c) -> bool:
    """kvip ca: also kvip [appears widely]."""
    return _eq(c, "suffix", "kvip")


def sutra_3_2_77(c) -> bool:
    """sthaḥ ka ca: 'sthā' also takes ka."""
    return _eq(c, "dhatu_lemma", "sthā") and _eq(c, "suffix", "ka")


def sutra_3_2_78(c) -> bool:
    """supy ajātau ṇinis tācchīlye: with sup-upapada, non-jāti, in
    tācchīlya sense — ṇini."""
    return (c.get("has_sup_upapada", False)
            and not c.get("is_jati", False)
            and _eq(c, "semantic_context", "tacchilya"))


def sutra_3_2_79(c) -> bool:
    """kartary upamāne: in kartṛ-relation with upamāna — ṇini."""
    return _eq(c, "role", Role.KARTR) and c.get("is_upamana", False)


def sutra_3_2_80(c) -> bool:
    """vrate: in vrata (observance) sense — ṇini."""
    return _eq(c, "semantic_context", "vrata")


def sutra_3_2_81(c) -> bool:
    """bahulam ābhīkṣṇye: variously in 'frequent' (abhīkṣṇya) sense."""
    return _eq(c, "semantic_context", "abhikshnya")


def sutra_3_2_82(c) -> bool:
    """manaḥ: with 'manas' as upapada — ṇini."""
    return _eq(c, "upapada", "manas")


def sutra_3_2_83(c) -> bool:
    """ātmamāne khaś ca: with 'ātman' as upapada in 'measuring oneself'
    sense — khaś."""
    return _eq(c, "upapada", "ātman") and _eq(c, "suffix", "khaś")


def sutra_3_2_84(c) -> bool:
    """bhūte: in past-time sense — kta/ktavat."""
    return _eq(c, "semantic_context", "bhuta") or _eq(c, "suffix", "kta")


def sutra_3_2_85(c) -> bool:
    """karaṇe yajaḥ: 'yaj' in karaṇa-relation — kta."""
    return _eq(c, "dhatu_lemma", "yaj") and _eq(c, "role", Role.KARANA)


def sutra_3_2_86(c) -> bool:
    """karmaṇi hanaḥ: 'han' in karman-relation — kta."""
    return _eq(c, "dhatu_lemma", "han") and _eq(c, "role", Role.KARMAN)


def sutra_3_2_87(c) -> bool:
    """brahmabhrūṇavṛtreṣu kvip: with brahman/bhrūṇa/vṛtra as upapada — kvip."""
    return _in(c, "upapada", {"brahman", "bhrūṇa", "vṛtra"})


def sutra_3_2_88(c) -> bool:
    """bahulaṃ chandasi: variously in Vedic."""
    return c.get("is_chandas", False)


def sutra_3_2_89(c) -> bool:
    """sukarmapāpamantrapuṇyeṣu kṛñaḥ: 'kṛ' with sukarman/pāpa/mantra/
    puṇya — ñyuṭ."""
    return (_eq(c, "dhatu_lemma", "kṛ")
            and _in(c, "upapada", {"sukarman", "pāpa", "mantra", "puṇya"}))


def sutra_3_2_90(c) -> bool:
    """some suñaḥ: 'su' (press soma) with 'soma' — kvip."""
    return _eq(c, "dhatu_lemma", "su") and _eq(c, "upapada", "soma")


def sutra_3_2_91(c) -> bool:
    """agnau ceḥ: 'ci' (gather) with 'agni' — kvip."""
    return _eq(c, "dhatu_lemma", "ci") and _eq(c, "upapada", "agni")


def sutra_3_2_92(c) -> bool:
    """karmaṇy agnyākhyāyām: in karman context for a fire-name — kvip."""
    return _eq(c, "role", Role.KARMAN) and c.get("is_agni_akhya", False)


def sutra_3_2_93(c) -> bool:
    """karmaṇī'nirvikriyaḥ: in karman, no further change — kvip."""
    return _eq(c, "role", Role.KARMAN) and not c.get("is_vikriya", False)


def sutra_3_2_94(c) -> bool:
    """dṛśeḥ kvanip: 'dṛś' takes kvanip."""
    return _eq(c, "dhatu_lemma", "dṛś") and _eq(c, "suffix", "kvanip")


def sutra_3_2_95(c) -> bool:
    """rājani yudhi-kṛñaḥ: 'yudh'/'kṛ' with 'rājan' — kvanip."""
    return (_in(c, "dhatu_lemma", {"yudh", "kṛ"})
            and _eq(c, "upapada", "rājan"))


def sutra_3_2_96(c) -> bool:
    """sahe ca: also with 'saha' upapada — kvanip."""
    return _eq(c, "upapada", "saha")


def sutra_3_2_97(c) -> bool:
    """saptamyāṃ janer ḍaḥ: 'jan' with locative upapada — ḍa."""
    return (_eq(c, "dhatu_lemma", "jan")
            and _eq(c, "case", Case.LOCATIVE))


def sutra_3_2_98(c) -> bool:
    """pañcamyām ajātau: ablative upapada, non-jāti — ḍa."""
    return (_eq(c, "case", Case.ABLATIVE)
            and not c.get("is_jati", False))


def sutra_3_2_99(c) -> bool:
    """upasarge ca saṃjñāyām: with upasarga in saṃjñā — ḍa."""
    return c.get("upasarga") is not None and c.get("is_samjna", False)


def sutra_3_2_100(c) -> bool:
    """anau karmaṇi: with 'anu' upasarga in karman — ḍa."""
    return _eq(c, "upasarga", "anu") and _eq(c, "role", Role.KARMAN)


def sutra_3_2_101(c) -> bool:
    """anyeṣv api dṛśyate: also seen in other contexts (bahulam)."""
    return c.get("is_bahulam", False)


def sutra_3_2_103(c) -> bool:
    """suyajor ṅvanip: 'su'/'yaj' take ṅvanip."""
    return (_in(c, "dhatu_lemma", {"su", "yaj"})
            and _eq(c, "suffix", "ṅvanip"))


def sutra_3_2_104(c) -> bool:
    """jīryater atṛn: 'jīr' (grow old) takes atṛn."""
    return _eq(c, "dhatu_lemma", "jīr") and _eq(c, "suffix", "atṛn")


def sutra_3_2_105(c) -> bool:
    """chandasi liṭ: in Vedic, liṭ is used [for general past]."""
    return c.get("is_chandas", False) and _eq(c, "lakara", Lakara.LIT)


def sutra_3_2_106(c) -> bool:
    """liṭaḥ kānajvā: liṭ replaced by kānac (suffix) in chandas/optional."""
    return _eq(c, "lakara", Lakara.LIT) and _eq(c, "suffix", "kānac")


def sutra_3_2_107(c) -> bool:
    """kvasuś ca: also kvasu suffix [for liṭ]."""
    return _eq(c, "suffix", "kvasu")


def sutra_3_2_108(c) -> bool:
    """bhāṣāyāṃ sadavasaśruvaḥ: in bhāṣā (classical), sad/vas/śru — kvasu."""
    return (not c.get("is_chandas", False)
            and _in(c, "dhatu_lemma", {"sad", "vas", "śru"})
            and _eq(c, "suffix", "kvasu"))


def sutra_3_2_109(c) -> bool:
    """upeyivān-anāśvān-anūcānaś ca: lexical kvasu derivatives —
    upeyivan, anāśvan, anūcān."""
    return _in(c, "derived_lemma", {"upeyivan", "anāśvan", "anūcān"})


def sutra_3_2_112(c) -> bool:
    """abhijñāvacane lṛṭ: lṛṭ in 'recollecting' sense."""
    return (_eq(c, "lakara", Lakara.LRT)
            and _eq(c, "semantic_context", "abhijna_vacana"))


def sutra_3_2_113(c) -> bool:
    """na yadi: NOT if 'yadi' (if) is present — exception."""
    return c.get("first") != "yadi"


def sutra_3_2_114(c) -> bool:
    """vibhāṣā sākāṅkṣe: optionally when expectation (ākāṅkṣā) present."""
    return c.get("is_sakanksha", False) and c.get("is_optional", True)


def sutra_3_2_115(c) -> bool:
    """parokṣe liṭ: liṭ in 'unseen / remote past' sense."""
    return (_eq(c, "lakara", Lakara.LIT)
            and _eq(c, "semantic_context", "paroksha"))


def sutra_3_2_116(c) -> bool:
    """haśaśvator laṅ ca: with 'ha'/'śaśvat' — laṅ also."""
    return _in(c, "first", {"ha", "śaśvat"}) and _eq(c, "lakara", Lakara.LAN)


def sutra_3_2_117(c) -> bool:
    """praśne cā'sannakāle: in question + recent-past sense — laṅ."""
    return (_eq(c, "lakara", Lakara.LAN)
            and _eq(c, "semantic_context", "prashna_asanna"))


def sutra_3_2_118(c) -> bool:
    """laṭ sme: with 'sma' — laṭ [for narrative past]."""
    return _eq(c, "lakara", Lakara.LAT) and _eq(c, "first", "sma")


def sutra_3_2_119(c) -> bool:
    """aparokṣe ca: also in 'witnessed' context — laṭ."""
    return _eq(c, "lakara", Lakara.LAT) and _eq(c, "semantic_context", "aparoksha")


def sutra_3_2_120(c) -> bool:
    """nanau pṛṣṭa-prativacane: with 'nanu' in answer-to-question — laṭ."""
    return _eq(c, "first", "nanu") and _eq(c, "semantic_context", "prishta_prativacana")


def sutra_3_2_121(c) -> bool:
    """nanvor vibhāṣā: optionally with 'na'/'nu'."""
    return _in(c, "first", {"na", "nu"}) and c.get("is_optional", True)


def sutra_3_2_122(c) -> bool:
    """puri luṅ cā'sme: with 'pura' + not-recent — luṅ."""
    return (_eq(c, "first", "pura")
            and _eq(c, "lakara", Lakara.LUN))


def sutra_3_2_124(c) -> bool:
    """laṭaḥ śatṛśānacāv aprathamāsamānādhikaraṇe: laṭ replaced by śatṛ/
    śānac in non-first-person same-locus context."""
    return (_eq(c, "lakara", Lakara.LAT)
            and _in(c, "suffix", {"śatṛ", "śānac"}))


def sutra_3_2_125(c) -> bool:
    """sambodhane ca: also in vocative — śatṛ/śānac."""
    return _eq(c, "case", Case.VOCATIVE)


def sutra_3_2_126(c) -> bool:
    """lakṣaṇa-hetvoḥ kriyāyāḥ: in 'mark / cause' of action — śatṛ/śānac."""
    return _in(c, "semantic_context", {"lakshana", "hetu"})


def sutra_3_2_127(c) -> bool:
    """tau sat: those two [śatṛ + śānac] are called 'sat'. Saṃjñā."""
    return _in(c, "suffix", {"śatṛ", "śānac"})


def sutra_3_2_128(c) -> bool:
    """pūṅyajoḥ śānan: 'pū'/'yaj' take śānan."""
    return _in(c, "dhatu_lemma", {"pū", "yaj"}) and _eq(c, "suffix", "śānan")


def sutra_3_2_129(c) -> bool:
    """tācchīlyavayovacanaśaktiṣu cānaś: in tācchīlya/vayas/śakti — cānaś."""
    return _in(c, "semantic_context", {"tacchilya", "vayas", "shakti"})


def sutra_3_2_130(c) -> bool:
    """iṅ-dhāryoḥ śatrak-ṛc-chriṇi: with 'iṅ'/'dhṛ' — śatra-/kṛcch-riṇ."""
    return _in(c, "dhatu_lemma", {"iṅ", "dhṛ"})


def sutra_3_2_131(c) -> bool:
    """dviṣo'mitre: 'dviṣ' in 'enemy' (amitra) sense — śatṛ."""
    return _eq(c, "dhatu_lemma", "dviṣ") and _eq(c, "semantic_context", "amitra")


def sutra_3_2_132(c) -> bool:
    """suño yajñasaṃyoge: 'su' (press) in yajña context — śatṛ."""
    return _eq(c, "dhatu_lemma", "su") and _eq(c, "semantic_context", "yajna")


def sutra_3_2_133(c) -> bool:
    """arhaḥ pūjāyām: 'arh' in 'honoring' sense — śatṛ."""
    return _eq(c, "dhatu_lemma", "arh") and _eq(c, "semantic_context", "puja")


def sutra_3_2_134(c) -> bool:
    """ākves tac-chīla-tad-dharma-tat-sādhukāriṣu: from āk (ākvi) in
    habit/dharma/skill senses."""
    return _in(c, "semantic_context", {"tacchila", "taddharma", "tatsadhukari"})


def sutra_3_2_136(c) -> bool:
    """alaṃkṛñ-nirākṛñ…iṣṇuc: long lexical list — iṣṇuc."""
    return _in(c, "dhatu_lemma", {
        "alaṃkṛ", "nirākṛ", "prajan", "utpac", "utpat",
        "unmad", "ruc", "apatrap", "vṛt", "vṛdh", "sah",
        "car",
    }) and _eq(c, "suffix", "iṣṇuc")


def sutra_3_2_137(c) -> bool:
    """ṇeś chandasi: 'ṇi' (ṇic) in Vedic — iṣṇuc."""
    return c.get("is_causative", False) and c.get("is_chandas", False)


def sutra_3_2_138(c) -> bool:
    """bhuvaś ca: also 'bhū' [in Vedic causative] — iṣṇuc."""
    return _eq(c, "dhatu_lemma", "bhū") and c.get("is_chandas", False)


def sutra_3_2_139(c) -> bool:
    """glājisthaś ca ksnuḥ: glā/ji/sthā — ksnu."""
    return _in(c, "dhatu_lemma", {"glā", "ji", "sthā"}) and _eq(c, "suffix", "ksnu")


def sutra_3_2_140(c) -> bool:
    """trasi-gṛdhi-dhṛṣi-kṣipeḥ knuḥ: tras/gṛdh/dhṛṣ/kṣip — knu."""
    return _in(c, "dhatu_lemma", {"tras", "gṛdh", "dhṛṣ", "kṣip"})


def sutra_3_2_141(c) -> bool:
    """śamity-aṣṭābhyo ghinuṇ: 'śam' and 8 others — ghinun."""
    return _in(c, "dhatu_lemma", {
        "śam", "tam", "kam", "ram", "dam", "kṣam", "śram", "bhram", "klam",
    }) and _eq(c, "suffix", "ghinun")


def sutra_3_2_142(c) -> bool:
    """saṃpṛcānurudhāṅyam…: very long list — ghinun."""
    return _in(c, "dhatu_lemma", {
        "saṃpṛc", "anurudh", "anuyam", "yas", "sṛ", "saṃsṛj",
        "paridev", "saṃjvar", "parikṣip", "pariraṭ", "parivad",
        "paridah", "parimuh", "duṣ", "dviṣ", "druh", "duh",
        "yuj", "ākrīḍ", "vivic", "tyaj", "raj", "bhaj",
        "aticar", "apacar", "amuṣ", "abhyāhan",
    })


def sutra_3_2_143(c) -> bool:
    """vau kaṣa-lasa-katthasrambhaḥ: with 'va' upasarga, kaṣ/las/kath/
    sramh — ghinun."""
    return (_in(c, "dhatu_lemma", {"kaṣ", "las", "kath", "srambh"})
            and _eq(c, "upasarga", "vi"))


def sutra_3_2_144(c) -> bool:
    """ape ca laṣaḥ: 'laṣ' with 'apa' — ghinun."""
    return _eq(c, "dhatu_lemma", "laṣ") and _eq(c, "upasarga", "apa")


def sutra_3_2_145(c) -> bool:
    """pre lapasṛ-dru-math-vad-avasaḥ: 'lap'/'sṛ'/'dru'/'math'/'vad'/
    'avas' with 'pra' — ghinun."""
    return (_in(c, "dhatu_lemma",
                {"lap", "sṛ", "dru", "math", "vad", "avas"})
            and _eq(c, "upasarga", "pra"))


def sutra_3_2_146(c) -> bool:
    """ninda-hiṃsa-kliśa-khāda-vināśa…vuñ: long list of bad-action
    roots — vuñ."""
    return _in(c, "dhatu_lemma", {
        "nind", "hiṃs", "kliś", "khād", "vināś",
        "parikṣip", "pariraṭ", "parivad", "vyābhāṣ", "asū",
    }) and _eq(c, "suffix", "vuñ")


def sutra_3_2_147(c) -> bool:
    """devikruśoś copasarge: with 'devi'/'kruś' and upasarga — vuñ."""
    return (_in(c, "dhatu_lemma", {"devi", "kruś"})
            and c.get("upasarga") is not None)


def sutra_3_2_148(c) -> bool:
    """calanaśabdārthād akarmakād yuc: from a motion/sound root, non-
    transitive — yuc."""
    return (_in(c, "semantic_context", {"calana", "shabda"})
            and c.get("is_akarmaka", False))


def sutra_3_2_149(c) -> bool:
    """anudāttetaś ca halādeḥ: anudātta-it-marked, consonant-initial — yuc."""
    return (c.get("is_anudatta_it", False)
            and c.get("is_haladi", False))


def sutra_3_2_150(c) -> bool:
    """ju-caṅkramy-adandramy-asṛ-gṛdhi-jvala-śuca-laṣa-pata-padaḥ:
    list of roots — yuc."""
    return _in(c, "dhatu_lemma", {
        "ju", "caṅkram", "dandramy", "sṛ", "gṛdh", "jval",
        "śuc", "laṣ", "pat", "pad",
    })


def sutra_3_2_151(c) -> bool:
    """krudha-maṇḍārthebhyaś ca: from kruddha- / maṇḍa-meaning roots — yuc."""
    return _in(c, "semantic_context", {"krodha", "manda"})


def sutra_3_2_152(c) -> bool:
    """na yaḥ: NOT for 'ya' (yā, go) — prohibition."""
    return c.get("dhatu_lemma") != "yā"


def sutra_3_2_153(c) -> bool:
    """sūda-dīpa-dīkṣaś ca: 'sūd'/'dīp'/'dīkṣ' — yuc."""
    return _in(c, "dhatu_lemma", {"sūd", "dīp", "dīkṣ"})


def sutra_3_2_154(c) -> bool:
    """laṣa-pata-pada-sthā-bhū-vṛṣa-hana-kama-gama-śṝbhya ukañ: long list — ukañ."""
    return _in(c, "dhatu_lemma", {
        "laṣ", "pat", "pad", "sthā", "bhū", "vṛṣ",
        "han", "kam", "gam", "śṝ",
    }) and _eq(c, "suffix", "ukañ")


def sutra_3_2_155(c) -> bool:
    """jalpa-bhikṣa-kuṭṭa-luṇṭa-vṛṅaḥ ṣākan: jalp/bhikṣ/kuṭṭ/luṇṭ/vṛ —
    ṣākan."""
    return _in(c, "dhatu_lemma", {"jalp", "bhikṣ", "kuṭṭ", "luṇṭ", "vṛ"})


def sutra_3_2_156(c) -> bool:
    """prajor iniḥ: 'prajan' (be born) takes in."""
    return _eq(c, "dhatu_lemma", "prajan") and _eq(c, "suffix", "in")


def sutra_3_2_157(c) -> bool:
    """jidṛkṣiviśrīṇvamāvyathābhyamaparibhūprasūbhyaś ca: list of
    intensive-form roots — in."""
    return _in(c, "dhatu_lemma", {
        "jidṛkṣ", "viśrī", "vamā", "vyatha", "vyathana",
        "abhyam", "paribhū", "prasū",
    })


def sutra_3_2_158(c) -> bool:
    """spṛhi-gṛhi-pati-dayi-nidrā-tandrā-śraddhābhya āluc: spṛh/gṛh/pat/
    day/nidra/tandra/śraddhā — āluc."""
    return (_in(c, "dhatu_lemma", {
        "spṛh", "gṛh", "pat", "day", "nidrā", "tandrā", "śraddhā",
    }) and _eq(c, "suffix", "āluc"))


def sutra_3_2_159(c) -> bool:
    """dādheṭsiśadasado ruḥ: dā/dheṭ/sic/śad/sad — ru."""
    return (_in(c, "dhatu_lemma", {"dā", "dheṭ", "sic", "śad", "sad"})
            and _eq(c, "suffix", "ru"))


def sutra_3_2_160(c) -> bool:
    """sṛghasyadaḥ kmarac: sṛ/ghas/yad — kmarac."""
    return (_in(c, "dhatu_lemma", {"sṛ", "ghas", "yad"})
            and _eq(c, "suffix", "kmarac"))


def sutra_3_2_161(c) -> bool:
    """bhañjabhāsamido ghurac: bhañj/bhās/mid — ghurac."""
    return (_in(c, "dhatu_lemma", {"bhañj", "bhās", "mid"})
            and _eq(c, "suffix", "ghurac"))


def sutra_3_2_162(c) -> bool:
    """vidi-bhidi-cchideḥ kurac: vid/bhid/cchid — kurac."""
    return (_in(c, "dhatu_lemma", {"vid", "bhid", "cchid"})
            and _eq(c, "suffix", "kurac"))


def sutra_3_2_163(c) -> bool:
    """iṇ-naś-ji-sartti-bhyaḥ kvarap: iṇ/naś/ji/sṛ — kvarap."""
    return (_in(c, "dhatu_lemma", {"iṇ", "naś", "ji", "sṛ"})
            and _eq(c, "suffix", "kvarap"))


def sutra_3_2_164(c) -> bool:
    """gatvaraś ca: 'gatvara' — kvarap."""
    return _eq(c, "derived_lemma", "gatvara")


def sutra_3_2_165(c) -> bool:
    """jāgurūkaḥ: 'jāgṛ' (awake) — ūka."""
    return _eq(c, "dhatu_lemma", "jāgṛ") and _eq(c, "suffix", "ūka")


def sutra_3_2_166(c) -> bool:
    """yaja-japa-daśāṃ yaṅaḥ: yaj/jap/daś with yaṅ — ūka."""
    return (_in(c, "dhatu_lemma", {"yaj", "jap", "daś"})
            and c.get("is_yang", False))


def sutra_3_2_167(c) -> bool:
    """nami-kampi-smyajasakamahiṃsadīpo raḥ: list — ra."""
    return (_in(c, "dhatu_lemma", {
        "nam", "kamp", "smṛ", "jas", "kam", "hiṃs", "dīp",
    }) and _eq(c, "suffix", "ra"))


def sutra_3_2_168(c) -> bool:
    """sanāśaṃsabhikṣa uḥ: san/āśaṃs/bhikṣ — u."""
    return (_in(c, "dhatu_lemma", {"san", "āśaṃs", "bhikṣ"})
            and _eq(c, "suffix", "u"))


def sutra_3_2_169(c) -> bool:
    """vinduricchuḥ: 'vindu' and 'icchu' (lexical)."""
    return _in(c, "derived_lemma", {"vindu", "icchu"})


def sutra_3_2_170(c) -> bool:
    """kyāc chandasi: kyāc suffix in Vedic."""
    return _eq(c, "suffix", "kyāc") and c.get("is_chandas", False)


def sutra_3_2_171(c) -> bool:
    """ādṛga-mahana-janaḥ kikinau liṭ ca: ādṛ/man/han/jan with liṭ — kikinau."""
    return (_in(c, "dhatu_lemma", {"ādṛ", "man", "han", "jan"})
            and _eq(c, "lakara", Lakara.LIT))


def sutra_3_2_172(c) -> bool:
    """svapi-tṛṣor najiṅ: svap/tṛṣ — najiṅ."""
    return (_in(c, "dhatu_lemma", {"svap", "tṛṣ"})
            and _eq(c, "suffix", "najiṅ"))


def sutra_3_2_173(c) -> bool:
    """śṝvandyor āruḥ: śṝ/vand — āru."""
    return (_in(c, "dhatu_lemma", {"śṝ", "vand"})
            and _eq(c, "suffix", "āru"))


def sutra_3_2_174(c) -> bool:
    """bhiyaḥ kruklukanau: 'bhī' — kruka/lukan."""
    return _eq(c, "dhatu_lemma", "bhī") and _in(c, "suffix", {"kruka", "lukan"})


def sutra_3_2_175(c) -> bool:
    """stheśabhāsa-pisakaso varac: sthā/iś/bhās/pisa/kas — varac."""
    return _in(c, "dhatu_lemma", {"sthā", "īś", "bhās", "pisa", "kas"})


def sutra_3_2_176(c) -> bool:
    """yaś ca yaṅaḥ: 'ya' [yaṅ-suffixed form] — varac."""
    return c.get("is_yang", False) and _eq(c, "suffix", "varac")


def sutra_3_2_177(c) -> bool:
    """bhrāja-bhāsa-dhurv-vidyut-orji-pṝ-jugrāvastuvaḥ kvip:
    bhrāj/bhās/dhurv/vidyut/ūrj/pṝ/jugrāvan/stu — kvip."""
    return (_in(c, "dhatu_lemma", {
        "bhrāj", "bhās", "dhurv", "vidyut", "ūrj",
        "pṝ", "jugrāvan", "stu",
    }) and _eq(c, "suffix", "kvip"))


def sutra_3_2_178(c) -> bool:
    """anyebhyo'pi dṛśyate: also in other contexts — kvip / bahulam."""
    return c.get("is_bahulam", False)


def sutra_3_2_179(c) -> bool:
    """bhuvaḥ saṃjñā'ntarayoḥ: 'bhū' in saṃjñā or 'antara' — kvip."""
    return _eq(c, "dhatu_lemma", "bhū") and (
        c.get("is_samjna", False) or _eq(c, "upapada", "antara"))


def sutra_3_2_180(c) -> bool:
    """vipra-sambhyo ḍvasaṃjñāyām: vipra/sam — ḍvac, not in saṃjñā."""
    return _in(c, "upasarga", {"vi", "pra", "sam"}) and not c.get("is_samjna", False)


def sutra_3_2_181(c) -> bool:
    """dhaḥ karmaṇi ṣṭran: 'dhā' in karman — ṣṭran."""
    return _eq(c, "dhatu_lemma", "dhā") and _eq(c, "role", Role.KARMAN)


def sutra_3_2_182(c) -> bool:
    """dāmnī-śasa-yuyuja-stu-tuda-si-sica-miha-pata-daśa-nahaḥ karaṇe:
    long list of roots in karaṇa — ṣṭran."""
    return (_in(c, "dhatu_lemma", {
        "dāmn", "śas", "yuj", "stu", "tud", "si", "sic",
        "mih", "pat", "daś", "nah",
    }) and _eq(c, "role", Role.KARANA))


def sutra_3_2_183(c) -> bool:
    """halasūkarayoḥ puvaḥ: 'pū' with 'hala'/'sūkara' — ṣṭran."""
    return _eq(c, "dhatu_lemma", "pū") and _in(c, "upapada", {"hala", "sūkara"})


def sutra_3_2_184(c) -> bool:
    """arti-lū-dhū-sū-khana-sahacara itraḥ: ṛ/lū/dhū/sū/khan/sahacar — itra."""
    return (_in(c, "dhatu_lemma", {"ṛ", "lū", "dhū", "sū", "khan", "sahacar"})
            and _eq(c, "suffix", "itra"))


def sutra_3_2_185(c) -> bool:
    """puvaḥ saṃjñāyām: 'pū' in saṃjñā — itra."""
    return _eq(c, "dhatu_lemma", "pū") and c.get("is_samjna", False)


def sutra_3_2_186(c) -> bool:
    """kartari carṣi-devatayoḥ: kartṛ with ṛṣi/devatā context — itra."""
    return (_eq(c, "role", Role.KARTR)
            and _in(c, "semantic_context", {"rishi", "devata"}))


def sutra_3_2_187(c) -> bool:
    """ñīta kta: ñī-marked roots take kta."""
    return c.get("is_nyit", False) and _eq(c, "suffix", "kta")


def sutra_3_2_188(c) -> bool:
    """mati-buddhi-pūjārthebhyaś ca: from 'thought / wisdom / honor'
    sense roots — kta."""
    return _in(c, "semantic_context", {"mati", "buddhi", "puja"})


# ===========================================================================
# Fixtures
# ===========================================================================


def _pn(positive_dict: dict, negative_dict: dict) -> tuple[dict, dict]:
    return positive_dict, negative_dict


FIXTURES: dict[str, tuple[dict, dict]] = {
    "3.2.2":   _pn({"upapada": "hve", "dhatu_lemma": "kṛ"},
                   {"upapada": "rāma", "dhatu_lemma": "bhū"}),
    "3.2.4":   _pn({"dhatu_lemma": "sthā", "has_sup_upapada": True},
                   {"dhatu_lemma": "sthā", "has_sup_upapada": False}),
    "3.2.5":   _pn({"dhatu_lemma": "parimṛj", "upapada": "tunda"},
                   {"dhatu_lemma": "rāma", "upapada": "phala"}),
    "3.2.6":   _pn({"dhatu_lemma": "dā", "upasarga": "pra"},
                   {"dhatu_lemma": "dā", "upasarga": "ni"}),
    "3.2.7":   _pn({"dhatu_lemma": "khyā", "upasarga": "sam"},
                   {"dhatu_lemma": "khyā", "upasarga": "ni"}),
    "3.2.8":   _pn({"dhatu_lemma": "gā", "suffix": "ṭak"},
                   {"dhatu_lemma": "rāma", "suffix": "ṭak"}),
    "3.2.9":   _pn({"dhatu_lemma": "hṛ", "semantic_context": "anudyamana",
                    "suffix": "ac"},
                   {"dhatu_lemma": "hṛ", "semantic_context": "other",
                    "suffix": "ac"}),
    "3.2.10":  _pn({"semantic_context": "vayas", "suffix": "ac"},
                   {"semantic_context": "other", "suffix": "ac"}),
    "3.2.11":  _pn({"upasarga": "ā", "semantic_context": "tacchilya"},
                   {"upasarga": "ni", "semantic_context": "other"}),
    "3.2.12":  _pn({"dhatu_lemma": "arh", "suffix": "ac"},
                   {"dhatu_lemma": "rāma", "suffix": "ac"}),
    "3.2.13":  _pn({"dhatu_lemma": "ram", "upapada": "stamba"},
                   {"dhatu_lemma": "ram", "upapada": "rāma"}),
    "3.2.14":  _pn({"upapada": "śam", "is_samjna": True},
                   {"upapada": "śam", "is_samjna": False}),
    "3.2.15":  _pn({"dhatu_lemma": "śī", "role": Role.ADHIKARANA},
                   {"dhatu_lemma": "śī", "role": Role.KARTR}),
    "3.2.17":  _pn({"upapada": "bhikṣā"},
                   {"upapada": "rāma"}),
    "3.2.18":  _pn({"dhatu_lemma": "sṛ", "upapada": "puras"},
                   {"dhatu_lemma": "sṛ", "upapada": "rāma"}),
    "3.2.19":  _pn({"upapada": "pūrva", "role": Role.KARTR},
                   {"upapada": "pūrva", "role": Role.KARMAN}),
    "3.2.20":  _pn({"dhatu_lemma": "kṛ", "semantic_context": "hetu"},
                   {"dhatu_lemma": "kṛ", "semantic_context": "other"}),
    "3.2.21":  _pn({"upapada": "divā"},
                   {"upapada": "rāma"}),
    "3.2.22":  _pn({"dhatu_lemma": "bhṛ", "role": Role.KARMAN},
                   {"dhatu_lemma": "bhṛ", "role": Role.KARTR}),
    "3.2.23":  _pn({"upapada": "rāma"},
                   {"upapada": "śabda"}),
    "3.2.24":  _pn({"upapada": "stamba", "suffix": "in"},
                   {"upapada": "rāma", "suffix": "in"}),
    "3.2.25":  _pn({"dhatu_lemma": "hṛ", "upapada": "dṛti",
                    "semantic_context": "pashu"},
                   {"dhatu_lemma": "hṛ", "upapada": "rāma",
                    "semantic_context": "other"}),
    "3.2.26":  _pn({"upapada": "phalegrahi"},
                   {"upapada": "rāma"}),
    "3.2.27":  _pn({"is_chandas": True, "dhatu_lemma": "van"},
                   {"is_chandas": False, "dhatu_lemma": "van"}),
    "3.2.28":  _pn({"dhatu_lemma": "ej", "suffix": "khaś"},
                   {"dhatu_lemma": "rāma", "suffix": "khaś"}),
    "3.2.29":  _pn({"dhatu_lemma": "dhmā", "upapada": "nāsikā"},
                   {"dhatu_lemma": "dhmā", "upapada": "rāma"}),
    "3.2.30":  _pn({"upapada": "nāḍī"},
                   {"upapada": "rāma"}),
    "3.2.31":  _pn({"dhatu_lemma": "ruj", "upasarga": "ud", "upapada": "kūla"},
                   {"dhatu_lemma": "ruj", "upasarga": "ni", "upapada": "rāma"}),
    "3.2.32":  _pn({"dhatu_lemma": "lih", "upapada": "vahā"},
                   {"dhatu_lemma": "lih", "upapada": "rāma"}),
    "3.2.33":  _pn({"dhatu_lemma": "pac", "semantic_context": "parimana"},
                   {"dhatu_lemma": "pac", "semantic_context": "other"}),
    "3.2.34":  _pn({"upapada": "mita"},
                   {"upapada": "rāma"}),
    "3.2.35":  _pn({"dhatu_lemma": "tud", "upapada": "vidhu"},
                   {"dhatu_lemma": "tud", "upapada": "rāma"}),
    "3.2.36":  _pn({"dhatu_lemma": "dṛś", "upapada": "asūrya"},
                   {"dhatu_lemma": "dṛś", "upapada": "rāma"}),
    "3.2.37":  _pn({"derived_lemma": "ugrampaśya"},
                   {"derived_lemma": "rāma"}),
    "3.2.38":  _pn({"dhatu_lemma": "vad", "upapada": "priya"},
                   {"dhatu_lemma": "vad", "upapada": "rāma"}),
    "3.2.39":  _pn({"dhatu_lemma": "tap", "upapada": "dviṣant"},
                   {"dhatu_lemma": "tap", "upapada": "rāma"}),
    "3.2.40":  _pn({"dhatu_lemma": "yam", "upapada": "vāc",
                    "semantic_context": "vrata"},
                   {"dhatu_lemma": "yam", "upapada": "vāc",
                    "semantic_context": "other"}),
    "3.2.41":  _pn({"dhatu_lemma": "dṛ", "upapada": "pur"},
                   {"dhatu_lemma": "dṛ", "upapada": "rāma"}),
    "3.2.42":  _pn({"dhatu_lemma": "kaṣ", "upapada": "sarvakūla"},
                   {"dhatu_lemma": "kaṣ", "upapada": "rāma"}),
    "3.2.43":  _pn({"dhatu_lemma": "kṛ", "upapada": "megha"},
                   {"dhatu_lemma": "kṛ", "upapada": "rāma"}),
    "3.2.44":  _pn({"upapada": "kṣema"},
                   {"upapada": "rāma"}),
    "3.2.45":  _pn({"dhatu_lemma": "bhū", "semantic_context": "ashita",
                    "role": Role.KARANA},
                   {"dhatu_lemma": "bhū", "semantic_context": "other",
                    "role": Role.KARTR}),
    "3.2.46":  _pn({"is_samjna": True, "dhatu_lemma": "bhṛ"},
                   {"is_samjna": False, "dhatu_lemma": "bhṛ"}),
    "3.2.47":  _pn({"dhatu_lemma": "gam", "is_samjna": True},
                   {"dhatu_lemma": "gam", "is_samjna": False}),
    "3.2.48":  _pn({"upapada": "anta"},
                   {"upapada": "rāma"}),
    "3.2.49":  _pn({"dhatu_lemma": "han", "semantic_context": "ashish"},
                   {"dhatu_lemma": "han", "semantic_context": "other"}),
    "3.2.50":  _pn({"upasarga": "apa", "upapada": "kleśa"},
                   {"upasarga": "pra", "upapada": "rāma"}),
    "3.2.51":  _pn({"upapada": "kumāra", "suffix": "ṇini"},
                   {"upapada": "rāma", "suffix": "ṇini"}),
    "3.2.52":  _pn({"upapada": "jāyā", "semantic_context": "lakshana"},
                   {"upapada": "jāyā", "semantic_context": "other"}),
    "3.2.53":  _pn({"is_amanusha_kartri": True},
                   {"is_amanusha_kartri": False}),
    "3.2.54":  _pn({"upapada": "hasti", "semantic_context": "shakti"},
                   {"upapada": "hasti", "semantic_context": "other"}),
    "3.2.55":  _pn({"derived_lemma": "pāṇighāta", "semantic_context": "shilpa"},
                   {"derived_lemma": "rāma", "semantic_context": "other"}),
    "3.2.56":  _pn({"dhatu_lemma": "kṛ", "upapada": "āḍhya",
                    "role": Role.KARANA},
                   {"dhatu_lemma": "kṛ", "upapada": "rāma",
                    "role": Role.KARTR}),
    "3.2.57":  _pn({"dhatu_lemma": "bhū", "is_kartari": True,
                    "suffix": "khiṣṇuc"},
                   {"dhatu_lemma": "bhū", "is_kartari": False,
                    "suffix": "kta"}),
    "3.2.58":  _pn({"dhatu_lemma": "spṛś", "upapada": "rāma", "suffix": "kvin"},
                   {"dhatu_lemma": "spṛś", "upapada": "udaka", "suffix": "kvin"}),
    "3.2.59":  _pn({"derived_lemma": "ṛtvij"},
                   {"derived_lemma": "rāma"}),
    "3.2.60":  _pn({"dhatu_lemma": "dṛś", "upapada": "tyad",
                    "semantic_context": "analocana"},
                   {"dhatu_lemma": "dṛś", "upapada": "tyad",
                    "semantic_context": "other"}),
    "3.2.61":  _pn({"dhatu_lemma": "yuj", "suffix": "kvip"},
                   {"dhatu_lemma": "rāma", "suffix": "kvip"}),
    "3.2.62":  _pn({"dhatu_lemma": "bhaj", "suffix": "ṇvi"},
                   {"dhatu_lemma": "rāma", "suffix": "ṇvi"}),
    "3.2.63":  _pn({"dhatu_lemma": "sah", "is_chandas": True},
                   {"dhatu_lemma": "sah", "is_chandas": False}),
    "3.2.64":  _pn({"dhatu_lemma": "vah", "suffix": "ṇvi"},
                   {"dhatu_lemma": "rāma", "suffix": "ṇvi"}),
    "3.2.65":  _pn({"upapada": "kavya"},
                   {"upapada": "rāma"}),
    "3.2.66":  _pn({"upapada": "havya"},
                   {"upapada": "rāma"}),
    "3.2.67":  _pn({"dhatu_lemma": "jan", "suffix": "viṭ"},
                   {"dhatu_lemma": "rāma", "suffix": "viṭ"}),
    "3.2.68":  _pn({"dhatu_lemma": "ad", "upapada": "rāma"},
                   {"dhatu_lemma": "ad", "upapada": "anna"}),
    "3.2.69":  _pn({"upapada": "kravya"},
                   {"upapada": "rāma"}),
    "3.2.70":  _pn({"dhatu_lemma": "duh", "suffix": "kab"},
                   {"dhatu_lemma": "rāma", "suffix": "kab"}),
    "3.2.71":  _pn({"is_mantra": True, "derived_lemma": "śvetavah"},
                   {"is_mantra": False, "derived_lemma": "rāma"}),
    "3.2.72":  _pn({"dhatu_lemma": "yaj", "upasarga": "ava"},
                   {"dhatu_lemma": "yaj", "upasarga": "pra"}),
    "3.2.73":  _pn({"is_chandas": True, "dhatu_lemma": "vij"},
                   {"is_chandas": False, "dhatu_lemma": "rāma"}),
    "3.2.74":  _pn({"dhatu_ends_in": "ā", "suffix": "manin"},
                   {"dhatu_ends_in": "a", "suffix": "kta"}),
    "3.2.75":  _pn({"is_bahulam": True},
                   {"is_bahulam": False}),
    "3.2.76":  _pn({"suffix": "kvip"},
                   {"suffix": "kta"}),
    "3.2.77":  _pn({"dhatu_lemma": "sthā", "suffix": "ka"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.2.78":  _pn({"has_sup_upapada": True, "is_jati": False,
                    "semantic_context": "tacchilya"},
                   {"has_sup_upapada": False, "is_jati": True,
                    "semantic_context": "other"}),
    "3.2.79":  _pn({"role": Role.KARTR, "is_upamana": True},
                   {"role": Role.KARMAN, "is_upamana": False}),
    "3.2.80":  _pn({"semantic_context": "vrata"},
                   {"semantic_context": "other"}),
    "3.2.81":  _pn({"semantic_context": "abhikshnya"},
                   {"semantic_context": "other"}),
    "3.2.82":  _pn({"upapada": "manas"},
                   {"upapada": "rāma"}),
    "3.2.83":  _pn({"upapada": "ātman", "suffix": "khaś"},
                   {"upapada": "rāma", "suffix": "khaś"}),
    "3.2.84":  _pn({"semantic_context": "bhuta"},
                   {"semantic_context": "other", "suffix": "ṇvul"}),
    "3.2.85":  _pn({"dhatu_lemma": "yaj", "role": Role.KARANA},
                   {"dhatu_lemma": "yaj", "role": Role.KARTR}),
    "3.2.86":  _pn({"dhatu_lemma": "han", "role": Role.KARMAN},
                   {"dhatu_lemma": "han", "role": Role.KARTR}),
    "3.2.87":  _pn({"upapada": "brahman"},
                   {"upapada": "rāma"}),
    "3.2.88":  _pn({"is_chandas": True},
                   {"is_chandas": False}),
    "3.2.89":  _pn({"dhatu_lemma": "kṛ", "upapada": "puṇya"},
                   {"dhatu_lemma": "kṛ", "upapada": "rāma"}),
    "3.2.90":  _pn({"dhatu_lemma": "su", "upapada": "soma"},
                   {"dhatu_lemma": "su", "upapada": "rāma"}),
    "3.2.91":  _pn({"dhatu_lemma": "ci", "upapada": "agni"},
                   {"dhatu_lemma": "ci", "upapada": "rāma"}),
    "3.2.92":  _pn({"role": Role.KARMAN, "is_agni_akhya": True},
                   {"role": Role.KARMAN, "is_agni_akhya": False}),
    "3.2.93":  _pn({"role": Role.KARMAN, "is_vikriya": False},
                   {"role": Role.KARMAN, "is_vikriya": True}),
    "3.2.94":  _pn({"dhatu_lemma": "dṛś", "suffix": "kvanip"},
                   {"dhatu_lemma": "rāma", "suffix": "kvanip"}),
    "3.2.95":  _pn({"dhatu_lemma": "yudh", "upapada": "rājan"},
                   {"dhatu_lemma": "yudh", "upapada": "rāma"}),
    "3.2.96":  _pn({"upapada": "saha"},
                   {"upapada": "rāma"}),
    "3.2.97":  _pn({"dhatu_lemma": "jan", "case": Case.LOCATIVE},
                   {"dhatu_lemma": "jan", "case": Case.NOMINATIVE}),
    "3.2.98":  _pn({"case": Case.ABLATIVE, "is_jati": False},
                   {"case": Case.ABLATIVE, "is_jati": True}),
    "3.2.99":  _pn({"upasarga": "pra", "is_samjna": True},
                   {"upasarga": None, "is_samjna": False}),
    "3.2.100": _pn({"upasarga": "anu", "role": Role.KARMAN},
                   {"upasarga": "anu", "role": Role.KARTR}),
    "3.2.101": _pn({"is_bahulam": True},
                   {"is_bahulam": False}),
    "3.2.103": _pn({"dhatu_lemma": "su", "suffix": "ṅvanip"},
                   {"dhatu_lemma": "rāma", "suffix": "ṅvanip"}),
    "3.2.104": _pn({"dhatu_lemma": "jīr", "suffix": "atṛn"},
                   {"dhatu_lemma": "rāma", "suffix": "atṛn"}),
    "3.2.105": _pn({"is_chandas": True, "lakara": Lakara.LIT},
                   {"is_chandas": False, "lakara": Lakara.LAT}),
    "3.2.106": _pn({"lakara": Lakara.LIT, "suffix": "kānac"},
                   {"lakara": Lakara.LAT, "suffix": "kta"}),
    "3.2.107": _pn({"suffix": "kvasu"},
                   {"suffix": "kta"}),
    "3.2.108": _pn({"is_chandas": False, "dhatu_lemma": "sad",
                    "suffix": "kvasu"},
                   {"is_chandas": True, "dhatu_lemma": "rāma",
                    "suffix": "kta"}),
    "3.2.109": _pn({"derived_lemma": "upeyivan"},
                   {"derived_lemma": "rāma"}),
    "3.2.112": _pn({"lakara": Lakara.LRT,
                    "semantic_context": "abhijna_vacana"},
                   {"lakara": Lakara.LRT, "semantic_context": "other"}),
    "3.2.113": _pn({"first": "atha"},
                   {"first": "yadi"}),
    "3.2.114": _pn({"is_sakanksha": True, "is_optional": True},
                   {"is_sakanksha": False, "is_optional": True}),
    "3.2.115": _pn({"lakara": Lakara.LIT, "semantic_context": "paroksha"},
                   {"lakara": Lakara.LIT, "semantic_context": "other"}),
    "3.2.116": _pn({"first": "ha", "lakara": Lakara.LAN},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.2.117": _pn({"lakara": Lakara.LAN,
                    "semantic_context": "prashna_asanna"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.2.118": _pn({"lakara": Lakara.LAT, "first": "sma"},
                   {"lakara": Lakara.LAT, "first": "rāma"}),
    "3.2.119": _pn({"lakara": Lakara.LAT, "semantic_context": "aparoksha"},
                   {"lakara": Lakara.LAT, "semantic_context": "other"}),
    "3.2.120": _pn({"first": "nanu",
                    "semantic_context": "prishta_prativacana"},
                   {"first": "rāma", "semantic_context": "other"}),
    "3.2.121": _pn({"first": "na", "is_optional": True},
                   {"first": "rāma", "is_optional": True}),
    "3.2.122": _pn({"first": "pura", "lakara": Lakara.LUN},
                   {"first": "rāma", "lakara": Lakara.LAT}),
    "3.2.124": _pn({"lakara": Lakara.LAT, "suffix": "śatṛ"},
                   {"lakara": Lakara.LAT, "suffix": "kta"}),
    "3.2.125": _pn({"case": Case.VOCATIVE},
                   {"case": Case.NOMINATIVE}),
    "3.2.126": _pn({"semantic_context": "lakshana"},
                   {"semantic_context": "other"}),
    "3.2.127": _pn({"suffix": "śatṛ"},
                   {"suffix": "kta"}),
    "3.2.128": _pn({"dhatu_lemma": "pū", "suffix": "śānan"},
                   {"dhatu_lemma": "rāma", "suffix": "śānan"}),
    "3.2.129": _pn({"semantic_context": "tacchilya"},
                   {"semantic_context": "other"}),
    "3.2.130": _pn({"dhatu_lemma": "iṅ"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.131": _pn({"dhatu_lemma": "dviṣ", "semantic_context": "amitra"},
                   {"dhatu_lemma": "dviṣ", "semantic_context": "other"}),
    "3.2.132": _pn({"dhatu_lemma": "su", "semantic_context": "yajna"},
                   {"dhatu_lemma": "su", "semantic_context": "other"}),
    "3.2.133": _pn({"dhatu_lemma": "arh", "semantic_context": "puja"},
                   {"dhatu_lemma": "arh", "semantic_context": "other"}),
    "3.2.134": _pn({"semantic_context": "tacchila"},
                   {"semantic_context": "other"}),
    "3.2.136": _pn({"dhatu_lemma": "alaṃkṛ", "suffix": "iṣṇuc"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.2.137": _pn({"is_causative": True, "is_chandas": True},
                   {"is_causative": False, "is_chandas": False}),
    "3.2.138": _pn({"dhatu_lemma": "bhū", "is_chandas": True},
                   {"dhatu_lemma": "bhū", "is_chandas": False}),
    "3.2.139": _pn({"dhatu_lemma": "glā", "suffix": "ksnu"},
                   {"dhatu_lemma": "rāma", "suffix": "ksnu"}),
    "3.2.140": _pn({"dhatu_lemma": "tras"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.141": _pn({"dhatu_lemma": "śam", "suffix": "ghinun"},
                   {"dhatu_lemma": "rāma", "suffix": "ghinun"}),
    "3.2.142": _pn({"dhatu_lemma": "saṃpṛc"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.143": _pn({"dhatu_lemma": "kaṣ", "upasarga": "vi"},
                   {"dhatu_lemma": "kaṣ", "upasarga": "ni"}),
    "3.2.144": _pn({"dhatu_lemma": "laṣ", "upasarga": "apa"},
                   {"dhatu_lemma": "laṣ", "upasarga": "pra"}),
    "3.2.145": _pn({"dhatu_lemma": "lap", "upasarga": "pra"},
                   {"dhatu_lemma": "lap", "upasarga": "ni"}),
    "3.2.146": _pn({"dhatu_lemma": "nind", "suffix": "vuñ"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.2.147": _pn({"dhatu_lemma": "devi", "upasarga": "pra"},
                   {"dhatu_lemma": "devi", "upasarga": None}),
    "3.2.148": _pn({"semantic_context": "calana", "is_akarmaka": True},
                   {"semantic_context": "calana", "is_akarmaka": False}),
    "3.2.149": _pn({"is_anudatta_it": True, "is_haladi": True},
                   {"is_anudatta_it": False, "is_haladi": False}),
    "3.2.150": _pn({"dhatu_lemma": "ju"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.151": _pn({"semantic_context": "krodha"},
                   {"semantic_context": "other"}),
    "3.2.152": _pn({"dhatu_lemma": "bhū"},
                   {"dhatu_lemma": "yā"}),
    "3.2.153": _pn({"dhatu_lemma": "sūd"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.154": _pn({"dhatu_lemma": "laṣ", "suffix": "ukañ"},
                   {"dhatu_lemma": "rāma", "suffix": "ukañ"}),
    "3.2.155": _pn({"dhatu_lemma": "jalp"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.156": _pn({"dhatu_lemma": "prajan", "suffix": "in"},
                   {"dhatu_lemma": "rāma", "suffix": "in"}),
    "3.2.157": _pn({"dhatu_lemma": "jidṛkṣ"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.158": _pn({"dhatu_lemma": "spṛh", "suffix": "āluc"},
                   {"dhatu_lemma": "rāma", "suffix": "āluc"}),
    "3.2.159": _pn({"dhatu_lemma": "dā", "suffix": "ru"},
                   {"dhatu_lemma": "rāma", "suffix": "ru"}),
    "3.2.160": _pn({"dhatu_lemma": "sṛ", "suffix": "kmarac"},
                   {"dhatu_lemma": "rāma", "suffix": "kmarac"}),
    "3.2.161": _pn({"dhatu_lemma": "bhañj", "suffix": "ghurac"},
                   {"dhatu_lemma": "rāma", "suffix": "ghurac"}),
    "3.2.162": _pn({"dhatu_lemma": "vid", "suffix": "kurac"},
                   {"dhatu_lemma": "rāma", "suffix": "kurac"}),
    "3.2.163": _pn({"dhatu_lemma": "iṇ", "suffix": "kvarap"},
                   {"dhatu_lemma": "rāma", "suffix": "kvarap"}),
    "3.2.164": _pn({"derived_lemma": "gatvara"},
                   {"derived_lemma": "rāma"}),
    "3.2.165": _pn({"dhatu_lemma": "jāgṛ", "suffix": "ūka"},
                   {"dhatu_lemma": "rāma", "suffix": "ūka"}),
    "3.2.166": _pn({"dhatu_lemma": "yaj", "is_yang": True},
                   {"dhatu_lemma": "yaj", "is_yang": False}),
    "3.2.167": _pn({"dhatu_lemma": "nam", "suffix": "ra"},
                   {"dhatu_lemma": "rāma", "suffix": "ra"}),
    "3.2.168": _pn({"dhatu_lemma": "san", "suffix": "u"},
                   {"dhatu_lemma": "rāma", "suffix": "u"}),
    "3.2.169": _pn({"derived_lemma": "vindu"},
                   {"derived_lemma": "rāma"}),
    "3.2.170": _pn({"suffix": "kyāc", "is_chandas": True},
                   {"suffix": "kyāc", "is_chandas": False}),
    "3.2.171": _pn({"dhatu_lemma": "ādṛ", "lakara": Lakara.LIT},
                   {"dhatu_lemma": "rāma", "lakara": Lakara.LAT}),
    "3.2.172": _pn({"dhatu_lemma": "svap", "suffix": "najiṅ"},
                   {"dhatu_lemma": "rāma", "suffix": "najiṅ"}),
    "3.2.173": _pn({"dhatu_lemma": "śṝ", "suffix": "āru"},
                   {"dhatu_lemma": "rāma", "suffix": "āru"}),
    "3.2.174": _pn({"dhatu_lemma": "bhī", "suffix": "kruka"},
                   {"dhatu_lemma": "rāma", "suffix": "kta"}),
    "3.2.175": _pn({"dhatu_lemma": "sthā"},
                   {"dhatu_lemma": "rāma"}),
    "3.2.176": _pn({"is_yang": True, "suffix": "varac"},
                   {"is_yang": False, "suffix": "kta"}),
    "3.2.177": _pn({"dhatu_lemma": "bhrāj", "suffix": "kvip"},
                   {"dhatu_lemma": "rāma", "suffix": "kvip"}),
    "3.2.178": _pn({"is_bahulam": True},
                   {"is_bahulam": False}),
    "3.2.179": _pn({"dhatu_lemma": "bhū", "is_samjna": True},
                   {"dhatu_lemma": "rāma", "is_samjna": False}),
    "3.2.180": _pn({"upasarga": "vi", "is_samjna": False},
                   {"upasarga": "vi", "is_samjna": True}),
    "3.2.181": _pn({"dhatu_lemma": "dhā", "role": Role.KARMAN},
                   {"dhatu_lemma": "dhā", "role": Role.KARTR}),
    "3.2.182": _pn({"dhatu_lemma": "yuj", "role": Role.KARANA},
                   {"dhatu_lemma": "yuj", "role": Role.KARTR}),
    "3.2.183": _pn({"dhatu_lemma": "pū", "upapada": "hala"},
                   {"dhatu_lemma": "pū", "upapada": "rāma"}),
    "3.2.184": _pn({"dhatu_lemma": "lū", "suffix": "itra"},
                   {"dhatu_lemma": "rāma", "suffix": "itra"}),
    "3.2.185": _pn({"dhatu_lemma": "pū", "is_samjna": True},
                   {"dhatu_lemma": "pū", "is_samjna": False}),
    "3.2.186": _pn({"role": Role.KARTR, "semantic_context": "rishi"},
                   {"role": Role.KARTR, "semantic_context": "other"}),
    "3.2.187": _pn({"is_nyit": True, "suffix": "kta"},
                   {"is_nyit": False, "suffix": "ṇvul"}),
    "3.2.188": _pn({"semantic_context": "mati"},
                   {"semantic_context": "other"}),
}


(
    IMPLEMENTED_IDS,
    has_real_implementation,
    handler_for,
    positive_features,
    negative_features,
) = make_module_api(FIXTURES, globals())
