"""Generate Phase 25 exhaustive VM/AST/lowering and borrow-negative test modules."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from sanskript.bytecode import OpCode  # noqa: E402
from sanskript.phase25_exhaustive_registry import COMPILER_EMITTED_OPCODES  # noqa: E402

from tools.phase0_common import ast_statement_nodes  # noqa: E402

EXHAUSTIVE_PATH = ROOT / "tests" / "test_phase25_exhaustive_coverage.py"
BORROW_PATH = ROOT / "tests" / "test_phase25_borrow_negatives.py"


def _snake_case(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()


HEADER = '''"""AUTO-GENERATED by tools/generate_phase25_tests.py — do not edit by hand."""

from __future__ import annotations

import re
import unittest

from sanskript.ast import Program
from sanskript.bytecode import OpCode
from sanskript.phase25_ast_smoke import AST_PROGRAM_BUILDERS, build_ast_program
from sanskript.phase25_exhaustive_registry import COMPILER_EMITTED_OPCODES
from sanskript.phase25_opcode_smoke import run_opcode_smoke


def _snake_case(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\\1_\\2", name).lower()


class Phase25OpcodeExhaustiveTests(unittest.TestCase):
    """Dedicated VM smoke — one test per OpCode enum member."""
'''

BORROW_HEADER = '''"""AUTO-GENERATED borrow-checker negative corpus for Phase 25."""

from __future__ import annotations

import unittest

from sanskript.ast import Bind, Literal, Program, Reference
from sanskript.errors import TypeCheckError
from sanskript.type_checker import check_program


def _rakshita(program: Program) -> None:
    check_program(Program(program.statements, safety_tier="rakshita", **{
        k: v for k, v in program.__dict__.items() if k != "statements" and v
    }))


class Phase25BorrowNegativeTests(unittest.TestCase):
'''

BORROW_CASES: list[tuple[str, str]] = [
    (
        "mutable_reborrow_conflict",
        """Program(
            (
                Bind("x", Literal(1), ownership="owned"),
                Bind("a", Reference("x"), ownership="borrow_mut"),
                Bind("b", Reference("x"), ownership="borrow_mut"),
            ),
            safety_tier="rakshita",
        )""",
    ),
    (
        "borrow_requires_named_reference",
        """Program((Bind("b", Literal(1), ownership="borrow"),), safety_tier="rakshita")""",
    ),
    (
        "mutable_borrow_conflicts_with_shared",
        """Program(
            (
                Bind("x", Literal(1), ownership="owned"),
                Bind("a", Reference("x"), ownership="borrow"),
                Bind("b", Reference("x"), ownership="borrow_mut"),
            ),
            safety_tier="rakshita",
        )""",
    ),
    (
        "cannot_move_borrow_alias",
        """Program(
            (
                Bind("x", Literal(1), ownership="owned"),
                Bind("b", Reference("x"), ownership="borrow"),
                Bind("m", Reference("b"), ownership="owned"),
            ),
            safety_tier="rakshita",
        )""",
    ),
    (
        "mutable_borrow_of_immutable_binding",
        """Program(
            (
                Bind("x", Literal(1), immutable=True, ownership="owned"),
                Bind("b", Reference("x"), ownership="borrow_mut"),
            ),
            safety_tier="rakshita",
        )""",
    ),
]


def _emit_opcode_tests() -> list[str]:
    lines: list[str] = []
    for opcode in OpCode:
        fn = f"test_opcode_{opcode.value}"
        lines.append(f"    def {fn}(self) -> None:")
        lines.append(f"        run_opcode_smoke(OpCode.{opcode.name})")
        lines.append("")
    return lines


def _emit_ast_tests(nodes: list[str]) -> list[str]:
    lines = [
        "",
        "class Phase25AstNodeExhaustiveTests(unittest.TestCase):",
        '    """Dedicated AST builder — one test per Statement union member."""',
        "",
    ]
    for node in nodes:
        fn = f"test_ast_{_snake_case(node)}"
        lines.append(f"    def {fn}(self) -> None:")
        lines.append(f"        program = build_ast_program({node!r})")
        lines.append("        self.assertIsInstance(program, Program)")
        lines.append(f"        self.assertIn({node!r}, AST_PROGRAM_BUILDERS)")
        lines.append("")
    return lines


def _emit_lowering_tests() -> list[str]:
    lines = [
        "",
        "class Phase25CompilerLoweringTests(unittest.TestCase):",
        '    """Dedicated reference test per compiler-emitted OpCode."""',
        "",
        "    def test_lowering_inventory_matches_compiler_source(self) -> None:",
        "        self.assertGreaterEqual(len(COMPILER_EMITTED_OPCODES), 1)",
        "",
    ]
    for member in COMPILER_EMITTED_OPCODES:
        fn = f"test_lowering_{member.lower()}"
        lines.append(f"    def {fn}(self) -> None:")
        lines.append(f"        run_opcode_smoke(OpCode.{member})")
        lines.append("")
    return lines


def write_exhaustive(path: Path) -> None:
    nodes = ast_statement_nodes()
    body = (
        [HEADER]
        + _emit_opcode_tests()
        + _emit_ast_tests(nodes)
        + _emit_lowering_tests()
        + ["", 'if __name__ == "__main__":', "    unittest.main()", ""]
    )
    path.write_text("\n".join(body), encoding="utf-8")


def write_borrow(path: Path) -> None:
    lines = [BORROW_HEADER]
    for name, program_src in BORROW_CASES:
        fn = f"test_borrow_negative_{name}"
        lines.append(f"    def {fn}(self) -> None:")
        lines.append(f"        with self.assertRaises(TypeCheckError):")
        lines.append(f"            check_program({program_src})")
        lines.append("")
    lines.extend(['', 'if __name__ == "__main__":', "    unittest.main()", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Phase 25 exhaustive test modules")
    parser.add_argument("--exhaustive", type=Path, default=EXHAUSTIVE_PATH)
    parser.add_argument("--borrow", type=Path, default=BORROW_PATH)
    args = parser.parse_args(argv)
    write_exhaustive(args.exhaustive)
    write_borrow(args.borrow)
    print(args.exhaustive)
    print(args.borrow)
    print(f"opcodes={len(OpCode)} ast_nodes={len(ast_statement_nodes())} lowerings={len(COMPILER_EMITTED_OPCODES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
